// Connection Forms Unit - Unit Authoring Config
// Generated from legacy pq_unit_joint_connecting_forms_sqa_final_v1.0.2_fixed.

const __PQ_NORMALIZE_UNIT_CONFIG__ = (
  (typeof window !== 'undefined' && window.PQUnitConfigNormalizer) ||
  (typeof globalThis !== 'undefined' && globalThis.PQUnitConfigNormalizer)
);

if (!__PQ_NORMALIZE_UNIT_CONFIG__ || typeof __PQ_NORMALIZE_UNIT_CONFIG__.normalize !== 'function') {
  throw new Error('PQUnitConfigNormalizer must load before unit.config.js');
}

const UNIT_CFG = __PQ_NORMALIZE_UNIT_CONFIG__.normalize({
  "schemaVersion": 1,
  "identity": {
    "lessonId": "joint",
    "unitId": "joint_connecting_forms",
    "unitKey": "connection-forms",
    "storagePrefix": "joint_connecting_forms",
    "keyPrefix": "cf_"
  },
  "moodle": {
    "wsGetFunction": "local_prequran_get_joint_connecting_forms_state",
    "wsSetFunction": "local_prequran_set_joint_connecting_forms_state"
  },
  "release": {
    "version": "1.0.0",
    "assetVersion": "joint-rules-20260601a"
  },
  "localization": {
    "defaultLanguage": "en",
    "fallbackLanguage": "en",
    "defaultScope": "both",
    "supportedLanguages": [
      "en",
      "ar",
      "so",
      "sw",
      "pa",
      "ur"
    ],
    "translations": {
      "ar": {},
      "so": {},
      "sw": {},
      "pa": {},
      "ur": {}
    }
  },
  "assets": {
    "cdnRoot": "/pre_quraan",
    "unitMediaRoot": "/lessons/connection-forms/media",
    "filePrefix": "cf_",
    "mediaPadWidth": 2,
    "audioExt": ".mp3",
    "soundAudioExt": ".mp3",
    "videoFilePrefix": "cf_"
  },
  "routes": {
    "academyHomeUrl": "https://quraan.academy/"
  },
  "messaging": {
    "useConfigStepMessages": true,
    "disableLegacyCompletionFeedback": true
  },
  "messageUi": {
    "titleText": "Message",
    "continueText": "Continue",
    "clap": {
      "enabled": true,
      "visual": true,
      "audio": "",
      "delayMs": 120
    }
  },
  "stepNavigation": {
    "previous": {
      "enabled": true,
      "label": "Step Back",
      "title": "Go back one step",
      "confirmTitle": "Go back one step?",
      "confirmText": "This will move you back to {previousStep}. Your progress for {currentStep} and {previousStep} will be reset so you can try again.",
      "confirmContinueText": "Yes, go back",
      "confirmCancelText": "Stay here"
    },
    "skip": {
      "confirmTitle": "Skip this step?",
      "confirmText": "This will mark {currentStep} complete and move you to the next step.",
      "confirmContinueText": "Yes, skip step",
      "confirmCancelText": "Stay here"
    }
  },
  "steps": [
    {
      "id": "lecture",
      "step_index": 1,
      "type": "lecture",
      "label": "Lecture",
      "arabicLabel": "شرح",
      "passFilters": [
        "all"
      ]
    },
    {
      "id": "rules",
      "step_index": 2,
      "type": "content",
      "label": "Rules",
      "arabicLabel": "القواعد",
      "actionLabel": "Complete Rules",
      "actionArabicLabel": "أكمل القواعد",
      "passFilters": [
        "connectionForms"
      ],
      "filter": "connectionForms"
    },
    {
      "id": "listen",
      "step_index": 3,
      "type": "playlist",
      "label": "Listen",
      "arabicLabel": "استمع",
      "passFilters": [
        "connectionForms"
      ],
      "filter": "connectionForms"
    },
    {
      "id": "animate",
      "step_index": 4,
      "type": "animate",
      "label": "Animate",
      "arabicLabel": "شاهد الكتابة",
      "passFilters": [
        "connectionForms"
      ],
      "filter": "connectionForms"
    },
    {
      "id": "write1",
      "step_index": 5,
      "type": "write",
      "label": "Write 1",
      "arabicLabel": "اكتب ١",
      "passFilters": [
        "write1connectionforms"
      ],
      "filter": "write1connectionforms"
    },
    {
      "id": "write2",
      "step_index": 6,
      "type": "write",
      "label": "Write 2",
      "arabicLabel": "اكتب ٢",
      "passFilters": [
        "write2connectionforms"
      ],
      "filter": "write2connectionforms"
    },
    {
      "id": "write3",
      "step_index": 7,
      "type": "write",
      "label": "Write 3",
      "arabicLabel": "اكتب ٣",
      "passFilters": [
        "write3connectionforms"
      ],
      "filter": "write3connectionforms"
    },
    {
      "id": "write4",
      "step_index": 8,
      "type": "write",
      "label": "Write 4",
      "arabicLabel": "اكتب ٤",
      "passFilters": [
        "write4joined2letters"
      ],
      "filter": "write4joined2letters"
    },
    {
      "id": "write5",
      "step_index": 9,
      "type": "write",
      "label": "Write 5",
      "arabicLabel": "اكتب ٥",
      "passFilters": [
        "write5joined3letters"
      ],
      "filter": "write5joined3letters"
    },
    {
      "id": "write6",
      "step_index": 10,
      "type": "write",
      "label": "Write 6",
      "arabicLabel": "اكتب ٦",
      "passFilters": [
        "write6joined4letters"
      ],
      "filter": "write6joined4letters"
    },
    {
      "id": "write7",
      "step_index": 11,
      "type": "write",
      "label": "Write 7",
      "arabicLabel": "اكتب ٧",
      "passFilters": [
        "write7joined5letters"
      ],
      "filter": "write7joined5letters"
    }
  ],
  "filterSets": {
    "all": [
      "cf_01_i",
      "cf_01_f",
      "cf_02_i",
      "cf_02_b",
      "cf_02_m",
      "cf_02_f",
      "cf_03_i",
      "cf_03_b",
      "cf_03_m",
      "cf_03_f",
      "cf_04_i",
      "cf_04_b",
      "cf_04_m",
      "cf_04_f",
      "cf_05_i",
      "cf_05_b",
      "cf_05_m",
      "cf_05_f",
      "cf_06_i",
      "cf_06_b",
      "cf_06_m",
      "cf_06_f",
      "cf_08_i",
      "cf_08_f",
      "cf_09_i",
      "cf_09_f",
      "cf_10_i",
      "cf_10_f",
      "cf_11_i",
      "cf_11_f",
      "cf_12_i",
      "cf_12_b",
      "cf_12_m",
      "cf_12_f",
      "cf_13_i",
      "cf_13_b",
      "cf_13_m",
      "cf_13_f",
      "cf_14_i",
      "cf_14_b",
      "cf_14_m",
      "cf_14_f",
      "cf_15_i",
      "cf_15_b",
      "cf_15_m",
      "cf_15_f",
      "cf_16_i",
      "cf_16_b",
      "cf_16_m",
      "cf_16_f",
      "cf_17_i",
      "cf_17_b",
      "cf_17_m",
      "cf_17_f",
      "cf_18_i",
      "cf_18_b",
      "cf_18_m",
      "cf_18_f",
      "cf_19_i",
      "cf_19_b",
      "cf_19_m",
      "cf_19_f",
      "cf_20_i",
      "cf_20_b",
      "cf_20_m",
      "cf_20_f",
      "cf_21_i",
      "cf_21_b",
      "cf_21_m",
      "cf_21_f",
      "cf_22_i",
      "cf_22_b",
      "cf_22_m",
      "cf_22_f",
      "cf_23_i",
      "cf_23_b",
      "cf_23_m",
      "cf_23_f",
      "cf_24_i",
      "cf_24_b",
      "cf_24_m",
      "cf_24_f",
      "cf_25_i",
      "cf_25_b",
      "cf_25_m",
      "cf_25_f",
      "cf_26_i",
      "cf_26_b",
      "cf_26_m",
      "cf_26_f",
      "cf_27_i",
      "cf_27_f",
      "cf_28_b",
      "cf_28_f"
    ],
    "connectionForms": [
      "cf_01_i",
      "cf_01_f",
      "cf_02_i",
      "cf_02_b",
      "cf_02_m",
      "cf_02_f",
      "cf_03_i",
      "cf_03_b",
      "cf_03_m",
      "cf_03_f",
      "cf_04_i",
      "cf_04_b",
      "cf_04_m",
      "cf_04_f",
      "cf_05_i",
      "cf_05_b",
      "cf_05_m",
      "cf_05_f",
      "cf_06_i",
      "cf_06_b",
      "cf_06_m",
      "cf_06_f",
      "cf_08_i",
      "cf_08_f",
      "cf_09_i",
      "cf_09_f",
      "cf_10_i",
      "cf_10_f",
      "cf_11_i",
      "cf_11_f",
      "cf_12_i",
      "cf_12_b",
      "cf_12_m",
      "cf_12_f",
      "cf_13_i",
      "cf_13_b",
      "cf_13_m",
      "cf_13_f",
      "cf_14_i",
      "cf_14_b",
      "cf_14_m",
      "cf_14_f",
      "cf_15_i",
      "cf_15_b",
      "cf_15_m",
      "cf_15_f",
      "cf_16_i",
      "cf_16_b",
      "cf_16_m",
      "cf_16_f",
      "cf_17_i",
      "cf_17_b",
      "cf_17_m",
      "cf_17_f",
      "cf_18_i",
      "cf_18_b",
      "cf_18_m",
      "cf_18_f",
      "cf_19_i",
      "cf_19_b",
      "cf_19_m",
      "cf_19_f",
      "cf_20_i",
      "cf_20_b",
      "cf_20_m",
      "cf_20_f",
      "cf_21_i",
      "cf_21_b",
      "cf_21_m",
      "cf_21_f",
      "cf_22_i",
      "cf_22_b",
      "cf_22_m",
      "cf_22_f",
      "cf_23_i",
      "cf_23_b",
      "cf_23_m",
      "cf_23_f",
      "cf_24_i",
      "cf_24_b",
      "cf_24_m",
      "cf_24_f",
      "cf_25_i",
      "cf_25_b",
      "cf_25_m",
      "cf_25_f",
      "cf_26_i",
      "cf_26_b",
      "cf_26_m",
      "cf_26_f",
      "cf_27_i",
      "cf_27_f",
      "cf_28_b",
      "cf_28_f"
    ],
    "write4joined2letters": [
      "cf_join4_01",
      "cf_join4_02",
      "cf_join4_03",
      "cf_join4_04",
      "cf_join4_05",
      "cf_join4_06",
      "cf_join4_07",
      "cf_join4_08",
      "cf_join4_09",
      "cf_join4_10",
      "cf_join4_11",
      "cf_join4_12",
      "cf_join4_13",
      "cf_join4_14",
      "cf_join4_15",
      "cf_join4_16",
      "cf_join4_17",
      "cf_join4_18",
      "cf_join4_19",
      "cf_join4_20",
      "cf_join4_21",
      "cf_join4_22",
      "cf_join4_23",
      "cf_join4_24",
      "cf_join4_25",
      "cf_join4_26",
      "cf_join4_27",
      "cf_join4_28",
      "cf_join4_29",
      "cf_join4_30",
      "cf_join4_31",
      "cf_join4_32",
      "cf_join4_33",
      "cf_join4_34",
      "cf_join4_35",
      "cf_join4_36",
      "cf_join4_37",
      "cf_join4_38",
      "cf_join4_39",
      "cf_join4_40",
      "cf_join4_41",
      "cf_join4_42",
      "cf_join4_43",
      "cf_join4_44",
      "cf_join4_45",
      "cf_join4_46",
      "cf_join4_47",
      "cf_join4_48",
      "cf_join4_49",
      "cf_join4_50",
      "cf_join4_51",
      "cf_join4_52",
      "cf_join4_53",
      "cf_join4_54",
      "cf_join4_55",
      "cf_join4_56",
      "cf_join4_57",
      "cf_join4_58",
      "cf_join4_59",
      "cf_join4_60"
    ],
    "write5joined3letters": [
      "cf_join5_01",
      "cf_join5_02",
      "cf_join5_03",
      "cf_join5_04",
      "cf_join5_05",
      "cf_join5_06",
      "cf_join5_07",
      "cf_join5_08",
      "cf_join5_09",
      "cf_join5_10",
      "cf_join5_11",
      "cf_join5_12",
      "cf_join5_13",
      "cf_join5_14",
      "cf_join5_15",
      "cf_join5_16",
      "cf_join5_17",
      "cf_join5_18",
      "cf_join5_19",
      "cf_join5_20",
      "cf_join5_21",
      "cf_join5_22",
      "cf_join5_23",
      "cf_join5_24",
      "cf_join5_25",
      "cf_join5_26",
      "cf_join5_27",
      "cf_join5_28",
      "cf_join5_29",
      "cf_join5_30",
      "cf_join5_31",
      "cf_join5_32",
      "cf_join5_33",
      "cf_join5_34",
      "cf_join5_35",
      "cf_join5_36",
      "cf_join5_37",
      "cf_join5_38",
      "cf_join5_39",
      "cf_join5_40"
    ],
    "write6joined4letters": [
      "cf_join6_01",
      "cf_join6_02",
      "cf_join6_03",
      "cf_join6_04",
      "cf_join6_05",
      "cf_join6_06",
      "cf_join6_07",
      "cf_join6_08",
      "cf_join6_09",
      "cf_join6_10",
      "cf_join6_11",
      "cf_join6_12",
      "cf_join6_13",
      "cf_join6_14",
      "cf_join6_15",
      "cf_join6_16",
      "cf_join6_17",
      "cf_join6_18",
      "cf_join6_19",
      "cf_join6_20",
      "cf_join6_21",
      "cf_join6_22",
      "cf_join6_23",
      "cf_join6_24",
      "cf_join6_25",
      "cf_join6_26",
      "cf_join6_27",
      "cf_join6_28",
      "cf_join6_29",
      "cf_join6_30"
    ],
    "write7joined5letters": [
      "cf_join7_01",
      "cf_join7_02",
      "cf_join7_03",
      "cf_join7_04",
      "cf_join7_05",
      "cf_join7_06",
      "cf_join7_07",
      "cf_join7_08",
      "cf_join7_09",
      "cf_join7_10",
      "cf_join7_11",
      "cf_join7_12",
      "cf_join7_13",
      "cf_join7_14",
      "cf_join7_15",
      "cf_join7_16",
      "cf_join7_17",
      "cf_join7_18",
      "cf_join7_19",
      "cf_join7_20",
      "cf_join7_21",
      "cf_join7_22",
      "cf_join7_23",
      "cf_join7_24",
      "cf_join7_25"
    ],
    "write1connectionforms": [
      "cf_02_i",
      "cf_02_b",
      "cf_02_m",
      "cf_02_f",
      "cf_03_i",
      "cf_03_b",
      "cf_03_m",
      "cf_03_f",
      "cf_04_i",
      "cf_04_b",
      "cf_04_m",
      "cf_04_f",
      "cf_05_i",
      "cf_05_b",
      "cf_05_m",
      "cf_05_f",
      "cf_06_i",
      "cf_06_b",
      "cf_06_m",
      "cf_06_f",
      "cf_08_i",
      "cf_08_f",
      "cf_09_i",
      "cf_09_f",
      "cf_10_i",
      "cf_10_f",
      "cf_11_i",
      "cf_11_f",
      "cf_12_i",
      "cf_12_b",
      "cf_12_m",
      "cf_12_f"
    ],
    "write2connectionforms": [
      "cf_13_i",
      "cf_13_b",
      "cf_13_m",
      "cf_13_f",
      "cf_14_i",
      "cf_14_b",
      "cf_14_m",
      "cf_14_f",
      "cf_15_i",
      "cf_15_b",
      "cf_15_m",
      "cf_15_f",
      "cf_16_i",
      "cf_16_b",
      "cf_16_m",
      "cf_16_f",
      "cf_17_i",
      "cf_17_b",
      "cf_17_m",
      "cf_17_f",
      "cf_18_i",
      "cf_18_b",
      "cf_18_m",
      "cf_18_f",
      "cf_19_i",
      "cf_19_b",
      "cf_19_m",
      "cf_19_f",
      "cf_20_i",
      "cf_20_b",
      "cf_20_m",
      "cf_20_f"
    ],
    "write3connectionforms": [
      "cf_21_i",
      "cf_21_b",
      "cf_21_m",
      "cf_21_f",
      "cf_22_i",
      "cf_22_b",
      "cf_22_m",
      "cf_22_f",
      "cf_23_i",
      "cf_23_b",
      "cf_23_m",
      "cf_23_f",
      "cf_24_i",
      "cf_24_b",
      "cf_24_m",
      "cf_24_f",
      "cf_25_i",
      "cf_25_b",
      "cf_25_m",
      "cf_25_f",
      "cf_26_i",
      "cf_26_b",
      "cf_26_m",
      "cf_26_f",
      "cf_27_i",
      "cf_27_f",
      "cf_28_b",
      "cf_28_f"
    ]
  },
  "layout": {
    "layoutMode": "flow-span",
    "browserGridCols": 4,
    "mobileGridCols": 1,
    "sepFontSize": "3.25rem",
    "smallFontSize": "0.95rem",
    "mobileTileMinHeight": "132px",
    "mobileSepFontSize": "2.7rem",
    "mobileSmallFontSize": "0.9rem",
    "rtlColFromLtr": false,
    "width": "100%",
    "maxWidth": "100%",
    "columnGap": "12px",
    "rowGap": "12px",
    "minTileWidth": "0px"
  },
  "focusBadge": {
    "label": "Try to Focus",
    "icon": "✨"
  },
  "rewardBar": {
    "progressLabel": "Progress",
    "unitsDoneLabel": "Units Done",
    "totalStarsLabel": "Total Stars",
    "thisUnitLabel": "This Unit"
  },
  "stepperUi": {
    "stepPrefix": "Step",
    "progressLabel": "Progress"
  },
  "playback": {
    "letterAudioMode": "both",
    "letterAudioSequenceGapMs": 120,
    "appendFormDescriptionAudio": true,
    "steps": {
      "listen": {
        "letterAudioMode": "both",
        "beforeStartMs": 500,
        "betweenLettersMs": 750,
        "afterCompleteMs": 500
      },
      "animate": {
        "letterAudioMode": "both",
        "beforeStartMs": 500,
        "betweenLettersMs": 700,
        "afterCompleteMs": 500
      },
      "write1": {
        "letterAudioMode": "both"
      },
      "write2": {
        "letterAudioMode": "both"
      },
      "write3": {
        "letterAudioMode": "both"
      },
      "write4": {
        "letterAudioMode": "both"
      },
      "write5": {
        "letterAudioMode": "both"
      },
      "write6": {
        "letterAudioMode": "both"
      },
      "write7": {
        "letterAudioMode": "both"
      }
    }
  },
  "messages": {
    "base": "/pre_quraan/messages/unit_steps/connection-forms/",
    "manifest": "./unit.messages.js",
    "version": "connection-forms-messages-v0.1.0",
    "entry": {},
    "entryPasses": {},
    "completion": {}
  },
  "media": {
    "audioBase": "/pre_quraan/lessons/connection-forms/media/audio/male/",
    "l6Base": "/pre_quraan/lessons/connection-forms/media/audio/male/",
    "fallbackAudioBase": "/pre_quraan/lessons/connection-forms/media/audio/male/",
    "watchBase": "/pre_quraan/lessons/connection-forms/media/video/",
    "fallbackWatchBase": "/pre_quraan/lessons/connection-forms/media/video/",
    "animateBase": "/pre_quraan/lessons/connection-forms/media/video/",
    "formDescriptionBase": "/pre_quraan/lessons/connection-forms/media/audio/forms/",
    "lectureUrl": "/pre_quraan/messages/lectures/connection-forms_lecture.mp4",
    "voiceBases": {
      "child_boy": "/pre_quraan/lessons/connection-forms/media/audio/male/",
      "child_girl": "",
      "adult_male": "/pre_quraan/lessons/connection-forms/media/audio/male/",
      "adult_female": ""
    }
  },
  "formDescriptionAudioByForm": {
    "i": "independent.mp3",
    "b": "beginning.mp3",
    "m": "middle.mp3",
    "f": "final.mp3"
  },
  "write": {
    "chunkSize": 32,
    "chunks": [
      32,
      32,
      28,
      60,
      40,
      30,
      25
    ],
    "rows": 1,
    "cols": 1,
    "wideWords": [],
    "spanWords": {},
    "minPassesRequired": 1,
    "adapter": {
      "unitKey": "joint_connecting_forms",
      "buttonId": "btnTrace",
      "displayLabel": "Write"
    },
    "canvas": {
      "width": 800,
      "height": 320,
      "borderColor": "#e7dbc1",
      "borderRadius": "10px",
      "inkColor": "#0d223a",
      "inkWidth": 8,
      "guide": {
        "top": 110,
        "mid": 150,
        "base": 205,
        "bottom": 260,
        "sidePadding": 24,
        "topColor": "#e8e2cf",
        "midColor": "#e0d6bc",
        "baseColor": "#d5c8a2",
        "bottomColor": "#e8e2cf",
        "midDash": [
          14,
          10
        ]
      },
      "ghostText": {
        "color": "#10223a",
        "alpha": 0.18,
        "normalFontPx": 74,
        "wideFontPx": 50
      }
    }
  },
  "listenPlus": {
    "enabled": false,
    "imageBase": "/pre_quraan/lessons/connection-forms/media/listen_plus/animals/images/",
    "audioBase": "/pre_quraan/lessons/connection-forms/media/listen_plus/animals/audio/",
    "imageExt": ".png",
    "audioExt": ".mp3",
    "title": "Listen+",
    "subtitle": "Arabic sound + animal sound",
    "map": {}
  },
  "words": {
    "enabled": false,
    "imageBase": "/pre_quraan/lessons/connection-forms/media/words/images/",
    "audioBase": "/pre_quraan/lessons/connection-forms/media/words/audio/",
    "imageExt": ".png",
    "audioExt": ".mp3",
    "title": "Words",
    "subtitle": "Arabic letter + Arabic word",
    "map": {}
  },
  "ui": {
    "pageTitle": "PQ Unit - Connection Forms Unit",
    "headerTitle": "Connection Forms Unit",
    "aboutLabel": "About Connection Forms",
    "showDbSavedToast": false
  },
  "stepInjection": {
    "watch": false,
    "speak": false,
    "submit": false,
    "beforeListen": [
      {
        "id": "rules",
        "type": "content",
        "label": "Rules",
        "arabicLabel": "القواعد",
        "actionLabel": "Complete Rules",
        "actionArabicLabel": "أكمل القواعد",
        "filter": "connectionForms",
        "passFilters": [
          "connectionForms"
        ]
      }
    ]
  },
  "defaults": {
    "voice": "child_boy",
    "speed": "1.0",
    "repeat": "1",
    "filter": "all"
  },
  "wordLimit": 249,
  "content": {
    "items": [
      {
        "key": "cf_01_i",
        "text": "ا",
        "ar": "ا",
        "small": "ا منفصل",
        "en": "Alif Independent",
        "row": 1,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "Independent",
        "pass": 0
      },
      {
        "key": "cf_01_f",
        "text": "ـا",
        "ar": "ـا",
        "small": "ا آخر",
        "en": "Alif Final",
        "row": 1,
        "displayCol": 2,
        "audio": "cf_01_f.mp3",
        "video": "cf_01_f.mp4",
        "filterType": "Final",
        "pass": 0
      },
      {
        "key": "cf_02_i",
        "text": "ب",
        "ar": "ب",
        "small": "ب منفصل",
        "en": "Baa Independent",
        "row": 1,
        "displayCol": 3,
        "audio": "cf_02_i.mp3",
        "video": "cf_02_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_02_b",
        "text": "بـ",
        "ar": "بـ",
        "small": "ب أول",
        "en": "Baa Beginning",
        "row": 1,
        "displayCol": 4,
        "audio": "cf_02_b.mp3",
        "video": "cf_02_b.mp4",
        "filterType": "Beginning",
        "pass": 1
      },
      {
        "key": "cf_02_m",
        "text": "ـبـ",
        "ar": "ـبـ",
        "small": "ب وسط",
        "en": "Baa Middle",
        "row": 2,
        "displayCol": 1,
        "audio": "cf_02_m.mp3",
        "video": "cf_02_m.mp4",
        "filterType": "Middle",
        "pass": 1
      },
      {
        "key": "cf_02_f",
        "text": "ـب",
        "ar": "ـب",
        "small": "ب آخر",
        "en": "Baa Final",
        "row": 2,
        "displayCol": 2,
        "audio": "cf_02_f.mp3",
        "video": "cf_02_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_03_i",
        "text": "ت",
        "ar": "ت",
        "small": "ت منفصل",
        "en": "Taa Independent",
        "row": 2,
        "displayCol": 3,
        "audio": "cf_03_i.mp3",
        "video": "cf_03_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_03_b",
        "text": "تـ",
        "ar": "تـ",
        "small": "ت أول",
        "en": "Taa Beginning",
        "row": 2,
        "displayCol": 4,
        "audio": "cf_03_b.mp3",
        "video": "cf_03_b.mp4",
        "filterType": "Beginning",
        "pass": 1
      },
      {
        "key": "cf_03_m",
        "text": "ـتـ",
        "ar": "ـتـ",
        "small": "ت وسط",
        "en": "Taa Middle",
        "row": 3,
        "displayCol": 1,
        "audio": "cf_03_m.mp3",
        "video": "cf_03_m.mp4",
        "filterType": "Middle",
        "pass": 1
      },
      {
        "key": "cf_03_f",
        "text": "ـت",
        "ar": "ـت",
        "small": "ت آخر",
        "en": "Taa Final",
        "row": 3,
        "displayCol": 2,
        "audio": "cf_03_f.mp3",
        "video": "cf_03_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_04_i",
        "text": "ث",
        "ar": "ث",
        "small": "ث منفصل",
        "en": "Thaa Independent",
        "row": 3,
        "displayCol": 3,
        "audio": "cf_04_i.mp3",
        "video": "cf_04_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_04_b",
        "text": "ثـ",
        "ar": "ثـ",
        "small": "ث أول",
        "en": "Thaa Beginning",
        "row": 3,
        "displayCol": 4,
        "audio": "cf_04_b.mp3",
        "video": "cf_04_b.mp4",
        "filterType": "Beginning",
        "pass": 1
      },
      {
        "key": "cf_04_m",
        "text": "ـثـ",
        "ar": "ـثـ",
        "small": "ث وسط",
        "en": "Thaa Middle",
        "row": 4,
        "displayCol": 1,
        "audio": "cf_04_m.mp3",
        "video": "cf_04_m.mp4",
        "filterType": "Middle",
        "pass": 1
      },
      {
        "key": "cf_04_f",
        "text": "ـث",
        "ar": "ـث",
        "small": "ث آخر",
        "en": "Thaa Final",
        "row": 4,
        "displayCol": 2,
        "audio": "cf_04_f.mp3",
        "video": "cf_04_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_05_i",
        "text": "ج",
        "ar": "ج",
        "small": "ج منفصل",
        "en": "Jeem Independent",
        "row": 4,
        "displayCol": 3,
        "audio": "cf_05_i.mp3",
        "video": "cf_05_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_05_b",
        "text": "جـ",
        "ar": "جـ",
        "small": "ج أول",
        "en": "Jeem Beginning",
        "row": 4,
        "displayCol": 4,
        "audio": "cf_05_b.mp3",
        "video": "cf_05_b.mp4",
        "filterType": "Beginning",
        "pass": 1
      },
      {
        "key": "cf_05_m",
        "text": "ـجـ",
        "ar": "ـجـ",
        "small": "ج وسط",
        "en": "Jeem Middle",
        "row": 5,
        "displayCol": 1,
        "audio": "cf_05_m.mp3",
        "video": "cf_05_m.mp4",
        "filterType": "Middle",
        "pass": 1
      },
      {
        "key": "cf_05_f",
        "text": "ـج",
        "ar": "ـج",
        "small": "ج آخر",
        "en": "Jeem Final",
        "row": 5,
        "displayCol": 2,
        "audio": "cf_05_f.mp3",
        "video": "cf_05_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_06_i",
        "text": "ح",
        "ar": "ح",
        "small": "ح منفصل",
        "en": "Haa Independent",
        "row": 5,
        "displayCol": 3,
        "audio": "cf_06_i.mp3",
        "video": "cf_06_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_06_b",
        "text": "حـ",
        "ar": "حـ",
        "small": "ح أول",
        "en": "Haa Beginning",
        "row": 5,
        "displayCol": 4,
        "audio": "cf_06_b.mp3",
        "video": "cf_06_b.mp4",
        "filterType": "Beginning",
        "pass": 1
      },
      {
        "key": "cf_06_m",
        "text": "ـحـ",
        "ar": "ـحـ",
        "small": "ح وسط",
        "en": "Haa Middle",
        "row": 6,
        "displayCol": 1,
        "audio": "cf_06_m.mp3",
        "video": "cf_06_m.mp4",
        "filterType": "Middle",
        "pass": 1
      },
      {
        "key": "cf_06_f",
        "text": "ـح",
        "ar": "ـح",
        "small": "ح آخر",
        "en": "Haa Final",
        "row": 6,
        "displayCol": 2,
        "audio": "cf_06_f.mp3",
        "video": "cf_06_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_08_i",
        "text": "د",
        "ar": "د",
        "small": "د منفصل",
        "en": "Daal Independent",
        "row": 6,
        "displayCol": 3,
        "audio": "cf_08_i.mp3",
        "video": "cf_08_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_08_f",
        "text": "ـد",
        "ar": "ـد",
        "small": "د آخر",
        "en": "Daal Final",
        "row": 6,
        "displayCol": 4,
        "audio": "cf_08_f.mp3",
        "video": "cf_08_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_09_i",
        "text": "ذ",
        "ar": "ذ",
        "small": "ذ منفصل",
        "en": "Dhaal Independent",
        "row": 7,
        "displayCol": 1,
        "audio": "cf_09_i.mp3",
        "video": "cf_09_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_09_f",
        "text": "ـذ",
        "ar": "ـذ",
        "small": "ذ آخر",
        "en": "Dhaal Final",
        "row": 7,
        "displayCol": 2,
        "audio": "cf_09_f.mp3",
        "video": "cf_09_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_10_i",
        "text": "ر",
        "ar": "ر",
        "small": "ر منفصل",
        "en": "Raa Independent",
        "row": 7,
        "displayCol": 3,
        "audio": "cf_10_i.mp3",
        "video": "cf_10_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_10_f",
        "text": "ـر",
        "ar": "ـر",
        "small": "ر آخر",
        "en": "Raa Final",
        "row": 7,
        "displayCol": 4,
        "audio": "cf_10_f.mp3",
        "video": "cf_10_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_11_i",
        "text": "ز",
        "ar": "ز",
        "small": "ز منفصل",
        "en": "Zay Independent",
        "row": 8,
        "displayCol": 1,
        "audio": "cf_11_i.mp3",
        "video": "cf_11_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_11_f",
        "text": "ـز",
        "ar": "ـز",
        "small": "ز آخر",
        "en": "Zay Final",
        "row": 8,
        "displayCol": 2,
        "audio": "cf_11_f.mp3",
        "video": "cf_11_f.mp4",
        "filterType": "Final",
        "pass": 1
      },
      {
        "key": "cf_12_i",
        "text": "س",
        "ar": "س",
        "small": "س منفصل",
        "en": "Seen Independent",
        "row": 8,
        "displayCol": 3,
        "audio": "cf_12_i.mp3",
        "video": "cf_12_i.mp4",
        "filterType": "Independent",
        "pass": 1
      },
      {
        "key": "cf_12_b",
        "text": "سـ",
        "ar": "سـ",
        "small": "س أول",
        "en": "Seen Beginning",
        "row": 8,
        "displayCol": 4,
        "audio": "cf_12_b.mp3",
        "video": "cf_12_b.mp4",
        "filterType": "Beginning",
        "pass": 1
      },
      {
        "key": "cf_12_m",
        "text": "ـسـ",
        "ar": "ـسـ",
        "small": "س وسط",
        "en": "Seen Middle",
        "row": 9,
        "displayCol": 1,
        "audio": "cf_12_m.mp3",
        "video": "cf_12_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_12_f",
        "text": "ـس",
        "ar": "ـس",
        "small": "س آخر",
        "en": "Seen Final",
        "row": 9,
        "displayCol": 2,
        "audio": "cf_12_f.mp3",
        "video": "cf_12_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_13_i",
        "text": "ش",
        "ar": "ش",
        "small": "ش منفصل",
        "en": "Sheen Independent",
        "row": 9,
        "displayCol": 3,
        "audio": "cf_13_i.mp3",
        "video": "cf_13_i.mp4",
        "filterType": "Independent",
        "pass": 2
      },
      {
        "key": "cf_13_b",
        "text": "شـ",
        "ar": "شـ",
        "small": "ش أول",
        "en": "Sheen Beginning",
        "row": 9,
        "displayCol": 4,
        "audio": "cf_13_b.mp3",
        "video": "cf_13_b.mp4",
        "filterType": "Beginning",
        "pass": 2
      },
      {
        "key": "cf_13_m",
        "text": "ـشـ",
        "ar": "ـشـ",
        "small": "ش وسط",
        "en": "Sheen Middle",
        "row": 10,
        "displayCol": 1,
        "audio": "cf_13_m.mp3",
        "video": "cf_13_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_13_f",
        "text": "ـش",
        "ar": "ـش",
        "small": "ش آخر",
        "en": "Sheen Final",
        "row": 10,
        "displayCol": 2,
        "audio": "cf_13_f.mp3",
        "video": "cf_13_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_14_i",
        "text": "ص",
        "ar": "ص",
        "small": "ص منفصل",
        "en": "Saad Independent",
        "row": 10,
        "displayCol": 3,
        "audio": "cf_14_i.mp3",
        "video": "cf_14_i.mp4",
        "filterType": "Independent",
        "pass": 2
      },
      {
        "key": "cf_14_b",
        "text": "صـ",
        "ar": "صـ",
        "small": "ص أول",
        "en": "Saad Beginning",
        "row": 10,
        "displayCol": 4,
        "audio": "cf_14_b.mp3",
        "video": "cf_14_b.mp4",
        "filterType": "Beginning",
        "pass": 2
      },
      {
        "key": "cf_14_m",
        "text": "ـصـ",
        "ar": "ـصـ",
        "small": "ص وسط",
        "en": "Saad Middle",
        "row": 11,
        "displayCol": 1,
        "audio": "cf_14_m.mp3",
        "video": "cf_14_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_14_f",
        "text": "ـص",
        "ar": "ـص",
        "small": "ص آخر",
        "en": "Saad Final",
        "row": 11,
        "displayCol": 2,
        "audio": "cf_14_f.mp3",
        "video": "cf_14_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_15_i",
        "text": "ض",
        "ar": "ض",
        "small": "ض منفصل",
        "en": "Daad Independent",
        "row": 11,
        "displayCol": 3,
        "audio": "cf_15_i.mp3",
        "video": "cf_15_i.mp4",
        "filterType": "Independent",
        "pass": 2
      },
      {
        "key": "cf_15_b",
        "text": "ضـ",
        "ar": "ضـ",
        "small": "ض أول",
        "en": "Daad Beginning",
        "row": 11,
        "displayCol": 4,
        "audio": "cf_15_b.mp3",
        "video": "cf_15_b.mp4",
        "filterType": "Beginning",
        "pass": 2
      },
      {
        "key": "cf_15_m",
        "text": "ـضـ",
        "ar": "ـضـ",
        "small": "ض وسط",
        "en": "Daad Middle",
        "row": 12,
        "displayCol": 1,
        "audio": "cf_15_m.mp3",
        "video": "cf_15_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_15_f",
        "text": "ـض",
        "ar": "ـض",
        "small": "ض آخر",
        "en": "Daad Final",
        "row": 12,
        "displayCol": 2,
        "audio": "cf_15_f.mp3",
        "video": "cf_15_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_16_i",
        "text": "ط",
        "ar": "ط",
        "small": "ط منفصل",
        "en": "Taa heavy Independent",
        "row": 12,
        "displayCol": 3,
        "audio": "cf_16_i.mp3",
        "video": "cf_16_i.mp4",
        "filterType": "Independent",
        "pass": 2
      },
      {
        "key": "cf_16_b",
        "text": "طـ",
        "ar": "طـ",
        "small": "ط أول",
        "en": "Taa heavy Beginning",
        "row": 12,
        "displayCol": 4,
        "audio": "cf_16_b.mp3",
        "video": "cf_16_b.mp4",
        "filterType": "Beginning",
        "pass": 2
      },
      {
        "key": "cf_16_m",
        "text": "ـطـ",
        "ar": "ـطـ",
        "small": "ط وسط",
        "en": "Taa heavy Middle",
        "row": 13,
        "displayCol": 1,
        "audio": "cf_16_m.mp3",
        "video": "cf_16_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_16_f",
        "text": "ـط",
        "ar": "ـط",
        "small": "ط آخر",
        "en": "Taa heavy Final",
        "row": 13,
        "displayCol": 2,
        "audio": "cf_16_f.mp3",
        "video": "cf_16_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_17_i",
        "text": "ظ",
        "ar": "ظ",
        "small": "ظ منفصل",
        "en": "Dhaa heavy Independent",
        "row": 13,
        "displayCol": 3,
        "audio": "cf_17_i.mp3",
        "video": "cf_17_i.mp4",
        "filterType": "Independent",
        "pass": 2
      },
      {
        "key": "cf_17_b",
        "text": "ظـ",
        "ar": "ظـ",
        "small": "ظ أول",
        "en": "Dhaa heavy Beginning",
        "row": 13,
        "displayCol": 4,
        "audio": "cf_17_b.mp3",
        "video": "cf_17_b.mp4",
        "filterType": "Beginning",
        "pass": 2
      },
      {
        "key": "cf_17_m",
        "text": "ـظـ",
        "ar": "ـظـ",
        "small": "ظ وسط",
        "en": "Dhaa heavy Middle",
        "row": 14,
        "displayCol": 1,
        "audio": "cf_17_m.mp3",
        "video": "cf_17_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_17_f",
        "text": "ـظ",
        "ar": "ـظ",
        "small": "ظ آخر",
        "en": "Dhaa heavy Final",
        "row": 14,
        "displayCol": 2,
        "audio": "cf_17_f.mp3",
        "video": "cf_17_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_18_i",
        "text": "ع",
        "ar": "ع",
        "small": "ع منفصل",
        "en": "Ayn Independent",
        "row": 14,
        "displayCol": 3,
        "audio": "cf_18_i.mp3",
        "video": "cf_18_i.mp4",
        "filterType": "Independent",
        "pass": 2
      },
      {
        "key": "cf_18_b",
        "text": "عـ",
        "ar": "عـ",
        "small": "ع أول",
        "en": "Ayn Beginning",
        "row": 14,
        "displayCol": 4,
        "audio": "cf_18_b.mp3",
        "video": "cf_18_b.mp4",
        "filterType": "Beginning",
        "pass": 2
      },
      {
        "key": "cf_18_m",
        "text": "ـعـ",
        "ar": "ـعـ",
        "small": "ع وسط",
        "en": "Ayn Middle",
        "row": 15,
        "displayCol": 1,
        "audio": "cf_18_m.mp3",
        "video": "cf_18_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_18_f",
        "text": "ـع",
        "ar": "ـع",
        "small": "ع آخر",
        "en": "Ayn Final",
        "row": 15,
        "displayCol": 2,
        "audio": "cf_18_f.mp3",
        "video": "cf_18_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_19_i",
        "text": "غ",
        "ar": "غ",
        "small": "غ منفصل",
        "en": "Ghayn Independent",
        "row": 15,
        "displayCol": 3,
        "audio": "cf_19_i.mp3",
        "video": "cf_19_i.mp4",
        "filterType": "Independent",
        "pass": 2
      },
      {
        "key": "cf_19_b",
        "text": "غـ",
        "ar": "غـ",
        "small": "غ أول",
        "en": "Ghayn Beginning",
        "row": 15,
        "displayCol": 4,
        "audio": "cf_19_b.mp3",
        "video": "cf_19_b.mp4",
        "filterType": "Beginning",
        "pass": 2
      },
      {
        "key": "cf_19_m",
        "text": "ـغـ",
        "ar": "ـغـ",
        "small": "غ وسط",
        "en": "Ghayn Middle",
        "row": 16,
        "displayCol": 1,
        "audio": "cf_19_m.mp3",
        "video": "cf_19_m.mp4",
        "filterType": "Middle",
        "pass": 2
      },
      {
        "key": "cf_19_f",
        "text": "ـغ",
        "ar": "ـغ",
        "small": "غ آخر",
        "en": "Ghayn Final",
        "row": 16,
        "displayCol": 2,
        "audio": "cf_19_f.mp3",
        "video": "cf_19_f.mp4",
        "filterType": "Final",
        "pass": 2
      },
      {
        "key": "cf_20_i",
        "text": "ف",
        "ar": "ف",
        "small": "ف منفصل",
        "en": "Faa Independent",
        "row": 16,
        "displayCol": 3,
        "audio": "cf_20_i.mp3",
        "video": "cf_20_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_20_b",
        "text": "فـ",
        "ar": "فـ",
        "small": "ف أول",
        "en": "Faa Beginning",
        "row": 16,
        "displayCol": 4,
        "audio": "cf_20_b.mp3",
        "video": "cf_20_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_20_m",
        "text": "ـفـ",
        "ar": "ـفـ",
        "small": "ف وسط",
        "en": "Faa Middle",
        "row": 17,
        "displayCol": 1,
        "audio": "cf_20_m.mp3",
        "video": "cf_20_m.mp4",
        "filterType": "Middle",
        "pass": 3
      },
      {
        "key": "cf_20_f",
        "text": "ـف",
        "ar": "ـف",
        "small": "ف آخر",
        "en": "Faa Final",
        "row": 17,
        "displayCol": 2,
        "audio": "cf_20_f.mp3",
        "video": "cf_20_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_21_i",
        "text": "ق",
        "ar": "ق",
        "small": "ق منفصل",
        "en": "Qaaf Independent",
        "row": 17,
        "displayCol": 3,
        "audio": "cf_21_i.mp3",
        "video": "cf_21_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_21_b",
        "text": "قـ",
        "ar": "قـ",
        "small": "ق أول",
        "en": "Qaaf Beginning",
        "row": 17,
        "displayCol": 4,
        "audio": "cf_21_b.mp3",
        "video": "cf_21_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_21_m",
        "text": "ـقـ",
        "ar": "ـقـ",
        "small": "ق وسط",
        "en": "Qaaf Middle",
        "row": 18,
        "displayCol": 1,
        "audio": "cf_21_m.mp3",
        "video": "cf_21_m.mp4",
        "filterType": "Middle",
        "pass": 3
      },
      {
        "key": "cf_21_f",
        "text": "ـق",
        "ar": "ـق",
        "small": "ق آخر",
        "en": "Qaaf Final",
        "row": 18,
        "displayCol": 2,
        "audio": "cf_21_f.mp3",
        "video": "cf_21_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_22_i",
        "text": "ك",
        "ar": "ك",
        "small": "ك منفصل",
        "en": "Kaaf Independent",
        "row": 18,
        "displayCol": 3,
        "audio": "cf_22_i.mp3",
        "video": "cf_22_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_22_b",
        "text": "كـ",
        "ar": "كـ",
        "small": "ك أول",
        "en": "Kaaf Beginning",
        "row": 18,
        "displayCol": 4,
        "audio": "cf_22_b.mp3",
        "video": "cf_22_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_22_m",
        "text": "ـكـ",
        "ar": "ـكـ",
        "small": "ك وسط",
        "en": "Kaaf Middle",
        "row": 19,
        "displayCol": 1,
        "audio": "cf_22_m.mp3",
        "video": "cf_22_m.mp4",
        "filterType": "Middle",
        "pass": 3
      },
      {
        "key": "cf_22_f",
        "text": "ـك",
        "ar": "ـك",
        "small": "ك آخر",
        "en": "Kaaf Final",
        "row": 19,
        "displayCol": 2,
        "audio": "cf_22_f.mp3",
        "video": "cf_22_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_23_i",
        "text": "ل",
        "ar": "ل",
        "small": "ل منفصل",
        "en": "Laam Independent",
        "row": 19,
        "displayCol": 3,
        "audio": "cf_23_i.mp3",
        "video": "cf_23_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_23_b",
        "text": "لـ",
        "ar": "لـ",
        "small": "ل أول",
        "en": "Laam Beginning",
        "row": 19,
        "displayCol": 4,
        "audio": "cf_23_b.mp3",
        "video": "cf_23_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_23_m",
        "text": "ـلـ",
        "ar": "ـلـ",
        "small": "ل وسط",
        "en": "Laam Middle",
        "row": 20,
        "displayCol": 1,
        "audio": "cf_23_m.mp3",
        "video": "cf_23_m.mp4",
        "filterType": "Middle",
        "pass": 3
      },
      {
        "key": "cf_23_f",
        "text": "ـل",
        "ar": "ـل",
        "small": "ل آخر",
        "en": "Laam Final",
        "row": 20,
        "displayCol": 2,
        "audio": "cf_23_f.mp3",
        "video": "cf_23_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_24_i",
        "text": "م",
        "ar": "م",
        "small": "م منفصل",
        "en": "Meem Independent",
        "row": 20,
        "displayCol": 3,
        "audio": "cf_24_i.mp3",
        "video": "cf_24_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_24_b",
        "text": "مـ",
        "ar": "مـ",
        "small": "م أول",
        "en": "Meem Beginning",
        "row": 20,
        "displayCol": 4,
        "audio": "cf_24_b.mp3",
        "video": "cf_24_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_24_m",
        "text": "ـمـ",
        "ar": "ـمـ",
        "small": "م وسط",
        "en": "Meem Middle",
        "row": 21,
        "displayCol": 1,
        "audio": "cf_24_m.mp3",
        "video": "cf_24_m.mp4",
        "filterType": "Middle",
        "pass": 3
      },
      {
        "key": "cf_24_f",
        "text": "ـم",
        "ar": "ـم",
        "small": "م آخر",
        "en": "Meem Final",
        "row": 21,
        "displayCol": 2,
        "audio": "cf_24_f.mp3",
        "video": "cf_24_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_25_i",
        "text": "ن",
        "ar": "ن",
        "small": "ن منفصل",
        "en": "Noon Independent",
        "row": 21,
        "displayCol": 3,
        "audio": "cf_25_i.mp3",
        "video": "cf_25_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_25_b",
        "text": "نـ",
        "ar": "نـ",
        "small": "ن أول",
        "en": "Noon Beginning",
        "row": 21,
        "displayCol": 4,
        "audio": "cf_25_b.mp3",
        "video": "cf_25_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_25_m",
        "text": "ـنـ",
        "ar": "ـنـ",
        "small": "ن وسط",
        "en": "Noon Middle",
        "row": 22,
        "displayCol": 1,
        "audio": "cf_25_m.mp3",
        "video": "cf_25_m.mp4",
        "filterType": "Middle",
        "pass": 3
      },
      {
        "key": "cf_25_f",
        "text": "ـن",
        "ar": "ـن",
        "small": "ن آخر",
        "en": "Noon Final",
        "row": 22,
        "displayCol": 2,
        "audio": "cf_25_f.mp3",
        "video": "cf_25_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_26_i",
        "text": "ه",
        "ar": "ه",
        "small": "ه منفصل",
        "en": "Haa Independent",
        "row": 22,
        "displayCol": 3,
        "audio": "cf_26_i.mp3",
        "video": "cf_26_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_26_b",
        "text": "هـ",
        "ar": "هـ",
        "small": "ه أول",
        "en": "Haa Beginning",
        "row": 22,
        "displayCol": 4,
        "audio": "cf_26_b.mp3",
        "video": "cf_26_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_26_m",
        "text": "ـهـ",
        "ar": "ـهـ",
        "small": "ه وسط",
        "en": "Haa Middle",
        "row": 23,
        "displayCol": 1,
        "audio": "cf_26_m.mp3",
        "video": "cf_26_m.mp4",
        "filterType": "Middle",
        "pass": 3
      },
      {
        "key": "cf_26_f",
        "text": "ـه",
        "ar": "ـه",
        "small": "ه آخر",
        "en": "Haa Final",
        "row": 23,
        "displayCol": 2,
        "audio": "cf_26_f.mp3",
        "video": "cf_26_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_27_i",
        "text": "و",
        "ar": "و",
        "small": "و منفصل",
        "en": "Waw Independent",
        "row": 23,
        "displayCol": 3,
        "audio": "cf_27_i.mp3",
        "video": "cf_27_i.mp4",
        "filterType": "Independent",
        "pass": 3
      },
      {
        "key": "cf_27_f",
        "text": "ـو",
        "ar": "ـو",
        "small": "و آخر",
        "en": "Waw Final",
        "row": 23,
        "displayCol": 4,
        "audio": "cf_27_f.mp3",
        "video": "cf_27_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_28_b",
        "text": "يـ",
        "ar": "يـ",
        "small": "ي أول",
        "en": "Yaa Beginning",
        "row": 24,
        "displayCol": 1,
        "audio": "cf_28_b.mp3",
        "video": "cf_28_b.mp4",
        "filterType": "Beginning",
        "pass": 3
      },
      {
        "key": "cf_28_f",
        "text": "ـي",
        "ar": "ـي",
        "small": "ي آخر",
        "en": "Yaa Final",
        "row": 24,
        "displayCol": 2,
        "audio": "cf_28_f.mp3",
        "video": "cf_28_f.mp4",
        "filterType": "Final",
        "pass": 3
      },
      {
        "key": "cf_join4_01",
        "text": "بـت",
        "ar": "بـت",
        "small": "2-letter joins",
        "en": "ب ت",
        "row": 1,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_02",
        "text": "بـج",
        "ar": "بـج",
        "small": "2-letter joins",
        "en": "ب ج",
        "row": 1,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_03",
        "text": "بـس",
        "ar": "بـس",
        "small": "2-letter joins",
        "en": "ب س",
        "row": 1,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_04",
        "text": "بـم",
        "ar": "بـم",
        "small": "2-letter joins",
        "en": "ب م",
        "row": 1,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_05",
        "text": "بـن",
        "ar": "بـن",
        "small": "2-letter joins",
        "en": "ب ن",
        "row": 2,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_06",
        "text": "بـي",
        "ar": "بـي",
        "small": "2-letter joins",
        "en": "ب ي",
        "row": 2,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_07",
        "text": "تـب",
        "ar": "تـب",
        "small": "2-letter joins",
        "en": "ت ب",
        "row": 2,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_08",
        "text": "تـح",
        "ar": "تـح",
        "small": "2-letter joins",
        "en": "ت ح",
        "row": 2,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_09",
        "text": "تـش",
        "ar": "تـش",
        "small": "2-letter joins",
        "en": "ت ش",
        "row": 3,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_10",
        "text": "تـل",
        "ar": "تـل",
        "small": "2-letter joins",
        "en": "ت ل",
        "row": 3,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_11",
        "text": "تـو",
        "ar": "تـو",
        "small": "2-letter joins",
        "en": "ت و",
        "row": 3,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_12",
        "text": "تـي",
        "ar": "تـي",
        "small": "2-letter joins",
        "en": "ت ي",
        "row": 3,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_13",
        "text": "ثـب",
        "ar": "ثـب",
        "small": "2-letter joins",
        "en": "ث ب",
        "row": 4,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_14",
        "text": "ثـج",
        "ar": "ثـج",
        "small": "2-letter joins",
        "en": "ث ج",
        "row": 4,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_15",
        "text": "ثـص",
        "ar": "ثـص",
        "small": "2-letter joins",
        "en": "ث ص",
        "row": 4,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_16",
        "text": "ثـك",
        "ar": "ثـك",
        "small": "2-letter joins",
        "en": "ث ك",
        "row": 4,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_17",
        "text": "ثـم",
        "ar": "ثـم",
        "small": "2-letter joins",
        "en": "ث م",
        "row": 5,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_18",
        "text": "ثـه",
        "ar": "ثـه",
        "small": "2-letter joins",
        "en": "ث ه",
        "row": 5,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_19",
        "text": "جـب",
        "ar": "جـب",
        "small": "2-letter joins",
        "en": "ج ب",
        "row": 5,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_20",
        "text": "جـت",
        "ar": "جـت",
        "small": "2-letter joins",
        "en": "ج ت",
        "row": 5,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_21",
        "text": "جـس",
        "ar": "جـس",
        "small": "2-letter joins",
        "en": "ج س",
        "row": 6,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_22",
        "text": "جـع",
        "ar": "جـع",
        "small": "2-letter joins",
        "en": "ج ع",
        "row": 6,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_23",
        "text": "جـف",
        "ar": "جـف",
        "small": "2-letter joins",
        "en": "ج ف",
        "row": 6,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_24",
        "text": "جـن",
        "ar": "جـن",
        "small": "2-letter joins",
        "en": "ج ن",
        "row": 6,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_25",
        "text": "حـب",
        "ar": "حـب",
        "small": "2-letter joins",
        "en": "ح ب",
        "row": 7,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_26",
        "text": "حـث",
        "ar": "حـث",
        "small": "2-letter joins",
        "en": "ح ث",
        "row": 7,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_27",
        "text": "حـش",
        "ar": "حـش",
        "small": "2-letter joins",
        "en": "ح ش",
        "row": 7,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_28",
        "text": "حـق",
        "ar": "حـق",
        "small": "2-letter joins",
        "en": "ح ق",
        "row": 7,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_29",
        "text": "حـل",
        "ar": "حـل",
        "small": "2-letter joins",
        "en": "ح ل",
        "row": 8,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_30",
        "text": "حـي",
        "ar": "حـي",
        "small": "2-letter joins",
        "en": "ح ي",
        "row": 8,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_31",
        "text": "خـب",
        "ar": "خـب",
        "small": "2-letter joins",
        "en": "خ ب",
        "row": 8,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_32",
        "text": "خـج",
        "ar": "خـج",
        "small": "2-letter joins",
        "en": "خ ج",
        "row": 8,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_33",
        "text": "خـص",
        "ar": "خـص",
        "small": "2-letter joins",
        "en": "خ ص",
        "row": 9,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_34",
        "text": "خـط",
        "ar": "خـط",
        "small": "2-letter joins",
        "en": "خ ط",
        "row": 9,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_35",
        "text": "خـم",
        "ar": "خـم",
        "small": "2-letter joins",
        "en": "خ م",
        "row": 9,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_36",
        "text": "خـو",
        "ar": "خـو",
        "small": "2-letter joins",
        "en": "خ و",
        "row": 9,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_37",
        "text": "سـب",
        "ar": "سـب",
        "small": "2-letter joins",
        "en": "س ب",
        "row": 10,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_38",
        "text": "سـت",
        "ar": "سـت",
        "small": "2-letter joins",
        "en": "س ت",
        "row": 10,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_39",
        "text": "سـج",
        "ar": "سـج",
        "small": "2-letter joins",
        "en": "س ج",
        "row": 10,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_40",
        "text": "سـض",
        "ar": "سـض",
        "small": "2-letter joins",
        "en": "س ض",
        "row": 10,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_41",
        "text": "سـك",
        "ar": "سـك",
        "small": "2-letter joins",
        "en": "س ك",
        "row": 11,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_42",
        "text": "سـن",
        "ar": "سـن",
        "small": "2-letter joins",
        "en": "س ن",
        "row": 11,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_43",
        "text": "شـب",
        "ar": "شـب",
        "small": "2-letter joins",
        "en": "ش ب",
        "row": 11,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_44",
        "text": "شـث",
        "ar": "شـث",
        "small": "2-letter joins",
        "en": "ش ث",
        "row": 11,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_45",
        "text": "شـح",
        "ar": "شـح",
        "small": "2-letter joins",
        "en": "ش ح",
        "row": 12,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_46",
        "text": "شـغ",
        "ar": "شـغ",
        "small": "2-letter joins",
        "en": "ش غ",
        "row": 12,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_47",
        "text": "شـل",
        "ar": "شـل",
        "small": "2-letter joins",
        "en": "ش ل",
        "row": 12,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_48",
        "text": "شـي",
        "ar": "شـي",
        "small": "2-letter joins",
        "en": "ش ي",
        "row": 12,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_49",
        "text": "صـب",
        "ar": "صـب",
        "small": "2-letter joins",
        "en": "ص ب",
        "row": 13,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_50",
        "text": "صـج",
        "ar": "صـج",
        "small": "2-letter joins",
        "en": "ص ج",
        "row": 13,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_51",
        "text": "صـد",
        "ar": "صـد",
        "small": "2-letter joins",
        "en": "ص د",
        "row": 13,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_52",
        "text": "صـف",
        "ar": "صـف",
        "small": "2-letter joins",
        "en": "ص ف",
        "row": 13,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_53",
        "text": "صـم",
        "ar": "صـم",
        "small": "2-letter joins",
        "en": "ص م",
        "row": 14,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_54",
        "text": "صـو",
        "ar": "صـو",
        "small": "2-letter joins",
        "en": "ص و",
        "row": 14,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_55",
        "text": "ضـب",
        "ar": "ضـب",
        "small": "2-letter joins",
        "en": "ض ب",
        "row": 14,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_56",
        "text": "ضـح",
        "ar": "ضـح",
        "small": "2-letter joins",
        "en": "ض ح",
        "row": 14,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_57",
        "text": "ضـر",
        "ar": "ضـر",
        "small": "2-letter joins",
        "en": "ض ر",
        "row": 15,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_58",
        "text": "ضـق",
        "ar": "ضـق",
        "small": "2-letter joins",
        "en": "ض ق",
        "row": 15,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_59",
        "text": "ضـن",
        "ar": "ضـن",
        "small": "2-letter joins",
        "en": "ض ن",
        "row": 15,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join4_60",
        "text": "ضـي",
        "ar": "ضـي",
        "small": "2-letter joins",
        "en": "ض ي",
        "row": 15,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 4
      },
      {
        "key": "cf_join5_01",
        "text": "بابت",
        "ar": "بابت",
        "small": "3-letter joins",
        "en": "ب ا ب ت",
        "row": 1,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_02",
        "text": "تثج",
        "ar": "تثج",
        "small": "3-letter joins",
        "en": "ت ث ج",
        "row": 1,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_03",
        "text": "جحخ",
        "ar": "جحخ",
        "small": "3-letter joins",
        "en": "ج ح خ",
        "row": 1,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_04",
        "text": "دذر",
        "ar": "دذر",
        "small": "3-letter joins",
        "en": "د ذ ر",
        "row": 1,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_05",
        "text": "رزس",
        "ar": "رزس",
        "small": "3-letter joins",
        "en": "ر ز س",
        "row": 2,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_06",
        "text": "شصض",
        "ar": "شصض",
        "small": "3-letter joins",
        "en": "ش ص ض",
        "row": 2,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_07",
        "text": "طظع",
        "ar": "طظع",
        "small": "3-letter joins",
        "en": "ط ظ ع",
        "row": 2,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_08",
        "text": "غفق",
        "ar": "غفق",
        "small": "3-letter joins",
        "en": "غ ف ق",
        "row": 2,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_09",
        "text": "كلم",
        "ar": "كلم",
        "small": "3-letter joins",
        "en": "ك ل م",
        "row": 3,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_10",
        "text": "نهو",
        "ar": "نهو",
        "small": "3-letter joins",
        "en": "ن ه و",
        "row": 3,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_11",
        "text": "ويب",
        "ar": "ويب",
        "small": "3-letter joins",
        "en": "و ي ب",
        "row": 3,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_12",
        "text": "يتج",
        "ar": "يتج",
        "small": "3-letter joins",
        "en": "ي ت ج",
        "row": 3,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_13",
        "text": "ثحب",
        "ar": "ثحب",
        "small": "3-letter joins",
        "en": "ث ح ب",
        "row": 4,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_14",
        "text": "خدس",
        "ar": "خدس",
        "small": "3-letter joins",
        "en": "خ د س",
        "row": 4,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_15",
        "text": "ذرش",
        "ar": "ذرش",
        "small": "3-letter joins",
        "en": "ذ ر ش",
        "row": 4,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_16",
        "text": "زصض",
        "ar": "زصض",
        "small": "3-letter joins",
        "en": "ز ص ض",
        "row": 4,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_17",
        "text": "طعغ",
        "ar": "طعغ",
        "small": "3-letter joins",
        "en": "ط ع غ",
        "row": 5,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_18",
        "text": "فقك",
        "ar": "فقك",
        "small": "3-letter joins",
        "en": "ف ق ك",
        "row": 5,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_19",
        "text": "لمن",
        "ar": "لمن",
        "small": "3-letter joins",
        "en": "ل م ن",
        "row": 5,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_20",
        "text": "هوي",
        "ar": "هوي",
        "small": "3-letter joins",
        "en": "ه و ي",
        "row": 5,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_21",
        "text": "ابج",
        "ar": "ابج",
        "small": "3-letter joins",
        "en": "ا ب ج",
        "row": 6,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_22",
        "text": "بتح",
        "ar": "بتح",
        "small": "3-letter joins",
        "en": "ب ت ح",
        "row": 6,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_23",
        "text": "ثخد",
        "ar": "ثخد",
        "small": "3-letter joins",
        "en": "ث خ د",
        "row": 6,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_24",
        "text": "جذر",
        "ar": "جذر",
        "small": "3-letter joins",
        "en": "ج ذ ر",
        "row": 6,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_25",
        "text": "حسز",
        "ar": "حسز",
        "small": "3-letter joins",
        "en": "ح س ز",
        "row": 7,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_26",
        "text": "خشص",
        "ar": "خشص",
        "small": "3-letter joins",
        "en": "خ ش ص",
        "row": 7,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_27",
        "text": "ضطع",
        "ar": "ضطع",
        "small": "3-letter joins",
        "en": "ض ط ع",
        "row": 7,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_28",
        "text": "ظغف",
        "ar": "ظغف",
        "small": "3-letter joins",
        "en": "ظ غ ف",
        "row": 7,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_29",
        "text": "قكل",
        "ar": "قكل",
        "small": "3-letter joins",
        "en": "ق ك ل",
        "row": 8,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_30",
        "text": "منه",
        "ar": "منه",
        "small": "3-letter joins",
        "en": "م ن ه",
        "row": 8,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_31",
        "text": "ويب",
        "ar": "ويب",
        "small": "3-letter joins",
        "en": "و ي ب",
        "row": 8,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_32",
        "text": "يتث",
        "ar": "يتث",
        "small": "3-letter joins",
        "en": "ي ت ث",
        "row": 8,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_33",
        "text": "بجح",
        "ar": "بجح",
        "small": "3-letter joins",
        "en": "ب ج ح",
        "row": 9,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_34",
        "text": "تدذ",
        "ar": "تدذ",
        "small": "3-letter joins",
        "en": "ت د ذ",
        "row": 9,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_35",
        "text": "ثرز",
        "ar": "ثرز",
        "small": "3-letter joins",
        "en": "ث ر ز",
        "row": 9,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_36",
        "text": "جسش",
        "ar": "جسش",
        "small": "3-letter joins",
        "en": "ج س ش",
        "row": 9,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_37",
        "text": "حصض",
        "ar": "حصض",
        "small": "3-letter joins",
        "en": "ح ص ض",
        "row": 10,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_38",
        "text": "خطظ",
        "ar": "خطظ",
        "small": "3-letter joins",
        "en": "خ ط ظ",
        "row": 10,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_39",
        "text": "دعغ",
        "ar": "دعغ",
        "small": "3-letter joins",
        "en": "د ع غ",
        "row": 10,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join5_40",
        "text": "ذفق",
        "ar": "ذفق",
        "small": "3-letter joins",
        "en": "ذ ف ق",
        "row": 10,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 5
      },
      {
        "key": "cf_join6_01",
        "text": "ابتث",
        "ar": "ابتث",
        "small": "4-letter joins",
        "en": "ا ب ت ث",
        "row": 1,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_02",
        "text": "جحخد",
        "ar": "جحخد",
        "small": "4-letter joins",
        "en": "ج ح خ د",
        "row": 1,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_03",
        "text": "ذرزس",
        "ar": "ذرزس",
        "small": "4-letter joins",
        "en": "ذ ر ز س",
        "row": 1,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_04",
        "text": "شصضط",
        "ar": "شصضط",
        "small": "4-letter joins",
        "en": "ش ص ض ط",
        "row": 1,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_05",
        "text": "ظعغف",
        "ar": "ظعغف",
        "small": "4-letter joins",
        "en": "ظ ع غ ف",
        "row": 2,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_06",
        "text": "قكلم",
        "ar": "قكلم",
        "small": "4-letter joins",
        "en": "ق ك ل م",
        "row": 2,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_07",
        "text": "نهوي",
        "ar": "نهوي",
        "small": "4-letter joins",
        "en": "ن ه و ي",
        "row": 2,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_08",
        "text": "بتثج",
        "ar": "بتثج",
        "small": "4-letter joins",
        "en": "ب ت ث ج",
        "row": 2,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_09",
        "text": "حخدر",
        "ar": "حخدر",
        "small": "4-letter joins",
        "en": "ح خ د ر",
        "row": 3,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_10",
        "text": "زسشص",
        "ar": "زسشص",
        "small": "4-letter joins",
        "en": "ز س ش ص",
        "row": 3,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_11",
        "text": "ضطظع",
        "ar": "ضطظع",
        "small": "4-letter joins",
        "en": "ض ط ظ ع",
        "row": 3,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_12",
        "text": "غفقك",
        "ar": "غفقك",
        "small": "4-letter joins",
        "en": "غ ف ق ك",
        "row": 3,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_13",
        "text": "لمنه",
        "ar": "لمنه",
        "small": "4-letter joins",
        "en": "ل م ن ه",
        "row": 4,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_14",
        "text": "وياب",
        "ar": "وياب",
        "small": "4-letter joins",
        "en": "و ي ا ب",
        "row": 4,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_15",
        "text": "تثجح",
        "ar": "تثجح",
        "small": "4-letter joins",
        "en": "ت ث ج ح",
        "row": 4,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_16",
        "text": "خدذر",
        "ar": "خدذر",
        "small": "4-letter joins",
        "en": "خ د ذ ر",
        "row": 4,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_17",
        "text": "رزسش",
        "ar": "رزسش",
        "small": "4-letter joins",
        "en": "ر ز س ش",
        "row": 5,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_18",
        "text": "صضطع",
        "ar": "صضطع",
        "small": "4-letter joins",
        "en": "ص ض ط ع",
        "row": 5,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_19",
        "text": "ظعغف",
        "ar": "ظعغف",
        "small": "4-letter joins",
        "en": "ظ ع غ ف",
        "row": 5,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_20",
        "text": "قكلم",
        "ar": "قكلم",
        "small": "4-letter joins",
        "en": "ق ك ل م",
        "row": 5,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_21",
        "text": "نهوي",
        "ar": "نهوي",
        "small": "4-letter joins",
        "en": "ن ه و ي",
        "row": 6,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_22",
        "text": "ابجح",
        "ar": "ابجح",
        "small": "4-letter joins",
        "en": "ا ب ج ح",
        "row": 6,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_23",
        "text": "تثخد",
        "ar": "تثخد",
        "small": "4-letter joins",
        "en": "ت ث خ د",
        "row": 6,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_24",
        "text": "ذرسش",
        "ar": "ذرسش",
        "small": "4-letter joins",
        "en": "ذ ر س ش",
        "row": 6,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_25",
        "text": "صضطظ",
        "ar": "صضطظ",
        "small": "4-letter joins",
        "en": "ص ض ط ظ",
        "row": 7,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_26",
        "text": "عغفق",
        "ar": "عغفق",
        "small": "4-letter joins",
        "en": "ع غ ف ق",
        "row": 7,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_27",
        "text": "كلمن",
        "ar": "كلمن",
        "small": "4-letter joins",
        "en": "ك ل م ن",
        "row": 7,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_28",
        "text": "هويـت",
        "ar": "هويـت",
        "small": "4-letter joins",
        "en": "ه و ي ت",
        "row": 7,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_29",
        "text": "بثجح",
        "ar": "بثجح",
        "small": "4-letter joins",
        "en": "ب ث ج ح",
        "row": 8,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join6_30",
        "text": "خدذر",
        "ar": "خدذر",
        "small": "4-letter joins",
        "en": "خ د ذ ر",
        "row": 8,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 6
      },
      {
        "key": "cf_join7_01",
        "text": "ابتثج",
        "ar": "ابتثج",
        "small": "5-letter joins",
        "en": "ا ب ت ث ج",
        "row": 1,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_02",
        "text": "حخدذر",
        "ar": "حخدذر",
        "small": "5-letter joins",
        "en": "ح خ د ذ ر",
        "row": 1,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_03",
        "text": "زسشصض",
        "ar": "زسشصض",
        "small": "5-letter joins",
        "en": "ز س ش ص ض",
        "row": 1,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_04",
        "text": "طظعغف",
        "ar": "طظعغف",
        "small": "5-letter joins",
        "en": "ط ظ ع غ ف",
        "row": 1,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_05",
        "text": "قكلمن",
        "ar": "قكلمن",
        "small": "5-letter joins",
        "en": "ق ك ل م ن",
        "row": 2,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_06",
        "text": "هوياب",
        "ar": "هوياب",
        "small": "5-letter joins",
        "en": "ه و ي ا ب",
        "row": 2,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_07",
        "text": "تثجحخ",
        "ar": "تثجحخ",
        "small": "5-letter joins",
        "en": "ت ث ج ح خ",
        "row": 2,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_08",
        "text": "دذرزس",
        "ar": "دذرزس",
        "small": "5-letter joins",
        "en": "د ذ ر ز س",
        "row": 2,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_09",
        "text": "شصضطظ",
        "ar": "شصضطظ",
        "small": "5-letter joins",
        "en": "ش ص ض ط ظ",
        "row": 3,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_10",
        "text": "عغفقك",
        "ar": "عغفقك",
        "small": "5-letter joins",
        "en": "ع غ ف ق ك",
        "row": 3,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_11",
        "text": "لمنهو",
        "ar": "لمنهو",
        "small": "5-letter joins",
        "en": "ل م ن ه و",
        "row": 3,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_12",
        "text": "يابتث",
        "ar": "يابتث",
        "small": "5-letter joins",
        "en": "ي ا ب ت ث",
        "row": 3,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_13",
        "text": "جحخدذ",
        "ar": "جحخدذ",
        "small": "5-letter joins",
        "en": "ج ح خ د ذ",
        "row": 4,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_14",
        "text": "رزسشص",
        "ar": "رزسشص",
        "small": "5-letter joins",
        "en": "ر ز س ش ص",
        "row": 4,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_15",
        "text": "ضطظعغ",
        "ar": "ضطظعغ",
        "small": "5-letter joins",
        "en": "ض ط ظ ع غ",
        "row": 4,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_16",
        "text": "فقكلم",
        "ar": "فقكلم",
        "small": "5-letter joins",
        "en": "ف ق ك ل م",
        "row": 4,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_17",
        "text": "نهوياب",
        "ar": "نهوياب",
        "small": "5-letter joins",
        "en": "ن ه و ي ا ب",
        "row": 5,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_18",
        "text": "تثجحخ",
        "ar": "تثجحخ",
        "small": "5-letter joins",
        "en": "ت ث ج ح خ",
        "row": 5,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_19",
        "text": "دذرزس",
        "ar": "دذرزس",
        "small": "5-letter joins",
        "en": "د ذ ر ز س",
        "row": 5,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_20",
        "text": "شصضطظ",
        "ar": "شصضطظ",
        "small": "5-letter joins",
        "en": "ش ص ض ط ظ",
        "row": 5,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_21",
        "text": "عغفقك",
        "ar": "عغفقك",
        "small": "5-letter joins",
        "en": "ع غ ف ق ك",
        "row": 6,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_22",
        "text": "لمنهوي",
        "ar": "لمنهوي",
        "small": "5-letter joins",
        "en": "ل م ن ه و ي",
        "row": 6,
        "displayCol": 2,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_23",
        "text": "ابتثج",
        "ar": "ابتثج",
        "small": "5-letter joins",
        "en": "ا ب ت ث ج",
        "row": 6,
        "displayCol": 3,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_24",
        "text": "حخدذر",
        "ar": "حخدذر",
        "small": "5-letter joins",
        "en": "ح خ د ذ ر",
        "row": 6,
        "displayCol": 4,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      },
      {
        "key": "cf_join7_25",
        "text": "زسشصض",
        "ar": "زسشصض",
        "small": "5-letter joins",
        "en": "ز س ش ص ض",
        "row": 7,
        "displayCol": 1,
        "audio": "cf_01_i.mp3",
        "video": "cf_01_i.mp4",
        "filterType": "",
        "pass": 7
      }
    ]
  },
  "assetVersion": "joint-rules-20260601a",
  "ASSET_VERSION": "joint-rules-20260601a"
}
);

if (typeof window !== 'undefined') {
  window.UNIT_CFG = UNIT_CFG;
}
