# -*- coding: utf-8 -*-
"""
The Convincing step: a claim, three reasons, one of which does the work.

Cambridge defines Convincing as "presenting evidence to justify or challenge a
mathematical idea or solution". A tap-to-answer deck cannot ask a child to write
a justification, so this asks them to RECOGNISE one - which is the honest
approximation, and is recorded as an approximation rather than as coverage.

Every wrong reason is one of two kinds, and both are deliberate:
  - a plain misconception (the error the wrong answers already encode)
  - something TRUE that explains nothing ("they are both small numbers")
The second kind is the point of the step.
"""

# shared narration - the idea is identical in every lesson, so the script is too
EXPLAIN = (
    '<mstts:express-as style="calm" styledegree="1.15"><prosody rate="-8%">'
    '<s>Getting the right answer is only half of it.</s><s>Knowing why it is right is the other half.</s>'
    '</prosody></mstts:express-as><break time="330ms"/>'
    '<mstts:express-as style="friendly" styledegree="1.25">'
    '<s>Here is something that is true.</s><s>Underneath are three reasons somebody gave for it.</s>'
    '<s>Only one of them actually explains it.</s></mstts:express-as><break time="330ms"/>'
    '<mstts:express-as style="empathetic" styledegree="1.3"><prosody rate="-6%">'
    '<s>Watch for a reason that is true and still explains nothing.</s>'
    '<s>Both numbers are small can be perfectly true and tell you nothing about why the answer is what it is.</s>'
    '</prosody></mstts:express-as><break time="330ms"/>'
    '<mstts:express-as style="cheerful" styledegree="1.45">'
    '<s>Read all three, then pick the one that really does the work.</s></mstts:express-as>'
)

# claim, the reason that works, two that do not, and what makes the difference
G3 = {
"up-to-a-thousand": [
 ("348 is bigger than 315.",
  "Both have 3 hundreds, so look at the tens: 4 tens beats 1 ten.",
  ["348 has more digits than 315.", "8 is bigger than 5."],
  "Start at the biggest column. The hundreds match, so the tens settle it and the ones never get a say."),
 ("70 × 10 = 700.",
  "Every digit moves one column left, so the 7 tens become 7 hundreds.",
  ["You add a zero on the end.", "70 and 10 both end in zero, so the answer does too."],
  "Adding a zero happens to work for whole numbers and stops working the moment there is a decimal point. The move is the part that is actually true."),
 ("462 is even.",
  "It ends in 2, and 2 shares into two equal groups.",
  ["It has a 4 at the front, and 4 is even.", "462 is a big number, and big numbers are even."],
  "Only the last digit decides. The hundreds and the tens make no difference at all."),
 ("In 505 the two 5s are not worth the same.",
  "The left 5 stands in the hundreds column and the right one in the ones, so they are worth 500 and 5.",
  ["One of them is written first.", "The 0 in the middle makes them different."],
  "Position decides value. The digit only says how many."),
 ("607 rounds to 610 to the nearest ten.",
  "607 is past 605, which is halfway between 600 and 610.",
  ["600 is nearer because 607 starts with a 6.", "607 has a 7 in it, and 7 is a big digit."],
  "Find the two tens either side, mark halfway, then see which side the number falls."),
 ("63 + 28 is easier worked out as 63 + 30 − 2.",
  "30 is a round number to add, and taking the extra 2 back off puts it right.",
  ["28 and 30 are the same.", "You can add numbers in any order, so it does not matter."],
  "The second one is perfectly true and still does not explain this move. Adding a round number is what makes it easier."),
],
"rows-and-rules": [
 ("If you know 8 × 5 = 40, you already know 5 × 8.",
  "Turning an array on its side does not change how many dots are in it.",
  ["8 and 5 are both in the answer 40.", "5 and 8 are both smaller than 40."],
  "One array, read two ways. That is why every times fact you learn is really two."),
 ("24 × 3 = 72.",
  "20 threes are 60 and 4 threes are 12, and 60 + 12 = 72.",
  ["20 threes are 60, so the answer is 60.", "24 and 3 both go into 72."],
  "Both parts have to be multiplied. Stopping at the tens leaves you exactly the ones part short."),
 ("17 shared between 5 leaves 2 over.",
  "5 threes are 15, and 17 − 15 = 2, and 2 is smaller than 5.",
  ["17 and 5 are both odd numbers.", "2 is left because 17 ends in a 7."],
  "The check that costs nothing: the remainder must be smaller than the number of groups, or everybody could have had one more."),
 ("245 is a multiple of 5.",
  "It ends in 5, and every multiple of 5 ends in 0 or 5.",
  ["It has a 5 in it.", "2 + 4 + 5 = 11, and 11 is odd."],
  "Having a 5 somewhere is not the test. The last digit is."),
 ("The sequence 4, 7, 10, 13 goes up in 3s.",
  "Every number is 3 more than the one before, and that happens every time.",
  ["7 − 4 = 3.", "It starts at 4 and ends at 13."],
  "One gap is not enough. 2, 4, 8 looks like adding 2 until you reach the 8."),
 ("If ? + 9 = 21 then the box is 12.",
  "Taking the 9 back off 21 leaves 12, and 12 + 9 = 21 puts it back.",
  ["21 and 9 both have a 1 in them.", "9 + 21 = 30, so the box is 30."],
  "Undo what was done, then put your answer back in to check it."),
],
"equal-parts": [
 ("A shape cut into 4 pieces is not always cut into quarters.",
  "Quarters have to be four equal pieces, and these are not the same size.",
  ["Quarters have to be square.", "You can only make quarters from a circle."],
  "Equal is the word that does the work. Four pieces is not enough on its own."),
 ("One half and five tenths are worth the same.",
  "Both colour exactly half the bar - the pieces are just smaller and there are more of them.",
  ["5 and 10 are bigger numbers, so five tenths is bigger.", "They both have a 5 in them."],
  "Bigger numbers do not make a bigger fraction."),
 ("One quarter is bigger than one tenth.",
  "Sharing between 4 gives everybody a bigger piece than sharing between 10.",
  ["4 is smaller than 10, so one quarter is smaller.", "They are both one piece, so they are equal."],
  "With single pieces the bigger bottom number makes the smaller piece."),
 ("Two fifths plus one fifth is three fifths, not three tenths.",
  "You counted pieces without changing their size, so the bottom number stays 5.",
  ["5 + 5 = 10, so the bottom becomes 10.", "2 + 1 = 3, so the answer is just 3."],
  "The bottom number says how big each piece is. Adding pieces does not make them smaller."),
 ("Three quarters of 20 is 15.",
  "20 ÷ 4 = 5 for one quarter, then 5 × 3 = 15 for three of them.",
  ["3 × 4 = 12, and 20 − 12 = 8.", "20 − 4 − 3 = 13."],
  "Divide by the bottom to find one part, then multiply by the top."),
 ("Two shapes can look completely different and both show one half.",
  "What makes it a half is the size of the part next to the whole, not the shape it happens to be.",
  ["Only if the two shapes are the same size.", "Only if both are cut straight down the middle."],
  "A square cut corner to corner and a circle cut across are both halves."),
],
"sides-sizes-seconds": [
 ("A squashed six-sided shape is still a hexagon.",
  "A hexagon is any shape with six straight sides; being squashed makes it irregular, not something else.",
  ["Only regular shapes get names.", "It is a hexagon because it is wide."],
  "Regular tells you the sides are equal. The name tells you how many there are."),
 ("A rectangle 6 cm by 2 cm has a perimeter of 16 cm.",
  "6 + 2 + 6 + 2 = 16, because the other two sides are the same as the first two.",
  ["6 + 2 = 8.", "6 × 2 = 12."],
  "Only two numbers get written on a rectangle because the other two match. They still have to be added."),
 ("Two shapes can cover the same number of squares and have different perimeters.",
  "Area is the space inside and perimeter is the distance round the edge, and they do not grow together.",
  ["That cannot happen - same area always means same perimeter.", "Only if one of them is a circle."],
  "A long thin rectangle and a fat one can cover the same squares and have very different edges."),
 ("A parallelogram has no line of symmetry.",
  "Folding it either way leaves the two halves not matching, even though the fold does make two equal pieces.",
  ["It has none because it has four sides.", "It has one straight down the middle."],
  "Cutting into two equal pieces is not enough. The halves have to be mirror images."),
 ("At twenty five minutes to four, the hour is still 3.",
  "The short hand has passed the 3 and has not reached the 4 yet.",
  ["The long hand is near the 4, so the hour is 4.", "It is 4 because twenty five to four has a 4 in it."],
  "Read the hour the short hand has passed, never the one it is heading for."),
 ("You would measure a pencil in centimetres, not kilometres.",
  "A pencil is about 15 cm; measured in kilometres the number would be far too small to be any use.",
  ["Kilometres are only for measuring roads.", "A pencil cannot be measured in kilometres at all."],
  "Any unit would work. You pick the one that gives a sensible number."),
],
"ask-count-chart": [
 ("Asking the class their favourite fruit needs data; asking how many days are in a week does not.",
  "The first has different answers from different people; the second has one answer for everybody.",
  ["The first is a longer question.", "The second one is about maths and the first one is not."],
  "The test is whether the answers would vary."),
 ("On a pictogram where one picture means 5, four pictures mean 20.",
  "Each picture stands for 5, and 4 × 5 = 20.",
  ["There are four pictures, so it is 4.", "5 + 4 = 9."],
  "Read the key first, every single time."),
 ("Rolling a 7 on an ordinary dice will not happen.",
  "An ordinary dice only has the numbers 1 to 6 on it, so there is no 7 to land on.",
  ["It is very unlikely, but it could still happen.", "It will not happen because 7 is a big number."],
  "Save will not for things that genuinely cannot happen. Unlikely is a different thing."),
 ("A tally is better than a bar chart for counting cars as they drive past.",
  "You can add one mark as each car passes; you cannot draw a bar for cars that have already gone.",
  ["Tallies are always better than bar charts.", "Bar charts do not work outdoors."],
  "Each way of showing data is good at one thing. This one is about keeping up while it happens."),
 ("A number in the middle of a Venn diagram is in both hoops.",
  "The middle is where the two hoops overlap, so it answers yes to both questions.",
  ["The middle means it is in neither hoop.", "The middle is for the ones you are not sure about."],
  "Outside both hoops is the part that means neither."),
 ("Three spins of a spinner do not tell you which colour is most likely.",
  "A few spins can come out any way at all; the pattern only shows after many.",
  ["Spinners are always fair.", "Three spins is plenty to be sure."],
  "The smallest colour can easily win the first three."),
],
}

G1 = {
"up-to-twenty": [
 ("There are 12 counters, even when they are spread out.",
  "Moving them apart does not add any, so there are still 12.",
  ["Spread out means there are more.", "You have to count again to make more."],
  "How many does not change when you move things about."),
 ("13 is bigger than 11.",
  "13 comes after 11 when you count, so it is more.",
  ["13 has a 3 in it, and 3 is small.", "They are the same because both start with a 1."],
  "The one you say later when counting is the bigger one."),
 ("7 is an odd number.",
  "If you pair them up, one is left on its own.",
  ["7 is odd because it is a small number.", "7 is odd because it has a 7 in it."],
  "Pair them off. If one is left alone, it is odd."),
 ("6 and 4 make 10.",
  "Put 6 in the ten frame and then 4 more, and it is exactly full.",
  ["6 and 4 both fit in a frame.", "6 and 4 make 11."],
  "A full ten frame is ten."),
 ("Double 5 is 10.",
  "Double means two lots of the same, and 5 and 5 makes 10.",
  ["Double means add 2, so it is 7.", "Double 5 is 15."],
  "Double is the same number twice."),
 ("Taking 3 away from 9 leaves 6.",
  "Cross out 3 of the 9 and count what is left, and there are 6.",
  ["9 and 3 make 12.", "3 is left because 9 take away 3 has a 3 in it."],
  "Taking away always leaves you with fewer than you started with."),
],
"what-comes-next": [
 ("In red, blue, red, blue, red, the next one is blue.",
  "The pattern repeats red then blue, and red has just been.",
  ["The next one is red because red is first.", "Any colour can come next."],
  "Find the part that repeats, then carry it on."),
 ("2, 4, 6, 8 goes up in 2s.",
  "Each number is 2 more than the one before it.",
  ["They are all even, so it goes up in 2s.", "It goes up in 2s because it starts at 2."],
  "The first one is true and still does not tell you the jump. Look at the gap between them."),
 ("The missing number in 5, 6, ?, 8 is 7.",
  "The numbers go up by 1, and 7 comes between 6 and 8.",
  ["It is 7 because 7 is a lucky number.", "It could be any number at all."],
  "Count on from the one before."),
 ("If 3 and something makes 5, the something is 2.",
  "3 and 2 make 5, so 2 goes in the box.",
  ["The box is 8, because 3 and 5 make 8.", "The box is 5."],
  "Count on from 3 up to 5 and see how far you went."),
 ("A pattern that grows 1, 3, 5 adds 2 each time.",
  "1 and 2 more is 3, and 3 and 2 more is 5.",
  ["It adds 1 each time.", "It adds 2 because 2 is in the middle."],
  "Check the jump more than once before you trust it."),
 ("4 add 1 is the same as 3 add 2.",
  "4 and 1 makes 5, and 3 and 2 makes 5, so both sides are worth 5.",
  ["They are the same because all the numbers are small.", "They are not the same, because the numbers are different."],
  "The equals sign means both sides are worth the same."),
],
"halves-and-wholes": [
 ("A cake is cut in half only when the two pieces are the same.",
  "Half means two pieces exactly the same size.",
  ["Half means two pieces, any size at all.", "Half means the biggest piece."],
  "Two pieces is not enough. They have to match."),
 ("Half of 8 is 4.",
  "Share 8 into two equal groups and each group has 4.",
  ["Half of 8 is 2, because 8 has a 2 in it.", "Half of 8 is 6."],
  "Share it fairly into two."),
 ("Two halves make one whole.",
  "Put both halves back together and you have the whole thing again.",
  ["Two halves make two.", "Two halves make a quarter."],
  "Nothing is missing when you put them back together."),
 ("A square can be cut in half in more than one way.",
  "Down the middle or corner to corner both make two equal pieces.",
  ["Only down the middle counts.", "A square cannot be cut in half."],
  "The two pieces can look different and still both be halves."),
 ("Half of a group of 6 apples is 3 apples.",
  "Share the 6 apples between two people and each one gets 3.",
  ["Half of 6 apples means cutting every apple up.", "Half of 6 is 2."],
  "A half can be half of a group, not only half of one thing."),
 ("The bigger piece is not a half.",
  "If one piece is bigger then the two are not equal, so neither of them is a half.",
  ["The bigger piece is always the half.", "Both pieces are halves however you cut them."],
  "Equal is what makes it a half."),
],
"shapes-and-sizes": [
 ("A triangle has three sides.",
  "Count the straight sides all the way round and there are three.",
  ["A triangle has three sides because it is small.", "A triangle has four sides."],
  "Count the sides to name a flat shape."),
 ("A square turned on its corner is still a square.",
  "It still has four straight sides all the same, and turning it does not change that.",
  ["It turns into a diamond.", "It turns into a triangle."],
  "Turning a shape never changes what it is."),
 ("A ball is not a circle.",
  "A ball is solid and you can hold it, and a circle is flat.",
  ["A ball is not a circle because it is bigger.", "A ball is not a circle because it rolls."],
  "Flat shapes and solid shapes are two different families."),
 ("You can only tell which pencil is longer if you line them up.",
  "Start them both at the same end, and then one reaches further.",
  ["The longer one is the one with the nicer colour.", "The longer one is the one nearer the top."],
  "Start them level, or you cannot tell."),
 ("Half past 3 is not the same as 3 o'clock.",
  "At half past, the long hand has gone half way round since 3 o'clock.",
  ["They are the same because both say 3.", "Half past 3 comes before 3 o'clock."],
  "Half past is half an hour later."),
 ("There are 7 days in a week.",
  "Count them: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.",
  ["There are 7 because 7 is a big number.", "There are 5, because the weekend does not count."],
  "Say them and count as you go."),
],
"asking-and-sorting": [
 ("You have to ask everybody to find the class favourite colour.",
  "Different people like different colours, so you cannot know until you ask them.",
  ["You can just pick your own favourite.", "Everybody likes the same colour anyway."],
  "If the answers would be different, you have to go and collect them."),
 ("The tallest bar shows the one most children chose.",
  "A taller bar means more children chose it.",
  ["The tallest bar is the one on the left.", "The tallest bar shows the fewest."],
  "Height shows how many."),
 ("A tally mark laid across four others means five.",
  "Four marks and the fifth laid across them makes one bundle of five.",
  ["The one across means six.", "The one across means somebody made a mistake."],
  "Count the bundles in fives."),
 ("Something in the middle of two hoops belongs to both.",
  "The middle is where the hoops overlap, so it is in both of them.",
  ["The middle means it belongs to neither.", "The middle is for the ones you cannot sort."],
  "Outside both hoops is the part that means neither."),
 ("If two bars are the same height, neither one won.",
  "The same height means the same number of children chose each one.",
  ["The first one won because it comes first.", "Two bars cannot be the same height."],
  "Bars can tie, and a tie is a real answer."),
 ("This chart tells you about our class, not about the whole school.",
  "Only the children in our class were asked.",
  ["It tells you about everybody in the world.", "Charts are always about the whole school."],
  "Data only tells you about the people you actually asked."),
],
}
