# -*- coding: utf-8 -*-
"""Grade 2's "How do you know?" claims, read by
../lesson-app-tools/add-reasoning-step.py.

Each item: a claim that is TRUE, the reason that explains it, two reasons that
do not, and what makes the difference (spoken after the answer). Every wrong
reason is either the mistake the lesson teaches against, or something true
that explains nothing - the second kind is the point of the step. Worded for
six- and seven-year-olds: short sentences, the lesson's own numbers.
"""

BANKS = {
"tens-and-ones": [
 ("52 is more than 48.",
  "5 tens is more than 4 tens.",
  ["8 is bigger than 2.", "52 has a 2 in it."],
  "The tens decide first. The ones only matter when the tens are the same."),
 ("In 36, the 3 is worth 30.",
  "The 3 is in the tens place, so it means 3 tens.",
  ["3 is a small number.", "The 3 comes before the 6."],
  "Where a digit sits decides what it is worth. In the tens place, 3 means 3 tens."),
 ("14 is even.",
  "14 counters make 7 pairs with none left over.",
  ["14 has a 1 in it.", "14 is less than 20."],
  "Even means every counter has a partner. How big the number is does not matter."),
 ("37 rounds to 40.",
  "37 is only 3 away from 40, but it is 7 away from 30.",
  ["37 is close to 30.", "40 is a round number."],
  "Rounding finds the nearer ten, so look at how far away each ten is."),
 ("25 add 10 is 35.",
  "Adding one ten makes 2 tens into 3 tens.",
  ["You add the 1 to the 5.", "10 is a round number."],
  "Adding ten changes the tens. The ones stay just as they were."),
 ("12 sweets shared between 3 friends gives 4 each.",
  "3 groups of 4 make 12.",
  ["12 take away 3 is 9.", "4 is an even number."],
  "Sharing makes equal groups. Check it by putting the groups back together."),
],
"coins-and-change": [
 ("A 50 note and a 20 coin make 70 shillings.",
  "Start at 50 and count on 20: 60, 70.",
  ["There are two pieces of money.", "The note is bigger than the coin."],
  "Counting money means adding what each piece is worth, not counting the pieces."),
 ("One 50 shilling note is worth more than four 10 shilling coins.",
  "Four 10s make 40, and 50 is more than 40.",
  ["Four is more than one.", "Notes are made of paper."],
  "Count what the money is worth, not how many pieces there are."),
 ("With 35 shillings, you need 15 more for a book that costs 50.",
  "Counting on from 35 to 50 takes 5 and then 10, which is 15.",
  ["You add 50 and 35.", "35 is less than 50."],
  "How much more is the gap between what you have and the price. Count on across it."),
 ("You can pay 70 shillings with just two pieces.",
  "A 50 and a 20 make 70.",
  ["70 is an even number.", "Seven 10 shilling coins make 70."],
  "Seven 10s do make 70, but that is seven pieces. The biggest pieces that fit use the fewest."),
 ("45 sh and KSh 45 are the same amount.",
  "Both say forty-five shillings. Only the letters are in a different place.",
  ["They both have a 4 and a 5.", "Money is always written with letters."],
  "The number is the amount. The letters only say that it is money."),
 ("Musa had 30 shillings, saved 20 and spent 15. Now he has 35.",
  "30 add 20 is 50, and 50 take away 15 is 35.",
  ["30 add 20 add 15 is 65.", "He spent less than he saved."],
  "Saving adds and spending takes away. He did spend less than he saved, but that alone does not tell you he has 35."),
],
"fair-shares": [
 ("This shape is cut into halves.",
  "It is cut into 2 parts, and the parts are the same size.",
  ["It has a line down the middle.", "Halves are small."],
  "A line alone is not enough. The two parts must be exactly the same size."),
 ("One half is bigger than one quarter.",
  "The same whole cut into 2 pieces has bigger pieces than when it is cut into 4.",
  ["4 is bigger than 2.", "Both are less than one whole."],
  "More pieces means each piece is smaller, so a quarter is the smaller piece."),
 ("Two quarters are the same as one half.",
  "Two quarters cover exactly the same part of the whole as one half.",
  ["2 and 4 are both even.", "Two quarters has bigger numbers."],
  "Fractions can have different names and be the same size. Put them side by side and compare."),
 ("Half of 8 is 4.",
  "8 shared into 2 equal groups gives 4 in each group.",
  ["8 is a big number.", "4 is an even number."],
  "Half means 2 equal groups. The answer is what is in one group."),
 ("One quarter and two quarters make three quarters.",
  "The pieces are all quarters, so you count them: 1 and 2 make 3.",
  ["You add the bottom numbers too.", "3 is more than 2."],
  "The bottom number says what size the pieces are, and that does not change when you add them."),
 ("Five quarters is more than one whole.",
  "Four quarters make a whole, and there is one more quarter.",
  ["5 is a big number.", "A pizza has lots of slices."],
  "Count the quarters in one whole first. Anything past four quarters is more than one whole."),
],
"patterns-that-grow": [
 ("After red, blue, red, blue comes red.",
  "Red and blue take turns, and blue was last.",
  ["Red is the first colour.", "There are two colours."],
  "Find the part that repeats, then see where you are in it."),
 ("5, 10, 15, 20 goes up in fives.",
  "Each number is 5 more than the one before, every time.",
  ["It starts with 5.", "The numbers end in 5 or 0."],
  "The step between the numbers is what matters, so check every jump."),
 ("The missing number in 10, 20, gap, 40 is 30.",
  "It goes up in tens, and 20 add 10 is 30.",
  ["30 is between 20 and 40.", "There is only one gap."],
  "Lots of numbers are between 20 and 40. The step tells you which one it is."),
 ("Counting back in twos from 20 goes 20, 18, 16, 14.",
  "Each number is 2 less than the one before.",
  ["They are all even numbers.", "They all have a 1 or a 2 at the front."],
  "They are all even is true, but counting back is what puts them in that order."),
 ("On the hundred square, the number just below 34 is 44.",
  "Each row holds 10 numbers, so going down one row adds 10.",
  ["44 has two 4s.", "34 and 44 both end in 4."],
  "Both end in 4 is true, and it happens because going down adds a whole ten."),
 ("Star, moon, star, moon is a repeating pattern.",
  "The same part, star and moon, comes again and again.",
  ["It has two shapes.", "Stars and moons are in the sky."],
  "A pattern repeats when one part keeps coming back in the same order."),
],
"sides-and-corners": [
 ("A square has 4 corners.",
  "It has 4 sides, and a corner is where two sides meet.",
  ["It is a flat shape.", "All its sides are the same length."],
  "Sides and corners go together. Count one and you know the other."),
 ("This shape is a triangle.",
  "It has exactly 3 straight sides.",
  ["It is pointed at the top.", "It is small."],
  "A triangle can point any way and be any size. Three straight sides is what makes it one."),
 ("A rectangle has 2 lines of symmetry.",
  "Only the fold down the middle and the fold across the middle make the halves match.",
  ["It has 4 sides.", "It has 4 corners."],
  "It has 4 sides is true, but a fold from corner to corner does not match, so only 2 folds work."),
 ("A dice is a cube.",
  "It has 6 flat faces, and every face is a square.",
  ["It has spots on it.", "You can roll it."],
  "Spots and rolling are true, but it is the 6 square faces that make it a cube."),
 ("A quarter turn clockwise from pointing up points to the right.",
  "Clockwise goes the way clock hands go, and a quarter turn goes a quarter of the way round.",
  ["Right is the hand you write with.", "Up and right are next to each other."],
  "Clockwise tells you which way to turn, and a quarter tells you how far."),
 ("A square looks the same 4 times in one whole turn.",
  "It has 4 equal sides and 4 equal corners, so each quarter turn lands it on itself.",
  ["Square is a short word.", "A square has 4 sides, like a rectangle."],
  "A rectangle has 4 sides too, and it looks the same only twice. Equal sides are what matter."),
],
"which-way-from-here": [
 ("When the robot faces down the page, its left is on your right.",
  "Its left depends on the way it faces, and it is facing the other way to you.",
  ["Robots are not the same as people.", "Left is always on the left of the page."],
  "Turn with the robot. Left and right depend on the way you are facing."),
 ("To reach a flag two squares in front of the robot, press forward twice.",
  "Forward moves one square the way the robot faces, and the flag is two squares that way.",
  ["Two is a small number.", "The flag is at the top."],
  "Count the squares in the direction the robot is facing."),
 ("The cat is between the two chairs.",
  "There is a chair on each side of the cat.",
  ["The cat is small.", "The cat is next to a chair."],
  "Next to one chair is not between. Between needs something on each side."),
 ("A dot 2 squares from the mirror line lands 2 squares away on the other side.",
  "A reflection is always the same distance from the line.",
  ["2 is an even number.", "Mirrors are shiny."],
  "The distance to the line stays the same. Only the side changes."),
 ("A dot on the mirror line stays on the line.",
  "It is no distance from the line, so its reflection is no distance from it too.",
  ["It is already in the middle.", "The line is purple."],
  "Same distance on the other side, and no distance stays no distance."),
 ("Turning right twice makes the robot face the other way.",
  "Two quarter turns make a half turn, and a half turn faces the opposite way.",
  ["Right is a good way to go.", "The robot has turned before."],
  "Count the quarter turns. Two of them make a half turn."),
],
"how-much-how-long": [
 ("The pencil is longer than the crayon.",
  "They start at the same line, and the pencil ends further along.",
  ["The pencil is yellow.", "The crayon is fatter."],
  "When things start together, only where they end matters."),
 ("Measuring with cubes only works if the cubes are the same size.",
  "Cubes of different sizes would count different lengths as one cube.",
  ["Cubes are square.", "You need lots of cubes."],
  "Every unit must be the same, or the count means nothing."),
 ("You start measuring at 0 on a ruler.",
  "Zero is where the length begins, so the number at the end is the length.",
  ["0 is the first mark on the ruler.", "Rulers always start at 1."],
  "Starting at 1 would add a centimetre that is not there."),
 ("A room is measured in metres, not centimetres.",
  "A room is big, and metres are the bigger unit.",
  ["Metres is a longer word.", "Centimetres are only for rulers."],
  "Pick the unit that fits the size, so the number makes sense."),
 ("When the balance is level, both sides weigh the same.",
  "A balance tips down on the heavier side, so level means neither side is heavier.",
  ["Level looks tidy.", "The weights are made of metal."],
  "Down means heavier. Level means the same."),
 ("The jug that takes more cups of water holds more.",
  "Every cup is the same amount, so more cups means more water.",
  ["It is taller.", "It is a jug."],
  "Tall is not the same as holding more. Count the cups, which are all the same size."),
],
"half-past-quarter-to": [
 ("When the long hand points at the 6, it is half past.",
  "The long hand has gone half way round the clock from the 12.",
  ["6 is an even number.", "The short hand is near a number."],
  "Half past means the long hand is half way round, and the 6 is half way round from the 12."),
 ("At twenty past, the long hand points at the 4.",
  "Each number is 5 minutes, and 4 fives are 20.",
  ["20 has a 2 in it.", "4 comes before 5."],
  "The long hand counts in fives, so 4 numbers round is 20 minutes."),
 ("Quarter to 4 comes before four o clock.",
  "Quarter to means there are still 15 minutes to go before 4.",
  ["4 is a small number.", "Quarter is a short word."],
  "To means before the next hour. Past means after the hour."),
 ("7:15 is quarter past 7.",
  "15 minutes past the hour is a quarter of the way round the clock.",
  ["It has a 7 in it.", "15 is an odd number."],
  "The minutes after the dots say how far past the hour it is, and 15 minutes is a quarter of an hour."),
 ("A week is longer than a day.",
  "A week has 7 days in it.",
  ["Week is a longer word.", "A week starts on a Monday."],
  "One unit of time holds several of the smaller unit."),
 ("There are 12 months in a year.",
  "January to December is 12 months, and then a new year starts.",
  ["12 is an even number.", "A clock has 12 numbers."],
  "A clock has 12 numbers is true, but it is not why a year has 12 months."),
],
"count-it-chart-it": [
 ("Two bundles of tally marks and 2 more marks make 12.",
  "Each bundle is 5, so count 5, 10, then 11, 12.",
  ["2 and 2 make 4.", "Tally marks are straight lines."],
  "Count each bundle as 5, then count on the loose marks."),
 ("In this pictogram, 6 pictures mean 6 children.",
  "Here each picture stands for one child.",
  ["The pictures are all the same.", "6 is an even number."],
  "Always check what one picture stands for before you count."),
 ("A red ball goes in the box that is red and round.",
  "Both labels are true for it, and that is the only box where both are.",
  ["Balls are fun.", "Red is a bright colour."],
  "A box in a Carroll diagram needs both of its labels to be true."),
 ("Football was chosen most, because its column is the tallest.",
  "Each block is one vote, and the football column has the most blocks.",
  ["Football is a popular game.", "The football column is on the left."],
  "What is popular in the world is not the data. The blocks are."),
 ("Tossing a coin 10 times does not always give 5 heads.",
  "Each toss lands by chance, so the results can come out uneven.",
  ["Coins are round.", "Heads is on the front."],
  "Chance means you cannot be sure. Half and half is only what you expect over lots of tosses."),
 ("Heads, tails, heads, tails, heads, tails is a regular pattern.",
  "The part heads, tails comes again and again.",
  ["It uses a coin.", "There are 6 tosses."],
  "Regular means a part keeps repeating. A real coin hardly ever does that for long."),
],
}
