<?php
defined('MOODLE_INTERNAL') || die();

// Generated from Top_10_Cities_Per_Country.xlsx. Used to filter city choices after country selection.
return [
    'cities' => [
        'Aarhus' => 'Aarhus',
        'Abidjan' => 'Abidjan',
        'Abomey-Calavi' => 'Abomey-Calavi',
        'Abu Dhabi' => 'Abu Dhabi',
        'Abuja' => 'Abuja',
        'Accra' => 'Accra',
        'Adama' => 'Adama',
        'Adamstown' => 'Adamstown',
        'Adana' => 'Adana',
        'Addis Ababa' => 'Addis Ababa',
        'Addu City' => 'Addu City',
        'Adelaide' => 'Adelaide',
        'Aden' => 'Aden',
        'Ahmedabad' => 'Ahmedabad',
        'Airai' => 'Airai',
        'Akhalgori' => 'Akhalgori',
        'Al Jahra' => 'Al Jahra',
        'Al Rayyan' => 'Al Rayyan',
        'Alajuela' => 'Alajuela',
        'Alele' => 'Alele',
        'Aleppo' => 'Aleppo',
        'Alexandria' => 'Alexandria',
        'Algiers' => 'Algiers',
        'Ali Sabieh' => 'Ali Sabieh',
        'All Saints' => 'All Saints',
        'Almaty' => 'Almaty',
        'Alofi' => 'Alofi',
        'Amman' => 'Amman',
        'Amsterdam' => 'Amsterdam',
        'Amuri' => 'Amuri',
        'Andorra la Vella' => 'Andorra la Vella',
        'Ankara' => 'Ankara',
        'Anna\'s Retreat' => 'Anna\'s Retreat',
        'Anse Etoile' => 'Anse Etoile',
        'Antalya' => 'Antalya',
        'Antananarivo' => 'Antananarivo',
        'Antwerp' => 'Antwerp',
        'Apia' => 'Apia',
        'Arequipa' => 'Arequipa',
        'Arusha' => 'Arusha',
        'Asau' => 'Asau',
        'Ashgabat' => 'Ashgabat',
        'Asmara' => 'Asmara',
        'Astana' => 'Astana',
        'Asunción' => 'Asunción',
        'Asyut' => 'Asyut',
        'Atafu' => 'Atafu',
        'Athens' => 'Athens',
        'Atlanta Metro Area' => 'Atlanta Metro Area',
        'Auckland' => 'Auckland',
        'Avarua' => 'Avarua',
        'Awasa' => 'Awasa',
        'Ayios Nikolaos' => 'Ayios Nikolaos',
        'Baghdad' => 'Baghdad',
        'Bahir Dar' => 'Bahir Dar',
        'Bairiki' => 'Bairiki',
        'Baku' => 'Baku',
        'Bamako' => 'Bamako',
        'Bandar Seri Begawan' => 'Bandar Seri Begawan',
        'Bandung' => 'Bandung',
        'Bangalore' => 'Bangalore',
        'Bangkok' => 'Bangkok',
        'Bangui' => 'Bangui',
        'Banja Luka' => 'Banja Luka',
        'Banjul' => 'Banjul',
        'Bantam' => 'Bantam',
        'Barcelona' => 'Barcelona',
        'Barentsburg' => 'Barentsburg',
        'Barisal' => 'Barisal',
        'Basra' => 'Basra',
        'Basseterre' => 'Basseterre',
        'Bata' => 'Bata',
        'Bayamón' => 'Bayamón',
        'Beau Bassin-Rose Hill' => 'Beau Bassin-Rose Hill',
        'Beijing' => 'Beijing',
        'Beira' => 'Beira',
        'Beirut' => 'Beirut',
        'Bekasi' => 'Bekasi',
        'Belgrade' => 'Belgrade',
        'Belize City' => 'Belize City',
        'Belmopan' => 'Belmopan',
        'Belo Horizonte' => 'Belo Horizonte',
        'Benghazi' => 'Benghazi',
        'Benin City' => 'Benin City',
        'Bergen' => 'Bergen',
        'Berlin' => 'Berlin',
        'Bern' => 'Bern',
        'Betio' => 'Betio',
        'Bimbo' => 'Bimbo',
        'Birkirkara' => 'Birkirkara',
        'Birmingham' => 'Birmingham',
        'Bishkek' => 'Bishkek',
        'Bissau' => 'Bissau',
        'Bitola' => 'Bitola',
        'Blantyre' => 'Blantyre',
        'Bo' => 'Bo',
        'Bobo-Dioulasso' => 'Bobo-Dioulasso',
        'Bogotá' => 'Bogotá',
        'Bordeaux' => 'Bordeaux',
        'Borgo Maggiore' => 'Borgo Maggiore',
        'Bouaké' => 'Bouaké',
        'Brades' => 'Brades',
        'Brasília' => 'Brasília',
        'Bratislava' => 'Bratislava',
        'Brazzaville' => 'Brazzaville',
        'Bridgetown' => 'Bridgetown',
        'Brikama' => 'Brikama',
        'Brisbane' => 'Brisbane',
        'Bristol' => 'Bristol',
        'Brno' => 'Brno',
        'Brussels' => 'Brussels',
        'Bucharest' => 'Bucharest',
        'Budapest' => 'Budapest',
        'Buenos Aires' => 'Buenos Aires',
        'Buffalo City' => 'Buffalo City',
        'Bujumbura' => 'Bujumbura',
        'Bulawayo' => 'Bulawayo',
        'Burnt Pine' => 'Burnt Pine',
        'Bursa' => 'Bursa',
        'Busan' => 'Busan',
        'Cairo' => 'Cairo',
        'Calgary' => 'Calgary',
        'Canberra' => 'Canberra',
        'Cape Town' => 'Cape Town',
        'Caracas' => 'Caracas',
        'Casablanca' => 'Casablanca',
        'Castries' => 'Castries',
        'Cayenne' => 'Cayenne',
        'Cebu City' => 'Cebu City',
        'Central Coast' => 'Central Coast',
        'Chaguanas' => 'Chaguanas',
        'Charlestown' => 'Charlestown',
        'Charlotte Amalie' => 'Charlotte Amalie',
        'Chelyabinsk' => 'Chelyabinsk',
        'Chengdu' => 'Chengdu',
        'Chennai' => 'Chennai',
        'chicago Metro Area' => 'chicago Metro Area',
        'Chittagong' => 'Chittagong',
        'Chișinău' => 'Chișinău',
        'Chongqing' => 'Chongqing',
        'Christchurch' => 'Christchurch',
        'Ciudad de la Costa' => 'Ciudad de la Costa',
        'Ciudad del Este' => 'Ciudad del Este',
        'Ciudad Juárez' => 'Ciudad Juárez',
        'Cluj-Napoca' => 'Cluj-Napoca',
        'Cockburn Town' => 'Cockburn Town',
        'Cologne' => 'Cologne',
        'Colombo' => 'Colombo',
        'Colón' => 'Colón',
        'Comilla' => 'Comilla',
        'Conakry' => 'Conakry',
        'Constanța' => 'Constanța',
        'Copenhagen' => 'Copenhagen',
        'Cork' => 'Cork',
        'Cotonou' => 'Cotonou',
        'Cul De Sac' => 'Cul De Sac',
        'Curitiba' => 'Curitiba',
        'Córdoba' => 'Córdoba',
        'Dakar' => 'Dakar',
        'Dakhla' => 'Dakhla',
        'Dallas-Fort Worth Metro Area' => 'Dallas-Fort Worth Metro Area',
        'Damascus' => 'Damascus',
        'Dar es Salaam' => 'Dar es Salaam',
        'Dare' => 'Dare',
        'Darkhan' => 'Darkhan',
        'Daugavpils' => 'Daugavpils',
        'Debrecen' => 'Debrecen',
        'Dehiwala-Mount Lavinia' => 'Dehiwala-Mount Lavinia',
        'Delhi' => 'Delhi',
        'Denigomudu' => 'Denigomudu',
        'Depok' => 'Depok',
        'Dessie' => 'Dessie',
        'Detroit Metro Area' => 'Detroit Metro Area',
        'Dhaka' => 'Dhaka',
        'Dili' => 'Dili',
        'Dire Dawa' => 'Dire Dawa',
        'Djibouti' => 'Djibouti',
        'Dodoma' => 'Dodoma',
        'Dogana' => 'Dogana',
        'Doha' => 'Doha',
        'Donetsk' => 'Donetsk',
        'Dortmund' => 'Dortmund',
        'Douala' => 'Douala',
        'Douglas' => 'Douglas',
        'Dubai' => 'Dubai',
        'Dublin' => 'Dublin',
        'Durban' => 'Durban',
        'Durrës' => 'Durrës',
        'Dushanbe' => 'Dushanbe',
        'Dzaoudzi' => 'Dzaoudzi',
        'Düsseldorf' => 'Düsseldorf',
        'East Jerusalem' => 'East Jerusalem',
        'Ebeye' => 'Ebeye',
        'Ecatepec' => 'Ecatepec',
        'Edinburgh' => 'Edinburgh',
        'Edmonton' => 'Edmonton',
        'Ekurhuleni' => 'Ekurhuleni',
        'El Alto' => 'El Alto',
        'El Mahalla El Kubra' => 'El Mahalla El Kubra',
        'Eldoret' => 'Eldoret',
        'Enugu' => 'Enugu',
        'Episkopi Cantonment' => 'Episkopi Cantonment',
        'Esch-sur-Alzette' => 'Esch-sur-Alzette',
        'Espoo' => 'Espoo',
        'Essen' => 'Essen',
        'eThekwini' => 'eThekwini',
        'Faisalabad' => 'Faisalabad',
        'Fakaofo' => 'Fakaofo',
        'Fez' => 'Fez',
        'Five Cays' => 'Five Cays',
        'Flying Fish Cove' => 'Flying Fish Cove',
        'Fortaleza' => 'Fortaleza',
        'Francistown' => 'Francistown',
        'Frankfurt' => 'Frankfurt',
        'Freeport' => 'Freeport',
        'Freetown' => 'Freetown',
        'Fukuoka' => 'Fukuoka',
        'Funafuti' => 'Funafuti',
        'Gaborone' => 'Gaborone',
        'Gabú' => 'Gabú',
        'Gagra' => 'Gagra',
        'Ganja' => 'Ganja',
        'Garapan' => 'Garapan',
        'Gaza City' => 'Gaza City',
        'Gaziantep' => 'Gaziantep',
        'Gazipur' => 'Gazipur',
        'Gbarnga' => 'Gbarnga',
        'Geneva' => 'Geneva',
        'George Town' => 'George Town',
        'Georgetown' => 'Georgetown',
        'Gibraltar' => 'Gibraltar',
        'Giza' => 'Giza',
        'Gizo' => 'Gizo',
        'Glasgow' => 'Glasgow',
        'Gold Coast' => 'Gold Coast',
        'Gonaïves' => 'Gonaïves',
        'Gondar' => 'Gondar',
        'Goose Green' => 'Goose Green',
        'Gothenburg' => 'Gothenburg',
        'Gouyave' => 'Gouyave',
        'Graz' => 'Graz',
        'Gros Islet' => 'Gros Islet',
        'Grytviken' => 'Grytviken',
        'Guadalajara' => 'Guadalajara',
        'Guangzhou' => 'Guangzhou',
        'Guatemala City' => 'Guatemala City',
        'Guayaquil' => 'Guayaquil',
        'Gujranwala' => 'Gujranwala',
        'Gulu' => 'Gulu',
        'Gustavia' => 'Gustavia',
        'Gyumri' => 'Gyumri',
        'Hagåtña' => 'Hagåtña',
        'Hakupu' => 'Hakupu',
        'Half Tree Hollow' => 'Half Tree Hollow',
        'Hamburg' => 'Hamburg',
        'Hamhung' => 'Hamhung',
        'Hamilton' => 'Hamilton',
        'Hanoi' => 'Hanoi',
        'Harare' => 'Harare',
        'Hargeisa' => 'Hargeisa',
        'Havana' => 'Havana',
        'Hebron' => 'Hebron',
        'Helsinki' => 'Helsinki',
        'Ho Chi Minh City' => 'Ho Chi Minh City',
        'Homel' => 'Homel',
        'Honda Road' => 'Honda Road',
        'Honiara' => 'Honiara',
        'Houston Metro Area' => 'Houston Metro Area',
        'Huambo' => 'Huambo',
        'Hyderabad' => 'Hyderabad',
        'Ibadan' => 'Ibadan',
        'Ilorin' => 'Ilorin',
        'Islamabad' => 'Islamabad',
        'Istanbul' => 'Istanbul',
        'Izmir' => 'Izmir',
        'Jakarta' => 'Jakarta',
        'Jamestown' => 'Jamestown',
        'Jeddah' => 'Jeddah',
        'Jerusalem' => 'Jerusalem',
        'Jijiga' => 'Jijiga',
        'Jimma' => 'Jimma',
        'Johannesburg' => 'Johannesburg',
        'Jomala' => 'Jomala',
        'Jos' => 'Jos',
        'Juba' => 'Juba',
        'Kabul' => 'Kabul',
        'Kaduna' => 'Kaduna',
        'Kahama' => 'Kahama',
        'Kampala' => 'Kampala',
        'Kandahar' => 'Kandahar',
        'Kandy' => 'Kandy',
        'Kangundo-Tala' => 'Kangundo-Tala',
        'Kano' => 'Kano',
        'Karachi' => 'Karachi',
        'Kasese' => 'Kasese',
        'Kathmandu' => 'Kathmandu',
        'Kaunas' => 'Kaunas',
        'Kawasaki' => 'Kawasaki',
        'Kayseri' => 'Kayseri',
        'Kazan' => 'Kazan',
        'Kehancha' => 'Kehancha',
        'Keren' => 'Keren',
        'Kharkiv' => 'Kharkiv',
        'Khartoum' => 'Khartoum',
        'Khujand' => 'Khujand',
        'Khulna' => 'Khulna',
        'Kiev' => 'Kiev',
        'Kigali' => 'Kigali',
        'Kikuyu' => 'Kikuyu',
        'King Edward Point' => 'King Edward Point',
        'Kingston' => 'Kingston',
        'Kingstown' => 'Kingstown',
        'Kinshasa' => 'Kinshasa',
        'Kira' => 'Kira',
        'Kisumu' => 'Kisumu',
        'Kitchener' => 'Kitchener',
        'Kitwe' => 'Kitwe',
        'Klaksvík' => 'Klaksvík',
        'Kobe' => 'Kobe',
        'Kolkata' => 'Kolkata',
        'Konya' => 'Konya',
        'Koror' => 'Koror',
        'Kowloon' => 'Kowloon',
        'Košice' => 'Košice',
        'Kraków' => 'Kraków',
        'Kuala Belait' => 'Kuala Belait',
        'Kuala Lumpur' => 'Kuala Lumpur',
        'Kumasi' => 'Kumasi',
        'Kutaisi' => 'Kutaisi',
        'Kuwait City' => 'Kuwait City',
        'Kyoto' => 'Kyoto',
        'Kópavogur' => 'Kópavogur',
        'La Condamine' => 'La Condamine',
        'Laayoune' => 'Laayoune',
        'Lae' => 'Lae',
        'Lagos' => 'Lagos',
        'Lahore' => 'Lahore',
        'Leeds' => 'Leeds',
        'Leicester' => 'Leicester',
        'Lelydorp' => 'Lelydorp',
        'Les Escaldes' => 'Les Escaldes',
        'León' => 'León',
        'Libreville' => 'Libreville',
        'Lille' => 'Lille',
        'Lilongwe' => 'Lilongwe',
        'Lima' => 'Lima',
        'Limassol' => 'Limassol',
        'Linden' => 'Linden',
        'Lisbon' => 'Lisbon',
        'Liverpool' => 'Liverpool',
        'Ljubljana' => 'Ljubljana',
        'Lomé' => 'Lomé',
        'London' => 'London',
        'Longyearbyen' => 'Longyearbyen',
        'Los Angeles Metro Area' => 'Los Angeles Metro Area',
        'Lower Prince\'s Quarter' => 'Lower Prince\'s Quarter',
        'Luanda' => 'Luanda',
        'Lubumbashi' => 'Lubumbashi',
        'Luganville' => 'Luganville',
        'Lugazi' => 'Lugazi',
        'Lusaka' => 'Lusaka',
        'Luxembourg City' => 'Luxembourg City',
        'Lyon' => 'Lyon',
        'Madrid' => 'Madrid',
        'Mahina' => 'Mahina',
        'Majuro' => 'Majuro',
        'Malabo' => 'Malabo',
        'Maldonado' => 'Maldonado',
        'Malindi' => 'Malindi',
        'Malé' => 'Malé',
        'Mamoudzou' => 'Mamoudzou',
        'Managua' => 'Managua',
        'Manama' => 'Manama',
        'Manaus' => 'Manaus',
        'Manchester' => 'Manchester',
        'Mandalay' => 'Mandalay',
        'Mangaung' => 'Mangaung',
        'Mangilao' => 'Mangilao',
        'Manila' => 'Manila',
        'Mansoura' => 'Mansoura',
        'Manzini' => 'Manzini',
        'Maputo' => 'Maputo',
        'Maracaibo' => 'Maracaibo',
        'Maribor' => 'Maribor',
        'Mariehamn' => 'Mariehamn',
        'Marigot' => 'Marigot',
        'Marseille' => 'Marseille',
        'Masaka' => 'Masaka',
        'Maseru' => 'Maseru',
        'Mashhad' => 'Mashhad',
        'Mata-Utu' => 'Mata-Utu',
        'Mbabane' => 'Mbabane',
        'Mbarara' => 'Mbarara',
        'Mbeya' => 'Mbeya',
        'Medan' => 'Medan',
        'Medellín' => 'Medellín',
        'Mek\'ele' => 'Mek\'ele',
        'Melbourne' => 'Melbourne',
        'Mersin' => 'Mersin',
        'Mexico City' => 'Mexico City',
        'Milan' => 'Milan',
        'Mindelo' => 'Mindelo',
        'Minsk' => 'Minsk',
        'Miquelon' => 'Miquelon',
        'Mogadishu' => 'Mogadishu',
        'Mombasa' => 'Mombasa',
        'Monaco' => 'Monaco',
        'Monrovia' => 'Monrovia',
        'Monte Carlo' => 'Monte Carlo',
        'Monterrey' => 'Monterrey',
        'Montevideo' => 'Montevideo',
        'Montpellier' => 'Montpellier',
        'Montreal' => 'Montreal',
        'Morogoro' => 'Morogoro',
        'Moroni' => 'Moroni',
        'Moscow' => 'Moscow',
        'Mosta' => 'Mosta',
        'Moundou' => 'Moundou',
        'Muhanga' => 'Muhanga',
        'Mukono' => 'Mukono',
        'Multan' => 'Multan',
        'Mumbai' => 'Mumbai',
        'Munich' => 'Munich',
        'Muscat' => 'Muscat',
        'Mutsamudu' => 'Mutsamudu',
        'Muyinga' => 'Muyinga',
        'Mwanza' => 'Mwanza',
        'N\'Djamena' => 'N\'Djamena',
        'Nagoya' => 'Nagoya',
        'Nairobi' => 'Nairobi',
        'Nakuru' => 'Nakuru',
        'Namangan' => 'Namangan',
        'Nanjing' => 'Nanjing',
        'Nansana' => 'Nansana',
        'Nantes' => 'Nantes',
        'Narayanganj' => 'Narayanganj',
        'Nasinu' => 'Nasinu',
        'Nassau' => 'Nassau',
        'Nay Pyi Taw' => 'Nay Pyi Taw',
        'Neiafu' => 'Neiafu',
        'Nelson Mandela Bay' => 'Nelson Mandela Bay',
        'New Delhi' => 'New Delhi',
        'New Taipei' => 'New Taipei',
        'New York City' => 'New York City',
        'New York City Metro Area' => 'New York City Metro Area',
        'Newcastle' => 'Newcastle',
        'Nezahualcóyotl' => 'Nezahualcóyotl',
        'Ngerulmud' => 'Ngerulmud',
        'Niamey' => 'Niamey',
        'Nice' => 'Nice',
        'Nicosia' => 'Nicosia',
        'Nikšić' => 'Nikšić',
        'Nizhny Novgorod' => 'Nizhny Novgorod',
        'Nonthaburi' => 'Nonthaburi',
        'North Side' => 'North Side',
        'Nouadhibou' => 'Nouadhibou',
        'Nouakchott' => 'Nouakchott',
        'Nouméa' => 'Nouméa',
        'Novi Sad' => 'Novi Sad',
        'Novosibirsk' => 'Novosibirsk',
        'Nu\'uuli' => 'Nu\'uuli',
        'Nukuʻalofa' => 'Nukuʻalofa',
        'Nuuk' => 'Nuuk',
        'Nzérékoré' => 'Nzérékoré',
        'Omdurman' => 'Omdurman',
        'Omsk' => 'Omsk',
        'Onchan' => 'Onchan',
        'Oran' => 'Oran',
        'Oranjestad' => 'Oranjestad',
        'Osaka' => 'Osaka',
        'Osh' => 'Osh',
        'Oslo' => 'Oslo',
        'Ostrava' => 'Ostrava',
        'Other' => 'Other city not listed',
        'Ottawa' => 'Ottawa',
        'Ouagadougou' => 'Ouagadougou',
        'Pago Pago' => 'Pago Pago',
        'Pak Kret' => 'Pak Kret',
        'Pakxe' => 'Pakxe',
        'Palembang' => 'Palembang',
        'Palikir' => 'Palikir',
        'Panama City' => 'Panama City',
        'Papeete' => 'Papeete',
        'Paramaribo' => 'Paramaribo',
        'Paris' => 'Paris',
        'Perth' => 'Perth',
        'Peshawar' => 'Peshawar',
        'Philipsburg' => 'Philipsburg',
        'Phnom Penh' => 'Phnom Penh',
        'Phuntsholing' => 'Phuntsholing',
        'Plovdiv' => 'Plovdiv',
        'Podgorica' => 'Podgorica',
        'Pointe-Noire' => 'Pointe-Noire',
        'Pokhara' => 'Pokhara',
        'Ponce' => 'Ponce',
        'Poon Saan' => 'Poon Saan',
        'Port Harcourt' => 'Port Harcourt',
        'Port Louis' => 'Port Louis',
        'Port Moresby' => 'Port Moresby',
        'Port of Spain' => 'Port of Spain',
        'Port Said' => 'Port Said',
        'Port Sudan' => 'Port Sudan',
        'Port Vila' => 'Port Vila',
        'Port-au-Prince' => 'Port-au-Prince',
        'Port-Gentil' => 'Port-Gentil',
        'Porto' => 'Porto',
        'Porto Alegre' => 'Porto Alegre',
        'Porto-Novo' => 'Porto-Novo',
        'Portsmouth' => 'Portsmouth',
        'Prague' => 'Prague',
        'Praia' => 'Praia',
        'Pretoria' => 'Pretoria',
        'Pristina' => 'Pristina',
        'Prizren' => 'Prizren',
        'Puebla' => 'Puebla',
        'Puente Alto' => 'Puente Alto',
        'Pune' => 'Pune',
        'Pyongyang' => 'Pyongyang',
        'Quebec City' => 'Quebec City',
        'Quetta' => 'Quetta',
        'Quetzaltenango' => 'Quetzaltenango',
        'Quezon City' => 'Quezon City',
        'Quito' => 'Quito',
        'Rabat' => 'Rabat',
        'Rajshahi' => 'Rajshahi',
        'Rambaud' => 'Rambaud',
        'Rangpur' => 'Rangpur',
        'Rawalpindi' => 'Rawalpindi',
        'Recife' => 'Recife',
        'Reykjavík' => 'Reykjavík',
        'Rhine-Ruhr' => 'Rhine-Ruhr',
        'Riffa' => 'Riffa',
        'Riga' => 'Riga',
        'Rio de Janeiro' => 'Rio de Janeiro',
        'Rita' => 'Rita',
        'Riyadh' => 'Riyadh',
        'Road Town' => 'Road Town',
        'Rome' => 'Rome',
        'Roseau' => 'Roseau',
        'Rostov-on-Don' => 'Rostov-on-Don',
        'Rotterdam' => 'Rotterdam',
        'Ruiru' => 'Ruiru',
        'Rundu' => 'Rundu',
        'Saint Helier' => 'Saint Helier',
        'Saint Peter Port' => 'Saint Peter Port',
        'Saint Peter\'s' => 'Saint Peter\'s',
        'Saint Petersburg' => 'Saint Petersburg',
        'Saint Saviour' => 'Saint Saviour',
        'Saint-Laurent-du-Maroni' => 'Saint-Laurent-du-Maroni',
        'Saint-Pierre' => 'Saint-Pierre',
        'Saitama' => 'Saitama',
        'Salalah' => 'Salalah',
        'Salvador' => 'Salvador',
        'Samara' => 'Samara',
        'San Antonio' => 'San Antonio',
        'San Fernando' => 'San Fernando',
        'San Francisco Metro Area' => 'San Francisco Metro Area',
        'San Ignacio' => 'San Ignacio',
        'San José' => 'San José',
        'San Juan' => 'San Juan',
        'San Marino' => 'San Marino',
        'San Pedro Sula' => 'San Pedro Sula',
        'San Salvador' => 'San Salvador',
        'Sana\'a' => 'Sana\'a',
        'Santa Ana' => 'Santa Ana',
        'Santa Cruz de la Sierra' => 'Santa Cruz de la Sierra',
        'Santiago' => 'Santiago',
        'Santiago de Cuba' => 'Santiago de Cuba',
        'Santiago de los Caballeros' => 'Santiago de los Caballeros',
        'Santo Domingo' => 'Santo Domingo',
        'Sapporo' => 'Sapporo',
        'Sarajevo' => 'Sarajevo',
        'Schaan' => 'Schaan',
        'Semarang' => 'Semarang',
        'Seoul' => 'Seoul',
        'Serekunda' => 'Serekunda',
        'Sfax' => 'Sfax',
        'Shanghai' => 'Shanghai',
        'Sheffield' => 'Sheffield',
        'Shenzhen' => 'Shenzhen',
        'Shubra El Kheima' => 'Shubra El Kheima',
        'Shusha' => 'Shusha',
        'Siem Reap' => 'Siem Reap',
        'Sikasso' => 'Sikasso',
        'Singapore' => 'Singapore',
        'Sint Michiel' => 'Sint Michiel',
        'Sint Nicolaas' => 'Sint Nicolaas',
        'Sisimiut' => 'Sisimiut',
        'Skopje' => 'Skopje',
        'Sofia' => 'Sofia',
        'Sokodé' => 'Sokodé',
        'South Tangerang' => 'South Tangerang',
        'Spanish Town' => 'Spanish Town',
        'Speightstown' => 'Speightstown',
        'Split' => 'Split',
        'Sri Jayawardenepura Kotte' => 'Sri Jayawardenepura Kotte',
        'Ssabagabo' => 'Ssabagabo',
        'St. George\'s' => 'St. George\'s',
        'St. Jean' => 'St. Jean',
        'St. John\'s' => 'St. John\'s',
        'Stanley' => 'Stanley',
        'Stepanakert' => 'Stepanakert',
        'Stockholm' => 'Stockholm',
        'Strasbourg' => 'Strasbourg',
        'Stuttgart' => 'Stuttgart',
        'Sucre, La Paz' => 'Sucre, La Paz',
        'Suez' => 'Suez',
        'Sukhumi' => 'Sukhumi',
        'Sunshine Coast' => 'Sunshine Coast',
        'Surabaya' => 'Surabaya',
        'Surat' => 'Surat',
        'Suva' => 'Suva',
        'Sydney' => 'Sydney',
        'Sylhet' => 'Sylhet',
        'São Paulo' => 'São Paulo',
        'São Tomé' => 'São Tomé',
        'Tabora' => 'Tabora',
        'Tafuna' => 'Tafuna',
        'Taichung' => 'Taichung',
        'Taipei' => 'Taipei',
        'Tallinn' => 'Tallinn',
        'Tampere' => 'Tampere',
        'Tamuning' => 'Tamuning',
        'Tanga' => 'Tanga',
        'Tangerang' => 'Tangerang',
        'Tanta' => 'Tanta',
        'Tarawa' => 'Tarawa',
        'Tartu' => 'Tartu',
        'Tashkent' => 'Tashkent',
        'Tbilisi' => 'Tbilisi',
        'Tegucigalpa' => 'Tegucigalpa',
        'Tehran' => 'Tehran',
        'Tel Aviv' => 'Tel Aviv',
        'Teyateyaneng' => 'Teyateyaneng',
        'The Valley' => 'The Valley',
        'Thessaloniki' => 'Thessaloniki',
        'Thimphu' => 'Thimphu',
        'Tianjin' => 'Tianjin',
        'Tighina' => 'Tighina',
        'Tijuana' => 'Tijuana',
        'Tirana' => 'Tirana',
        'Tiraspol' => 'Tiraspol',
        'Toamasina' => 'Toamasina',
        'Tokyo' => 'Tokyo',
        'Toronto' => 'Toronto',
        'Touba' => 'Touba',
        'Toulouse' => 'Toulouse',
        'Trindade' => 'Trindade',
        'Tripoli' => 'Tripoli',
        'Tshwane' => 'Tshwane',
        'Tskhinvali' => 'Tskhinvali',
        'Tunis' => 'Tunis',
        'Tórshavn' => 'Tórshavn',
        'Türkmenabat' => 'Türkmenabat',
        'Ulaanbaatar' => 'Ulaanbaatar',
        'Vaduz' => 'Vaduz',
        'Vaitele' => 'Vaitele',
        'Vale' => 'Vale',
        'Valletta' => 'Valletta',
        'Vancouver' => 'Vancouver',
        'Vatican City' => 'Vatican City',
        'Victoria' => 'Victoria',
        'Vienna' => 'Vienna',
        'Vientiane' => 'Vientiane',
        'Vilnius' => 'Vilnius',
        'Warsaw' => 'Warsaw',
        'Washington, D.C. Metro Area' => 'Washington, D.C. Metro Area',
        'Wellington' => 'Wellington',
        'Weno' => 'Weno',
        'West Bay' => 'West Bay',
        'West Island' => 'West Island',
        'Willemstad' => 'Willemstad',
        'Windhoek' => 'Windhoek',
        'Winnipeg' => 'Winnipeg',
        'Wuhan' => 'Wuhan',
        'Wé' => 'Wé',
        'Xi\'an' => 'Xi\'an',
        'Yamoussoukro' => 'Yamoussoukro',
        'Yangon' => 'Yangon',
        'Yaoundé' => 'Yaoundé',
        'Yaren' => 'Yaren',
        'Yei' => 'Yei',
        'Yekaterinburg' => 'Yekaterinburg',
        'Yerevan' => 'Yerevan',
        'Yokohama' => 'Yokohama',
        'Zagreb' => 'Zagreb',
        'Zanzibar City' => 'Zanzibar City',
        'Zapopan' => 'Zapopan',
        'Zarqa' => 'Zarqa',
        'Zinder' => 'Zinder',
        'Zürich' => 'Zürich',
    ],
    'country_cities' => [
        'Abkhazia' => [
            'Gagra' => 'Gagra',
            'Sukhumi' => 'Sukhumi',
            'Other' => 'Other city not listed',
        ],
        'Abkhazia (Georgia)' => [
            'Gagra' => 'Gagra',
            'Sukhumi' => 'Sukhumi',
            'Other' => 'Other city not listed',
        ],
        'Afghanistan' => [
            'Kabul' => 'Kabul',
            'Kandahar' => 'Kandahar',
            'Other' => 'Other city not listed',
        ],
        'Akrotiri and Dhekelia' => [
            'Ayios Nikolaos' => 'Ayios Nikolaos',
            'Episkopi Cantonment' => 'Episkopi Cantonment',
            'Other' => 'Other city not listed',
        ],
        'Akrotiri and Dhekelia (UK)' => [
            'Ayios Nikolaos' => 'Ayios Nikolaos',
            'Episkopi Cantonment' => 'Episkopi Cantonment',
            'Other' => 'Other city not listed',
        ],
        'Albania' => [
            'Durrës' => 'Durrës',
            'Tirana' => 'Tirana',
            'Other' => 'Other city not listed',
        ],
        'Algeria' => [
            'Algiers' => 'Algiers',
            'Oran' => 'Oran',
            'Other' => 'Other city not listed',
        ],
        'American Samoa' => [
            'Nu\'uuli' => 'Nu\'uuli',
            'Pago Pago' => 'Pago Pago',
            'Tafuna' => 'Tafuna',
            'Other' => 'Other city not listed',
        ],
        'American Samoa (US)' => [
            'Nu\'uuli' => 'Nu\'uuli',
            'Pago Pago' => 'Pago Pago',
            'Tafuna' => 'Tafuna',
            'Other' => 'Other city not listed',
        ],
        'Andorra' => [
            'Andorra la Vella' => 'Andorra la Vella',
            'Les Escaldes' => 'Les Escaldes',
            'Other' => 'Other city not listed',
        ],
        'Angola' => [
            'Huambo' => 'Huambo',
            'Luanda' => 'Luanda',
            'Other' => 'Other city not listed',
        ],
        'Anguilla' => [
            'North Side' => 'North Side',
            'The Valley' => 'The Valley',
            'Other' => 'Other city not listed',
        ],
        'Anguilla (UK)' => [
            'North Side' => 'North Side',
            'The Valley' => 'The Valley',
            'Other' => 'Other city not listed',
        ],
        'Antigua and Barbuda' => [
            'All Saints' => 'All Saints',
            'St. John\'s' => 'St. John\'s',
            'Other' => 'Other city not listed',
        ],
        'Argentina' => [
            'Buenos Aires' => 'Buenos Aires',
            'Córdoba' => 'Córdoba',
            'Other' => 'Other city not listed',
        ],
        'Armenia' => [
            'Gyumri' => 'Gyumri',
            'Yerevan' => 'Yerevan',
            'Other' => 'Other city not listed',
        ],
        'Aruba' => [
            'Oranjestad' => 'Oranjestad',
            'Sint Nicolaas' => 'Sint Nicolaas',
            'Other' => 'Other city not listed',
        ],
        'Aruba (Netherlands)' => [
            'Oranjestad' => 'Oranjestad',
            'Sint Nicolaas' => 'Sint Nicolaas',
            'Other' => 'Other city not listed',
        ],
        'Australia' => [
            'Adelaide' => 'Adelaide',
            'Brisbane' => 'Brisbane',
            'Canberra' => 'Canberra',
            'Central Coast' => 'Central Coast',
            'Gold Coast' => 'Gold Coast',
            'Melbourne' => 'Melbourne',
            'Newcastle' => 'Newcastle',
            'Perth' => 'Perth',
            'Sunshine Coast' => 'Sunshine Coast',
            'Sydney' => 'Sydney',
            'Other' => 'Other city not listed',
        ],
        'Austria' => [
            'Graz' => 'Graz',
            'Vienna' => 'Vienna',
            'Other' => 'Other city not listed',
        ],
        'Azerbaijan' => [
            'Baku' => 'Baku',
            'Ganja' => 'Ganja',
            'Other' => 'Other city not listed',
        ],
        'Bahamas' => [
            'Freeport' => 'Freeport',
            'Nassau' => 'Nassau',
            'Other' => 'Other city not listed',
        ],
        'Bahrain' => [
            'Manama' => 'Manama',
            'Riffa' => 'Riffa',
            'Other' => 'Other city not listed',
        ],
        'Bangladesh' => [
            'Barisal' => 'Barisal',
            'Chittagong' => 'Chittagong',
            'Comilla' => 'Comilla',
            'Dhaka' => 'Dhaka',
            'Gazipur' => 'Gazipur',
            'Khulna' => 'Khulna',
            'Narayanganj' => 'Narayanganj',
            'Rajshahi' => 'Rajshahi',
            'Rangpur' => 'Rangpur',
            'Sylhet' => 'Sylhet',
            'Other' => 'Other city not listed',
        ],
        'Barbados' => [
            'Bridgetown' => 'Bridgetown',
            'Speightstown' => 'Speightstown',
            'Other' => 'Other city not listed',
        ],
        'Belarus' => [
            'Homel' => 'Homel',
            'Minsk' => 'Minsk',
            'Other' => 'Other city not listed',
        ],
        'Belgium' => [
            'Antwerp' => 'Antwerp',
            'Brussels' => 'Brussels',
            'Other' => 'Other city not listed',
        ],
        'Belize' => [
            'Belize City' => 'Belize City',
            'Belmopan' => 'Belmopan',
            'San Ignacio' => 'San Ignacio',
            'Other' => 'Other city not listed',
        ],
        'Benin' => [
            'Abomey-Calavi' => 'Abomey-Calavi',
            'Cotonou' => 'Cotonou',
            'Porto-Novo' => 'Porto-Novo',
            'Other' => 'Other city not listed',
        ],
        'Bermuda' => [
            'Hamilton' => 'Hamilton',
            'St. George\'s' => 'St. George\'s',
            'Other' => 'Other city not listed',
        ],
        'Bermuda (UK)' => [
            'Hamilton' => 'Hamilton',
            'St. George\'s' => 'St. George\'s',
            'Other' => 'Other city not listed',
        ],
        'Bhutan' => [
            'Phuntsholing' => 'Phuntsholing',
            'Thimphu' => 'Thimphu',
            'Other' => 'Other city not listed',
        ],
        'Bolivia' => [
            'El Alto' => 'El Alto',
            'Santa Cruz de la Sierra' => 'Santa Cruz de la Sierra',
            'Sucre, La Paz' => 'Sucre, La Paz',
            'Other' => 'Other city not listed',
        ],
        'Bolivia, Plurinational State of' => [
            'El Alto' => 'El Alto',
            'Santa Cruz de la Sierra' => 'Santa Cruz de la Sierra',
            'Sucre, La Paz' => 'Sucre, La Paz',
            'Other' => 'Other city not listed',
        ],
        'Bosnia and Herzegovina' => [
            'Banja Luka' => 'Banja Luka',
            'Sarajevo' => 'Sarajevo',
            'Other' => 'Other city not listed',
        ],
        'Botswana' => [
            'Francistown' => 'Francistown',
            'Gaborone' => 'Gaborone',
            'Other' => 'Other city not listed',
        ],
        'Brazil' => [
            'Belo Horizonte' => 'Belo Horizonte',
            'Brasília' => 'Brasília',
            'Curitiba' => 'Curitiba',
            'Fortaleza' => 'Fortaleza',
            'Manaus' => 'Manaus',
            'Porto Alegre' => 'Porto Alegre',
            'Recife' => 'Recife',
            'Rio de Janeiro' => 'Rio de Janeiro',
            'Salvador' => 'Salvador',
            'São Paulo' => 'São Paulo',
            'Other' => 'Other city not listed',
        ],
        'British Virgin Islands' => [
            'Road Town' => 'Road Town',
            'Spanish Town' => 'Spanish Town',
            'Other' => 'Other city not listed',
        ],
        'British Virgin Islands (UK)' => [
            'Road Town' => 'Road Town',
            'Spanish Town' => 'Spanish Town',
            'Other' => 'Other city not listed',
        ],
        'Brunei' => [
            'Bandar Seri Begawan' => 'Bandar Seri Begawan',
            'Kuala Belait' => 'Kuala Belait',
            'Other' => 'Other city not listed',
        ],
        'Brunei Darussalam' => [
            'Bandar Seri Begawan' => 'Bandar Seri Begawan',
            'Kuala Belait' => 'Kuala Belait',
            'Other' => 'Other city not listed',
        ],
        'Bulgaria' => [
            'Plovdiv' => 'Plovdiv',
            'Sofia' => 'Sofia',
            'Other' => 'Other city not listed',
        ],
        'Burkina Faso' => [
            'Bobo-Dioulasso' => 'Bobo-Dioulasso',
            'Ouagadougou' => 'Ouagadougou',
            'Other' => 'Other city not listed',
        ],
        'Burundi' => [
            'Bujumbura' => 'Bujumbura',
            'Muyinga' => 'Muyinga',
            'Other' => 'Other city not listed',
        ],
        'Cabo Verde' => [
            'Mindelo' => 'Mindelo',
            'Praia' => 'Praia',
            'Other' => 'Other city not listed',
        ],
        'Cambodia' => [
            'Phnom Penh' => 'Phnom Penh',
            'Siem Reap' => 'Siem Reap',
            'Other' => 'Other city not listed',
        ],
        'Cameroon' => [
            'Douala' => 'Douala',
            'Yaoundé' => 'Yaoundé',
            'Other' => 'Other city not listed',
        ],
        'Canada' => [
            'Calgary' => 'Calgary',
            'Edmonton' => 'Edmonton',
            'Hamilton' => 'Hamilton',
            'Kitchener' => 'Kitchener',
            'Montreal' => 'Montreal',
            'Ottawa' => 'Ottawa',
            'Quebec City' => 'Quebec City',
            'Toronto' => 'Toronto',
            'Vancouver' => 'Vancouver',
            'Winnipeg' => 'Winnipeg',
            'Other' => 'Other city not listed',
        ],
        'Cape Verde' => [
            'Mindelo' => 'Mindelo',
            'Praia' => 'Praia',
            'Other' => 'Other city not listed',
        ],
        'Cayman Islands' => [
            'George Town' => 'George Town',
            'West Bay' => 'West Bay',
            'Other' => 'Other city not listed',
        ],
        'Cayman Islands (UK)' => [
            'George Town' => 'George Town',
            'West Bay' => 'West Bay',
            'Other' => 'Other city not listed',
        ],
        'Central African Republic' => [
            'Bangui' => 'Bangui',
            'Bimbo' => 'Bimbo',
            'Other' => 'Other city not listed',
        ],
        'Chad' => [
            'Moundou' => 'Moundou',
            'N\'Djamena' => 'N\'Djamena',
            'Other' => 'Other city not listed',
        ],
        'Chile' => [
            'Puente Alto' => 'Puente Alto',
            'Santiago' => 'Santiago',
            'Other' => 'Other city not listed',
        ],
        'China' => [
            'Beijing' => 'Beijing',
            'Chengdu' => 'Chengdu',
            'Chongqing' => 'Chongqing',
            'Guangzhou' => 'Guangzhou',
            'Nanjing' => 'Nanjing',
            'Shanghai' => 'Shanghai',
            'Shenzhen' => 'Shenzhen',
            'Tianjin' => 'Tianjin',
            'Wuhan' => 'Wuhan',
            'Xi\'an' => 'Xi\'an',
            'Other' => 'Other city not listed',
        ],
        'Christmas Island' => [
            'Flying Fish Cove' => 'Flying Fish Cove',
            'Poon Saan' => 'Poon Saan',
            'Other' => 'Other city not listed',
        ],
        'Christmas Island (Australia)' => [
            'Flying Fish Cove' => 'Flying Fish Cove',
            'Poon Saan' => 'Poon Saan',
            'Other' => 'Other city not listed',
        ],
        'Cocos Islands' => [
            'Bantam' => 'Bantam',
            'West Island' => 'West Island',
            'Other' => 'Other city not listed',
        ],
        'Cocos Islands (Australia)' => [
            'Bantam' => 'Bantam',
            'West Island' => 'West Island',
            'Other' => 'Other city not listed',
        ],
        'Colombia' => [
            'Bogotá' => 'Bogotá',
            'Medellín' => 'Medellín',
            'Other' => 'Other city not listed',
        ],
        'Comoros' => [
            'Moroni' => 'Moroni',
            'Mutsamudu' => 'Mutsamudu',
            'Other' => 'Other city not listed',
        ],
        'Cook Islands' => [
            'Amuri' => 'Amuri',
            'Avarua' => 'Avarua',
            'Other' => 'Other city not listed',
        ],
        'Cook Islands (New Zealand)' => [
            'Amuri' => 'Amuri',
            'Avarua' => 'Avarua',
            'Other' => 'Other city not listed',
        ],
        'Costa Rica' => [
            'Alajuela' => 'Alajuela',
            'San José' => 'San José',
            'Other' => 'Other city not listed',
        ],
        'Croatia' => [
            'Split' => 'Split',
            'Zagreb' => 'Zagreb',
            'Other' => 'Other city not listed',
        ],
        'Cuba' => [
            'Havana' => 'Havana',
            'Santiago de Cuba' => 'Santiago de Cuba',
            'Other' => 'Other city not listed',
        ],
        'Curaçao' => [
            'Sint Michiel' => 'Sint Michiel',
            'Willemstad' => 'Willemstad',
            'Other' => 'Other city not listed',
        ],
        'Curaçao (Netherlands)' => [
            'Sint Michiel' => 'Sint Michiel',
            'Willemstad' => 'Willemstad',
            'Other' => 'Other city not listed',
        ],
        'Cyprus' => [
            'Limassol' => 'Limassol',
            'Nicosia' => 'Nicosia',
            'Other' => 'Other city not listed',
        ],
        'Czech Republic' => [
            'Brno' => 'Brno',
            'Ostrava' => 'Ostrava',
            'Prague' => 'Prague',
            'Other' => 'Other city not listed',
        ],
        'Côte d\'Ivoire' => [
            'Abidjan' => 'Abidjan',
            'Bouaké' => 'Bouaké',
            'Yamoussoukro' => 'Yamoussoukro',
            'Other' => 'Other city not listed',
        ],
        'Democratic Republic of the Congo' => [
            'Kinshasa' => 'Kinshasa',
            'Lubumbashi' => 'Lubumbashi',
            'Other' => 'Other city not listed',
        ],
        'Denmark' => [
            'Aarhus' => 'Aarhus',
            'Copenhagen' => 'Copenhagen',
            'Other' => 'Other city not listed',
        ],
        'Djibouti' => [
            'Ali Sabieh' => 'Ali Sabieh',
            'Djibouti' => 'Djibouti',
            'Other' => 'Other city not listed',
        ],
        'Dominica' => [
            'Portsmouth' => 'Portsmouth',
            'Roseau' => 'Roseau',
            'Other' => 'Other city not listed',
        ],
        'Dominican Republic' => [
            'Santiago de los Caballeros' => 'Santiago de los Caballeros',
            'Santo Domingo' => 'Santo Domingo',
            'Other' => 'Other city not listed',
        ],
        'East Timor' => [
            'Dare' => 'Dare',
            'Dili' => 'Dili',
            'Other' => 'Other city not listed',
        ],
        'Ecuador' => [
            'Guayaquil' => 'Guayaquil',
            'Quito' => 'Quito',
            'Other' => 'Other city not listed',
        ],
        'Egypt' => [
            'Alexandria' => 'Alexandria',
            'Asyut' => 'Asyut',
            'Cairo' => 'Cairo',
            'El Mahalla El Kubra' => 'El Mahalla El Kubra',
            'Giza' => 'Giza',
            'Mansoura' => 'Mansoura',
            'Port Said' => 'Port Said',
            'Shubra El Kheima' => 'Shubra El Kheima',
            'Suez' => 'Suez',
            'Tanta' => 'Tanta',
            'Other' => 'Other city not listed',
        ],
        'El Salvador' => [
            'San Salvador' => 'San Salvador',
            'Santa Ana' => 'Santa Ana',
            'Other' => 'Other city not listed',
        ],
        'Equatorial Guinea' => [
            'Bata' => 'Bata',
            'Malabo' => 'Malabo',
            'Other' => 'Other city not listed',
        ],
        'Eritrea' => [
            'Asmara' => 'Asmara',
            'Keren' => 'Keren',
            'Other' => 'Other city not listed',
        ],
        'Estonia' => [
            'Tallinn' => 'Tallinn',
            'Tartu' => 'Tartu',
            'Other' => 'Other city not listed',
        ],
        'Ethiopia' => [
            'Adama' => 'Adama',
            'Addis Ababa' => 'Addis Ababa',
            'Awasa' => 'Awasa',
            'Bahir Dar' => 'Bahir Dar',
            'Dessie' => 'Dessie',
            'Dire Dawa' => 'Dire Dawa',
            'Gondar' => 'Gondar',
            'Jijiga' => 'Jijiga',
            'Jimma' => 'Jimma',
            'Mek\'ele' => 'Mek\'ele',
            'Other' => 'Other city not listed',
        ],
        'Falkland Islands' => [
            'Goose Green' => 'Goose Green',
            'Stanley' => 'Stanley',
            'Other' => 'Other city not listed',
        ],
        'Falkland Islands (UK)' => [
            'Goose Green' => 'Goose Green',
            'Stanley' => 'Stanley',
            'Other' => 'Other city not listed',
        ],
        'Faroe Islands' => [
            'Klaksvík' => 'Klaksvík',
            'Tórshavn' => 'Tórshavn',
            'Other' => 'Other city not listed',
        ],
        'Faroe Islands (Denmark)' => [
            'Klaksvík' => 'Klaksvík',
            'Tórshavn' => 'Tórshavn',
            'Other' => 'Other city not listed',
        ],
        'Federated States of Micronesia' => [
            'Palikir' => 'Palikir',
            'Weno' => 'Weno',
            'Other' => 'Other city not listed',
        ],
        'Fiji' => [
            'Nasinu' => 'Nasinu',
            'Suva' => 'Suva',
            'Other' => 'Other city not listed',
        ],
        'Finland' => [
            'Espoo' => 'Espoo',
            'Helsinki' => 'Helsinki',
            'Tampere' => 'Tampere',
            'Other' => 'Other city not listed',
        ],
        'France' => [
            'Bordeaux' => 'Bordeaux',
            'Lille' => 'Lille',
            'Lyon' => 'Lyon',
            'Marseille' => 'Marseille',
            'Montpellier' => 'Montpellier',
            'Nantes' => 'Nantes',
            'Nice' => 'Nice',
            'Paris' => 'Paris',
            'Strasbourg' => 'Strasbourg',
            'Toulouse' => 'Toulouse',
            'Other' => 'Other city not listed',
        ],
        'French Guiana' => [
            'Cayenne' => 'Cayenne',
            'Saint-Laurent-du-Maroni' => 'Saint-Laurent-du-Maroni',
            'Other' => 'Other city not listed',
        ],
        'French Guiana (France)' => [
            'Cayenne' => 'Cayenne',
            'Saint-Laurent-du-Maroni' => 'Saint-Laurent-du-Maroni',
            'Other' => 'Other city not listed',
        ],
        'French Polynesia' => [
            'Mahina' => 'Mahina',
            'Papeete' => 'Papeete',
            'Other' => 'Other city not listed',
        ],
        'French Polynesia (France)' => [
            'Mahina' => 'Mahina',
            'Papeete' => 'Papeete',
            'Other' => 'Other city not listed',
        ],
        'Gabon' => [
            'Libreville' => 'Libreville',
            'Port-Gentil' => 'Port-Gentil',
            'Other' => 'Other city not listed',
        ],
        'Gambia' => [
            'Banjul' => 'Banjul',
            'Brikama' => 'Brikama',
            'Serekunda' => 'Serekunda',
            'Other' => 'Other city not listed',
        ],
        'Georgia' => [
            'Kutaisi' => 'Kutaisi',
            'Tbilisi' => 'Tbilisi',
            'Other' => 'Other city not listed',
        ],
        'Germany' => [
            'Berlin' => 'Berlin',
            'Cologne' => 'Cologne',
            'Dortmund' => 'Dortmund',
            'Düsseldorf' => 'Düsseldorf',
            'Essen' => 'Essen',
            'Frankfurt' => 'Frankfurt',
            'Hamburg' => 'Hamburg',
            'Munich' => 'Munich',
            'Rhine-Ruhr' => 'Rhine-Ruhr',
            'Stuttgart' => 'Stuttgart',
            'Other' => 'Other city not listed',
        ],
        'Ghana' => [
            'Accra' => 'Accra',
            'Kumasi' => 'Kumasi',
            'Other' => 'Other city not listed',
        ],
        'Gibraltar' => [
            'Gibraltar' => 'Gibraltar',
            'Other' => 'Other city not listed',
        ],
        'Gibraltar (UK)' => [
            'Gibraltar' => 'Gibraltar',
            'Other' => 'Other city not listed',
        ],
        'Greece' => [
            'Athens' => 'Athens',
            'Thessaloniki' => 'Thessaloniki',
            'Other' => 'Other city not listed',
        ],
        'Greenland' => [
            'Nuuk' => 'Nuuk',
            'Sisimiut' => 'Sisimiut',
            'Other' => 'Other city not listed',
        ],
        'Greenland (Denmark)' => [
            'Nuuk' => 'Nuuk',
            'Sisimiut' => 'Sisimiut',
            'Other' => 'Other city not listed',
        ],
        'Grenada' => [
            'Gouyave' => 'Gouyave',
            'St. George\'s' => 'St. George\'s',
            'Other' => 'Other city not listed',
        ],
        'Guam' => [
            'Hagåtña' => 'Hagåtña',
            'Mangilao' => 'Mangilao',
            'Tamuning' => 'Tamuning',
            'Other' => 'Other city not listed',
        ],
        'Guam (US)' => [
            'Hagåtña' => 'Hagåtña',
            'Mangilao' => 'Mangilao',
            'Tamuning' => 'Tamuning',
            'Other' => 'Other city not listed',
        ],
        'Guatemala' => [
            'Guatemala City' => 'Guatemala City',
            'Quetzaltenango' => 'Quetzaltenango',
            'Other' => 'Other city not listed',
        ],
        'Guernsey' => [
            'Saint Peter Port' => 'Saint Peter Port',
            'Vale' => 'Vale',
            'Other' => 'Other city not listed',
        ],
        'Guernsey (UK)' => [
            'Saint Peter Port' => 'Saint Peter Port',
            'Vale' => 'Vale',
            'Other' => 'Other city not listed',
        ],
        'Guinea' => [
            'Conakry' => 'Conakry',
            'Nzérékoré' => 'Nzérékoré',
            'Other' => 'Other city not listed',
        ],
        'Guinea-Bissau' => [
            'Bissau' => 'Bissau',
            'Gabú' => 'Gabú',
            'Other' => 'Other city not listed',
        ],
        'Guyana' => [
            'Georgetown' => 'Georgetown',
            'Linden' => 'Linden',
            'Other' => 'Other city not listed',
        ],
        'Haiti' => [
            'Gonaïves' => 'Gonaïves',
            'Port-au-Prince' => 'Port-au-Prince',
            'Other' => 'Other city not listed',
        ],
        'Honduras' => [
            'San Pedro Sula' => 'San Pedro Sula',
            'Tegucigalpa' => 'Tegucigalpa',
            'Other' => 'Other city not listed',
        ],
        'Hong Kong' => [
            'Kowloon' => 'Kowloon',
            'Victoria' => 'Victoria',
            'Other' => 'Other city not listed',
        ],
        'Hong Kong (China)' => [
            'Kowloon' => 'Kowloon',
            'Victoria' => 'Victoria',
            'Other' => 'Other city not listed',
        ],
        'Hungary' => [
            'Budapest' => 'Budapest',
            'Debrecen' => 'Debrecen',
            'Other' => 'Other city not listed',
        ],
        'Iceland' => [
            'Kópavogur' => 'Kópavogur',
            'Reykjavík' => 'Reykjavík',
            'Other' => 'Other city not listed',
        ],
        'India' => [
            'Ahmedabad' => 'Ahmedabad',
            'Bangalore' => 'Bangalore',
            'Chennai' => 'Chennai',
            'Delhi' => 'Delhi',
            'Hyderabad' => 'Hyderabad',
            'Kolkata' => 'Kolkata',
            'Mumbai' => 'Mumbai',
            'New Delhi' => 'New Delhi',
            'Pune' => 'Pune',
            'Surat' => 'Surat',
            'Other' => 'Other city not listed',
        ],
        'Indonesia' => [
            'Bandung' => 'Bandung',
            'Bekasi' => 'Bekasi',
            'Depok' => 'Depok',
            'Jakarta' => 'Jakarta',
            'Medan' => 'Medan',
            'Palembang' => 'Palembang',
            'Semarang' => 'Semarang',
            'South Tangerang' => 'South Tangerang',
            'Surabaya' => 'Surabaya',
            'Tangerang' => 'Tangerang',
            'Other' => 'Other city not listed',
        ],
        'Iran' => [
            'Mashhad' => 'Mashhad',
            'Tehran' => 'Tehran',
            'Other' => 'Other city not listed',
        ],
        'Iran, Islamic Republic of' => [
            'Mashhad' => 'Mashhad',
            'Tehran' => 'Tehran',
            'Other' => 'Other city not listed',
        ],
        'Iraq' => [
            'Baghdad' => 'Baghdad',
            'Basra' => 'Basra',
            'Other' => 'Other city not listed',
        ],
        'Ireland' => [
            'Cork' => 'Cork',
            'Dublin' => 'Dublin',
            'Other' => 'Other city not listed',
        ],
        'Isle of Man' => [
            'Douglas' => 'Douglas',
            'Onchan' => 'Onchan',
            'Other' => 'Other city not listed',
        ],
        'Isle of Man (UK)' => [
            'Douglas' => 'Douglas',
            'Onchan' => 'Onchan',
            'Other' => 'Other city not listed',
        ],
        'Israel' => [
            'Jerusalem' => 'Jerusalem',
            'Tel Aviv' => 'Tel Aviv',
            'Other' => 'Other city not listed',
        ],
        'Italy' => [
            'Milan' => 'Milan',
            'Rome' => 'Rome',
            'Other' => 'Other city not listed',
        ],
        'Jamaica' => [
            'Kingston' => 'Kingston',
            'Spanish Town' => 'Spanish Town',
            'Other' => 'Other city not listed',
        ],
        'Japan' => [
            'Fukuoka' => 'Fukuoka',
            'Kawasaki' => 'Kawasaki',
            'Kobe' => 'Kobe',
            'Kyoto' => 'Kyoto',
            'Nagoya' => 'Nagoya',
            'Osaka' => 'Osaka',
            'Saitama' => 'Saitama',
            'Sapporo' => 'Sapporo',
            'Tokyo' => 'Tokyo',
            'Yokohama' => 'Yokohama',
            'Other' => 'Other city not listed',
        ],
        'Jersey' => [
            'Saint Helier' => 'Saint Helier',
            'Saint Saviour' => 'Saint Saviour',
            'Other' => 'Other city not listed',
        ],
        'Jersey (UK)' => [
            'Saint Helier' => 'Saint Helier',
            'Saint Saviour' => 'Saint Saviour',
            'Other' => 'Other city not listed',
        ],
        'Jordan' => [
            'Amman' => 'Amman',
            'Zarqa' => 'Zarqa',
            'Other' => 'Other city not listed',
        ],
        'Kazakhstan' => [
            'Almaty' => 'Almaty',
            'Astana' => 'Astana',
            'Other' => 'Other city not listed',
        ],
        'Kenya' => [
            'Eldoret' => 'Eldoret',
            'Kangundo-Tala' => 'Kangundo-Tala',
            'Kehancha' => 'Kehancha',
            'Kikuyu' => 'Kikuyu',
            'Kisumu' => 'Kisumu',
            'Malindi' => 'Malindi',
            'Mombasa' => 'Mombasa',
            'Nairobi' => 'Nairobi',
            'Nakuru' => 'Nakuru',
            'Ruiru' => 'Ruiru',
            'Other' => 'Other city not listed',
        ],
        'Kiribati' => [
            'Bairiki' => 'Bairiki',
            'Betio' => 'Betio',
            'Tarawa' => 'Tarawa',
            'Other' => 'Other city not listed',
        ],
        'Korea, Democratic People\'s Republic of' => [
            'Hamhung' => 'Hamhung',
            'Pyongyang' => 'Pyongyang',
            'Other' => 'Other city not listed',
        ],
        'Korea, Republic of' => [
            'Busan' => 'Busan',
            'Seoul' => 'Seoul',
            'Other' => 'Other city not listed',
        ],
        'Kosovo' => [
            'Pristina' => 'Pristina',
            'Prizren' => 'Prizren',
            'Other' => 'Other city not listed',
        ],
        'Kuwait' => [
            'Al Jahra' => 'Al Jahra',
            'Kuwait City' => 'Kuwait City',
            'Other' => 'Other city not listed',
        ],
        'Kyrgyzstan' => [
            'Bishkek' => 'Bishkek',
            'Osh' => 'Osh',
            'Other' => 'Other city not listed',
        ],
        'Lao People\'s Democratic Republic' => [
            'Pakxe' => 'Pakxe',
            'Vientiane' => 'Vientiane',
            'Other' => 'Other city not listed',
        ],
        'Laos' => [
            'Pakxe' => 'Pakxe',
            'Vientiane' => 'Vientiane',
            'Other' => 'Other city not listed',
        ],
        'Latvia' => [
            'Daugavpils' => 'Daugavpils',
            'Riga' => 'Riga',
            'Other' => 'Other city not listed',
        ],
        'Lebanon' => [
            'Beirut' => 'Beirut',
            'Tripoli' => 'Tripoli',
            'Other' => 'Other city not listed',
        ],
        'Lesotho' => [
            'Maseru' => 'Maseru',
            'Teyateyaneng' => 'Teyateyaneng',
            'Other' => 'Other city not listed',
        ],
        'Liberia' => [
            'Gbarnga' => 'Gbarnga',
            'Monrovia' => 'Monrovia',
            'Other' => 'Other city not listed',
        ],
        'Libya' => [
            'Benghazi' => 'Benghazi',
            'Tripoli' => 'Tripoli',
            'Other' => 'Other city not listed',
        ],
        'Liechtenstein' => [
            'Schaan' => 'Schaan',
            'Vaduz' => 'Vaduz',
            'Other' => 'Other city not listed',
        ],
        'Lithuania' => [
            'Kaunas' => 'Kaunas',
            'Vilnius' => 'Vilnius',
            'Other' => 'Other city not listed',
        ],
        'Luxembourg' => [
            'Esch-sur-Alzette' => 'Esch-sur-Alzette',
            'Luxembourg City' => 'Luxembourg City',
            'Other' => 'Other city not listed',
        ],
        'Macedonia' => [
            'Bitola' => 'Bitola',
            'Skopje' => 'Skopje',
            'Other' => 'Other city not listed',
        ],
        'Madagascar' => [
            'Antananarivo' => 'Antananarivo',
            'Toamasina' => 'Toamasina',
            'Other' => 'Other city not listed',
        ],
        'Malawi' => [
            'Blantyre' => 'Blantyre',
            'Lilongwe' => 'Lilongwe',
            'Other' => 'Other city not listed',
        ],
        'Malaysia' => [
            'George Town' => 'George Town',
            'Kuala Lumpur' => 'Kuala Lumpur',
            'Other' => 'Other city not listed',
        ],
        'Maldives' => [
            'Addu City' => 'Addu City',
            'Malé' => 'Malé',
            'Other' => 'Other city not listed',
        ],
        'Mali' => [
            'Bamako' => 'Bamako',
            'Sikasso' => 'Sikasso',
            'Other' => 'Other city not listed',
        ],
        'Malta' => [
            'Birkirkara' => 'Birkirkara',
            'Mosta' => 'Mosta',
            'Valletta' => 'Valletta',
            'Other' => 'Other city not listed',
        ],
        'Marshall Islands' => [
            'Ebeye' => 'Ebeye',
            'Majuro' => 'Majuro',
            'Rita' => 'Rita',
            'Other' => 'Other city not listed',
        ],
        'Mauritania' => [
            'Nouadhibou' => 'Nouadhibou',
            'Nouakchott' => 'Nouakchott',
            'Other' => 'Other city not listed',
        ],
        'Mauritius' => [
            'Beau Bassin-Rose Hill' => 'Beau Bassin-Rose Hill',
            'Port Louis' => 'Port Louis',
            'Other' => 'Other city not listed',
        ],
        'Mayotte' => [
            'Dzaoudzi' => 'Dzaoudzi',
            'Mamoudzou' => 'Mamoudzou',
            'Other' => 'Other city not listed',
        ],
        'Mayotte (France)' => [
            'Dzaoudzi' => 'Dzaoudzi',
            'Mamoudzou' => 'Mamoudzou',
            'Other' => 'Other city not listed',
        ],
        'Mexico' => [
            'Ciudad Juárez' => 'Ciudad Juárez',
            'Ecatepec' => 'Ecatepec',
            'Guadalajara' => 'Guadalajara',
            'León' => 'León',
            'Mexico City' => 'Mexico City',
            'Monterrey' => 'Monterrey',
            'Nezahualcóyotl' => 'Nezahualcóyotl',
            'Puebla' => 'Puebla',
            'Tijuana' => 'Tijuana',
            'Zapopan' => 'Zapopan',
            'Other' => 'Other city not listed',
        ],
        'Moldova' => [
            'Chișinău' => 'Chișinău',
            'Tiraspol' => 'Tiraspol',
            'Other' => 'Other city not listed',
        ],
        'Moldova, Republic of' => [
            'Chișinău' => 'Chișinău',
            'Tiraspol' => 'Tiraspol',
            'Other' => 'Other city not listed',
        ],
        'Monaco' => [
            'La Condamine' => 'La Condamine',
            'Monaco' => 'Monaco',
            'Monte Carlo' => 'Monte Carlo',
            'Other' => 'Other city not listed',
        ],
        'Mongolia' => [
            'Darkhan' => 'Darkhan',
            'Ulaanbaatar' => 'Ulaanbaatar',
            'Other' => 'Other city not listed',
        ],
        'Montenegro' => [
            'Nikšić' => 'Nikšić',
            'Podgorica' => 'Podgorica',
            'Other' => 'Other city not listed',
        ],
        'Montserrat' => [
            'Brades' => 'Brades',
            'Saint Peter\'s' => 'Saint Peter\'s',
            'Other' => 'Other city not listed',
        ],
        'Montserrat (UK)' => [
            'Brades' => 'Brades',
            'Saint Peter\'s' => 'Saint Peter\'s',
            'Other' => 'Other city not listed',
        ],
        'Morocco' => [
            'Casablanca' => 'Casablanca',
            'Fez' => 'Fez',
            'Rabat' => 'Rabat',
            'Other' => 'Other city not listed',
        ],
        'Mozambique' => [
            'Beira' => 'Beira',
            'Maputo' => 'Maputo',
            'Other' => 'Other city not listed',
        ],
        'Myanmar' => [
            'Mandalay' => 'Mandalay',
            'Nay Pyi Taw' => 'Nay Pyi Taw',
            'Yangon' => 'Yangon',
            'Other' => 'Other city not listed',
        ],
        'Nagorno-Karabakh' => [
            'Shusha' => 'Shusha',
            'Stepanakert' => 'Stepanakert',
            'Other' => 'Other city not listed',
        ],
        'Nagorno-Karabakh (Azerbaijan)' => [
            'Shusha' => 'Shusha',
            'Stepanakert' => 'Stepanakert',
            'Other' => 'Other city not listed',
        ],
        'Namibia' => [
            'Rundu' => 'Rundu',
            'Windhoek' => 'Windhoek',
            'Other' => 'Other city not listed',
        ],
        'Nauru' => [
            'Denigomudu' => 'Denigomudu',
            'Yaren' => 'Yaren',
            'Other' => 'Other city not listed',
        ],
        'Nepal' => [
            'Kathmandu' => 'Kathmandu',
            'Pokhara' => 'Pokhara',
            'Other' => 'Other city not listed',
        ],
        'Netherlands' => [
            'Amsterdam' => 'Amsterdam',
            'Rotterdam' => 'Rotterdam',
            'Other' => 'Other city not listed',
        ],
        'New Caledonia' => [
            'Nouméa' => 'Nouméa',
            'Wé' => 'Wé',
            'Other' => 'Other city not listed',
        ],
        'New Caledonia (France)' => [
            'Nouméa' => 'Nouméa',
            'Wé' => 'Wé',
            'Other' => 'Other city not listed',
        ],
        'New Zealand' => [
            'Auckland' => 'Auckland',
            'Christchurch' => 'Christchurch',
            'Wellington' => 'Wellington',
            'Other' => 'Other city not listed',
        ],
        'Nicaragua' => [
            'León' => 'León',
            'Managua' => 'Managua',
            'Other' => 'Other city not listed',
        ],
        'Niger' => [
            'Niamey' => 'Niamey',
            'Zinder' => 'Zinder',
            'Other' => 'Other city not listed',
        ],
        'Nigeria' => [
            'Abuja' => 'Abuja',
            'Benin City' => 'Benin City',
            'Enugu' => 'Enugu',
            'Ibadan' => 'Ibadan',
            'Ilorin' => 'Ilorin',
            'Jos' => 'Jos',
            'Kaduna' => 'Kaduna',
            'Kano' => 'Kano',
            'Lagos' => 'Lagos',
            'Port Harcourt' => 'Port Harcourt',
            'Other' => 'Other city not listed',
        ],
        'Niue' => [
            'Alofi' => 'Alofi',
            'Hakupu' => 'Hakupu',
            'Other' => 'Other city not listed',
        ],
        'Niue (New Zealand)' => [
            'Alofi' => 'Alofi',
            'Hakupu' => 'Hakupu',
            'Other' => 'Other city not listed',
        ],
        'Norfolk Island' => [
            'Burnt Pine' => 'Burnt Pine',
            'Kingston' => 'Kingston',
            'Other' => 'Other city not listed',
        ],
        'Norfolk Island (Australia)' => [
            'Burnt Pine' => 'Burnt Pine',
            'Kingston' => 'Kingston',
            'Other' => 'Other city not listed',
        ],
        'North Korea' => [
            'Hamhung' => 'Hamhung',
            'Pyongyang' => 'Pyongyang',
            'Other' => 'Other city not listed',
        ],
        'Northern Mariana Islands' => [
            'Garapan' => 'Garapan',
            'San Antonio' => 'San Antonio',
            'Other' => 'Other city not listed',
        ],
        'Northern Mariana Islands (US)' => [
            'Garapan' => 'Garapan',
            'San Antonio' => 'San Antonio',
            'Other' => 'Other city not listed',
        ],
        'Norway' => [
            'Bergen' => 'Bergen',
            'Oslo' => 'Oslo',
            'Other' => 'Other city not listed',
        ],
        'Oman' => [
            'Muscat' => 'Muscat',
            'Salalah' => 'Salalah',
            'Other' => 'Other city not listed',
        ],
        'Pakistan' => [
            'Faisalabad' => 'Faisalabad',
            'Gujranwala' => 'Gujranwala',
            'Hyderabad' => 'Hyderabad',
            'Islamabad' => 'Islamabad',
            'Karachi' => 'Karachi',
            'Lahore' => 'Lahore',
            'Multan' => 'Multan',
            'Peshawar' => 'Peshawar',
            'Quetta' => 'Quetta',
            'Rawalpindi' => 'Rawalpindi',
            'Other' => 'Other city not listed',
        ],
        'Palau' => [
            'Airai' => 'Airai',
            'Koror' => 'Koror',
            'Ngerulmud' => 'Ngerulmud',
            'Other' => 'Other city not listed',
        ],
        'Palestine' => [
            'East Jerusalem' => 'East Jerusalem',
            'Gaza City' => 'Gaza City',
            'Hebron' => 'Hebron',
            'Other' => 'Other city not listed',
        ],
        'Panama' => [
            'Colón' => 'Colón',
            'Panama City' => 'Panama City',
            'Other' => 'Other city not listed',
        ],
        'Papua New Guinea' => [
            'Lae' => 'Lae',
            'Port Moresby' => 'Port Moresby',
            'Other' => 'Other city not listed',
        ],
        'Paraguay' => [
            'Asunción' => 'Asunción',
            'Ciudad del Este' => 'Ciudad del Este',
            'Other' => 'Other city not listed',
        ],
        'Peru' => [
            'Arequipa' => 'Arequipa',
            'Lima' => 'Lima',
            'Other' => 'Other city not listed',
        ],
        'Philippines' => [
            'Cebu City' => 'Cebu City',
            'Manila' => 'Manila',
            'Quezon City' => 'Quezon City',
            'Other' => 'Other city not listed',
        ],
        'Pitcairn Islands' => [
            'Adamstown' => 'Adamstown',
            'Other' => 'Other city not listed',
        ],
        'Pitcairn Islands (UK)' => [
            'Adamstown' => 'Adamstown',
            'Other' => 'Other city not listed',
        ],
        'Poland' => [
            'Kraków' => 'Kraków',
            'Warsaw' => 'Warsaw',
            'Other' => 'Other city not listed',
        ],
        'Portugal' => [
            'Lisbon' => 'Lisbon',
            'Porto' => 'Porto',
            'Other' => 'Other city not listed',
        ],
        'Puerto Rico' => [
            'Bayamón' => 'Bayamón',
            'Ponce' => 'Ponce',
            'San Juan' => 'San Juan',
            'Other' => 'Other city not listed',
        ],
        'Puerto Rico (US)' => [
            'Bayamón' => 'Bayamón',
            'Ponce' => 'Ponce',
            'San Juan' => 'San Juan',
            'Other' => 'Other city not listed',
        ],
        'Qatar' => [
            'Al Rayyan' => 'Al Rayyan',
            'Doha' => 'Doha',
            'Other' => 'Other city not listed',
        ],
        'Republic of the Congo' => [
            'Brazzaville' => 'Brazzaville',
            'Pointe-Noire' => 'Pointe-Noire',
            'Other' => 'Other city not listed',
        ],
        'Romania' => [
            'Bucharest' => 'Bucharest',
            'Cluj-Napoca' => 'Cluj-Napoca',
            'Constanța' => 'Constanța',
            'Other' => 'Other city not listed',
        ],
        'Russia' => [
            'Chelyabinsk' => 'Chelyabinsk',
            'Kazan' => 'Kazan',
            'Moscow' => 'Moscow',
            'Nizhny Novgorod' => 'Nizhny Novgorod',
            'Novosibirsk' => 'Novosibirsk',
            'Omsk' => 'Omsk',
            'Rostov-on-Don' => 'Rostov-on-Don',
            'Saint Petersburg' => 'Saint Petersburg',
            'Samara' => 'Samara',
            'Yekaterinburg' => 'Yekaterinburg',
            'Other' => 'Other city not listed',
        ],
        'Russian Federation' => [
            'Chelyabinsk' => 'Chelyabinsk',
            'Kazan' => 'Kazan',
            'Moscow' => 'Moscow',
            'Nizhny Novgorod' => 'Nizhny Novgorod',
            'Novosibirsk' => 'Novosibirsk',
            'Omsk' => 'Omsk',
            'Rostov-on-Don' => 'Rostov-on-Don',
            'Saint Petersburg' => 'Saint Petersburg',
            'Samara' => 'Samara',
            'Yekaterinburg' => 'Yekaterinburg',
            'Other' => 'Other city not listed',
        ],
        'Rwanda' => [
            'Kigali' => 'Kigali',
            'Muhanga' => 'Muhanga',
            'Other' => 'Other city not listed',
        ],
        'Saint Barthélemy' => [
            'Gustavia' => 'Gustavia',
            'St. Jean' => 'St. Jean',
            'Other' => 'Other city not listed',
        ],
        'Saint Barthélemy (France)' => [
            'Gustavia' => 'Gustavia',
            'St. Jean' => 'St. Jean',
            'Other' => 'Other city not listed',
        ],
        'Saint Helena' => [
            'Half Tree Hollow' => 'Half Tree Hollow',
            'Jamestown' => 'Jamestown',
            'Other' => 'Other city not listed',
        ],
        'Saint Helena (UK)' => [
            'Half Tree Hollow' => 'Half Tree Hollow',
            'Jamestown' => 'Jamestown',
            'Other' => 'Other city not listed',
        ],
        'Saint Kitts and Nevis' => [
            'Basseterre' => 'Basseterre',
            'Charlestown' => 'Charlestown',
            'Other' => 'Other city not listed',
        ],
        'Saint Lucia' => [
            'Castries' => 'Castries',
            'Gros Islet' => 'Gros Islet',
            'Other' => 'Other city not listed',
        ],
        'Saint Martin' => [
            'Marigot' => 'Marigot',
            'Rambaud' => 'Rambaud',
            'Other' => 'Other city not listed',
        ],
        'Saint Martin (France)' => [
            'Marigot' => 'Marigot',
            'Rambaud' => 'Rambaud',
            'Other' => 'Other city not listed',
        ],
        'Saint Pierre and Miquelon' => [
            'Miquelon' => 'Miquelon',
            'Saint-Pierre' => 'Saint-Pierre',
            'Other' => 'Other city not listed',
        ],
        'Saint Pierre and Miquelon (France)' => [
            'Miquelon' => 'Miquelon',
            'Saint-Pierre' => 'Saint-Pierre',
            'Other' => 'Other city not listed',
        ],
        'Saint Vincent and the Grenadines' => [
            'Georgetown' => 'Georgetown',
            'Kingstown' => 'Kingstown',
            'Other' => 'Other city not listed',
        ],
        'Samoa' => [
            'Apia' => 'Apia',
            'Vaitele' => 'Vaitele',
            'Other' => 'Other city not listed',
        ],
        'San Marino' => [
            'Borgo Maggiore' => 'Borgo Maggiore',
            'Dogana' => 'Dogana',
            'San Marino' => 'San Marino',
            'Other' => 'Other city not listed',
        ],
        'Saudi Arabia' => [
            'Jeddah' => 'Jeddah',
            'Riyadh' => 'Riyadh',
            'Other' => 'Other city not listed',
        ],
        'Senegal' => [
            'Dakar' => 'Dakar',
            'Touba' => 'Touba',
            'Other' => 'Other city not listed',
        ],
        'Serbia' => [
            'Belgrade' => 'Belgrade',
            'Novi Sad' => 'Novi Sad',
            'Other' => 'Other city not listed',
        ],
        'Seychelles' => [
            'Anse Etoile' => 'Anse Etoile',
            'Victoria' => 'Victoria',
            'Other' => 'Other city not listed',
        ],
        'Sierra Leone' => [
            'Bo' => 'Bo',
            'Freetown' => 'Freetown',
            'Other' => 'Other city not listed',
        ],
        'Singapore' => [
            'Singapore' => 'Singapore',
            'Other' => 'Other city not listed',
        ],
        'Sint Maarten' => [
            'Cul De Sac' => 'Cul De Sac',
            'Lower Prince\'s Quarter' => 'Lower Prince\'s Quarter',
            'Philipsburg' => 'Philipsburg',
            'Other' => 'Other city not listed',
        ],
        'Sint Maarten (Netherlands)' => [
            'Cul De Sac' => 'Cul De Sac',
            'Lower Prince\'s Quarter' => 'Lower Prince\'s Quarter',
            'Philipsburg' => 'Philipsburg',
            'Other' => 'Other city not listed',
        ],
        'Slovakia' => [
            'Bratislava' => 'Bratislava',
            'Košice' => 'Košice',
            'Other' => 'Other city not listed',
        ],
        'Slovenia' => [
            'Ljubljana' => 'Ljubljana',
            'Maribor' => 'Maribor',
            'Other' => 'Other city not listed',
        ],
        'Solomon Islands' => [
            'Gizo' => 'Gizo',
            'Honiara' => 'Honiara',
            'Other' => 'Other city not listed',
        ],
        'Somalia' => [
            'Hargeisa' => 'Hargeisa',
            'Mogadishu' => 'Mogadishu',
            'Other' => 'Other city not listed',
        ],
        'South Africa' => [
            'Buffalo City' => 'Buffalo City',
            'Cape Town' => 'Cape Town',
            'Durban' => 'Durban',
            'Ekurhuleni' => 'Ekurhuleni',
            'eThekwini' => 'eThekwini',
            'Johannesburg' => 'Johannesburg',
            'Mangaung' => 'Mangaung',
            'Nelson Mandela Bay' => 'Nelson Mandela Bay',
            'Pretoria' => 'Pretoria',
            'Tshwane' => 'Tshwane',
            'Other' => 'Other city not listed',
        ],
        'South Georgia and the South Sandwich Islands' => [
            'Grytviken' => 'Grytviken',
            'King Edward Point' => 'King Edward Point',
            'Other' => 'Other city not listed',
        ],
        'South Georgia and the South Sandwich Islands (UK)' => [
            'Grytviken' => 'Grytviken',
            'King Edward Point' => 'King Edward Point',
            'Other' => 'Other city not listed',
        ],
        'South Korea' => [
            'Busan' => 'Busan',
            'Seoul' => 'Seoul',
            'Other' => 'Other city not listed',
        ],
        'South Ossetia' => [
            'Akhalgori' => 'Akhalgori',
            'Tskhinvali' => 'Tskhinvali',
            'Other' => 'Other city not listed',
        ],
        'South Ossetia (Georgia)' => [
            'Akhalgori' => 'Akhalgori',
            'Tskhinvali' => 'Tskhinvali',
            'Other' => 'Other city not listed',
        ],
        'South Sudan' => [
            'Juba' => 'Juba',
            'Yei' => 'Yei',
            'Other' => 'Other city not listed',
        ],
        'Spain' => [
            'Barcelona' => 'Barcelona',
            'Madrid' => 'Madrid',
            'Other' => 'Other city not listed',
        ],
        'Sri Lanka' => [
            'Colombo' => 'Colombo',
            'Dehiwala-Mount Lavinia' => 'Dehiwala-Mount Lavinia',
            'Kandy' => 'Kandy',
            'Sri Jayawardenepura Kotte' => 'Sri Jayawardenepura Kotte',
            'Other' => 'Other city not listed',
        ],
        'Sudan' => [
            'Khartoum' => 'Khartoum',
            'Omdurman' => 'Omdurman',
            'Port Sudan' => 'Port Sudan',
            'Other' => 'Other city not listed',
        ],
        'Suriname' => [
            'Lelydorp' => 'Lelydorp',
            'Paramaribo' => 'Paramaribo',
            'Other' => 'Other city not listed',
        ],
        'Svalbard and Jan Mayen' => [
            'Barentsburg' => 'Barentsburg',
            'Longyearbyen' => 'Longyearbyen',
            'Other' => 'Other city not listed',
        ],
        'Svalbard and Jan Mayen (Norway)' => [
            'Barentsburg' => 'Barentsburg',
            'Longyearbyen' => 'Longyearbyen',
            'Other' => 'Other city not listed',
        ],
        'Swaziland' => [
            'Manzini' => 'Manzini',
            'Mbabane' => 'Mbabane',
            'Other' => 'Other city not listed',
        ],
        'Sweden' => [
            'Gothenburg' => 'Gothenburg',
            'Stockholm' => 'Stockholm',
            'Other' => 'Other city not listed',
        ],
        'Switzerland' => [
            'Bern' => 'Bern',
            'Geneva' => 'Geneva',
            'Zürich' => 'Zürich',
            'Other' => 'Other city not listed',
        ],
        'Syria' => [
            'Aleppo' => 'Aleppo',
            'Damascus' => 'Damascus',
            'Other' => 'Other city not listed',
        ],
        'Syrian Arab Republic' => [
            'Aleppo' => 'Aleppo',
            'Damascus' => 'Damascus',
            'Other' => 'Other city not listed',
        ],
        'São Tomé and Príncipe' => [
            'São Tomé' => 'São Tomé',
            'Trindade' => 'Trindade',
            'Other' => 'Other city not listed',
        ],
        'Taiwan' => [
            'New Taipei' => 'New Taipei',
            'Taichung' => 'Taichung',
            'Taipei' => 'Taipei',
            'Other' => 'Other city not listed',
        ],
        'Tajikistan' => [
            'Dushanbe' => 'Dushanbe',
            'Khujand' => 'Khujand',
            'Other' => 'Other city not listed',
        ],
        'Tanzania' => [
            'Arusha' => 'Arusha',
            'Dar es Salaam' => 'Dar es Salaam',
            'Dodoma' => 'Dodoma',
            'Kahama' => 'Kahama',
            'Mbeya' => 'Mbeya',
            'Morogoro' => 'Morogoro',
            'Mwanza' => 'Mwanza',
            'Tabora' => 'Tabora',
            'Tanga' => 'Tanga',
            'Zanzibar City' => 'Zanzibar City',
            'Other' => 'Other city not listed',
        ],
        'Tanzania, United Republic of' => [
            'Arusha' => 'Arusha',
            'Dar es Salaam' => 'Dar es Salaam',
            'Dodoma' => 'Dodoma',
            'Kahama' => 'Kahama',
            'Mbeya' => 'Mbeya',
            'Morogoro' => 'Morogoro',
            'Mwanza' => 'Mwanza',
            'Tabora' => 'Tabora',
            'Tanga' => 'Tanga',
            'Zanzibar City' => 'Zanzibar City',
            'Other' => 'Other city not listed',
        ],
        'Thailand' => [
            'Bangkok' => 'Bangkok',
            'Nonthaburi' => 'Nonthaburi',
            'Pak Kret' => 'Pak Kret',
            'Other' => 'Other city not listed',
        ],
        'Togo' => [
            'Lomé' => 'Lomé',
            'Sokodé' => 'Sokodé',
            'Other' => 'Other city not listed',
        ],
        'Tokelau' => [
            'Atafu' => 'Atafu',
            'Fakaofo' => 'Fakaofo',
            'Other' => 'Other city not listed',
        ],
        'Tokelau (New Zealand)' => [
            'Atafu' => 'Atafu',
            'Fakaofo' => 'Fakaofo',
            'Other' => 'Other city not listed',
        ],
        'Tonga' => [
            'Neiafu' => 'Neiafu',
            'Nukuʻalofa' => 'Nukuʻalofa',
            'Other' => 'Other city not listed',
        ],
        'Transnistria' => [
            'Tighina' => 'Tighina',
            'Tiraspol' => 'Tiraspol',
            'Other' => 'Other city not listed',
        ],
        'Transnistria (Moldova)' => [
            'Tighina' => 'Tighina',
            'Tiraspol' => 'Tiraspol',
            'Other' => 'Other city not listed',
        ],
        'Trinidad and Tobago' => [
            'Chaguanas' => 'Chaguanas',
            'Port of Spain' => 'Port of Spain',
            'San Fernando' => 'San Fernando',
            'Other' => 'Other city not listed',
        ],
        'Tunisia' => [
            'Sfax' => 'Sfax',
            'Tunis' => 'Tunis',
            'Other' => 'Other city not listed',
        ],
        'Turkey' => [
            'Adana' => 'Adana',
            'Ankara' => 'Ankara',
            'Antalya' => 'Antalya',
            'Bursa' => 'Bursa',
            'Gaziantep' => 'Gaziantep',
            'Istanbul' => 'Istanbul',
            'Izmir' => 'Izmir',
            'Kayseri' => 'Kayseri',
            'Konya' => 'Konya',
            'Mersin' => 'Mersin',
            'Other' => 'Other city not listed',
        ],
        'Turkmenistan' => [
            'Ashgabat' => 'Ashgabat',
            'Türkmenabat' => 'Türkmenabat',
            'Other' => 'Other city not listed',
        ],
        'Turks and Caicos Islands' => [
            'Cockburn Town' => 'Cockburn Town',
            'Five Cays' => 'Five Cays',
            'Honda Road' => 'Honda Road',
            'Other' => 'Other city not listed',
        ],
        'Turks and Caicos Islands (UK)' => [
            'Cockburn Town' => 'Cockburn Town',
            'Five Cays' => 'Five Cays',
            'Honda Road' => 'Honda Road',
            'Other' => 'Other city not listed',
        ],
        'Tuvalu' => [
            'Asau' => 'Asau',
            'Funafuti' => 'Funafuti',
            'Other' => 'Other city not listed',
        ],
        'Uganda' => [
            'Gulu' => 'Gulu',
            'Kampala' => 'Kampala',
            'Kasese' => 'Kasese',
            'Kira' => 'Kira',
            'Lugazi' => 'Lugazi',
            'Masaka' => 'Masaka',
            'Mbarara' => 'Mbarara',
            'Mukono' => 'Mukono',
            'Nansana' => 'Nansana',
            'Ssabagabo' => 'Ssabagabo',
            'Other' => 'Other city not listed',
        ],
        'Ukraine' => [
            'Donetsk' => 'Donetsk',
            'Kharkiv' => 'Kharkiv',
            'Kiev' => 'Kiev',
            'Other' => 'Other city not listed',
        ],
        'United Arab Emirates' => [
            'Abu Dhabi' => 'Abu Dhabi',
            'Dubai' => 'Dubai',
            'Other' => 'Other city not listed',
        ],
        'United Kingdom' => [
            'Birmingham' => 'Birmingham',
            'Bristol' => 'Bristol',
            'Edinburgh' => 'Edinburgh',
            'Glasgow' => 'Glasgow',
            'Leeds' => 'Leeds',
            'Leicester' => 'Leicester',
            'Liverpool' => 'Liverpool',
            'London' => 'London',
            'Manchester' => 'Manchester',
            'Sheffield' => 'Sheffield',
            'Other' => 'Other city not listed',
        ],
        'United States' => [
            'Atlanta Metro Area' => 'Atlanta Metro Area',
            'chicago Metro Area' => 'chicago Metro Area',
            'Dallas-Fort Worth Metro Area' => 'Dallas-Fort Worth Metro Area',
            'Detroit Metro Area' => 'Detroit Metro Area',
            'Houston Metro Area' => 'Houston Metro Area',
            'Los Angeles Metro Area' => 'Los Angeles Metro Area',
            'New York City' => 'New York City',
            'New York City Metro Area' => 'New York City Metro Area',
            'San Francisco Metro Area' => 'San Francisco Metro Area',
            'Washington, D.C. Metro Area' => 'Washington, D.C. Metro Area',
            'Other' => 'Other city not listed',
        ],
        'United States of America' => [
            'Atlanta Metro Area' => 'Atlanta Metro Area',
            'chicago Metro Area' => 'chicago Metro Area',
            'Dallas-Fort Worth Metro Area' => 'Dallas-Fort Worth Metro Area',
            'Detroit Metro Area' => 'Detroit Metro Area',
            'Houston Metro Area' => 'Houston Metro Area',
            'Los Angeles Metro Area' => 'Los Angeles Metro Area',
            'New York City' => 'New York City',
            'New York City Metro Area' => 'New York City Metro Area',
            'San Francisco Metro Area' => 'San Francisco Metro Area',
            'Washington, D.C. Metro Area' => 'Washington, D.C. Metro Area',
            'Other' => 'Other city not listed',
        ],
        'United States Virgin Islands' => [
            'Anna\'s Retreat' => 'Anna\'s Retreat',
            'Charlotte Amalie' => 'Charlotte Amalie',
            'Other' => 'Other city not listed',
        ],
        'United States Virgin Islands (US)' => [
            'Anna\'s Retreat' => 'Anna\'s Retreat',
            'Charlotte Amalie' => 'Charlotte Amalie',
            'Other' => 'Other city not listed',
        ],
        'Uruguay' => [
            'Ciudad de la Costa' => 'Ciudad de la Costa',
            'Maldonado' => 'Maldonado',
            'Montevideo' => 'Montevideo',
            'Other' => 'Other city not listed',
        ],
        'Uzbekistan' => [
            'Namangan' => 'Namangan',
            'Tashkent' => 'Tashkent',
            'Other' => 'Other city not listed',
        ],
        'Vanuatu' => [
            'Luganville' => 'Luganville',
            'Port Vila' => 'Port Vila',
            'Other' => 'Other city not listed',
        ],
        'Vatican City' => [
            'Vatican City' => 'Vatican City',
            'Other' => 'Other city not listed',
        ],
        'Venezuela' => [
            'Caracas' => 'Caracas',
            'Maracaibo' => 'Maracaibo',
            'Other' => 'Other city not listed',
        ],
        'Venezuela, Bolivarian Republic of' => [
            'Caracas' => 'Caracas',
            'Maracaibo' => 'Maracaibo',
            'Other' => 'Other city not listed',
        ],
        'Viet Nam' => [
            'Hanoi' => 'Hanoi',
            'Ho Chi Minh City' => 'Ho Chi Minh City',
            'Other' => 'Other city not listed',
        ],
        'Vietnam' => [
            'Hanoi' => 'Hanoi',
            'Ho Chi Minh City' => 'Ho Chi Minh City',
            'Other' => 'Other city not listed',
        ],
        'Wallis and Futuna' => [
            'Alele' => 'Alele',
            'Mata-Utu' => 'Mata-Utu',
            'Other' => 'Other city not listed',
        ],
        'Wallis and Futuna (France)' => [
            'Alele' => 'Alele',
            'Mata-Utu' => 'Mata-Utu',
            'Other' => 'Other city not listed',
        ],
        'Western Sahara' => [
            'Dakhla' => 'Dakhla',
            'Laayoune' => 'Laayoune',
            'Other' => 'Other city not listed',
        ],
        'Yemen' => [
            'Aden' => 'Aden',
            'Sana\'a' => 'Sana\'a',
            'Other' => 'Other city not listed',
        ],
        'Zambia' => [
            'Kitwe' => 'Kitwe',
            'Lusaka' => 'Lusaka',
            'Other' => 'Other city not listed',
        ],
        'Zimbabwe' => [
            'Bulawayo' => 'Bulawayo',
            'Harare' => 'Harare',
            'Other' => 'Other city not listed',
        ],
        'Åland' => [
            'Jomala' => 'Jomala',
            'Mariehamn' => 'Mariehamn',
            'Other' => 'Other city not listed',
        ],
        'Åland (Finland)' => [
            'Jomala' => 'Jomala',
            'Mariehamn' => 'Mariehamn',
            'Other' => 'Other city not listed',
        ],
    ],
];
