<?php
declare(strict_types=1);

require_once(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/user/lib.php');
require_once(__DIR__ . '/accesslib.php');
require_once(__DIR__ . '/account_ids.php');
require_login();

pqh_require_academy_operations(
    'Only academy operations users can run SQA full cross-role golden path verification.',
    new moodle_url('/local/hubredirect/workspace_dashboard.php'),
    'Cross-role golden path access required'
);

$workspaceid = pqh_current_workspace_id((int)$USER->id, optional_param('workspaceid', 0, PARAM_INT));
$consumercontext = pqh_requested_consumer_context();
$consumerid = (int)($consumercontext->consumerid ?? 0);
$runid = trim(optional_param('runid', '', PARAM_TEXT));
$coursekey = trim(optional_param('coursekey', 'pre_quraan', PARAM_ALPHANUMEXT));
$invoiceamount = trim(optional_param('invoiceamount', '25.00', PARAM_TEXT));
$cleanupmode = optional_param('cleanupmode', 'archive', PARAM_ALPHANUMEXT);
$action = optional_param('action', 'create_verify', PARAM_ALPHANUMEXT);
$result = null;
$error = '';

if ($workspaceid <= 0) {
    pqh_access_denied('Cross-role golden path requires a workspace context.', new moodle_url('/local/hubredirect/workspace_dashboard.php'), 'Workspace required');
}

function pqcrgp_table_ready(string $table): bool {
    global $DB;
    try {
        return $DB->get_manager()->table_exists($table);
    } catch (Throwable $e) {
        return false;
    }
}

function pqcrgp_has_field(string $table, string $field): bool {
    global $DB;
    try {
        return $DB->get_manager()->field_exists($table, $field);
    } catch (Throwable $e) {
        return false;
    }
}

function pqcrgp_filter_record(string $table, array $record): stdClass {
    $filtered = [];
    foreach ($record as $field => $value) {
        if ($field === 'id' || pqcrgp_has_field($table, $field)) {
            $filtered[$field] = $value;
        }
    }
    return (object)$filtered;
}

function pqcrgp_token(string $runid): string {
    $token = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '', $runid));
    return substr($token !== '' ? $token : sha1((string)time()), -18);
}

function pqcrgp_money(string $value, string $fallback = '25.00'): string {
    $clean = preg_replace('/[^0-9.\\-]+/', '', $value);
    if ($clean === '' || !is_numeric($clean)) {
        $clean = $fallback;
    }
    return number_format(max(0, (float)$clean), 2, '.', '');
}

function pqcrgp_insert_safe(string $table, array $record): int {
    global $DB;
    if (!pqcrgp_table_ready($table)) {
        return 0;
    }
    try {
        return (int)$DB->insert_record($table, pqcrgp_filter_record($table, $record));
    } catch (Throwable $e) {
        return 0;
    }
}

function pqcrgp_count_sql(string $sql, array $params = []): int {
    global $DB;
    try {
        return (int)$DB->count_records_sql($sql, $params);
    } catch (Throwable $e) {
        return 0;
    }
}

function pqcrgp_upsert_user(string $role, string $token, string $password = 'Mock@001!'): array {
    global $CFG, $DB;
    $username = 'crossrole.' . $role . '.' . $token;
    $email = $username . '@example.test';
    $existing = $DB->get_record('user', ['username' => $username, 'mnethostid' => $CFG->mnet_localhost_id], '*', IGNORE_MISSING);
    if ($existing) {
        $userid = (int)$existing->id;
        update_internal_user_password($existing, $password);
        $DB->update_record('user', (object)[
            'id' => $userid,
            'auth' => 'manual',
            'confirmed' => 1,
            'deleted' => 0,
            'suspended' => 0,
            'emailstop' => 1,
            'timemodified' => time(),
        ]);
    } else {
        $userid = (int)user_create_user((object)[
            'auth' => 'manual',
            'confirmed' => 1,
            'mnethostid' => $CFG->mnet_localhost_id,
            'username' => $username,
            'password' => $password,
            'firstname' => 'CrossRole',
            'lastname' => ucfirst($role) . ' ' . substr($token, -6),
            'email' => $email,
            'emailstop' => 1,
            'city' => 'SQA Cross Role City',
            'timezone' => 'Africa/Nairobi',
            'lang' => $CFG->lang ?? 'en',
            'description' => 'Generated by EduPlatform SQA full cross-role golden path.',
        ], true, false);
        pqh_assign_account_id($userid, $role === 'parent' ? 'parent' : $role);
    }
    return ['id' => $userid, 'username' => $username, 'email' => $email];
}

function pqcrgp_upsert_workspace_member(int $workspaceid, int $userid, string $role): void {
    global $DB, $USER;
    if (!pqcrgp_table_ready('local_prequran_workspace_member')) {
        return;
    }
    $existing = $DB->get_record('local_prequran_workspace_member', ['workspaceid' => $workspaceid, 'userid' => $userid], '*', IGNORE_MISSING);
    $record = [
        'workspaceid' => $workspaceid,
        'userid' => $userid,
        'role' => $role,
        'workspace_role' => $role,
        'status' => 'active',
        'notes' => 'SQA cross-role golden path fixture.',
        'createdby' => (int)$USER->id,
        'timecreated' => (int)($existing->timecreated ?? time()),
        'timemodified' => time(),
    ];
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record('local_prequran_workspace_member', pqcrgp_filter_record('local_prequran_workspace_member', $record));
    } else {
        $DB->insert_record('local_prequran_workspace_member', pqcrgp_filter_record('local_prequran_workspace_member', $record));
    }
}

function pqcrgp_live_audit(int $workspaceid, int $actorid, string $action, string $targettype, int $targetid, string $runid, array $details = []): int {
    return pqcrgp_insert_safe('local_prequran_live_audit', [
        'workspaceid' => $workspaceid,
        'sessionid' => (int)($details['sessionid'] ?? 0),
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => $targettype,
        'targetid' => $targetid,
        'details' => json_encode(['runid' => $runid] + $details, JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]);
}

function pqcrgp_course_audit(int $consumerid, int $workspaceid, int $actorid, string $action, string $targettype, int $targetid, string $runid, int $offeringid = 0, int $studentid = 0): int {
    return pqcrgp_insert_safe('local_prequran_course_audit', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'offeringid' => $offeringid,
        'requestid' => 0,
        'studentid' => $studentid,
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => $targettype,
        'targetid' => $targetid,
        'details' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]);
}

function pqcrgp_finance_audit(int $consumerid, int $workspaceid, int $actorid, int $studentid, int $invoiceid, string $runid, string $action): int {
    return pqcrgp_insert_safe('local_prequran_finance_audit', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'studentid' => $studentid,
        'billingaccountid' => 0,
        'invoiceid' => $invoiceid,
        'paymentid' => 0,
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => 'invoice',
        'targetid' => $invoiceid,
        'details' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]);
}

function pqcrgp_create_fixture(int $consumerid, int $workspaceid, string $runid, string $coursekey, string $invoiceamount, string $cleanupmode): array {
    global $USER;
    $token = pqcrgp_token($runid);
    $student = pqcrgp_upsert_user('student', $token);
    $parent = pqcrgp_upsert_user('parent', $token);
    $teacher = pqcrgp_upsert_user('teacher', $token);
    pqcrgp_upsert_workspace_member($workspaceid, (int)$student['id'], 'student');
    pqcrgp_upsert_workspace_member($workspaceid, (int)$parent['id'], 'parent');
    pqcrgp_upsert_workspace_member($workspaceid, (int)$teacher['id'], 'teacher');

    pqcrgp_insert_safe('local_prequran_comm_consent', [
        'workspaceid' => $workspaceid,
        'studentid' => (int)$student['id'],
        'guardianid' => (int)$parent['id'],
        'guardianemail' => (string)$parent['email'],
        'status' => 'consented',
        'consent_source' => 'sqa_cross_role',
        'details' => 'SQA cross-role parent link ' . $runid,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_live_consent', [
        'workspaceid' => $workspaceid,
        'studentid' => (int)$student['id'],
        'guardianid' => (int)$parent['id'],
        'guardianemail' => (string)$parent['email'],
        'status' => 'consented',
        'consent_source' => 'sqa_cross_role',
        'details' => 'SQA cross-role live consent ' . $runid,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_teacher_student', [
        'workspaceid' => $workspaceid,
        'teacherid' => (int)$teacher['id'],
        'studentid' => (int)$student['id'],
        'status' => 'active',
        'relationship_type' => 'primary',
        'notes' => 'SQA cross-role teacher assignment.',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    $offeringid = pqcrgp_insert_safe('local_prequran_course_offering', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'title' => 'SQA Cross Role Golden ' . $token,
        'course_key' => $coursekey,
        'moodlecourseid' => 0,
        'capacity' => 20,
        'status' => $cleanupmode === 'archive' ? 'archived' : 'published',
        'visibility' => 'institution_public',
        'tuition_amount' => pqcrgp_money($invoiceamount),
        'pricing_currency' => 'USD',
        'createdby' => (int)$USER->id,
        'modifiedby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    $invoiceamount = pqcrgp_money($invoiceamount);
    $invoiceid = pqcrgp_insert_safe('local_prequran_invoice', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'billingaccountid' => 0,
        'studentid' => (int)$student['id'],
        'invoicenumber' => 'SQA-XROLE-' . strtoupper(substr($token, -8)),
        'invoicetype' => 'tuition',
        'status' => 'paid',
        'currency' => 'USD',
        'subtotal' => $invoiceamount,
        'discounttotal' => '0.00',
        'taxtotal' => '0.00',
        'total' => $invoiceamount,
        'paidamount' => $invoiceamount,
        'creditedamount' => '0.00',
        'balancedue' => '0.00',
        'metadatajson' => json_encode(['runid' => $runid, 'cross_role' => true], JSON_UNESCAPED_SLASHES),
        'issuedat' => time(),
        'dueat' => time() + (14 * DAYSECS),
        'sentat' => time(),
        'createdby' => (int)$USER->id,
        'modifiedby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_invoice_line', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'invoiceid' => $invoiceid,
        'studentid' => (int)$student['id'],
        'description' => 'SQA cross-role golden path tuition',
        'quantity' => '1.00',
        'unitamount' => $invoiceamount,
        'linetotal' => $invoiceamount,
        'status' => 'active',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_payment', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'studentid' => (int)$student['id'],
        'invoiceid' => $invoiceid,
        'amount' => $invoiceamount,
        'currency' => 'USD',
        'paymentmethod' => 'manual',
        'status' => 'posted',
        'reference' => 'SQA-XROLE-' . $token,
        'receipt_number' => 'RCPT-XROLE-' . strtoupper(substr($token, -8)),
        'receiptnumber' => 'RCPT-XROLE-' . strtoupper(substr($token, -8)),
        'paidat' => time(),
        'createdby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    $sessionid = pqcrgp_insert_safe('local_prequran_live_session', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'teacherid' => (int)$teacher['id'],
        'course_key' => $coursekey,
        'title' => 'SQA Cross Role Session ' . $token,
        'status' => $cleanupmode === 'archive' ? 'archived' : 'scheduled',
        'scheduledstart' => time(),
        'scheduledend' => time() + HOURSECS,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_live_attendance', [
        'workspaceid' => $workspaceid,
        'sessionid' => $sessionid,
        'studentid' => (int)$student['id'],
        'teacherid' => (int)$teacher['id'],
        'status' => 'present',
        'attendance_status' => 'present',
        'notes' => 'SQA cross-role attendance.',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    $assessmentid = pqcrgp_insert_safe('local_prequran_assessment', [
        'workspaceid' => $workspaceid,
        'offeringid' => $offeringid,
        'teacherid' => (int)$teacher['id'],
        'title' => 'SQA Cross Role Assessment ' . $token,
        'assessment_type' => 'assignment',
        'maxpoints' => '100.00',
        'status' => 'published',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_grade', [
        'workspaceid' => $workspaceid,
        'assessmentid' => $assessmentid,
        'studentid' => (int)$student['id'],
        'teacherid' => (int)$teacher['id'],
        'scorepoints' => '96.00',
        'scorepercent' => '96.00',
        'lettergrade' => 'A',
        'status' => 'published',
        'feedback' => 'SQA cross-role academic evidence.',
        'publishedat' => time(),
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_student_path', [
        'workspaceid' => $workspaceid,
        'studentid' => (int)$student['id'],
        'teacherid' => (int)$teacher['id'],
        'course_key' => $coursekey,
        'advancement_status' => 'on_track',
        'teacher_comment' => 'SQA cross-role progress evidence.',
        'status' => 'active',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    $threadid = pqcrgp_insert_safe('local_prequran_comm_thread', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'studentid' => (int)$student['id'],
        'subject' => 'SQA Cross Role Message ' . $token,
        'status' => 'open',
        'createdby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_comm_message', [
        'threadid' => $threadid,
        'workspaceid' => $workspaceid,
        'senderid' => (int)$teacher['id'],
        'recipientid' => (int)$parent['id'],
        'body' => 'SQA cross-role parent teacher message ' . $runid,
        'status' => 'sent',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqcrgp_insert_safe('local_prequran_support_case', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'studentid' => (int)$student['id'],
        'openedby' => (int)$parent['id'],
        'title' => 'SQA Cross Role Support ' . $token,
        'status' => 'open',
        'priority' => 'normal',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    pqcrgp_live_audit($workspaceid, (int)$USER->id, 'sqa_cross_role_admin_verified', 'run', 0, $runid);
    pqcrgp_live_audit($workspaceid, (int)$teacher['id'], 'sqa_cross_role_teacher_attendance', 'live_session', $sessionid, $runid, ['studentid' => (int)$student['id'], 'sessionid' => $sessionid]);
    pqcrgp_live_audit($workspaceid, (int)$parent['id'], 'sqa_cross_role_parent_visibility', 'student', (int)$student['id'], $runid);
    pqcrgp_course_audit($consumerid, $workspaceid, (int)$USER->id, 'sqa_cross_role_course_progress', 'assessment', $assessmentid, $runid, $offeringid, (int)$student['id']);
    pqcrgp_course_audit($consumerid, $workspaceid, (int)$USER->id, 'sqa_cross_role_security_boundary', 'run', 0, $runid, $offeringid, (int)$student['id']);
    pqcrgp_finance_audit($consumerid, $workspaceid, (int)$USER->id, (int)$student['id'], $invoiceid, $runid, 'sqa_cross_role_invoice_paid');

    return [
        'student' => $student,
        'parent' => $parent,
        'teacher' => $teacher,
        'invoiceid' => $invoiceid,
        'offeringid' => $offeringid,
        'sessionid' => $sessionid,
        'assessmentid' => $assessmentid,
        'threadid' => $threadid,
    ];
}

function pqcrgp_checkpoints(int $workspaceid, string $runid, array $fixture): array {
    $studentid = (int)$fixture['student']['id'];
    $parentid = (int)$fixture['parent']['id'];
    $teacherid = (int)$fixture['teacher']['id'];
    $invoiceid = (int)$fixture['invoiceid'];
    $sessionid = (int)$fixture['sessionid'];
    $assessmentid = (int)$fixture['assessmentid'];
    $threadid = (int)$fixture['threadid'];
    $offeringid = (int)$fixture['offeringid'];

    $workspaceMembers = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_workspace_member} WHERE workspaceid = :workspaceid AND userid IN (:studentid, :parentid, :teacherid)", ['workspaceid' => $workspaceid, 'studentid' => $studentid, 'parentid' => $parentid, 'teacherid' => $teacherid]);
    $parentLinks = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_comm_consent} WHERE studentid = :studentid AND guardianid = :parentid", ['studentid' => $studentid, 'parentid' => $parentid]) + pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_live_consent} WHERE studentid = :studentid AND guardianid = :parentid", ['studentid' => $studentid, 'parentid' => $parentid]);
    $teacherEvidence = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_teacher_student} WHERE workspaceid = :workspaceid AND teacherid = :teacherid AND studentid = :studentid", ['workspaceid' => $workspaceid, 'teacherid' => $teacherid, 'studentid' => $studentid]) + pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_live_attendance} WHERE sessionid = :sessionid AND studentid = :studentid", ['sessionid' => $sessionid, 'studentid' => $studentid]);
    $financeEvidence = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_invoice} WHERE id = :invoiceid AND workspaceid = :workspaceid AND status = :status AND balancedue = :balance", ['invoiceid' => $invoiceid, 'workspaceid' => $workspaceid, 'status' => 'paid', 'balance' => '0.00']);
    $academicEvidence = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_grade} WHERE assessmentid = :assessmentid AND studentid = :studentid AND status = :status", ['assessmentid' => $assessmentid, 'studentid' => $studentid, 'status' => 'published']);
    $supportEvidence = ($threadid > 0 ? 1 : 0) + pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_comm_message} WHERE threadid = :threadid", ['threadid' => $threadid]);
    $liveAudit = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_live_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']);
    $courseAudit = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_course_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']);
    $financeAudit = pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_finance_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']);

    return [
        ['category' => 'admin operations readiness', 'status' => $workspaceMembers >= 3 ? 'PASS' : 'CHECK', 'evidence' => 'workspace_members=' . $workspaceMembers],
        ['category' => 'student journey evidence', 'status' => $studentid > 0 && $offeringid > 0 ? 'PASS' : 'CHECK', 'evidence' => 'student=' . $studentid . '; offering=' . $offeringid],
        ['category' => 'parent visibility evidence', 'status' => $parentLinks > 0 ? 'PASS' : 'CHECK', 'evidence' => 'parent_links=' . $parentLinks],
        ['category' => 'teacher classroom evidence', 'status' => $teacherEvidence > 0 ? 'PASS' : 'CHECK', 'evidence' => 'teacher_classroom_rows=' . $teacherEvidence],
        ['category' => 'finance receipt evidence', 'status' => $financeEvidence > 0 && $financeAudit > 0 ? 'PASS' : 'CHECK', 'evidence' => 'paid_invoice=' . $financeEvidence . '; finance_audit=' . $financeAudit],
        ['category' => 'academic progress evidence', 'status' => $academicEvidence > 0 && $courseAudit > 0 ? 'PASS' : 'CHECK', 'evidence' => 'grade=' . $academicEvidence . '; course_audit=' . $courseAudit],
        ['category' => 'support communications evidence', 'status' => $supportEvidence > 0 ? 'PASS' : 'CHECK', 'evidence' => 'thread_messages=' . $supportEvidence],
        ['category' => 'security boundary evidence', 'status' => $courseAudit > 0 ? 'PASS' : 'CHECK', 'evidence' => 'security boundary audit retained in course audit.'],
        ['category' => 'compliance export readiness', 'status' => ($studentid > 0 && $parentid > 0 && $teacherid > 0 && ($liveAudit + $courseAudit + $financeAudit) > 0) ? 'PASS' : 'CHECK', 'evidence' => 'student/parent/teacher ids ready; live=' . $liveAudit . '; course=' . $courseAudit . '; finance=' . $financeAudit],
        ['category' => 'audit and cleanup readiness', 'status' => ($liveAudit + $courseAudit + $financeAudit) > 0 ? 'PASS' : 'CHECK', 'evidence' => 'live=' . $liveAudit . '; course=' . $courseAudit . '; finance=' . $financeAudit],
    ];
}

function pqcrgp_create_verify(int $consumerid, int $workspaceid, string $runid, string $coursekey, string $invoiceamount, string $cleanupmode): array {
    $fixture = pqcrgp_create_fixture($consumerid, $workspaceid, $runid, $coursekey, $invoiceamount, $cleanupmode);
    $checkpoints = pqcrgp_checkpoints($workspaceid, $runid, $fixture);
    return [
        'runid' => $runid,
        'fixture' => $fixture,
        'checkpoints' => $checkpoints,
        'audit' => [
            'live' => pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_live_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']),
            'course' => pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_course_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']),
            'finance' => pqcrgp_count_sql("SELECT COUNT(1) FROM {local_prequran_finance_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']),
        ],
    ];
}

if ($action === 'create_verify') {
    try {
        if ($runid === '') {
            throw new invalid_parameter_exception('runid is required.');
        }
        $result = pqcrgp_create_verify($consumerid, $workspaceid, $runid, $coursekey, $invoiceamount, $cleanupmode);
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

$workspace = pqcrgp_table_ready('local_prequran_workspace') ? $DB->get_record('local_prequran_workspace', ['id' => $workspaceid], '*', IGNORE_MISSING) : null;
$urlparams = [];
if (!empty($consumercontext->consumerslug)) {
    $urlparams['consumer'] = (string)$consumercontext->consumerslug;
}
if ($workspaceid > 0) {
    $urlparams['workspaceid'] = $workspaceid;
}

$PAGE->set_url(new moodle_url('/local/hubredirect/cross_role_golden_path.php', $urlparams));
$PAGE->set_context(context_system::instance());
$PAGE->set_title('Full Cross-Role Golden Path');
$PAGE->set_heading('Full Cross-Role Golden Path');
echo $OUTPUT->header();
?>
<style>
.pqcrgp{max-width:1180px;margin:0 auto;padding:24px;color:#143044;font-family:system-ui,-apple-system,Segoe UI,Arial,sans-serif}.pqcrgp-top{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.pqcrgp h2{margin:0 0 6px;font-size:28px}.pqcrgp-muted{color:#617286;font-size:14px}.pqcrgp-btn{display:inline-flex;align-items:center;justify-content:center;border:1px solid #236454;background:#236454;color:#fff;border-radius:8px;padding:10px 14px;text-decoration:none;font-weight:700}.pqcrgp-btn--light{background:#fff;color:#236454}.pqcrgp-alert{border-radius:8px;padding:12px 14px;margin:12px 0}.pqcrgp-error{background:#fee2e2;color:#991b1b;border:1px solid #fecaca}.pqcrgp-panel{background:#fff;border:1px solid #d9e2ea;border-radius:8px;padding:16px;box-shadow:0 8px 24px rgba(15,23,42,.06)}.pqcrgp-table{width:100%;border-collapse:collapse}.pqcrgp-table th,.pqcrgp-table td{border-bottom:1px solid #e6edf3;padding:10px;text-align:left;vertical-align:top}.pqcrgp-pill{display:inline-flex;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:800;background:#e7f8ee;color:#166534}.pqcrgp-pill--check{background:#fef3c7;color:#92400e}.pqcrgp-code{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;border-radius:8px;padding:12px;overflow:auto;font-size:12px}
</style>
<div class="pqcrgp">
  <div class="pqcrgp-top">
    <div>
      <h2>Full Cross-Role Golden Path</h2>
      <div class="pqcrgp-muted"><?php echo s((string)($workspace->name ?? 'Workspace #' . $workspaceid)); ?> cross-role SQA verification for admin, student, parent, teacher, finance, academic, support, security, compliance, and cleanup evidence.</div>
    </div>
    <div><a class="pqcrgp-btn pqcrgp-btn--light" href="<?php echo (new moodle_url('/local/hubredirect/workspace_dashboard.php', $urlparams))->out(false); ?>">Workspace</a></div>
  </div>
  <?php if ($error !== ''): ?>
    <div class="pqcrgp-alert pqcrgp-error"><?php echo s($error); ?></div>
  <?php endif; ?>
  <section class="pqcrgp-panel">
    <table class="pqcrgp-table">
      <thead><tr><th>Checkpoint</th><th>Status</th><th>Evidence</th></tr></thead>
      <tbody>
      <?php foreach (($result['checkpoints'] ?? []) as $row): ?>
        <tr>
          <td><?php echo s((string)$row['category']); ?></td>
          <td><span class="pqcrgp-pill <?php echo (string)$row['status'] === 'PASS' ? '' : 'pqcrgp-pill--check'; ?>"><?php echo s((string)$row['status']); ?></span></td>
          <td><?php echo s((string)$row['evidence']); ?></td>
        </tr>
      <?php endforeach; ?>
      <?php if (!$result && $error === ''): ?>
        <tr><td colspan="3"><span class="pqcrgp-muted">Run with action=create_verify and a runid to generate cross-role evidence.</span></td></tr>
      <?php endif; ?>
      </tbody>
    </table>
  </section>
  <h3>Result JSON</h3>
  <pre id="pqcrgp-result" class="pqcrgp-code"><?php echo s(json_encode($result ?: new stdClass(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)); ?></pre>
</div>
<?php
echo $OUTPUT->footer();
