<?php
declare(strict_types=1);

require_once(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/user/lib.php');
require_once(__DIR__ . '/accesslib.php');
require_once(__DIR__ . '/account_ids.php');
require_login();

pqh_require_academy_operations(
    'Only academy operations users can run SQA data lifecycle cleanup verification.',
    new moodle_url('/local/hubredirect/workspace_dashboard.php'),
    'Data lifecycle cleanup access required'
);

$workspaceid = pqh_current_workspace_id((int)$USER->id, optional_param('workspaceid', 0, PARAM_INT));
$consumercontext = pqh_requested_consumer_context();
$consumerid = (int)($consumercontext->consumerid ?? 0);
$runid = trim(optional_param('runid', '', PARAM_TEXT));
$cleanupmode = optional_param('cleanupmode', 'archive', PARAM_ALPHANUMEXT);
$coursekey = trim(optional_param('coursekey', 'pre_quraan', PARAM_ALPHANUMEXT));
$password = optional_param('password', 'Mock@001!', PARAM_RAW);
$action = optional_param('action', 'create_archive_verify', PARAM_ALPHANUMEXT);
$result = null;
$error = '';

if ($workspaceid <= 0) {
    pqh_access_denied('Data lifecycle cleanup requires a workspace context.', new moodle_url('/local/hubredirect/workspace_dashboard.php'), 'Workspace required');
}

function pqdlc_table_ready(string $table): bool {
    global $DB;
    try {
        return $DB->get_manager()->table_exists($table);
    } catch (Throwable $e) {
        return false;
    }
}

function pqdlc_has_field(string $table, string $field): bool {
    global $DB;
    try {
        return $DB->get_manager()->field_exists($table, $field);
    } catch (Throwable $e) {
        return false;
    }
}

function pqdlc_filter_record(string $table, array $record): stdClass {
    $filtered = [];
    foreach ($record as $field => $value) {
        if ($field === 'id' || pqdlc_has_field($table, $field)) {
            $filtered[$field] = $value;
        }
    }
    return (object)$filtered;
}

function pqdlc_token(string $runid): string {
    $token = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '', $runid));
    return substr($token !== '' ? $token : sha1((string)time()), -18);
}

function pqdlc_count_sql(string $sql, array $params = []): int {
    global $DB;
    try {
        return (int)$DB->count_records_sql($sql, $params);
    } catch (Throwable $e) {
        return 0;
    }
}

function pqdlc_upsert_user(string $role, string $token, string $password): array {
    global $CFG, $DB;
    $username = 'lifecycle.' . $role . '.' . $token;
    $email = $username . '@example.test';
    $existing = $DB->get_record('user', [
        'username' => $username,
        'mnethostid' => $CFG->mnet_localhost_id,
    ], '*', IGNORE_MISSING);
    if ($existing) {
        $userid = (int)$existing->id;
        update_internal_user_password($existing, $password);
        $DB->update_record('user', (object)[
            'id' => $userid,
            'auth' => 'manual',
            'confirmed' => 1,
            'deleted' => 0,
            'suspended' => 0,
            'emailstop' => 1,
            'timemodified' => time(),
        ]);
    } else {
        $userid = (int)user_create_user((object)[
            'auth' => 'manual',
            'confirmed' => 1,
            'mnethostid' => $CFG->mnet_localhost_id,
            'username' => $username,
            'password' => $password,
            'firstname' => 'Lifecycle',
            'lastname' => ucfirst($role) . ' ' . substr($token, -6),
            'email' => $email,
            'emailstop' => 1,
            'city' => 'SQA Lifecycle City',
            'timezone' => 'Africa/Nairobi',
            'lang' => $CFG->lang ?? 'en',
            'description' => 'Generated by EduPlatform SQA data lifecycle cleanup fixture.',
        ], true, false);
        pqh_assign_account_id($userid, $role === 'parent' ? 'parent' : $role);
    }
    return ['id' => $userid, 'username' => $username, 'email' => $email];
}

function pqdlc_upsert_workspace_member(int $workspaceid, int $userid, string $role): int {
    global $DB, $USER;
    if (!pqdlc_table_ready('local_prequran_workspace_member')) {
        return 0;
    }
    $existing = $DB->get_record('local_prequran_workspace_member', ['workspaceid' => $workspaceid, 'userid' => $userid], '*', IGNORE_MISSING);
    $record = [
        'workspaceid' => $workspaceid,
        'userid' => $userid,
        'role' => $role,
        'workspace_role' => $role,
        'status' => 'active',
        'notes' => 'SQA lifecycle fixture active before archive.',
        'createdby' => (int)$USER->id,
        'timecreated' => (int)($existing->timecreated ?? time()),
        'timemodified' => time(),
    ];
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record('local_prequran_workspace_member', pqdlc_filter_record('local_prequran_workspace_member', $record));
        return (int)$existing->id;
    }
    return (int)$DB->insert_record('local_prequran_workspace_member', pqdlc_filter_record('local_prequran_workspace_member', $record));
}

function pqdlc_upsert_simple(string $table, array $conditions, array $record): int {
    global $DB;
    if (!pqdlc_table_ready($table)) {
        return 0;
    }
    $existing = $DB->get_record($table, $conditions, '*', IGNORE_MISSING);
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record($table, pqdlc_filter_record($table, $record));
        return (int)$existing->id;
    }
    return (int)$DB->insert_record($table, pqdlc_filter_record($table, $record));
}

function pqdlc_write_live_audit(int $workspaceid, int $actorid, string $action, string $targettype, int $targetid, string $runid, array $details = []): int {
    global $DB;
    if (!pqdlc_table_ready('local_prequran_live_audit')) {
        return 0;
    }
    return (int)$DB->insert_record('local_prequran_live_audit', pqdlc_filter_record('local_prequran_live_audit', [
        'workspaceid' => $workspaceid,
        'sessionid' => 0,
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => $targettype,
        'targetid' => $targetid,
        'details' => json_encode(['runid' => $runid] + $details, JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]));
}

function pqdlc_write_course_audit(int $consumerid, int $workspaceid, int $actorid, string $action, string $targettype, int $targetid, string $runid, int $offeringid = 0, int $studentid = 0): int {
    global $DB;
    if (!pqdlc_table_ready('local_prequran_course_audit')) {
        return 0;
    }
    return (int)$DB->insert_record('local_prequran_course_audit', pqdlc_filter_record('local_prequran_course_audit', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'offeringid' => $offeringid,
        'requestid' => 0,
        'studentid' => $studentid,
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => $targettype,
        'targetid' => $targetid,
        'details' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]));
}

function pqdlc_write_finance_audit(int $consumerid, int $workspaceid, int $actorid, int $studentid, int $invoiceid, string $runid): int {
    global $DB;
    if (!pqdlc_table_ready('local_prequran_finance_audit')) {
        return 0;
    }
    return (int)$DB->insert_record('local_prequran_finance_audit', pqdlc_filter_record('local_prequran_finance_audit', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'studentid' => $studentid,
        'billingaccountid' => 0,
        'invoiceid' => $invoiceid,
        'paymentid' => 0,
        'actorid' => $actorid,
        'action' => 'sqa_lifecycle_invoice_archived',
        'targettype' => 'invoice',
        'targetid' => $invoiceid,
        'details' => json_encode(['runid' => $runid, 'retained' => true], JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]));
}

function pqdlc_create_fixture(int $workspaceid, int $consumerid, string $runid, string $coursekey, string $password): array {
    global $USER;
    $token = pqdlc_token($runid);
    $student = pqdlc_upsert_user('student', $token, $password);
    $teacher = pqdlc_upsert_user('teacher', $token, $password);
    $parent = pqdlc_upsert_user('parent', $token, $password);
    foreach ([[$student['id'], 'student'], [$teacher['id'], 'teacher'], [$parent['id'], 'parent']] as $member) {
        pqdlc_upsert_workspace_member($workspaceid, (int)$member[0], (string)$member[1]);
    }

    pqdlc_upsert_simple('local_prequran_student_profile', ['userid' => $student['id']], [
        'userid' => $student['id'],
        'workspaceid' => $workspaceid,
        'displayname' => 'Lifecycle Student ' . substr($token, -6),
        'student_display_name' => 'Lifecycle Student ' . substr($token, -6),
        'status' => 'active',
        'current_level' => 'Pre-quraan Course',
        'course_type' => $coursekey,
        'createdby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqdlc_upsert_simple('local_prequran_teacher_profile', ['userid' => $teacher['id']], [
        'userid' => $teacher['id'],
        'workspaceid' => $workspaceid,
        'displayname' => 'Lifecycle Teacher ' . substr($token, -6),
        'teacher_display_name' => 'Lifecycle Teacher ' . substr($token, -6),
        'status' => 'active',
        'marketplace_status' => 'published',
        'marketplace_visible' => 1,
        'createdby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqdlc_upsert_simple('local_prequran_comm_consent', ['studentid' => $student['id'], 'guardianid' => $parent['id']], [
        'studentid' => $student['id'],
        'guardianid' => $parent['id'],
        'workspaceid' => $workspaceid,
        'student_messaging_enabled' => 1,
        'free_text_enabled' => 0,
        'parent_visible' => 1,
        'consent_source' => 'sqa_lifecycle',
        'details' => 'SQA lifecycle parent link ' . $runid,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    $offeringid = pqdlc_upsert_simple('local_prequran_course_offering', ['workspaceid' => $workspaceid, 'title' => 'SQA Lifecycle Offering ' . $token], [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'moodlecourseid' => 0,
        'course_key' => $coursekey,
        'title' => 'SQA Lifecycle Offering ' . $token,
        'summary' => 'Generated by SQA lifecycle cleanup verification.',
        'syllabus' => '',
        'prerequisites' => '',
        'startdate' => time(),
        'enddate' => time() + WEEKSECS,
        'capacity' => 5,
        'tuition_amount' => '25.00',
        'pricing_currency' => 'USD',
        'registration_fee' => '0.00',
        'materials_fee' => '0.00',
        'visibility' => 'workspace',
        'approval_mode' => 'admin_approval',
        'status' => 'published',
        'createdby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    $materialid = pqdlc_upsert_simple('local_prequran_workspace_material', ['workspaceid' => $workspaceid, 'title' => 'SQA Lifecycle Material ' . $token], [
        'workspaceid' => $workspaceid,
        'title' => 'SQA Lifecycle Material ' . $token,
        'material_type' => 'link',
        'course_key' => $coursekey,
        'description' => 'Generated by SQA lifecycle cleanup verification.',
        'source_url' => 'https://quraantest.academy/',
        'metadatajson' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'visibility' => 'students',
        'status' => 'active',
        'createdby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    $assignmentid = pqdlc_upsert_simple('local_prequran_workspace_mat_assign', ['workspaceid' => $workspaceid, 'materialid' => $materialid, 'target_type' => 'student', 'targetid' => $student['id']], [
        'workspaceid' => $workspaceid,
        'materialid' => $materialid,
        'target_type' => 'student',
        'targetid' => $student['id'],
        'status' => 'active',
        'workflow_status' => 'assigned',
        'assignedby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    $invoiceid = pqdlc_upsert_simple('local_prequran_invoice', ['workspaceid' => $workspaceid, 'invoicenumber' => 'SQA-LC-' . strtoupper($token)], [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'billingaccountid' => 0,
        'studentid' => $student['id'],
        'invoicenumber' => 'SQA-LC-' . strtoupper($token),
        'invoicetype' => 'tuition',
        'status' => 'issued',
        'currency' => 'USD',
        'subtotal' => '25.00',
        'discounttotal' => '0.00',
        'taxtotal' => '0.00',
        'total' => '25.00',
        'paidamount' => '0.00',
        'creditedamount' => '0.00',
        'balancedue' => '25.00',
        'policyversion' => 1,
        'policyhash' => sha1($runid),
        'metadatajson' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'issuedat' => time(),
        'dueat' => time() + WEEKSECS,
        'sentat' => time(),
        'createdby' => (int)$USER->id,
        'modifiedby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqdlc_upsert_simple('local_prequran_invoice_line', ['invoiceid' => $invoiceid, 'linesequence' => 1], [
        'invoiceid' => $invoiceid,
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'linesequence' => 1,
        'description' => 'SQA lifecycle invoice line ' . $runid,
        'quantity' => '1',
        'unitamount' => '25.00',
        'discountamount' => '0.00',
        'taxamount' => '0.00',
        'linetotal' => '25.00',
        'offeringid' => $offeringid,
        'status' => 'active',
        'metadatajson' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'createdby' => (int)$USER->id,
        'modifiedby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);

    pqdlc_write_live_audit($workspaceid, (int)$USER->id, 'sqa_lifecycle_fixture_created', 'run', 0, $runid);
    return [
        'token' => $token,
        'student' => $student,
        'teacher' => $teacher,
        'parent' => $parent,
        'offeringid' => $offeringid,
        'materialid' => $materialid,
        'assignmentid' => $assignmentid,
        'invoiceid' => $invoiceid,
    ];
}

function pqdlc_archive_fixture(int $workspaceid, int $consumerid, string $runid, array $fixture): array {
    global $DB, $USER;
    $counts = [
        'users_suspended' => 0,
        'workspace_members_archived' => 0,
        'student_profiles_archived' => 0,
        'teacher_profiles_archived' => 0,
        'parent_links_archived' => 0,
        'invoices_archived' => 0,
        'course_offerings_archived' => 0,
        'materials_archived' => 0,
        'assignments_archived' => 0,
        'audit_rows_retained' => 0,
    ];
    foreach (['student', 'teacher', 'parent'] as $role) {
        $userid = (int)$fixture[$role]['id'];
        if ($userid > 0) {
            $DB->update_record('user', (object)['id' => $userid, 'suspended' => 1, 'timemodified' => time()]);
            $counts['users_suspended']++;
            if (pqdlc_table_ready('local_prequran_workspace_member')) {
                $DB->set_field('local_prequran_workspace_member', 'status', 'archived', ['workspaceid' => $workspaceid, 'userid' => $userid]);
                $counts['workspace_members_archived']++;
            }
        }
    }
    if (pqdlc_table_ready('local_prequran_student_profile')) {
        $DB->set_field('local_prequran_student_profile', 'status', 'archived', ['userid' => (int)$fixture['student']['id']]);
        $counts['student_profiles_archived']++;
    }
    if (pqdlc_table_ready('local_prequran_teacher_profile')) {
        $DB->set_field('local_prequran_teacher_profile', 'status', 'inactive', ['userid' => (int)$fixture['teacher']['id']]);
        $counts['teacher_profiles_archived']++;
    }
    if (pqdlc_table_ready('local_prequran_comm_consent')) {
        $DB->set_field('local_prequran_comm_consent', 'parent_visible', 0, ['studentid' => (int)$fixture['student']['id'], 'guardianid' => (int)$fixture['parent']['id']]);
        $counts['parent_links_archived']++;
    }
    if (pqdlc_table_ready('local_prequran_invoice')) {
        $DB->update_record('local_prequran_invoice', pqdlc_filter_record('local_prequran_invoice', ['id' => (int)$fixture['invoiceid'], 'status' => 'archived', 'modifiedby' => (int)$USER->id, 'timemodified' => time()]));
        $counts['invoices_archived']++;
        if (pqdlc_table_ready('local_prequran_invoice_line')) {
            $DB->set_field('local_prequran_invoice_line', 'status', 'archived', ['invoiceid' => (int)$fixture['invoiceid']]);
        }
        $counts['audit_rows_retained'] += pqdlc_write_finance_audit($consumerid, $workspaceid, (int)$USER->id, (int)$fixture['student']['id'], (int)$fixture['invoiceid'], $runid) > 0 ? 1 : 0;
    }
    if (pqdlc_table_ready('local_prequran_course_offering')) {
        $DB->update_record('local_prequran_course_offering', pqdlc_filter_record('local_prequran_course_offering', ['id' => (int)$fixture['offeringid'], 'status' => 'archived', 'timemodified' => time()]));
        $counts['course_offerings_archived']++;
        $counts['audit_rows_retained'] += pqdlc_write_course_audit($consumerid, $workspaceid, (int)$USER->id, 'sqa_lifecycle_offering_archived', 'course_offering', (int)$fixture['offeringid'], $runid, (int)$fixture['offeringid'], (int)$fixture['student']['id']) > 0 ? 1 : 0;
    }
    if (pqdlc_table_ready('local_prequran_workspace_material')) {
        $DB->update_record('local_prequran_workspace_material', pqdlc_filter_record('local_prequran_workspace_material', ['id' => (int)$fixture['materialid'], 'status' => 'archived', 'timemodified' => time()]));
        $counts['materials_archived']++;
        $counts['audit_rows_retained'] += pqdlc_write_live_audit($workspaceid, (int)$USER->id, 'sqa_lifecycle_material_archived', 'workspace_material', (int)$fixture['materialid'], $runid) > 0 ? 1 : 0;
    }
    if (pqdlc_table_ready('local_prequran_workspace_mat_assign')) {
        $DB->update_record('local_prequran_workspace_mat_assign', pqdlc_filter_record('local_prequran_workspace_mat_assign', ['id' => (int)$fixture['assignmentid'], 'status' => 'inactive', 'timemodified' => time()]));
        $counts['assignments_archived']++;
    }
    $counts['audit_rows_retained'] += pqdlc_write_live_audit($workspaceid, (int)$USER->id, 'sqa_lifecycle_fixture_archived', 'run', 0, $runid, ['counts' => $counts]) > 0 ? 1 : 0;
    return $counts;
}

function pqdlc_active_counts(int $workspaceid, array $fixture): array {
    $studentid = (int)$fixture['student']['id'];
    $teacherid = (int)$fixture['teacher']['id'];
    $parentid = (int)$fixture['parent']['id'];
    return [
        'active_users' => pqdlc_count_sql("SELECT COUNT(1) FROM {user} WHERE id IN (:studentid, :teacherid, :parentid) AND deleted = 0 AND suspended = 0", ['studentid' => $studentid, 'teacherid' => $teacherid, 'parentid' => $parentid]),
        'active_workspace_members' => pqdlc_table_ready('local_prequran_workspace_member') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_workspace_member} WHERE workspaceid = :workspaceid AND userid IN (:studentid, :teacherid, :parentid) AND status <> :archived", ['workspaceid' => $workspaceid, 'studentid' => $studentid, 'teacherid' => $teacherid, 'parentid' => $parentid, 'archived' => 'archived']) : 0,
        'active_invoice_rows' => pqdlc_table_ready('local_prequran_invoice') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_invoice} WHERE id = :invoiceid AND status NOT IN ('archived', 'void', 'voided', 'cancelled')", ['invoiceid' => (int)$fixture['invoiceid']]) : 0,
        'active_course_offerings' => pqdlc_table_ready('local_prequran_course_offering') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_course_offering} WHERE id = :offeringid AND status <> :archived", ['offeringid' => (int)$fixture['offeringid'], 'archived' => 'archived']) : 0,
        'active_materials' => pqdlc_table_ready('local_prequran_workspace_material') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_workspace_material} WHERE id = :materialid AND status = :active", ['materialid' => (int)$fixture['materialid'], 'active' => 'active']) : 0,
        'active_assignments' => pqdlc_table_ready('local_prequran_workspace_mat_assign') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_workspace_mat_assign} WHERE id = :assignmentid AND status = :active", ['assignmentid' => (int)$fixture['assignmentid'], 'active' => 'active']) : 0,
        'parent_visible_links' => pqdlc_table_ready('local_prequran_comm_consent') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_comm_consent} WHERE studentid = :studentid AND guardianid = :parentid AND parent_visible = 1", ['studentid' => $studentid, 'parentid' => $parentid]) : 0,
    ];
}

function pqdlc_archive_counts(int $workspaceid, string $runid, array $fixture): array {
    $studentid = (int)$fixture['student']['id'];
    $teacherid = (int)$fixture['teacher']['id'];
    $parentid = (int)$fixture['parent']['id'];
    $needle = '%' . $runid . '%';
    return [
        'archived_users' => pqdlc_count_sql("SELECT COUNT(1) FROM {user} WHERE id IN (:studentid, :teacherid, :parentid) AND deleted = 0 AND suspended = 1", ['studentid' => $studentid, 'teacherid' => $teacherid, 'parentid' => $parentid]),
        'archived_workspace_members' => pqdlc_table_ready('local_prequran_workspace_member') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_workspace_member} WHERE workspaceid = :workspaceid AND userid IN (:studentid, :teacherid, :parentid) AND status = :archived", ['workspaceid' => $workspaceid, 'studentid' => $studentid, 'teacherid' => $teacherid, 'parentid' => $parentid, 'archived' => 'archived']) : 0,
        'retained_finance_audit' => pqdlc_table_ready('local_prequran_finance_audit') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_finance_audit} WHERE invoiceid = :invoiceid AND " . $GLOBALS['DB']->sql_like('details', ':needle', false), ['invoiceid' => (int)$fixture['invoiceid'], 'needle' => $needle]) : 0,
        'retained_course_audit' => pqdlc_table_ready('local_prequran_course_audit') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_course_audit} WHERE offeringid = :offeringid AND " . $GLOBALS['DB']->sql_like('details', ':needle', false), ['offeringid' => (int)$fixture['offeringid'], 'needle' => $needle]) : 0,
        'retained_live_audit' => pqdlc_table_ready('local_prequran_live_audit') ? pqdlc_count_sql("SELECT COUNT(1) FROM {local_prequran_live_audit} WHERE " . $GLOBALS['DB']->sql_like('details', ':needle', false), ['needle' => $needle]) : 0,
    ];
}

function pqdlc_rows(array $active, array $archived, array $counts, string $cleanupmode): array {
    $activeafter = array_sum($active);
    $auditretained = (int)$archived['retained_finance_audit'] + (int)$archived['retained_course_audit'] + (int)$archived['retained_live_audit'];
    return [
        ['category' => 'generated people lifecycle', 'status' => ((int)$active['active_users'] === 0 && (int)$archived['archived_users'] >= 3) ? 'PASS' : 'CHECK', 'evidence' => 'active_users=' . $active['active_users'] . '; archived_users=' . $archived['archived_users']],
        ['category' => 'invoice lifecycle', 'status' => ((int)$active['active_invoice_rows'] === 0 && (int)$counts['invoices_archived'] > 0) ? 'PASS' : 'CHECK', 'evidence' => 'active_invoice_rows=' . $active['active_invoice_rows'] . '; invoices_archived=' . $counts['invoices_archived']],
        ['category' => 'course offering lifecycle', 'status' => ((int)$active['active_course_offerings'] === 0 && (int)$counts['course_offerings_archived'] > 0) ? 'PASS' : 'CHECK', 'evidence' => 'active_course_offerings=' . $active['active_course_offerings'] . '; offerings_archived=' . $counts['course_offerings_archived']],
        ['category' => 'materials lifecycle', 'status' => ((int)$active['active_materials'] === 0 && (int)$active['active_assignments'] === 0 && (int)$counts['materials_archived'] > 0) ? 'PASS' : 'CHECK', 'evidence' => 'active_materials=' . $active['active_materials'] . '; active_assignments=' . $active['active_assignments'] . '; materials_archived=' . $counts['materials_archived']],
        ['category' => 'active queues hidden', 'status' => $activeafter === 0 ? 'PASS' : 'CHECK', 'evidence' => 'active_queue_total=' . $activeafter . '; parent_visible_links=' . $active['parent_visible_links']],
        ['category' => 'audit reporting retained', 'status' => $auditretained > 0 ? 'PASS' : 'CHECK', 'evidence' => 'finance_audit=' . $archived['retained_finance_audit'] . '; course_audit=' . $archived['retained_course_audit'] . '; live_audit=' . $archived['retained_live_audit']],
        ['category' => 'delete policy', 'status' => $cleanupmode === 'delete' ? 'BLOCKED' : 'PASS', 'evidence' => $cleanupmode === 'delete' ? 'delete blocked for audit-retained SQA lifecycle records' : 'archive mode completed'],
    ];
}

if ($runid === '') {
    $runid = 'data-lifecycle-' . date('ymdHis') . '-' . substr(sha1((string)microtime(true)), 0, 6);
}

try {
    if ($action === 'create_archive_verify') {
        if ($cleanupmode === 'delete') {
            throw new moodle_exception('Delete cleanup is blocked for audit-retained lifecycle records. Use archive mode.');
        }
        $fixture = pqdlc_create_fixture($workspaceid, $consumerid, $runid, $coursekey, $password);
        $before = pqdlc_active_counts($workspaceid, $fixture);
        $counts = pqdlc_archive_fixture($workspaceid, $consumerid, $runid, $fixture);
        $after = pqdlc_active_counts($workspaceid, $fixture);
        $archived = pqdlc_archive_counts($workspaceid, $runid, $fixture);
        $result = [
            'mode' => 'archive',
            'runid' => $runid,
            'fixture' => $fixture,
            'before' => $before,
            'active_after' => $after,
            'archived' => $archived,
            'counts' => $counts,
            'rows' => pqdlc_rows($after, $archived, $counts, $cleanupmode),
        ];
    }
} catch (Throwable $e) {
    $error = $e->getMessage();
}

$params = [
    'consumer' => (string)($consumercontext->consumerslug ?? ''),
    'workspaceid' => $workspaceid,
    'runid' => $runid,
    'coursekey' => $coursekey,
    'cleanupmode' => $cleanupmode,
];

$PAGE->set_context(context_system::instance());
$PAGE->set_url(new moodle_url('/local/hubredirect/data_lifecycle_cleanup.php', $params));
$PAGE->set_pagelayout('standard');
$PAGE->set_title('Data Lifecycle Cleanup');
$PAGE->set_heading('Data Lifecycle Cleanup');
$PAGE->add_body_class('pqdlc-page');

echo $OUTPUT->header();
?>
<style>
body.pqdlc-page header,body.pqdlc-page footer,body.pqdlc-page nav.navbar,body.pqdlc-page #page-header,body.pqdlc-page #page-footer,body.pqdlc-page .drawer,body.pqdlc-page .drawer-toggles,body.pqdlc-page .block-region,body.pqdlc-page [data-region="drawer"],body.pqdlc-page [data-region="right-hand-drawer"]{display:none!important}
body.pqdlc-page #page,body.pqdlc-page #page-content,body.pqdlc-page #region-main,body.pqdlc-page .main-inner{margin:0!important;padding:0!important;max-width:none!important;border:0!important}
.pqdlc-shell{min-height:100vh;padding:30px 18px 58px;background:#f4f8fb;color:#173044;font-family:system-ui,-apple-system,"Segoe UI",Arial,sans-serif}.pqdlc-wrap{max-width:1180px;margin:0 auto}.pqdlc-top,.pqdlc-panel{padding:18px;border:1px solid rgba(23,48,68,.12);border-radius:8px;background:#fff;box-shadow:0 12px 28px rgba(23,48,68,.06)}.pqdlc-top{margin-bottom:14px}.pqdlc-title{margin:0;color:#221b22;font-size:30px;font-weight:950}.pqdlc-sub{margin:7px 0 0;color:#5e7280;font-size:14px;font-weight:800}.pqdlc-table{width:100%;border-collapse:collapse}.pqdlc-table th,.pqdlc-table td{padding:11px 9px;border-bottom:1px solid rgba(23,48,68,.1);text-align:left;vertical-align:top;font-size:13px}.pqdlc-table th{color:#5e7280;background:#fbfdff;font-size:12px;font-weight:950;text-transform:uppercase}.pqdlc-pill{display:inline-flex;align-items:center;min-height:24px;padding:0 8px;border-radius:999px;background:#fff6dc;color:#79520f;font-size:12px;font-weight:950}.pqdlc-pill--ok{background:#edf9ef;color:#245c35}.pqdlc-pill--blocked{background:#ffe9e5;color:#8a2f1d}.pqdlc-error{padding:12px;border-radius:8px;background:#ffe9e5;color:#8a2f1d;font-weight:900}.pqdlc-code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word}
</style>
<main class="pqdlc-shell">
  <div class="pqdlc-wrap">
    <section class="pqdlc-top">
      <h1 class="pqdlc-title">Data Lifecycle Cleanup</h1>
      <p class="pqdlc-sub">Archive/delete policy verification for generated SQA students, teachers, parents, invoices, course offerings, and materials.</p>
    </section>
    <section class="pqdlc-panel">
      <?php if ($error !== ''): ?>
        <div class="pqdlc-error"><?php echo s($error); ?></div>
      <?php elseif ($result): ?>
        <table class="pqdlc-table">
          <thead><tr><th>Category</th><th>Status</th><th>Evidence</th></tr></thead>
          <tbody>
          <?php foreach ($result['rows'] as $row): ?>
            <tr>
              <td><?php echo s($row['category']); ?></td>
              <td><span class="pqdlc-pill <?php echo $row['status'] === 'PASS' ? 'pqdlc-pill--ok' : ($row['status'] === 'BLOCKED' ? 'pqdlc-pill--blocked' : ''); ?>"><?php echo s($row['status']); ?></span></td>
              <td><?php echo s($row['evidence']); ?></td>
            </tr>
          <?php endforeach; ?>
          </tbody>
        </table>
        <pre id="pqdlc-result" class="pqdlc-code"><?php echo s(json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)); ?></pre>
      <?php else: ?>
        <p>Ready to run lifecycle verification.</p>
      <?php endif; ?>
    </section>
  </div>
</main>
<?php
echo $OUTPUT->footer();
