<?php
declare(strict_types=1);

require_once(__DIR__ . '/../../config.php');
require_login();
require_once(__DIR__ . '/accesslib.php');
require_once(__DIR__ . '/workflow_documentlib.php');

$generatedid = required_param('generatedid', PARAM_INT);
$row = $DB->get_record('local_prequran_generated_doc', ['id' => $generatedid], '*', MUST_EXIST);
$workspaceid = (int)$row->workspaceid;
if ($workspaceid <= 0 || !pqh_user_can_manage_workspace((int)$USER->id, $workspaceid)) {
    pqh_access_denied('Generated document PDFs require workspace administrator access.', new moodle_url('/local/hubredirect/workspace_dashboard.php'), 'Document PDF access denied');
}
$document = $DB->get_record('local_prequran_document', ['id' => (int)$row->documentid], '*', IGNORE_MISSING);
$workspace = $DB->get_record('local_prequran_workspace', ['id' => $workspaceid], '*', IGNORE_MISSING);
$student = (int)$row->studentid > 0 ? core_user::get_user((int)$row->studentid, 'id,firstname,lastname,email', IGNORE_MISSING) : null;
$payload = json_decode((string)$row->payloadjson, true);
$payload = is_array($payload) ? $payload : [];

$pdflib = $CFG->libdir . '/pdflib.php';
if (!file_exists($pdflib)) {
    throw new invalid_parameter_exception('PDF library is not available in this Moodle installation.');
}
require_once($pdflib);
if (!class_exists('pdf')) {
    throw new invalid_parameter_exception('PDF library is not available.');
}

$title = trim((string)($document->title ?? ($payload['title'] ?? ucfirst((string)$row->doc_type))));
$title = $title !== '' ? $title : 'Generated Document';
$documentkey = trim((string)$row->document_key);
$issued = (int)($document->issuedat ?? $row->generatedat);
$html = '<h1 style="font-size:22px;">' . s($title) . '</h1>';
$html .= '<table cellpadding="6" cellspacing="0" border="1" style="border-color:#d8e2d8;">';
$html .= '<tr><td><strong>Institution</strong></td><td>' . s((string)($workspace->name ?? 'Workspace')) . '</td></tr>';
$html .= '<tr><td><strong>Document Type</strong></td><td>' . s((string)$row->doc_type) . '</td></tr>';
$html .= '<tr><td><strong>Document Key</strong></td><td>' . s($documentkey) . '</td></tr>';
$html .= '<tr><td><strong>Student</strong></td><td>' . s($student ? fullname($student) : 'N/A') . '</td></tr>';
$html .= '<tr><td><strong>Source</strong></td><td>' . s((string)$row->source_type) . ' #' . (int)$row->source_id . '</td></tr>';
$html .= '<tr><td><strong>Status</strong></td><td>' . s((string)$row->status) . '</td></tr>';
$html .= '<tr><td><strong>Issued</strong></td><td>' . s($issued > 0 ? userdate($issued) : userdate((int)$row->generatedat)) . '</td></tr>';
$html .= '</table>';
$award = null;
if ((string)$row->source_type === 'completion_award' && pqh_table_exists_safe('local_prequran_completion_award')) {
    $award = $DB->get_record('local_prequran_completion_award', ['id' => (int)$row->source_id], '*', IGNORE_MISSING);
}
if ($award) {
    $html .= '<h2 style="font-size:17px;">Certificate Details</h2>';
    $html .= '<table cellpadding="6" cellspacing="0" border="1" style="border-color:#d8e2d8;">';
    $html .= '<tr><td><strong>Award Number</strong></td><td>' . s((string)$award->awardnumber) . '</td></tr>';
    $html .= '<tr><td><strong>Award Type</strong></td><td>' . s((string)$award->award_type) . '</td></tr>';
    $html .= '<tr><td><strong>Completion</strong></td><td>' . s((string)$award->completion_percent) . '%</td></tr>';
    $html .= '<tr><td><strong>Final Grade</strong></td><td>' . s((string)$award->final_grade) . '</td></tr>';
    $html .= '</table>';
}
$note = trim((string)($payload['note'] ?? ''));
if ($note !== '') {
    $html .= '<h2 style="font-size:15px;">Notes</h2><p>' . nl2br(s($note)) . '</p>';
}
$html .= '<p style="font-size:10px;color:#58665c;">Generated by Pre-Quraan document management. This PDF should be matched against the document key and workspace audit record.</p>';

$pdf = new pdf(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8');
$pdf->SetCreator('Pre-Quraan');
$pdf->SetAuthor('Pre-Quraan');
$pdf->SetTitle($title);
$pdf->SetMargins(14, 14, 14);
$pdf->SetFooterMargin(10);
$pdf->SetAutoPageBreak(true, 18);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(true);
$pdf->AddPage();
$pdf->writeHTML($html, true, false, true, false, '');
$bytes = $pdf->Output('', 'S');
$hash = hash('sha256', $bytes);
if ((string)$row->pdfhash === '') {
    $row->pdfhash = $hash;
    $row->timemodified = time();
    $DB->update_record('local_prequran_generated_doc', $row);
}
if ($document) {
    pqwdoc_document_audit($workspaceid, (int)$document->id, (int)$USER->id, 'generated_pdf_downloaded', ['generatedid' => $generatedid, 'pdfhash' => $hash]);
}

$filename = clean_filename(strtolower((string)$row->doc_type) . '-' . ($documentkey !== '' ? $documentkey : (string)$generatedid) . '.pdf');
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . strlen($bytes));
echo $bytes;
