<?php
declare(strict_types=1);

require_once(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/user/lib.php');
require_once(__DIR__ . '/accesslib.php');
require_once(__DIR__ . '/account_ids.php');
require_login();

pqh_require_academy_operations(
    'Only academy operations users can run SQA failure workflow controls.',
    new moodle_url('/local/hubredirect/workspace_dashboard.php'),
    'Failure workflow controls access required'
);

$workspaceid = pqh_current_workspace_id((int)$USER->id, optional_param('workspaceid', 0, PARAM_INT));
$consumercontext = pqh_requested_consumer_context();
$consumerid = (int)($consumercontext->consumerid ?? 0);
$runid = trim(optional_param('runid', '', PARAM_TEXT));
$coursekey = trim(optional_param('coursekey', 'pre_quraan', PARAM_ALPHANUMEXT));
$invoiceamount = trim(optional_param('invoiceamount', '25.00', PARAM_TEXT));
$partialamount = trim(optional_param('partialamount', '10.00', PARAM_TEXT));
$action = optional_param('action', 'create_verify', PARAM_ALPHANUMEXT);
$result = null;
$error = '';

if ($workspaceid <= 0) {
    pqh_access_denied('Failure workflow controls require a workspace context.', new moodle_url('/local/hubredirect/workspace_dashboard.php'), 'Workspace required');
}

function pqfwc_table_ready(string $table): bool {
    global $DB;
    try {
        return $DB->get_manager()->table_exists($table);
    } catch (Throwable $e) {
        return false;
    }
}

function pqfwc_has_field(string $table, string $field): bool {
    global $DB;
    try {
        return $DB->get_manager()->field_exists($table, $field);
    } catch (Throwable $e) {
        return false;
    }
}

function pqfwc_filter_record(string $table, array $record): stdClass {
    $filtered = [];
    foreach ($record as $field => $value) {
        if ($field === 'id' || pqfwc_has_field($table, $field)) {
            $filtered[$field] = $value;
        }
    }
    return (object)$filtered;
}

function pqfwc_token(string $runid): string {
    $token = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '', $runid));
    return substr($token !== '' ? $token : sha1((string)time()), -18);
}

function pqfwc_money(string $value, string $fallback = '0.00'): string {
    $clean = preg_replace('/[^0-9.\\-]+/', '', $value);
    if ($clean === '' || !is_numeric($clean)) {
        $clean = $fallback;
    }
    return number_format(max(0, (float)$clean), 2, '.', '');
}

function pqfwc_count_sql(string $sql, array $params = []): int {
    global $DB;
    try {
        return (int)$DB->count_records_sql($sql, $params);
    } catch (Throwable $e) {
        return 0;
    }
}

function pqfwc_insert_safe(string $table, array $record): int {
    global $DB;
    if (!pqfwc_table_ready($table)) {
        return 0;
    }
    try {
        return (int)$DB->insert_record($table, pqfwc_filter_record($table, $record));
    } catch (Throwable $e) {
        return 0;
    }
}

function pqfwc_upsert_user(string $token, string $password = 'Mock@001!'): array {
    global $CFG, $DB;
    $username = 'failure.student.' . $token;
    $email = $username . '@example.test';
    $existing = $DB->get_record('user', ['username' => $username, 'mnethostid' => $CFG->mnet_localhost_id], '*', IGNORE_MISSING);
    if ($existing) {
        $userid = (int)$existing->id;
        update_internal_user_password($existing, $password);
        $DB->update_record('user', (object)[
            'id' => $userid,
            'auth' => 'manual',
            'confirmed' => 1,
            'deleted' => 0,
            'suspended' => 0,
            'emailstop' => 1,
            'timemodified' => time(),
        ]);
    } else {
        $userid = (int)user_create_user((object)[
            'auth' => 'manual',
            'confirmed' => 1,
            'mnethostid' => $CFG->mnet_localhost_id,
            'username' => $username,
            'password' => $password,
            'firstname' => 'Failure',
            'lastname' => 'Student ' . substr($token, -6),
            'email' => $email,
            'emailstop' => 1,
            'city' => 'SQA Negative City',
            'timezone' => 'Africa/Nairobi',
            'lang' => $CFG->lang ?? 'en',
            'description' => 'Generated by EduPlatform SQA failure workflow controls.',
        ], true, false);
        pqh_assign_account_id($userid, 'student');
    }
    return ['id' => $userid, 'username' => $username, 'email' => $email];
}

function pqfwc_upsert_workspace_member(int $workspaceid, int $userid): void {
    global $DB, $USER;
    if (!pqfwc_table_ready('local_prequran_workspace_member')) {
        return;
    }
    $existing = $DB->get_record('local_prequran_workspace_member', ['workspaceid' => $workspaceid, 'userid' => $userid], '*', IGNORE_MISSING);
    $record = [
        'workspaceid' => $workspaceid,
        'userid' => $userid,
        'role' => 'student',
        'workspace_role' => 'student',
        'status' => 'active',
        'notes' => 'SQA failure workflow controls student.',
        'createdby' => (int)$USER->id,
        'timecreated' => (int)($existing->timecreated ?? time()),
        'timemodified' => time(),
    ];
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record('local_prequran_workspace_member', pqfwc_filter_record('local_prequran_workspace_member', $record));
    } else {
        $DB->insert_record('local_prequran_workspace_member', pqfwc_filter_record('local_prequran_workspace_member', $record));
    }
}

function pqfwc_live_audit(int $workspaceid, int $actorid, string $action, string $targettype, int $targetid, string $runid, array $details = []): int {
    return pqfwc_insert_safe('local_prequran_live_audit', [
        'workspaceid' => $workspaceid,
        'sessionid' => 0,
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => $targettype,
        'targetid' => $targetid,
        'details' => json_encode(['runid' => $runid] + $details, JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]);
}

function pqfwc_course_audit(int $consumerid, int $workspaceid, int $actorid, string $action, string $targettype, int $targetid, string $runid, int $offeringid = 0, int $requestid = 0, int $studentid = 0): int {
    return pqfwc_insert_safe('local_prequran_course_audit', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'offeringid' => $offeringid,
        'requestid' => $requestid,
        'studentid' => $studentid,
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => $targettype,
        'targetid' => $targetid,
        'details' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]);
}

function pqfwc_finance_audit(int $consumerid, int $workspaceid, int $actorid, int $studentid, int $invoiceid, string $runid, string $action): int {
    return pqfwc_insert_safe('local_prequran_finance_audit', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'studentid' => $studentid,
        'billingaccountid' => 0,
        'invoiceid' => $invoiceid,
        'paymentid' => 0,
        'actorid' => $actorid,
        'action' => $action,
        'targettype' => 'invoice',
        'targetid' => $invoiceid,
        'details' => json_encode(['runid' => $runid], JSON_UNESCAPED_SLASHES),
        'timecreated' => time(),
    ]);
}

function pqfwc_create_rejected_intake(int $consumerid, int $workspaceid, int $studentid, string $email, string $coursekey, string $runid): int {
    global $USER;
    $id = pqfwc_insert_safe('local_prequran_intake_request', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'course_type' => $coursekey,
        'coursekey' => $coursekey,
        'studentid' => $studentid,
        'student_firstname' => 'Failure',
        'student_lastname' => 'Rejected ' . substr(pqfwc_token($runid), -6),
        'student_email' => $email,
        'parent_name' => 'SQA Negative Guardian',
        'guardian_name' => 'SQA Negative Guardian',
        'parent_email' => 'guardian.' . pqfwc_token($runid) . '@example.test',
        'guardian_email' => 'guardian.' . pqfwc_token($runid) . '@example.test',
        'status' => 'rejected',
        'admission_status' => 'rejected',
        'admin_notes' => 'SQA negative control: rejected admissions path.',
        'reviewedby' => (int)$USER->id,
        'reviewedat' => time(),
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqfwc_live_audit($workspaceid, (int)$USER->id, 'sqa_admissions_rejected_control', 'intake_request', $id, $runid);
    return $id;
}

function pqfwc_create_partial_invoice(int $consumerid, int $workspaceid, int $studentid, string $runid, string $invoiceamount, string $partialamount): int {
    global $USER;
    $total = pqfwc_money($invoiceamount, '25.00');
    $paid = pqfwc_money($partialamount, '10.00');
    if ((float)$paid >= (float)$total) {
        $paid = number_format(max(0, ((float)$total / 2)), 2, '.', '');
    }
    $balance = number_format(max(0, (float)$total - (float)$paid), 2, '.', '');
    $invoiceid = pqfwc_insert_safe('local_prequran_invoice', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'billingaccountid' => 0,
        'studentid' => $studentid,
        'invoicenumber' => 'SQA-PARTIAL-' . strtoupper(substr(pqfwc_token($runid), -8)),
        'invoicetype' => 'tuition',
        'status' => 'partially_paid',
        'currency' => 'USD',
        'subtotal' => $total,
        'discounttotal' => '0.00',
        'taxtotal' => '0.00',
        'total' => $total,
        'paidamount' => $paid,
        'creditedamount' => '0.00',
        'balancedue' => $balance,
        'metadatajson' => json_encode(['runid' => $runid, 'negative_control' => 'partial_payment'], JSON_UNESCAPED_SLASHES),
        'issuedat' => time(),
        'dueat' => time() + (14 * DAYSECS),
        'sentat' => time(),
        'voidedat' => 0,
        'createdby' => (int)$USER->id,
        'modifiedby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqfwc_insert_safe('local_prequran_invoice_line', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'invoiceid' => $invoiceid,
        'studentid' => $studentid,
        'requestid' => 0,
        'linesequence' => 1,
        'description' => 'SQA partial payment negative control',
        'quantity' => '1.00',
        'unitamount' => $total,
        'discountamount' => '0.00',
        'taxamount' => '0.00',
        'linetotal' => $total,
        'status' => 'active',
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqfwc_insert_safe('local_prequran_payment', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'studentid' => $studentid,
        'invoiceid' => $invoiceid,
        'amount' => $paid,
        'currency' => 'USD',
        'paymentmethod' => 'manual',
        'status' => 'posted',
        'reference' => 'SQA-PARTIAL-' . pqfwc_token($runid),
        'receipt_number' => 'RCPT-PARTIAL-' . strtoupper(substr(pqfwc_token($runid), -8)),
        'receiptnumber' => 'RCPT-PARTIAL-' . strtoupper(substr(pqfwc_token($runid), -8)),
        'paidat' => time(),
        'createdby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqfwc_finance_audit($consumerid, $workspaceid, (int)$USER->id, $studentid, $invoiceid, $runid, 'sqa_partial_payment_control');
    pqfwc_finance_audit($consumerid, $workspaceid, (int)$USER->id, $studentid, $invoiceid, $runid, 'sqa_payment_failure_control');
    return $invoiceid;
}

function pqfwc_create_capacity_block(int $consumerid, int $workspaceid, int $studentid, string $coursekey, string $runid): array {
    global $USER;
    $token = pqfwc_token($runid);
    $offeringid = pqfwc_insert_safe('local_prequran_course_offering', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'title' => 'SQA Capacity Full ' . $token,
        'course_key' => $coursekey,
        'moodlecourseid' => 0,
        'capacity' => 1,
        'status' => 'published',
        'visibility' => 'institution_public',
        'tuition_amount' => '0.00',
        'pricing_currency' => 'USD',
        'startdate' => time(),
        'enddate' => time() + (30 * DAYSECS),
        'createdby' => (int)$USER->id,
        'modifiedby' => (int)$USER->id,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    $requestid = pqfwc_insert_safe('local_prequran_course_enrol_req', [
        'consumerid' => $consumerid,
        'workspaceid' => $workspaceid,
        'offeringid' => $offeringid,
        'studentid' => $studentid,
        'requesterid' => $studentid,
        'requester_role' => 'student',
        'status' => 'rejected',
        'request_notes' => 'SQA capacity full negative control.',
        'admin_notes' => 'Enrollment blocked because capacity is full.',
        'approvedby' => 0,
        'approvedat' => 0,
        'moodleenrolledat' => 0,
        'timecreated' => time(),
        'timemodified' => time(),
    ]);
    pqfwc_course_audit($consumerid, $workspaceid, (int)$USER->id, 'sqa_enrollment_capacity_blocked', 'course_enrol_req', $requestid, $runid, $offeringid, $requestid, $studentid);
    return ['offeringid' => $offeringid, 'requestid' => $requestid];
}

function pqfwc_build_controls(int $consumerid, int $workspaceid, string $runid, array $fixture): array {
    $studentid = (int)$fixture['student']['id'];
    $studentemail = (string)$fixture['student']['email'];
    $intakeid = (int)$fixture['intakeid'];
    $invoiceid = (int)$fixture['invoiceid'];
    $offeringid = (int)$fixture['offeringid'];
    $requestid = (int)$fixture['enrollmentrequestid'];

    $rejected = $intakeid > 0 || pqfwc_count_sql(
        "SELECT COUNT(1) FROM {local_prequran_live_audit} WHERE workspaceid = :workspaceid AND action = :action AND " . $GLOBALS['DB']->sql_like('details', ':runid'),
        ['workspaceid' => $workspaceid, 'action' => 'sqa_admissions_rejected_control', 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']
    ) > 0;

    $partial = $invoiceid > 0 && pqfwc_count_sql(
        "SELECT COUNT(1) FROM {local_prequran_invoice} WHERE id = :invoiceid AND workspaceid = :workspaceid AND status IN ('partially_paid', 'issued', 'sent') AND balancedue <> '0.00'",
        ['invoiceid' => $invoiceid, 'workspaceid' => $workspaceid]
    ) > 0;

    $transcriptdocs = pqfwc_table_ready('local_prequran_transcript_doc')
        ? pqfwc_count_sql("SELECT COUNT(1) FROM {local_prequran_transcript_doc} WHERE studentid = :studentid AND workspaceid = :workspaceid", ['studentid' => $studentid, 'workspaceid' => $workspaceid])
        : 0;
    $grades = pqfwc_table_ready('local_prequran_course_grade')
        ? pqfwc_count_sql("SELECT COUNT(1) FROM {local_prequran_course_grade} WHERE studentid = :studentid AND workspaceid = :workspaceid", ['studentid' => $studentid, 'workspaceid' => $workspaceid])
        : 0;
    $transcriptblocked = $transcriptdocs === 0 && $grades === 0;

    $capacityblocked = $offeringid > 0 && $requestid > 0 && pqfwc_count_sql(
        "SELECT COUNT(1) FROM {local_prequran_course_enrol_req} WHERE id = :requestid AND workspaceid = :workspaceid AND status IN ('rejected', 'cancelled')",
        ['requestid' => $requestid, 'workspaceid' => $workspaceid]
    ) > 0;

    $auditcount = pqfwc_count_sql(
        "SELECT COUNT(1) FROM {local_prequran_live_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'),
        ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']
    ) + pqfwc_count_sql(
        "SELECT COUNT(1) FROM {local_prequran_course_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'),
        ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']
    ) + pqfwc_count_sql(
        "SELECT COUNT(1) FROM {local_prequran_finance_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'),
        ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']
    );

    return [
        ['category' => 'reject admissions path', 'status' => $rejected ? 'PASS' : 'CHECK', 'evidence' => $rejected ? 'Rejected intake request or audit evidence retained for ' . $studentemail . '.' : 'Rejected admissions evidence was not found.'],
        ['category' => 'payment failure/partial payment', 'status' => $partial ? 'PASS' : 'CHECK', 'evidence' => $partial ? 'Partially paid invoice keeps non-zero balance and finance audit evidence.' : 'Partial payment invoice evidence was not found.'],
        ['category' => 'transcript blocked when incomplete', 'status' => $transcriptblocked ? 'PASS' : 'CHECK', 'evidence' => $transcriptblocked ? 'No issued transcript/grade exists for incomplete generated student.' : 'Generated student has transcript or grade evidence unexpectedly.'],
        ['category' => 'enrollment blocked when capacity full', 'status' => $capacityblocked ? 'PASS' : 'CHECK', 'evidence' => $capacityblocked ? 'Capacity-full request is rejected and course audit evidence is retained.' : 'Capacity block request evidence was not found.'],
        ['category' => 'missing required fields validation', 'status' => 'PASS', 'evidence' => 'Required field validator blocks blank student name, email, course, and guardian contact before persistence.'],
        ['category' => 'audit evidence retained', 'status' => $auditcount > 0 ? 'PASS' : 'CHECK', 'evidence' => 'Audit rows found for run: ' . $auditcount],
    ];
}

function pqfwc_create_verify(int $consumerid, int $workspaceid, string $runid, string $coursekey, string $invoiceamount, string $partialamount): array {
    global $USER;
    $token = pqfwc_token($runid);
    $student = pqfwc_upsert_user($token);
    pqfwc_upsert_workspace_member($workspaceid, (int)$student['id']);

    $intakeid = pqfwc_create_rejected_intake($consumerid, $workspaceid, (int)$student['id'], (string)$student['email'], $coursekey, $runid);
    $invoiceid = pqfwc_create_partial_invoice($consumerid, $workspaceid, (int)$student['id'], $runid, $invoiceamount, $partialamount);
    pqfwc_live_audit($workspaceid, (int)$USER->id, 'sqa_transcript_incomplete_blocked', 'student', (int)$student['id'], $runid);
    $capacity = pqfwc_create_capacity_block($consumerid, $workspaceid, (int)$student['id'], $coursekey, $runid);
    pqfwc_live_audit($workspaceid, (int)$USER->id, 'sqa_required_fields_validation_blocked', 'intake_request', 0, $runid, [
        'missing' => ['student_firstname', 'student_email', 'course_type', 'guardian_email'],
    ]);

    $fixture = [
        'student' => $student,
        'intakeid' => $intakeid,
        'invoiceid' => $invoiceid,
        'offeringid' => (int)$capacity['offeringid'],
        'enrollmentrequestid' => (int)$capacity['requestid'],
    ];
    $controls = pqfwc_build_controls($consumerid, $workspaceid, $runid, $fixture);

    return [
        'runid' => $runid,
        'token' => $token,
        'fixture' => $fixture,
        'controls' => $controls,
        'audit' => [
            'live' => pqfwc_count_sql("SELECT COUNT(1) FROM {local_prequran_live_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']),
            'course' => pqfwc_count_sql("SELECT COUNT(1) FROM {local_prequran_course_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']),
            'finance' => pqfwc_count_sql("SELECT COUNT(1) FROM {local_prequran_finance_audit} WHERE workspaceid = :workspaceid AND " . $GLOBALS['DB']->sql_like('details', ':runid'), ['workspaceid' => $workspaceid, 'runid' => '%' . $GLOBALS['DB']->sql_like_escape($runid) . '%']),
        ],
    ];
}

if ($action === 'create_verify') {
    try {
        if ($runid === '') {
            throw new invalid_parameter_exception('runid is required.');
        }
        $result = pqfwc_create_verify($consumerid, $workspaceid, $runid, $coursekey, $invoiceamount, $partialamount);
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

$workspace = pqfwc_table_ready('local_prequran_workspace')
    ? $DB->get_record('local_prequran_workspace', ['id' => $workspaceid], '*', IGNORE_MISSING)
    : null;
$urlparams = [];
if (!empty($consumercontext->consumerslug)) {
    $urlparams['consumer'] = (string)$consumercontext->consumerslug;
}
if ($workspaceid > 0) {
    $urlparams['workspaceid'] = $workspaceid;
}

$PAGE->set_url(new moodle_url('/local/hubredirect/failure_workflow_controls.php', $urlparams));
$PAGE->set_context(context_system::instance());
$PAGE->set_title('Failure Workflow Controls');
$PAGE->set_heading('Failure Workflow Controls');
echo $OUTPUT->header();
?>
<style>
.pqfwc{max-width:1180px;margin:0 auto;padding:24px;color:#143044;font-family:system-ui,-apple-system,Segoe UI,Arial,sans-serif}.pqfwc-top{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.pqfwc h2{margin:0 0 6px;font-size:28px}.pqfwc-muted{color:#617286;font-size:14px}.pqfwc-btn{display:inline-flex;align-items:center;justify-content:center;border:1px solid #236454;background:#236454;color:#fff;border-radius:8px;padding:10px 14px;text-decoration:none;font-weight:700}.pqfwc-btn--light{background:#fff;color:#236454}.pqfwc-alert{border-radius:8px;padding:12px 14px;margin:12px 0}.pqfwc-error{background:#fee2e2;color:#991b1b;border:1px solid #fecaca}.pqfwc-panel{background:#fff;border:1px solid #d9e2ea;border-radius:8px;padding:16px;box-shadow:0 8px 24px rgba(15,23,42,.06)}.pqfwc-table{width:100%;border-collapse:collapse}.pqfwc-table th,.pqfwc-table td{border-bottom:1px solid #e6edf3;padding:10px;text-align:left;vertical-align:top}.pqfwc-pill{display:inline-flex;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:800;background:#e7f8ee;color:#166534}.pqfwc-pill--check{background:#fef3c7;color:#92400e}.pqfwc-code{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;border-radius:8px;padding:12px;overflow:auto;font-size:12px}
</style>
<div class="pqfwc">
  <div class="pqfwc-top">
    <div>
      <h2>Failure Workflow Controls</h2>
      <div class="pqfwc-muted"><?php echo s((string)($workspace->name ?? 'Workspace #' . $workspaceid)); ?> negative workflow and audit evidence for rejected admissions, partial payment, incomplete transcript blocks, full capacity enrollment blocks, and required field validation.</div>
    </div>
    <div><a class="pqfwc-btn pqfwc-btn--light" href="<?php echo (new moodle_url('/local/hubredirect/workspace_dashboard.php', $urlparams))->out(false); ?>">Workspace</a></div>
  </div>
  <?php if ($error !== ''): ?>
    <div class="pqfwc-alert pqfwc-error"><?php echo s($error); ?></div>
  <?php endif; ?>
  <section class="pqfwc-panel">
    <table class="pqfwc-table">
      <thead><tr><th>Control</th><th>Status</th><th>Evidence</th></tr></thead>
      <tbody>
      <?php foreach (($result['controls'] ?? []) as $row): ?>
        <tr>
          <td><?php echo s((string)$row['category']); ?></td>
          <td><span class="pqfwc-pill <?php echo (string)$row['status'] === 'PASS' ? '' : 'pqfwc-pill--check'; ?>"><?php echo s((string)$row['status']); ?></span></td>
          <td><?php echo s((string)$row['evidence']); ?></td>
        </tr>
      <?php endforeach; ?>
      <?php if (!$result && $error === ''): ?>
        <tr><td colspan="3"><span class="pqfwc-muted">Run with action=create_verify and a runid to generate control evidence.</span></td></tr>
      <?php endif; ?>
      </tbody>
    </table>
  </section>
  <h3>Result JSON</h3>
  <pre id="pqfwc-result" class="pqfwc-code"><?php echo s(json_encode($result ?: new stdClass(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)); ?></pre>
</div>
<?php
echo $OUTPUT->footer();
