<?php
declare(strict_types=1);

require_once(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/user/lib.php');
require_once(__DIR__ . '/accesslib.php');
require_once(__DIR__ . '/account_ids.php');
require_login();

pqh_require_academy_operations(
    'Only academy operations users can create SQA teacher portal fixtures.',
    new moodle_url('/local/hubredirect/dashboard.php'),
    'SQA teacher fixture access required'
);

$workspaceid = optional_param('workspaceid', 0, PARAM_INT);
$teacherid = optional_param('teacherid', 0, PARAM_INT);
$runid = trim(optional_param('runid', '', PARAM_TEXT));
$coursekey = trim(optional_param('coursekey', 'pre_quraan', PARAM_ALPHANUMEXT));
$studentpassword = optional_param('studentpassword', 'Mock@001!', PARAM_RAW);
$teacherpassword = optional_param('teacherpassword', 'Mock@001!', PARAM_RAW);
$result = null;
$error = '';

function pqsqtf_table_ready(string $table): bool {
    global $DB;
    try {
        return $DB->get_manager()->table_exists($table);
    } catch (Throwable $e) {
        return false;
    }
}

function pqsqtf_has_field(string $table, string $field): bool {
    global $DB;
    try {
        return $DB->get_manager()->field_exists($table, $field);
    } catch (Throwable $e) {
        return false;
    }
}

function pqsqtf_filter_record(string $table, array $record): stdClass {
    $filtered = [];
    foreach ($record as $field => $value) {
        if ($field === 'id' || pqsqtf_has_field($table, $field)) {
            $filtered[$field] = $value;
        }
    }
    return (object)$filtered;
}

function pqsqtf_token(string $value): string {
    $token = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '', $value));
    return substr($token !== '' ? $token : sha1((string)time()), -18);
}

function pqsqtf_upsert_workspace_member(int $workspaceid, int $userid, string $role): int {
    global $DB, $USER;
    if ($workspaceid <= 0 || $userid <= 0 || !pqsqtf_table_ready('local_prequran_workspace_member')) {
        return 0;
    }
    $now = time();
    $existing = $DB->get_record('local_prequran_workspace_member', [
        'workspaceid' => $workspaceid,
        'userid' => $userid,
    ], '*', IGNORE_MISSING);
    $record = [
        'workspaceid' => $workspaceid,
        'userid' => $userid,
        'role' => $role,
        'status' => 'active',
        'notes' => 'Created or refreshed by SQA teacher portal fixture.',
        'createdby' => (int)$USER->id,
        'timecreated' => (int)($existing->timecreated ?? $now),
        'timemodified' => $now,
    ];
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record('local_prequran_workspace_member', pqsqtf_filter_record('local_prequran_workspace_member', $record));
        return (int)$existing->id;
    }
    return (int)$DB->insert_record('local_prequran_workspace_member', pqsqtf_filter_record('local_prequran_workspace_member', $record));
}

function pqsqtf_create_student(int $workspaceid, string $runid, string $password): array {
    global $CFG, $DB, $USER;
    $token = pqsqtf_token($runid);
    $username = 'student.portal.' . $token;
    $email = $username . '@example.test';
    $existing = $DB->get_record('user', [
        'username' => $username,
        'mnethostid' => $CFG->mnet_localhost_id,
        'deleted' => 0,
    ], '*', IGNORE_MISSING);

    if ($existing) {
        $userid = (int)$existing->id;
    } else {
        $userid = (int)user_create_user((object)[
            'auth' => 'manual',
            'confirmed' => 1,
            'mnethostid' => $CFG->mnet_localhost_id,
            'username' => $username,
            'password' => $password,
            'firstname' => 'Portal',
            'lastname' => 'Student ' . substr($token, -6),
            'email' => $email,
            'emailstop' => 1,
            'city' => 'SQA Teacher Portal City',
            'timezone' => 'Africa/Nairobi',
            'lang' => $CFG->lang ?? 'en',
            'description' => 'Generated by EduPlatform SQA teacher portal fixture.',
        ], true, false);
        pqh_assign_account_id($userid, 'student');
    }

    pqsqtf_upsert_workspace_member($workspaceid, $userid, 'student');

    if (pqsqtf_table_ready('local_prequran_student_profile')) {
        $existingprofile = $DB->get_record('local_prequran_student_profile', ['userid' => $userid], '*', IGNORE_MISSING);
        $record = [
            'userid' => $userid,
            'workspaceid' => $workspaceid,
            'displayname' => 'Portal Student ' . substr($token, -6),
            'student_display_name' => 'Portal Student ' . substr($token, -6),
            'status' => 'active',
            'current_level' => 'Pre-quraan Course',
            'course_type' => 'pre_quraan',
            'createdby' => (int)$USER->id,
            'timecreated' => (int)($existingprofile->timecreated ?? time()),
            'timemodified' => time(),
        ];
        if ($existingprofile) {
            $record['id'] = (int)$existingprofile->id;
            $DB->update_record('local_prequran_student_profile', pqsqtf_filter_record('local_prequran_student_profile', $record));
        } else {
            $DB->insert_record('local_prequran_student_profile', pqsqtf_filter_record('local_prequran_student_profile', $record));
        }
    }

    return [
        'userid' => $userid,
        'username' => $username,
        'email' => $email,
    ];
}

function pqsqtf_reset_teacher_password(int $teacherid, string $password): void {
    global $DB;
    $teacher = core_user::get_user($teacherid, '*', MUST_EXIST);
    update_internal_user_password($teacher, $password);
    $DB->update_record('user', (object)[
        'id' => $teacherid,
        'auth' => 'manual',
        'confirmed' => 1,
        'suspended' => 0,
        'deleted' => 0,
        'policyagreed' => 1,
        'emailstop' => (int)($teacher->emailstop ?? 0),
        'timemodified' => time(),
    ]);
    if (function_exists('unset_user_preference')) {
        unset_user_preference('auth_forcepasswordchange', $teacherid);
    }
}

function pqsqtf_upsert_teacher_student(int $workspaceid, int $teacherid, int $studentid): int {
    global $DB, $USER;
    $now = time();
    $existing = $DB->get_record('local_prequran_teacher_student', [
        'workspaceid' => $workspaceid,
        'teacherid' => $teacherid,
        'studentid' => $studentid,
    ], '*', IGNORE_MISSING);
    $record = [
        'workspaceid' => $workspaceid,
        'teacherid' => $teacherid,
        'studentid' => $studentid,
        'cohortid' => 0,
        'status' => 'active',
        'assignedby' => (int)$USER->id,
        'timecreated' => (int)($existing->timecreated ?? $now),
        'timemodified' => $now,
    ];
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record('local_prequran_teacher_student', pqsqtf_filter_record('local_prequran_teacher_student', $record));
        return (int)$existing->id;
    }
    return (int)$DB->insert_record('local_prequran_teacher_student', pqsqtf_filter_record('local_prequran_teacher_student', $record));
}

function pqsqtf_create_session(int $workspaceid, int $teacherid, int $studentid, string $runid): int {
    global $DB, $USER;
    $now = time();
    $start = strtotime('today 10:00') ?: $now;
    if ($start < $now - HOURSECS) {
        $start = $now + 600;
    }
    $meetingid = 'sqa-teacher-portal-' . pqsqtf_token($runid);
    $existing = $DB->get_record('local_prequran_live_session', [
        'workspaceid' => $workspaceid,
        'teacherid' => $teacherid,
        'bbb_meeting_id' => $meetingid,
    ], '*', IGNORE_MISSING);
    $record = [
        'workspaceid' => $workspaceid,
        'seriesid' => 0,
        'series_sequence' => 0,
        'cohortid' => 0,
        'teacherid' => $teacherid,
        'session_type' => 'teacher_led',
        'teacher_required' => 1,
        'report_to_teacherid' => $teacherid,
        'lessonid' => 'sqa-teacher-portal',
        'unitid' => 'teacher-portal',
        'title' => 'Automated SQA Teacher Portal Class ' . pqsqtf_token($runid),
        'description' => 'Generated by EduPlatform SQA teacher portal fixture.',
        'scheduled_start' => $start,
        'scheduled_end' => $start + HOURSECS,
        'timezone' => 'Africa/Nairobi',
        'status' => 'scheduled',
        'recording_enabled' => 0,
        'recording_consent_required' => 0,
        'parent_observer_allowed' => 0,
        'max_participants' => 12,
        'bbb_meeting_id' => $meetingid,
        'bbb_internal_meeting_id' => '',
        'bbb_created' => 0,
        'bbb_create_time' => 0,
        'bbb_last_error' => '',
        'createdby' => (int)$USER->id,
        'timecreated' => (int)($existing->timecreated ?? $now),
        'timemodified' => $now,
    ];
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record('local_prequran_live_session', pqsqtf_filter_record('local_prequran_live_session', $record));
        $sessionid = (int)$existing->id;
    } else {
        $sessionid = (int)$DB->insert_record('local_prequran_live_session', pqsqtf_filter_record('local_prequran_live_session', $record));
    }

    $student = core_user::get_user($studentid, 'id,firstname,lastname,email', MUST_EXIST);
    $existingparticipant = $DB->get_record('local_prequran_live_participant', [
        'sessionid' => $sessionid,
        'userid' => $studentid,
        'role' => 'student',
    ], '*', IGNORE_MISSING);
    $participant = [
        'workspaceid' => $workspaceid,
        'sessionid' => $sessionid,
        'userid' => $studentid,
        'role' => 'student',
        'studentid' => $studentid,
        'status' => 'active',
        'displayname' => fullname($student),
        'invitedby' => (int)$USER->id,
        'timecreated' => (int)($existingparticipant->timecreated ?? $now),
        'timemodified' => $now,
    ];
    if ($existingparticipant) {
        $participant['id'] = (int)$existingparticipant->id;
        $DB->update_record('local_prequran_live_participant', pqsqtf_filter_record('local_prequran_live_participant', $participant));
    } else {
        $DB->insert_record('local_prequran_live_participant', pqsqtf_filter_record('local_prequran_live_participant', $participant));
    }

    return $sessionid;
}

function pqsqtf_create_assessment(int $workspaceid, string $coursekey, string $runid): int {
    global $DB, $USER;
    $now = time();
    $title = 'Automated SQA Teacher Portal Assessment ' . pqsqtf_token($runid);
    $existing = $DB->get_record('local_prequran_assessment', [
        'workspaceid' => $workspaceid,
        'title' => $title,
    ], '*', IGNORE_MISSING);
    $offeringid = 0;
    if (pqsqtf_table_ready('local_prequran_course_offering')) {
        $offeringid = (int)$DB->get_field('local_prequran_course_offering', 'id', [
            'workspaceid' => $workspaceid,
            'course_key' => $coursekey,
        ], IGNORE_MISSING);
    }
    $record = [
        'workspaceid' => $workspaceid,
        'offeringid' => $offeringid,
        'categoryid' => 0,
        'assessment_type' => 'teacher_portal',
        'title' => $title,
        'description' => 'Generated by EduPlatform SQA teacher portal fixture.',
        'max_points' => '100',
        'weight_override' => '',
        'duedate' => $now + DAYSECS,
        'publishdate' => $now,
        'status' => 'published',
        'createdby' => (int)$USER->id,
        'timecreated' => (int)($existing->timecreated ?? $now),
        'timemodified' => $now,
    ];
    if ($existing) {
        $record['id'] = (int)$existing->id;
        $DB->update_record('local_prequran_assessment', pqsqtf_filter_record('local_prequran_assessment', $record));
        return (int)$existing->id;
    }
    return (int)$DB->insert_record('local_prequran_assessment', pqsqtf_filter_record('local_prequran_assessment', $record));
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        require_sesskey();
        foreach (['local_prequran_workspace_member', 'local_prequran_teacher_student', 'local_prequran_live_session', 'local_prequran_live_participant', 'local_prequran_assessment'] as $table) {
            if (!pqsqtf_table_ready($table)) {
                throw new invalid_parameter_exception('Required table is not ready: ' . $table);
            }
        }
        if ($workspaceid <= 0 || !$DB->record_exists('local_prequran_workspace', ['id' => $workspaceid])) {
            throw new invalid_parameter_exception('Choose a valid workspace before creating the teacher portal fixture.');
        }
        $teacher = $teacherid > 0 ? core_user::get_user($teacherid, 'id,firstname,lastname,email', IGNORE_MISSING) : false;
        if (!$teacher) {
            throw new invalid_parameter_exception('Choose a valid teacher user before creating the teacher portal fixture.');
        }
        if ($runid === '') {
            throw new invalid_parameter_exception('Run ID is required.');
        }

        pqsqtf_reset_teacher_password($teacherid, $teacherpassword);
        pqsqtf_upsert_workspace_member($workspaceid, $teacherid, 'teacher');
        $student = pqsqtf_create_student($workspaceid, $runid, $studentpassword);
        $assignmentid = pqsqtf_upsert_teacher_student($workspaceid, $teacherid, (int)$student['userid']);
        $sessionid = pqsqtf_create_session($workspaceid, $teacherid, (int)$student['userid'], $runid);
        $assessmentid = pqsqtf_create_assessment($workspaceid, $coursekey, $runid);

        $result = [
            'teacherid' => $teacherid,
            'workspaceid' => $workspaceid,
            'studentid' => (int)$student['userid'],
            'studentusername' => (string)$student['username'],
            'studentemail' => (string)$student['email'],
            'assignmentid' => $assignmentid,
            'sessionid' => $sessionid,
            'assessmentid' => $assessmentid,
        ];
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

$PAGE->set_context(context_system::instance());
$PAGE->set_url(new moodle_url('/local/hubredirect/sqa_teacher_portal_fixture.php', ['workspaceid' => $workspaceid, 'teacherid' => $teacherid]));
$PAGE->set_pagelayout('standard');
$PAGE->set_title('SQA Teacher Portal Fixture');
$PAGE->set_heading('SQA Teacher Portal Fixture');

echo $OUTPUT->header();
?>
<style>
.pqsqtf-wrap{max-width:980px;margin:0 auto;padding:24px}.pqsqtf-card{background:#fff;border:1px solid #dfe8e4;border-radius:10px;padding:20px;margin-bottom:14px}.pqsqtf-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.pqsqtf-field label{display:block;margin:0 0 5px;font-size:12px;font-weight:800}.pqsqtf-field input{width:100%;min-height:40px;border:1px solid #d7e1dc;border-radius:8px;padding:0 10px}.pqsqtf-btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 15px;border:0;border-radius:8px;background:#1f7a68;color:#fff!important;text-decoration:none;font-weight:900}.pqsqtf-ok{padding:13px 14px;border-radius:8px;background:#ecf9f1;color:#185c32;font-weight:800}.pqsqtf-error{padding:13px 14px;border-radius:8px;background:#fff0e6;color:#8a3e2e;font-weight:800}.pqsqtf-code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}
</style>
<main class="pqsqtf-wrap">
  <section class="pqsqtf-card">
    <h1>SQA Teacher Portal Fixture</h1>
    <p>Create the minimum records needed for a teacher to exercise portal classroom operations.</p>
  </section>
  <section class="pqsqtf-card">
    <?php if ($error !== ''): ?>
      <div class="pqsqtf-error"><?php echo s($error); ?></div>
    <?php elseif ($result): ?>
      <div class="pqsqtf-ok">
        Teacher portal fixture ready:
        teacherid=<span class="pqsqtf-code"><?php echo (int)$result['teacherid']; ?></span>,
        studentid=<span class="pqsqtf-code"><?php echo (int)$result['studentid']; ?></span>,
        sessionid=<span class="pqsqtf-code"><?php echo (int)$result['sessionid']; ?></span>,
        assessmentid=<span class="pqsqtf-code"><?php echo (int)$result['assessmentid']; ?></span>.
      </div>
      <pre id="pqsqtf-result"><?php echo s(json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)); ?></pre>
    <?php endif; ?>
    <form method="post">
      <input type="hidden" name="sesskey" value="<?php echo sesskey(); ?>">
      <div class="pqsqtf-grid">
        <div class="pqsqtf-field"><label>Workspace ID</label><input name="workspaceid" value="<?php echo s((string)$workspaceid); ?>"></div>
        <div class="pqsqtf-field"><label>Teacher user ID</label><input name="teacherid" value="<?php echo s((string)$teacherid); ?>"></div>
        <div class="pqsqtf-field"><label>Run ID</label><input name="runid" value="<?php echo s($runid); ?>"></div>
        <div class="pqsqtf-field"><label>Course key</label><input name="coursekey" value="<?php echo s($coursekey); ?>"></div>
        <div class="pqsqtf-field"><label>Student password</label><input name="studentpassword" value="<?php echo s($studentpassword); ?>"></div>
        <div class="pqsqtf-field"><label>Teacher password</label><input name="teacherpassword" value="<?php echo s($teacherpassword); ?>"></div>
      </div>
      <p><button class="pqsqtf-btn" type="submit">Create teacher portal fixture</button></p>
    </form>
  </section>
</main>
<?php
echo $OUTPUT->footer();
