<?php
defined('MOODLE_INTERNAL') || die();

$countrytimezoneoptions = require(__DIR__ . '/country_timezones.php');
$countrycityoptions = require(__DIR__ . '/country_cities.php');

return [
    'course_types' => [
        'pre_quraan' => 'Pre-Quraan',
        'tarbiyah_kids' => 'Tarbiyah Kids',
        'essential_arabic' => 'Essential Arabic',
        'quran_reading' => 'Quran Reading',
        'quran_tafsir' => 'Quran Tafsir',
        'quraan_memorization' => 'Quran Memorization',
    ],
    'countries' => ($countrytimezoneoptions['countries'] ?? []) + ['Other' => 'Other'],
    'cities' => ($countrycityoptions['cities'] ?? []) + ['Other' => 'Other city not listed'],
    'country_cities' => $countrycityoptions['country_cities'] ?? [],
    'timezones' => $countrytimezoneoptions['timezones'] ?? [],
    'country_timezones' => $countrytimezoneoptions['country_timezones'] ?? [],
    'primary_languages' => [
        'Somali' => 'Somali',
        'English' => 'English',
        'Arabic' => 'Arabic',
        'Swahili' => 'Swahili',
        'Other' => 'Other',
    ],
    'other_languages' => [
        'English' => 'English',
        'Arabic' => 'Arabic',
        'Somali' => 'Somali',
        'Swahili' => 'Swahili',
        'French' => 'French',
        'Other' => 'Other',
    ],
    'current_levels' => [
        'level_0' => 'Level 0',
        'level_1' => 'Level 1',
        'level_2' => 'Level 2',
        'level_3' => 'Level 3',
        'level_4' => 'Level 4',
    ],
    'student_access_types' => [
        'managed' => 'Managed Student',
        'unmanaged' => 'Unmanaged Student',
    ],
    'parent_relationships' => [
        'father' => 'Father',
        'mother' => 'Mother',
        'guardian' => 'Guardian',
        'other' => 'Other',
    ],
    'primary_grade_levels' => [
        'nursery' => 'Nursery',
        'kg' => 'KG',
        'grade_1' => 'Grade 1',
        'grade_2' => 'Grade 2',
        'grade_3' => 'Grade 3',
        'grade_4' => 'Grade 4',
        'grade_5' => 'Grade 5',
        'grade_6' => 'Grade 6',
        'grade_7' => 'Grade 7',
        'grade_8' => 'Grade 8',
        'other' => 'Other / not sure',
    ],
    'primary_curricula' => [
        'national' => 'National curriculum',
        'british' => 'British curriculum',
        'american' => 'American curriculum',
        'cambridge' => 'Cambridge',
        'islamic_studies' => 'Islamic studies / madrasa',
        'homeschool' => 'Homeschool',
        'other' => 'Other / not sure',
    ],
    'student_lives_with_options' => [
        'both_parents' => 'Both parents',
        'mother' => 'Mother',
        'father' => 'Father',
        'guardian' => 'Guardian',
        'other' => 'Other',
    ],
    'primary_class_formats' => [
        'online_live' => 'Online live class',
        'in_person' => 'In-person class',
        'hybrid' => 'Hybrid',
        'not_sure' => 'Not sure',
    ],
    'primary_group_sizes' => [
        'one_to_one' => 'One-to-one',
        'small_group' => 'Small group',
        'regular_class' => 'Regular class',
        'not_sure' => 'Not sure',
    ],
    'teacher_gender_preferences' => [
        'no_preference' => 'No preference',
        'female' => 'Female teacher preferred',
        'male' => 'Male teacher preferred',
    ],
    'islamic_program_interests' => [
        'quran_reading' => 'Quran reading',
        'tajweed' => 'Tajweed',
        'hifz_memorization' => 'Hifz / memorization',
        'tafsir' => 'Tafsir',
        'fiqh' => 'Fiqh',
        'aqeedah' => 'Aqeedah',
        'seerah' => 'Seerah',
        'adab' => 'Adab / manners',
        'arabic' => 'Arabic',
    ],
    'quran_reading_levels' => [
        'new_to_arabic' => 'New to Arabic letters',
        'letters_harakat' => 'Letters and harakat',
        'basic_words' => 'Basic words',
        'reads_slowly' => 'Reads slowly',
        'reads_fluently' => 'Reads fluently',
    ],
    'tajweed_levels' => [
        'none' => 'None',
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'memorization_statuses' => [
        'not_started' => 'Not started',
        'short_surahs' => 'Short surahs',
        'juz_amma' => 'Juz Amma',
        'multiple_juz' => 'Multiple juz',
        'hafiz_review' => 'Hafiz / revision',
    ],
    'arabic_reading_abilities' => [
        'none' => 'None',
        'letters' => 'Letters',
        'words' => 'Words',
        'sentences' => 'Sentences',
        'fluent' => 'Fluent',
    ],
    'previous_learning_methods' => [
        'madrasa' => 'Madrasa',
        'online' => 'Online',
        'home_teaching' => 'Home teaching',
        'hybrid' => 'Hybrid',
        'none' => 'None',
    ],
    'tafsir_levels' => [
        'none' => 'None',
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'christian_program_interests' => [
        'bible_studies' => 'Bible studies',
        'christian_foundations' => 'Christian foundations',
        'theology' => 'Theology',
        'discipleship' => 'Discipleship',
        'ministry_training' => 'Ministry training',
        'church_history' => 'Church history',
        'christian_leadership' => 'Christian leadership',
        'other' => 'Other',
    ],
    'bible_reading_levels' => [
        'not_yet_reading' => 'Not yet reading',
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'bible_knowledge_levels' => [
        'none' => 'None',
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'christian_studies_levels' => [
        'none' => 'None',
        'foundation' => 'Foundation',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'christian_previous_learning_methods' => [
        'church_sunday_school' => 'Church or Sunday school',
        'online' => 'Online',
        'home_teaching' => 'Home teaching',
        'christian_school' => 'Christian school',
        'hybrid' => 'Hybrid',
        'none' => 'None',
    ],
    'higher_application_levels' => [
        'certificate' => 'Certificate',
        'diploma' => 'Diploma',
        'undergraduate' => 'Undergraduate',
        'postgraduate_diploma' => 'Postgraduate diploma',
        'masters' => "Master's",
        'doctorate' => 'Doctorate',
        'other' => 'Other',
    ],
    'higher_qualification_levels' => [
        'secondary_school' => 'Secondary school',
        'certificate' => 'Certificate',
        'diploma' => 'Diploma',
        'bachelors' => "Bachelor's degree",
        'postgraduate_diploma' => 'Postgraduate diploma',
        'masters' => "Master's degree",
        'doctorate' => 'Doctorate',
        'other' => 'Other',
    ],
    'higher_academic_statuses' => [
        'completed' => 'Completed',
        'currently_enrolled' => 'Currently enrolled',
        'deferred' => 'Deferred',
        'withdrawn' => 'Withdrawn',
        'other' => 'Other',
    ],
    'higher_admission_routes' => [
        'direct_entry' => 'Direct entry',
        'transfer' => 'Transfer',
        'prior_learning' => 'Recognition of prior learning',
        'international' => 'International applicant',
        'mature' => 'Mature applicant',
        'other' => 'Other',
    ],
    'higher_transfer_credit_options' => [
        'yes' => 'Yes',
        'no' => 'No',
        'not_sure' => 'Not sure',
    ],
    'higher_study_modes' => [
        'regular' => 'Regular',
        'online' => 'Online',
        'hybrid' => 'Hybrid',
    ],
    'higher_study_loads' => [
        'full_time' => 'Full-time',
        'part_time' => 'Part-time',
        'flexible' => 'Flexible',
    ],
    'higher_funding_methods' => [
        'self_funded' => 'Self-funded',
        'government_funded' => 'Government-funded',
        'scholarship' => 'Scholarship',
        'employer_sponsored' => 'Employer-sponsored',
        'other' => 'Other',
        'not_confirmed' => 'Not yet confirmed',
    ],
    'higher_financial_aid_options' => [
        'yes' => 'Yes',
        'no' => 'No',
        'not_sure' => 'Not sure',
    ],
    'technical_programs' => [
        'information_technology' => 'Information technology',
        'electrical_installation' => 'Electrical installation',
        'plumbing' => 'Plumbing',
        'welding_fabrication' => 'Welding and fabrication',
        'automotive_repair' => 'Automotive repair',
        'construction' => 'Construction',
        'carpentry' => 'Carpentry',
        'electronics' => 'Electronics',
        'refrigeration_air_conditioning' => 'Refrigeration and air conditioning',
        'tailoring_garment_making' => 'Tailoring and garment making',
        'hospitality_catering' => 'Hospitality and catering',
        'agriculture' => 'Agriculture',
        'other' => 'Other',
    ],
    'technical_training_levels' => [
        'foundation' => 'Foundation',
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
        'refresher' => 'Refresher',
    ],
    'technical_experience_types' => [
        'none' => 'None',
        'informal_self_taught' => 'Informal or self-taught',
        'apprenticeship' => 'Apprenticeship',
        'previous_course' => 'Previous training course',
        'work_experience' => 'Work experience',
        'other' => 'Other',
    ],
    'technical_learning_methods' => [
        'training_centre' => 'Training centre',
        'workplace_apprenticeship' => 'Workplace or apprenticeship',
        'online' => 'Online',
        'home_self_study' => 'Home or self-study',
        'hybrid' => 'Hybrid',
        'none' => 'None',
    ],
    'technical_experience_durations' => [
        'none' => 'None',
        'under_6_months' => 'Less than 6 months',
        '6_12_months' => '6-12 months',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        'over_5_years' => 'More than 5 years',
    ],
    'technical_employment_statuses' => [
        'not_employed' => 'Not employed',
        'employed_in_field' => 'Employed in this field',
        'employed_other_field' => 'Employed in another field',
        'self_employed' => 'Self-employed',
        'apprentice_intern' => 'Apprentice or intern',
        'student' => 'Student',
    ],
    'technical_training_goals' => [
        'gain_employment' => 'Gain employment',
        'start_business' => 'Start a business',
        'improve_job_skills' => 'Improve current job skills',
        'obtain_certification' => 'Obtain certification',
        'prepare_apprenticeship' => 'Prepare for an apprenticeship',
        'personal_development' => 'Personal development',
        'other' => 'Other',
    ],
    'technical_training_formats' => [
        'classroom' => 'Classroom',
        'workshop_practical' => 'Workshop or practical',
        'online' => 'Online',
        'hybrid' => 'Hybrid',
        'workplace_based' => 'Workplace-based',
    ],
    'technical_training_schedules' => [
        'weekdays' => 'Weekdays',
        'evenings' => 'Evenings',
        'weekends' => 'Weekends',
        'flexible' => 'Flexible',
    ],
    'technical_tool_access_options' => [
        'full' => 'Full access',
        'partial' => 'Partial access',
        'none' => 'No access',
        'not_sure' => 'Not sure what is required',
    ],
    'technical_digital_skill_levels' => [
        'none' => 'None',
        'basic' => 'Basic',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'technical_yes_no_unsure' => [
        'yes' => 'Yes',
        'no' => 'No',
        'not_sure' => 'Not sure',
    ],
    'technical_protective_equipment_options' => [
        'yes' => 'Yes',
        'partially' => 'Partially',
        'no' => 'No',
        'not_applicable' => 'Not applicable',
    ],
    'professional_development_areas' => [
        'leadership_management' => 'Leadership and management',
        'project_management' => 'Project management',
        'communication' => 'Communication',
        'information_technology' => 'Information technology',
        'data_analytics' => 'Data and analytics',
        'finance_accounting' => 'Finance and accounting',
        'human_resources' => 'Human resources',
        'sales_marketing' => 'Sales and marketing',
        'education_training' => 'Education and training',
        'healthcare' => 'Healthcare',
        'entrepreneurship' => 'Entrepreneurship',
        'compliance_governance' => 'Compliance and governance',
        'other' => 'Other',
    ],
    'professional_industries' => [
        'government' => 'Government',
        'nonprofit' => 'Nonprofit',
        'education' => 'Education',
        'healthcare' => 'Healthcare',
        'finance' => 'Finance',
        'technology' => 'Technology',
        'construction' => 'Construction',
        'retail_commerce' => 'Retail and commerce',
        'hospitality' => 'Hospitality',
        'manufacturing' => 'Manufacturing',
        'agriculture' => 'Agriculture',
        'other' => 'Other',
    ],
    'professional_employment_statuses' => [
        'employed_full_time' => 'Employed full-time',
        'employed_part_time' => 'Employed part-time',
        'self_employed' => 'Self-employed',
        'business_owner' => 'Business owner',
        'consultant_freelancer' => 'Consultant or freelancer',
        'intern_trainee' => 'Intern or trainee',
        'seeking_employment' => 'Seeking employment',
        'not_employed' => 'Not currently employed',
    ],
    'professional_experience_ranges' => [
        'under_1_year' => 'Less than 1 year',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        '6_10_years' => '6-10 years',
        'over_10_years' => 'More than 10 years',
    ],
    'professional_responsibility_levels' => [
        'entry_level' => 'Entry level',
        'individual_contributor' => 'Individual contributor',
        'supervisor' => 'Supervisor',
        'manager' => 'Manager',
        'senior_manager' => 'Senior manager',
        'executive_director' => 'Executive or director',
        'business_owner' => 'Business owner',
        'other' => 'Other',
    ],
    'professional_development_goals' => [
        'improve_job_performance' => 'Improve current job performance',
        'prepare_promotion' => 'Prepare for promotion',
        'change_career' => 'Change career',
        'gain_certification' => 'Gain certification',
        'develop_leadership' => 'Develop leadership skills',
        'start_grow_business' => 'Start or grow a business',
        'return_employment' => 'Return to employment',
        'personal_development' => 'Personal development',
        'other' => 'Other',
    ],
    'professional_skill_levels' => [
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
        'expert' => 'Expert',
        'not_sure' => 'Not sure',
    ],
    'professional_learning_formats' => [
        'instructor_classroom' => 'Instructor-led classroom',
        'live_online' => 'Live online',
        'self_paced_online' => 'Self-paced online',
        'coaching_mentoring' => 'Coaching or mentoring',
        'workshop' => 'Workshop',
        'hybrid' => 'Hybrid',
    ],
    'professional_learning_schedules' => [
        'weekdays' => 'Weekdays',
        'evenings' => 'Evenings',
        'weekends' => 'Weekends',
        'flexible' => 'Flexible',
    ],
    'professional_course_intensities' => [
        'short_intensive' => 'Short intensive',
        'weekly_sessions' => 'Weekly sessions',
        'part_time_extended' => 'Part-time extended',
        'self_paced' => 'Self-paced',
        'flexible' => 'Flexible',
    ],
    'professional_sponsorship_options' => [
        'yes' => 'Yes',
        'no' => 'No',
        'under_consideration' => 'Under consideration',
    ],
    'professional_cpd_options' => [
        'yes' => 'Yes',
        'no' => 'No',
        'not_sure' => 'Not sure',
    ],
    'adult_learning_areas' => [
        'adult_literacy' => 'Adult literacy',
        'numeracy' => 'Numeracy',
        'language_learning' => 'Language learning',
        'digital_literacy' => 'Digital literacy',
        'secondary_completion' => 'Secondary education completion',
        'basic_vocational_skills' => 'Basic vocational skills',
        'life_skills' => 'Life skills',
        'financial_literacy' => 'Financial literacy',
        'citizenship_civic' => 'Citizenship or civic education',
        'personal_enrichment' => 'Personal enrichment',
        'other' => 'Other',
    ],
    'adult_education_levels' => [
        'no_formal_education' => 'No formal education',
        'primary' => 'Primary education',
        'lower_secondary' => 'Lower secondary',
        'upper_secondary' => 'Upper secondary',
        'certificate' => 'Certificate',
        'diploma' => 'Diploma',
        'degree_or_higher' => 'Degree or higher',
        'other' => 'Other',
    ],
    'adult_literacy_levels' => [
        'not_yet_reading_writing' => 'Not yet reading or writing',
        'letters_simple_words' => 'Recognises letters or simple words',
        'simple_sentences' => 'Reads and writes simple sentences',
        'independent' => 'Reads and writes independently',
        'advanced' => 'Advanced',
        'not_sure' => 'Not sure',
    ],
    'adult_numeracy_levels' => [
        'not_yet_numbers' => 'Not yet working with numbers',
        'basic_counting' => 'Basic counting',
        'basic_arithmetic' => 'Basic arithmetic',
        'everyday_calculations' => 'Everyday calculations',
        'advanced' => 'Advanced',
        'not_sure' => 'Not sure',
    ],
    'adult_digital_skill_levels' => [
        'none' => 'None',
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'adult_previous_experiences' => [
        'none' => 'None',
        'community_centre' => 'Community learning centre',
        'school_college' => 'School or college',
        'workplace_training' => 'Workplace training',
        'online_learning' => 'Online learning',
        'home_self_study' => 'Home or self-study',
        'other' => 'Other',
    ],
    'adult_learning_methods' => [
        'classroom' => 'Classroom',
        'community_centre' => 'Community centre',
        'online' => 'Online',
        'home_teaching' => 'Home teaching',
        'self_study' => 'Self-study',
        'hybrid' => 'Hybrid',
        'none' => 'None',
    ],
    'adult_learning_goals' => [
        'improve_literacy' => 'Improve reading and writing',
        'improve_numeracy' => 'Improve numeracy',
        'learn_language' => 'Learn a language',
        'gain_digital_skills' => 'Gain digital skills',
        'complete_school' => 'Complete school-level education',
        'prepare_employment' => 'Prepare for employment',
        'support_business' => 'Support a business',
        'personal_development' => 'Personal development',
        'other' => 'Other',
    ],
    'adult_employment_statuses' => [
        'employed_full_time' => 'Employed full-time',
        'employed_part_time' => 'Employed part-time',
        'self_employed' => 'Self-employed',
        'unemployed_seeking' => 'Unemployed and seeking work',
        'not_seeking' => 'Not currently seeking work',
        'retired' => 'Retired',
        'homemaker_caregiver' => 'Homemaker or caregiver',
        'student' => 'Student',
    ],
    'adult_learning_formats' => [
        'classroom' => 'Classroom',
        'live_online' => 'Live online',
        'self_paced_online' => 'Self-paced online',
        'community_based' => 'Community-based',
        'home_based' => 'Home-based',
        'hybrid' => 'Hybrid',
    ],
    'adult_learning_paces' => [
        'intensive' => 'Intensive',
        'regular' => 'Regular',
        'slow_supported' => 'Slow and supported',
        'self_paced' => 'Self-paced',
        'flexible' => 'Flexible',
    ],
    'adult_class_arrangements' => [
        'one_to_one' => 'One-to-one',
        'small_group' => 'Small group',
        'regular_group' => 'Regular group',
        'no_preference' => 'No preference',
    ],
    'adult_childcare_options' => [
        'yes' => 'Yes',
        'no' => 'No',
        'sometimes' => 'Sometimes',
        'prefer_not_say' => 'Prefer not to say',
    ],
    'adult_attendance_impact_options' => [
        'yes' => 'Yes',
        'no' => 'No',
        'sometimes' => 'Sometimes',
    ],
    'adult_access_limitations' => [
        'none' => 'None',
        'transport' => 'Transport limitation',
        'internet' => 'Internet limitation',
        'device' => 'Device limitation',
        'multiple' => 'Multiple limitations',
        'prefer_not_say' => 'Prefer not to say',
    ],
    'adult_learning_confidence_levels' => [
        'very_low' => 'Very low',
        'low' => 'Low',
        'moderate' => 'Moderate',
        'high' => 'High',
        'very_high' => 'Very high',
    ],
    'tajweed_sub_levels' => [
        'beginner' => 'Beginner',
        'middle' => 'Middle',
        'advanced' => 'Advanced',
    ],
    'level_definitions' => [
        'pre_quraan' => [
            'level_0' => 'New to Arabic letters, sounds, or harakat.',
            'level_1' => 'Can recognize, pronounce, and write the Arabic alphabet.',
            'level_2' => 'Can write 2 joined letters, 3 joined letters, 4 joined letters, and 5 joined letters.',
            'level_3' => 'Tajweed level - Beginner, Middle, or Advanced.',
            'level_4' => 'Can read simple Arabic words and is preparing to read the Quran fluently.',
        ],
        'tarbiyah_kids' => [
            'level 1' => 'Needs basic Islamic manners, habits, stories, and daily routines.',
            'level 2' => 'Understands simple values and can discuss guided stories or examples.',
            'level 3' => 'Can reflect on manners, choices, and Islamic values with more independence.',
        ],
        'essential_arabic' => [
            'level 1' => 'Beginning Arabic letters, sounds, basic words, and simple writing.',
            'level 2' => 'Can read and write simple words and is building vocabulary and sentences.',
            'level 3' => 'Can read short passages and is developing comprehension and expression.',
        ],
        'quran_reading' => [
            'level 1' => 'Can read short Arabic or Quran words with support.',
            'level 2' => 'Can read short passages but needs fluency, correction, and confidence.',
            'level 3' => 'Reads longer passages and needs tajweed, pace, and consistency support.',
        ],
        'quran_tafsir' => [
            'level 1' => 'Ready for simple meanings, vocabulary, stories, and guided reflection.',
            'level 2' => 'Can discuss short surahs or themes with teacher guidance.',
            'level 3' => 'Can connect meanings, lessons, and reflections across longer passages.',
        ],
        'quraan_memorization' => [
            'level 1' => 'Starting short surahs or needs a first memorization routine.',
            'level 2' => 'Has memorized some surahs and needs revision structure and listening.',
            'level 3' => 'Has ongoing memorization and needs stronger retention, review, and targets.',
        ],
    ],
    'learning_bases' => [
        'new learner' => 'New learner',
        'some_prior_learning' => 'Some prior learning',
        'can_read_basic_arabic' => 'Can read basic Arabic',
        'can_write_basic_arabic' => 'Can write basic Arabic',
        'can_understand_basic_arabic' => 'Can understand basic Arabic',
        'needs assessment' => 'Needs assessment',
    ],
    'availability_days' => [
        'mon' => 'Monday',
        'tue' => 'Tuesday',
        'wed' => 'Wednesday',
        'thu' => 'Thursday',
        'fri' => 'Friday',
        'sat' => 'Saturday',
        'sun' => 'Sunday',
    ],
    'availability_time_windows' => [
        '08:00' => '8:00 AM',
        '09:00' => '9:00 AM',
        '10:00' => '10:00 AM',
        '11:00' => '11:00 AM',
        '12:00' => '12:00 PM',
        '13:00' => '1:00 PM',
        '14:00' => '2:00 PM',
        '15:00' => '3:00 PM',
        '16:00' => '4:00 PM',
        '17:00' => '5:00 PM',
        '18:00' => '6:00 PM',
        '19:00' => '7:00 PM',
        '20:00' => '8:00 PM',
        '21:00' => '9:00 PM',
        '22:00' => '10:00 PM',
    ],
    'session_counts' => [
        '1' => '1 session per week',
        '2' => '2 sessions per week',
        '3' => '3 sessions per week',
        '4' => '4 sessions per week',
        '5' => '5 sessions per week',
        '6' => '6 sessions per week',
    ],
];
