<?php
defined('MOODLE_INTERNAL') || die();

$countrytimezoneoptions = require(__DIR__ . '/country_timezones.php');
$countrycityoptions = require(__DIR__ . '/country_cities.php');

return [
    'teacher_work_models' => [
        'independent_teacher' => 'Independent teacher/tutor',
        'marketplace_teacher' => 'Marketplace teacher/tutor',
    ],
    'preferred_contact_methods' => [
        'email' => 'Email',
        'phone' => 'Phone',
        'whatsapp' => 'WhatsApp',
    ],
    'teaching_experience_ranges' => [
        'none' => 'No formal experience',
        'under_1_year' => 'Less than 1 year',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        '6_10_years' => '6-10 years',
        'over_10_years' => 'More than 10 years',
    ],
    'teacher_qualification_levels' => [
        'secondary' => 'Secondary education',
        'certificate' => 'Certificate',
        'diploma' => 'Diploma',
        'bachelors' => "Bachelor's degree",
        'postgraduate_diploma' => 'Postgraduate diploma',
        'masters' => "Master's degree",
        'doctorate' => 'Doctorate',
        'other' => 'Other',
    ],
    'preferred_teaching_formats' => [
        'in_person' => 'In person',
        'live_online' => 'Live online',
        'hybrid' => 'Hybrid',
        'no_preference' => 'No preference',
    ],
    'preferred_learner_arrangements' => [
        'one_to_one' => 'One-to-one',
        'small_group' => 'Small group',
        'regular_group' => 'Regular group',
        'no_preference' => 'No preference',
    ],
    'technology_readiness_options' => [
        'fully_ready' => 'Fully ready',
        'partially_ready' => 'Partially ready',
        'support_required' => 'Support required',
        'not_applicable' => 'Not applicable',
    ],
    'professional_reference_options' => [
        'yes' => 'Yes',
        'no' => 'No',
        'later' => 'Can provide later',
    ],
    'primary_teacher_grade_levels' => [
        'early_years' => 'Early years / pre-primary',
        'grade_1' => 'Grade 1',
        'grade_2' => 'Grade 2',
        'grade_3' => 'Grade 3',
        'grade_4' => 'Grade 4',
        'grade_5' => 'Grade 5',
        'grade_6' => 'Grade 6',
        'upper_primary' => 'Upper primary / equivalent',
    ],
    'primary_teacher_curricula' => [
        'national' => 'National curriculum',
        'british' => 'British curriculum',
        'american' => 'American curriculum',
        'ib' => 'International Baccalaureate',
        'montessori' => 'Montessori',
        'cambridge' => 'Cambridge',
        'homeschool' => 'Homeschool curriculum',
        'other' => 'Other',
    ],
    'primary_classroom_management_levels' => [
        'beginner' => 'Beginner',
        'competent' => 'Competent',
        'experienced' => 'Experienced',
        'advanced' => 'Advanced',
    ],
    'primary_safeguarding_statuses' => [
        'completed' => 'Training completed',
        'expired' => 'Completed but needs renewal',
        'willing' => 'Not completed; willing to complete',
        'not_completed' => 'Not completed',
    ],
    'primary_parent_communication_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'regular' => 'Regular communication experience',
        'advanced' => 'Advanced parent partnership experience',
    ],
    'primary_learning_support_levels' => [
        'none' => 'No experience',
        'basic' => 'Basic experience',
        'moderate' => 'Moderate experience',
        'extensive' => 'Extensive experience',
    ],
    'primary_assessment_experience_options' => [
        'none' => 'No experience',
        'basic' => 'Basic lesson planning or assessment',
        'competent' => 'Competent',
        'advanced' => 'Advanced',
    ],
    'primary_background_check_statuses' => [
        'current' => 'Current background check available',
        'expired' => 'Expired or needs renewal',
        'willing' => 'Willing to complete',
        'not_available' => 'Not currently available',
    ],
    'higher_teacher_academic_ranks' => [
        'teaching_assistant' => 'Teaching assistant',
        'instructor' => 'Instructor',
        'lecturer' => 'Lecturer',
        'senior_lecturer' => 'Senior lecturer',
        'assistant_professor' => 'Assistant professor',
        'associate_professor' => 'Associate professor',
        'professor' => 'Professor',
        'industry_practitioner' => 'Industry practitioner / adjunct',
        'other' => 'Other',
    ],
    'higher_teacher_disciplines' => [
        'arts_humanities' => 'Arts and humanities',
        'business_management' => 'Business and management',
        'computer_science_it' => 'Computer science and IT',
        'education' => 'Education',
        'engineering' => 'Engineering',
        'health_sciences' => 'Health sciences',
        'law' => 'Law',
        'natural_sciences' => 'Natural sciences',
        'social_sciences' => 'Social sciences',
        'other' => 'Other',
    ],
    'higher_teacher_experience_levels' => [
        'none' => 'No higher-education teaching experience',
        'under_1_year' => 'Less than 1 year',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        '6_10_years' => '6-10 years',
        'over_10_years' => 'More than 10 years',
    ],
    'higher_teacher_research_levels' => [
        'none' => 'No research experience',
        'limited' => 'Limited experience',
        'active' => 'Active researcher',
        'experienced' => 'Experienced researcher',
        'research_lead' => 'Research lead / principal investigator',
    ],
    'higher_teacher_supervision_levels' => [
        'undergraduate_projects' => 'Undergraduate projects',
        'postgraduate_diploma' => 'Postgraduate diploma',
        'masters' => "Master's research",
        'doctorate' => 'Doctoral research',
        'none' => 'No supervision experience',
    ],
    'higher_teacher_course_design_levels' => [
        'none' => 'No experience',
        'contributor' => 'Course contributor',
        'designer' => 'Course designer',
        'programme_lead' => 'Programme or curriculum lead',
    ],
    'higher_teacher_assessment_levels' => [
        'basic' => 'Basic assessment experience',
        'competent' => 'Competent',
        'advanced' => 'Advanced',
        'external_examiner' => 'External examiner / moderator',
    ],
    'higher_teacher_accreditation_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'programme_review' => 'Programme review experience',
        'accreditation_lead' => 'Accreditation or quality-assurance lead',
    ],
    'technical_teacher_trades' => [
        'information_technology' => 'Information technology',
        'electrical_installation' => 'Electrical installation',
        'plumbing' => 'Plumbing',
        'welding_fabrication' => 'Welding and fabrication',
        'automotive_repair' => 'Automotive repair',
        'construction' => 'Construction',
        'carpentry' => 'Carpentry',
        'electronics' => 'Electronics',
        'refrigeration_air_conditioning' => 'Refrigeration and air conditioning',
        'tailoring_garment_making' => 'Tailoring and garment making',
        'hospitality_catering' => 'Hospitality and catering',
        'agriculture' => 'Agriculture',
        'other' => 'Other',
    ],
    'technical_teacher_industry_experience' => [
        'under_1_year' => 'Less than 1 year',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        '6_10_years' => '6-10 years',
        'over_10_years' => 'More than 10 years',
    ],
    'technical_teacher_practical_levels' => [
        'basic' => 'Basic',
        'competent' => 'Competent',
        'advanced' => 'Advanced',
        'master_trainer' => 'Master trainer / expert',
    ],
    'technical_teacher_safety_statuses' => [
        'current' => 'Current safety certification',
        'expired' => 'Expired or needs renewal',
        'willing' => 'Willing to complete required training',
        'none' => 'No current certification',
        'not_applicable' => 'Not applicable to this trade',
    ],
    'technical_teacher_supervision_levels' => [
        'none' => 'No experience',
        'assistant' => 'Assistant supervisor',
        'supervisor' => 'Apprenticeship supervisor',
        'programme_lead' => 'Apprenticeship programme lead',
    ],
    'technical_teacher_assessment_levels' => [
        'none' => 'No experience',
        'basic' => 'Basic practical assessment',
        'competent' => 'Competent assessor',
        'certified_assessor' => 'Certified competency assessor',
    ],
    'technical_teacher_workplace_training_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'regular' => 'Regular workplace training experience',
        'advanced' => 'Advanced workplace-training leadership',
    ],
    'adult_teacher_learning_areas' => [
        'adult_literacy' => 'Adult literacy',
        'numeracy' => 'Numeracy',
        'language_learning' => 'Language learning',
        'digital_literacy' => 'Digital literacy',
        'secondary_completion' => 'Secondary education completion',
        'basic_vocational_skills' => 'Basic vocational skills',
        'life_skills' => 'Life skills',
        'financial_literacy' => 'Financial literacy',
        'citizenship_civic' => 'Citizenship or civic education',
        'personal_enrichment' => 'Personal enrichment',
        'other' => 'Other',
    ],
    'adult_teacher_experience_levels' => [
        'none' => 'No formal adult-learning experience',
        'under_1_year' => 'Less than 1 year',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        '6_10_years' => '6-10 years',
        'over_10_years' => 'More than 10 years',
    ],
    'adult_teacher_instruction_levels' => [
        'none' => 'No experience',
        'basic' => 'Basic experience',
        'competent' => 'Competent',
        'advanced' => 'Advanced',
    ],
    'adult_teacher_facilitation_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'regular' => 'Regular facilitation experience',
        'advanced' => 'Advanced facilitator / trainer',
    ],
    'adult_teacher_learner_support_levels' => [
        'none' => 'No experience',
        'basic' => 'Basic learner support',
        'competent' => 'Competent learner support',
        'advanced' => 'Advanced learner-support practice',
    ],
    'adult_teacher_community_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'regular' => 'Regular community outreach',
        'programme_lead' => 'Community programme lead',
    ],
    'adult_teacher_barrier_support_levels' => [
        'none' => 'No experience',
        'basic' => 'Basic support experience',
        'competent' => 'Competent',
        'advanced' => 'Advanced support and referral experience',
    ],
    'professional_teacher_areas' => [
        'leadership_management' => 'Leadership and management',
        'project_management' => 'Project management',
        'communication' => 'Communication',
        'information_technology' => 'Information technology',
        'data_analytics' => 'Data and analytics',
        'finance_accounting' => 'Finance and accounting',
        'human_resources' => 'Human resources',
        'sales_marketing' => 'Sales and marketing',
        'education_training' => 'Education and training',
        'healthcare' => 'Healthcare',
        'entrepreneurship' => 'Entrepreneurship',
        'compliance_governance' => 'Compliance and governance',
        'other' => 'Other',
    ],
    'professional_teacher_industry_experience' => [
        'under_1_year' => 'Less than 1 year',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        '6_10_years' => '6-10 years',
        'over_10_years' => 'More than 10 years',
    ],
    'professional_teacher_responsibility_levels' => [
        'individual_contributor' => 'Individual contributor',
        'supervisor' => 'Supervisor',
        'manager' => 'Manager',
        'senior_manager' => 'Senior manager',
        'executive_director' => 'Executive or director',
        'consultant' => 'Consultant or specialist',
        'business_owner' => 'Business owner',
        'other' => 'Other',
    ],
    'professional_teacher_facilitation_levels' => [
        'beginner' => 'Beginner facilitator',
        'competent' => 'Competent facilitator',
        'advanced' => 'Advanced facilitator',
        'master_trainer' => 'Master trainer / train-the-trainer lead',
    ],
    'professional_teacher_coaching_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'regular' => 'Regular coaching or mentoring',
        'advanced' => 'Advanced coach or mentor',
    ],
    'professional_teacher_corporate_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'regular' => 'Regular organisational training',
        'programme_lead' => 'Corporate learning programme lead',
    ],
    'professional_teacher_cpd_levels' => [
        'none' => 'No experience',
        'content_provider' => 'CPD content provider',
        'accredited_facilitator' => 'Accredited facilitator',
        'programme_accreditation' => 'Programme accreditation experience',
    ],
    'professional_teacher_outcome_levels' => [
        'basic' => 'Basic feedback and evaluation',
        'competent' => 'Competent outcome measurement',
        'advanced' => 'Advanced workplace-impact evaluation',
        'evaluation_lead' => 'Learning evaluation lead',
    ],
    'islamic_teacher_subjects' => [
        'quran_reading' => 'Quran reading',
        'tajweed' => 'Tajweed',
        'hifz' => 'Hifz / memorisation',
        'tafsir' => 'Tafsir',
        'fiqh' => 'Fiqh',
        'aqeedah' => 'Aqeedah',
        'seerah' => 'Seerah',
        'arabic' => 'Arabic',
        'islamic_manners' => 'Islamic manners and character',
    ],
    'christian_teacher_subjects' => [
        'bible_studies' => 'Bible studies',
        'christian_foundations' => 'Christian foundations',
        'theology' => 'Theology',
        'discipleship' => 'Discipleship',
        'ministry_training' => 'Ministry training',
        'church_history' => 'Church history',
        'christian_leadership' => 'Christian leadership',
    ],
    'hindu_teacher_subjects' => [
        'hindu_scriptures' => 'Hindu scriptures',
        'philosophy' => 'Hindu philosophy',
        'ethics_values' => 'Ethics and values',
        'devotional_practice' => 'Devotional practice',
        'sanskrit' => 'Sanskrit',
        'history_traditions' => 'History and traditions',
        'community_leadership' => 'Community leadership',
    ],
    'faith_teacher_experience_levels' => [
        'under_1_year' => 'Less than 1 year',
        '1_2_years' => '1-2 years',
        '3_5_years' => '3-5 years',
        '6_10_years' => '6-10 years',
        'over_10_years' => 'More than 10 years',
    ],
    'faith_teacher_proficiency_levels' => [
        'foundation' => 'Foundation',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
        'scholar_teacher' => 'Scholar / specialist teacher',
    ],
    'faith_teacher_interpretation_levels' => [
        'none' => 'No formal experience',
        'foundation' => 'Foundation',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
    ],
    'faith_teacher_language_levels' => [
        'none' => 'None',
        'basic' => 'Basic',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
        'fluent' => 'Fluent',
    ],
    'faith_teacher_practice_levels' => [
        'none' => 'No formal experience',
        'basic' => 'Basic',
        'competent' => 'Competent',
        'advanced' => 'Advanced',
    ],
    'faith_teacher_community_levels' => [
        'none' => 'No experience',
        'limited' => 'Limited experience',
        'regular' => 'Regular community teaching',
        'leader' => 'Community or programme leader',
    ],
    'faith_teacher_reference_options' => [
        'available' => 'Faith-community reference available',
        'later' => 'Can provide later',
        'not_available' => 'Not currently available',
    ],
    'service_modes' => [
        'one_to_one_tutoring' => 'One-to-one tutoring',
        'small_group_classes' => 'Small group classes',
        'school_classes' => 'School classes',
        'live_online' => 'Live online teaching',
        'in_person' => 'In-person teaching',
        'recorded_content' => 'Recorded lessons/content',
        'homework_support' => 'Homework support',
        'assessment_placement' => 'Assessment/placement',
    ],
    'subject_areas' => [
        'languages' => 'Languages',
        'math' => 'Math',
        'science' => 'Science',
        'social_science' => 'Social Science',
        'technology' => 'Technology',
        'homeschool_support' => 'Homeschool Support',
        'tvet' => 'Technical & Vocational Education (TVET)',
        'special_needs_support' => 'Special Needs / Learning Support',
        'other_subjects' => 'Other subjects',
        'test_preparation' => 'Test preparation',
    ],
    'subject_languages' => [
        'english' => 'English',
        'arabic' => 'Arabic',
        'french' => 'French',
        'spanish' => 'Spanish',
        'swahili' => 'Swahili',
        'somali' => 'Somali',
        'amharic' => 'Amharic',
        'other' => 'Other',
    ],
    'age_groups' => [
        'early_childhood' => 'Early childhood',
        'primary_elementary' => 'Primary / elementary',
        'middle_school' => 'Middle school',
        'high_school' => 'High school',
        'university' => 'University',
        'tvet' => 'TVET',
        'adults' => 'Adults',
    ],
    'general_levels' => [
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
        'mixed_level' => 'Mixed level',
        'needs_assessment' => 'Needs assessment',
    ],
    'course_types' => [
        'pre_quraan' => 'Pre-Quraan',
        'tarbiyah_kids' => 'Tarbiyah Kids',
        'essential_arabic' => 'Essential Arabic',
        'quran_reading' => 'Quran Reading',
        'quran_tafsir' => 'Quran Tafsir',
        'quraan_memorization' => 'Quran Memorization',
    ],
    'countries' => ($countrytimezoneoptions['countries'] ?? []) + ['Other' => 'Other'],
    'cities' => ($countrycityoptions['cities'] ?? []) + ['Other' => 'Other city not listed'],
    'country_cities' => $countrycityoptions['country_cities'] ?? [],
    'timezones' => $countrytimezoneoptions['timezones'] ?? [],
    'country_timezones' => $countrytimezoneoptions['country_timezones'] ?? [],
    'primary_languages' => [
        'Somali' => 'Somali',
        'English' => 'English',
        'Arabic' => 'Arabic',
        'Swahili' => 'Swahili',
        'Other' => 'Other',
    ],
    'other_languages' => [
        'English' => 'English',
        'Arabic' => 'Arabic',
        'Somali' => 'Somali',
        'Swahili' => 'Swahili',
        'French' => 'French',
        'Other' => 'Other',
    ],
    'current_levels' => [
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
        'mixed_level' => 'Mixed level',
        'needs_assessment' => 'Needs assessment',
    ],
    'availability_days' => [
        'mon' => 'Monday',
        'tue' => 'Tuesday',
        'wed' => 'Wednesday',
        'thu' => 'Thursday',
        'fri' => 'Friday',
        'sat' => 'Saturday',
        'sun' => 'Sunday',
    ],
    'availability_slot_minutes' => 120,
    'availability_time_windows' => [
        '00:00' => '2:00 AM',
        '02:00' => '4:00 AM',
        '04:00' => '6:00 AM',
        '06:00' => '8:00 AM',
        '08:00' => '10:00 AM',
        '10:00' => '12:00 PM',
        '12:00' => '14:00 PM',
        '14:00' => '16:00 PM',
        '16:00' => '18:00 PM',
        '18:00' => '20:00 PM',
        '20:00' => '22:00 PM',
        '22:00' => '24:00 PM',
    ],
    'session_counts' => [
        '1' => '1 session per week',
        '2' => '2 sessions per week',
        '3' => '3 sessions per week',
        '4' => '4 sessions per week',
        '5' => '5 sessions per week',
        '6' => '6 sessions per week',
    ],
];
