-- Somali University: student profiles for pickers and portals
-- Run AFTER workspace-link.sql. MySQL/MariaDB. Prefix from DB_PREFIX (mdlgx_).
-- Safe to re-run (skips users that already have a profile). If an insert
-- fails with "Unknown column", remove that column and its value, re-run.

SET @workspaceid := 15;

START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_su_profiles;
CREATE TEMPORARY TABLE tmp_su_profiles (
  username VARCHAR(100) PRIMARY KEY,
  display_name VARCHAR(255),
  age INT,
  gender VARCHAR(20),
  city VARCHAR(120),
  course_type VARCHAR(255)
);
INSERT INTO tmp_su_profiles (username, display_name, age, gender, city, course_type) VALUES
('su-student001','Liban Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student002','Yusuf Farah',undefined,'undefined','undefined','Academic English I'),
('su-student003','Zahra Ismail',undefined,'undefined','undefined','Academic English I'),
('su-student004','Layla Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student005','Bashir Duale',undefined,'undefined','undefined','Arabic Language I'),
('su-student006','Hamdi Egal',undefined,'undefined','undefined','Principles of Economics I'),
('su-student007','Farah Farah',undefined,'undefined','undefined','Introduction to Computing'),
('su-student008','Hodan Nuur',undefined,'undefined','undefined','Academic English I'),
('su-student009','Jamal Guleed',undefined,'undefined','undefined','University Mathematics I'),
('su-student010','Yasmin Samatar',undefined,'undefined','undefined','Introduction to Computing'),
('su-student011','Rahma Hersi',undefined,'undefined','undefined','Arabic Language I'),
('su-student012','Hibo Hassan',undefined,'undefined','undefined','University Mathematics I'),
('su-student013','Jawahir Elmi',undefined,'undefined','undefined','University Mathematics I'),
('su-student014','Hibo Osman',undefined,'undefined','undefined','Introduction to Computing'),
('su-student015','Abdullahi Hussein',undefined,'undefined','undefined','Introduction to Computing'),
('su-student016','Hamdi Ali',undefined,'undefined','undefined','Arabic Language I'),
('su-student017','Nur Samatar',undefined,'undefined','undefined','Introduction to Computing'),
('su-student018','Rahma Elmi',undefined,'undefined','undefined','Academic English I'),
('su-student019','Maryan Hassan',undefined,'undefined','undefined','Arabic Language I'),
('su-student020','Iman Aden',undefined,'undefined','undefined','Principles of Economics I'),
('su-student021','Khadija Mohamed',undefined,'undefined','undefined','University Mathematics I'),
('su-student022','Yasmin Ismail',undefined,'undefined','undefined','Principles of Economics I'),
('su-student023','Ifrah Samatar',undefined,'undefined','undefined','Arabic Language I'),
('su-student024','Hodan Egal',undefined,'undefined','undefined','Academic English I'),
('su-student025','Rahma Egal',undefined,'undefined','undefined','Academic English I'),
('su-student026','Dahir Samatar',undefined,'undefined','undefined','Principles of Economics I'),
('su-student027','Yasmin Egal',undefined,'undefined','undefined','Academic English I'),
('su-student028','Mustaf Awale',undefined,'undefined','undefined','Arabic Language I'),
('su-student029','Abdullahi Farah',undefined,'undefined','undefined','Introduction to Computing'),
('su-student030','Sahra Osman',undefined,'undefined','undefined','University Mathematics I'),
('su-student031','Khalid Barre',undefined,'undefined','undefined','Introduction to Computing'),
('su-student032','Sharmarke Sheikh',undefined,'undefined','undefined','University Mathematics I'),
('su-student033','Amina Elmi',undefined,'undefined','undefined','Academic English I'),
('su-student034','Ubax Isse',undefined,'undefined','undefined','Academic English I'),
('su-student035','Jamal Jama',undefined,'undefined','undefined','Introduction to Computing'),
('su-student036','Liban Farah',undefined,'undefined','undefined','Academic English I'),
('su-student037','Yasmin Farah',undefined,'undefined','undefined','Arabic Language I'),
('su-student038','Omar Sheikh',undefined,'undefined','undefined','Principles of Economics I'),
('su-student039','Farhiya Nuur',undefined,'undefined','undefined','Principles of Economics I'),
('su-student040','Filsan Jama',undefined,'undefined','undefined','Arabic Language I'),
('su-student041','Omar Egal',undefined,'undefined','undefined','Academic English I'),
('su-student042','Mohamed Hussein',undefined,'undefined','undefined','Academic English I'),
('su-student043','Khadija Barre',undefined,'undefined','undefined','Arabic Language I'),
('su-student044','Elmi Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student045','Filsan Samatar',undefined,'undefined','undefined','Arabic Language I'),
('su-student046','Mohamed Barre',undefined,'undefined','undefined','Academic English I'),
('su-student047','Nimco Abdi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student048','Jawahir Mire',undefined,'undefined','undefined','Principles of Economics I'),
('su-student049','Sagal Mohamed',undefined,'undefined','undefined','Principles of Economics I'),
('su-student050','Sharmarke Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student051','Amina Warsame',undefined,'undefined','undefined','University Mathematics I'),
('su-student052','Sharmarke Nuur',undefined,'undefined','undefined','Arabic Language I'),
('su-student053','Nasra Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student054','Jawahir Aden',undefined,'undefined','undefined','Arabic Language I'),
('su-student055','Awil Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student056','Zahra Warsame',undefined,'undefined','undefined','Introduction to Computing'),
('su-student057','Deeqa Abdi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student058','Yusuf Mire',undefined,'undefined','undefined','Arabic Language I'),
('su-student059','Kaafi Nuur',undefined,'undefined','undefined','University Mathematics I'),
('su-student060','Dahir Osman',undefined,'undefined','undefined','University Mathematics I'),
('su-student061','Mohamed Mire',undefined,'undefined','undefined','Academic English I'),
('su-student062','Hibo Barre',undefined,'undefined','undefined','Principles of Economics I'),
('su-student063','Iman Gedi',undefined,'undefined','undefined','University Mathematics I'),
('su-student064','Jawahir Barre',undefined,'undefined','undefined','Introduction to Computing'),
('su-student065','Fadumo Nuur',undefined,'undefined','undefined','Introduction to Computing'),
('su-student066','Amina Egal',undefined,'undefined','undefined','Principles of Economics I'),
('su-student067','Hamza Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student068','Abdi Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student069','Amina Barre',undefined,'undefined','undefined','Introduction to Computing'),
('su-student070','Kaafi Hussein',undefined,'undefined','undefined','Academic English I'),
('su-student071','Warsame Isse',undefined,'undefined','undefined','Introduction to Computing'),
('su-student072','Sahra Warsame',undefined,'undefined','undefined','Academic English I'),
('su-student073','Zakariye Hersi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student074','Ahmed Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student075','Ifrah Barre',undefined,'undefined','undefined','University Mathematics I'),
('su-student076','Guled Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student077','Elmi Hersi',undefined,'undefined','undefined','Academic English I'),
('su-student078','Hamdi Hussein',undefined,'undefined','undefined','University Mathematics I'),
('su-student079','Deeqa Ali',undefined,'undefined','undefined','Arabic Language I'),
('su-student080','Omar Hersi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student081','Warsame Samatar',undefined,'undefined','undefined','Introduction to Computing'),
('su-student082','Abdullahi Awale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student083','Ismail Ismail',undefined,'undefined','undefined','University Mathematics I'),
('su-student084','Hibo Awale',undefined,'undefined','undefined','University Mathematics I'),
('su-student085','Ifrah Nuur',undefined,'undefined','undefined','Principles of Economics I'),
('su-student086','Omar Osman',undefined,'undefined','undefined','Principles of Economics I'),
('su-student087','Nasra Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student088','Hamdi Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student089','Deeqa Ismail',undefined,'undefined','undefined','Principles of Economics I'),
('su-student090','Halima Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student091','Awil Farah',undefined,'undefined','undefined','Principles of Economics I'),
('su-student092','Liban Ali',undefined,'undefined','undefined','Introduction to Computing'),
('su-student093','Awil Ali',undefined,'undefined','undefined','Academic English I'),
('su-student094','Warsame Guleed',undefined,'undefined','undefined','Introduction to Computing'),
('su-student095','Sahra Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student096','Ahmed Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student097','Iman Awale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student098','Halima Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student099','Nur Ismail',undefined,'undefined','undefined','Principles of Economics I'),
('su-student100','Zahra Elmi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student101','Abdi Gedi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student102','Kaafi Osman',undefined,'undefined','undefined','Introduction to Computing'),
('su-student103','Hamza Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student104','Liban Jama',undefined,'undefined','undefined','Introduction to Computing'),
('su-student105','Zahra Gedi',undefined,'undefined','undefined','Arabic Language I'),
('su-student106','Sagal Barre',undefined,'undefined','undefined','Arabic Language I'),
('su-student107','Rahma Hussein',undefined,'undefined','undefined','Principles of Economics I'),
('su-student108','Warsame Aden',undefined,'undefined','undefined','Academic English I'),
('su-student109','Jamal Hassan',undefined,'undefined','undefined','Academic English I'),
('su-student110','Hodan Duale',undefined,'undefined','undefined','Academic English I'),
('su-student111','Naima Barre',undefined,'undefined','undefined','University Mathematics I'),
('su-student112','Naima Jama',undefined,'undefined','undefined','Arabic Language I'),
('su-student113','Khadija Farah',undefined,'undefined','undefined','Arabic Language I'),
('su-student114','Iman Nuur',undefined,'undefined','undefined','Introduction to Computing'),
('su-student115','Guled Isse',undefined,'undefined','undefined','Academic English I'),
('su-student116','Omar Ali',undefined,'undefined','undefined','Arabic Language I'),
('su-student117','Hussein Hussein',undefined,'undefined','undefined','Arabic Language I'),
('su-student118','Hamdi Sheikh',undefined,'undefined','undefined','Academic English I'),
('su-student119','Nasra Isse',undefined,'undefined','undefined','Principles of Economics I'),
('su-student120','Khadija Hassan',undefined,'undefined','undefined','Academic English I'),
('su-student121','Omar Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student122','Rahma Abdi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student123','Layla Farah',undefined,'undefined','undefined','Arabic Language I'),
('su-student124','Hussein Awale',undefined,'undefined','undefined','Academic English I'),
('su-student125','Yusuf Mohamed',undefined,'undefined','undefined','Principles of Economics I'),
('su-student126','Nur Hersi',undefined,'undefined','undefined','Arabic Language I'),
('su-student127','Nur Duale',undefined,'undefined','undefined','Arabic Language I'),
('su-student128','Jawahir Hassan',undefined,'undefined','undefined','University Mathematics I'),
('su-student129','Jamal Isse',undefined,'undefined','undefined','Introduction to Computing'),
('su-student130','Hassan Abdi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student131','Hassan Barre',undefined,'undefined','undefined','Principles of Economics I'),
('su-student132','Rahma Mire',undefined,'undefined','undefined','Academic English I'),
('su-student133','Zahra Ali',undefined,'undefined','undefined','Arabic Language I'),
('su-student134','Mustaf Aden',undefined,'undefined','undefined','University Mathematics I'),
('su-student135','Amina Nuur',undefined,'undefined','undefined','Principles of Economics I'),
('su-student136','Awil Egal',undefined,'undefined','undefined','Introduction to Computing'),
('su-student137','Jamal Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student138','Liban Hersi',undefined,'undefined','undefined','Academic English I'),
('su-student139','Filsan Elmi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student140','Sharmarke Elmi',undefined,'undefined','undefined','Academic English I'),
('su-student141','Dahir Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student142','Warsame Barre',undefined,'undefined','undefined','Introduction to Computing'),
('su-student143','Rahma Nuur',undefined,'undefined','undefined','Academic English I'),
('su-student144','Ismail Sheikh',undefined,'undefined','undefined','Academic English I'),
('su-student145','Halima Nuur',undefined,'undefined','undefined','Academic English I'),
('su-student146','Hussein Jama',undefined,'undefined','undefined','Arabic Language I'),
('su-student147','Hamdi Samatar',undefined,'undefined','undefined','Arabic Language I'),
('su-student148','Hamdi Osman',undefined,'undefined','undefined','Introduction to Computing'),
('su-student149','Halima Sheikh',undefined,'undefined','undefined','University Mathematics I'),
('su-student150','Dahir Duale',undefined,'undefined','undefined','Academic English I'),
('su-student151','Hamza Jama',undefined,'undefined','undefined','Arabic Language I'),
('su-student152','Abdi Osman',undefined,'undefined','undefined','Arabic Language I'),
('su-student153','Nimco Hassan',undefined,'undefined','undefined','Principles of Economics I'),
('su-student154','Mustaf Nuur',undefined,'undefined','undefined','Principles of Economics I'),
('su-student155','Ifrah Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student156','Jawahir Nuur',undefined,'undefined','undefined','University Mathematics I'),
('su-student157','Mustaf Barre',undefined,'undefined','undefined','Arabic Language I'),
('su-student158','Ayaan Egal',undefined,'undefined','undefined','Academic English I'),
('su-student159','Deeqa Awale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student160','Ubax Hussein',undefined,'undefined','undefined','Principles of Economics I'),
('su-student161','Mustaf Warsame',undefined,'undefined','undefined','University Mathematics I'),
('su-student162','Hodan Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student163','Hibo Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student164','Guled Osman',undefined,'undefined','undefined','Introduction to Computing'),
('su-student165','Guled Hussein',undefined,'undefined','undefined','Academic English I'),
('su-student166','Khalid Mire',undefined,'undefined','undefined','Academic English I'),
('su-student167','Awil Jama',undefined,'undefined','undefined','Academic English I'),
('su-student168','Zakariye Hussein',undefined,'undefined','undefined','Introduction to Computing'),
('su-student169','Naima Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student170','Khalid Hersi',undefined,'undefined','undefined','University Mathematics I'),
('su-student171','Ayaan Hassan',undefined,'undefined','undefined','Arabic Language I'),
('su-student172','Layla Guleed',undefined,'undefined','undefined','Introduction to Computing'),
('su-student173','Rahma Barre',undefined,'undefined','undefined','Academic English I'),
('su-student174','Maryan Egal',undefined,'undefined','undefined','Academic English I'),
('su-student175','Naima Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student176','Zakariye Elmi',undefined,'undefined','undefined','University Mathematics I'),
('su-student177','Liban Warsame',undefined,'undefined','undefined','Introduction to Computing'),
('su-student178','Layla Nuur',undefined,'undefined','undefined','Arabic Language I'),
('su-student179','Farah Mire',undefined,'undefined','undefined','Introduction to Computing'),
('su-student180','Rahma Guleed',undefined,'undefined','undefined','Arabic Language I'),
('su-student181','Ubax Awale',undefined,'undefined','undefined','Arabic Language I'),
('su-student182','Yusuf Barre',undefined,'undefined','undefined','University Mathematics I'),
('su-student183','Jawahir Farah',undefined,'undefined','undefined','University Mathematics I'),
('su-student184','Omar Hassan',undefined,'undefined','undefined','University Mathematics I'),
('su-student185','Dahir Isse',undefined,'undefined','undefined','Introduction to Computing'),
('su-student186','Jamal Barre',undefined,'undefined','undefined','Academic English I'),
('su-student187','Farah Mohamed',undefined,'undefined','undefined','Introduction to Computing'),
('su-student188','Dahir Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student189','Ayaan Sheikh',undefined,'undefined','undefined','Arabic Language I'),
('su-student190','Jamal Gedi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student191','Hamdi Jama',undefined,'undefined','undefined','University Mathematics I'),
('su-student192','Sagal Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student193','Iman Farah',undefined,'undefined','undefined','Principles of Economics I'),
('su-student194','Farhiya Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student195','Amina Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student196','Jamal Samatar',undefined,'undefined','undefined','Arabic Language I'),
('su-student197','Khalid Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student198','Abdullahi Ismail',undefined,'undefined','undefined','University Mathematics I'),
('su-student199','Fadumo Ali',undefined,'undefined','undefined','Principles of Economics I'),
('su-student200','Farah Aden',undefined,'undefined','undefined','Principles of Economics I');
INSERT INTO tmp_su_profiles (username, display_name, age, gender, city, course_type) VALUES
('su-student201','Mohamed Sheikh',undefined,'undefined','undefined','Principles of Economics I'),
('su-student202','Hussein Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student203','Naima Abdi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student204','Naima Hersi',undefined,'undefined','undefined','Academic English I'),
('su-student205','Jawahir Ali',undefined,'undefined','undefined','Academic English I'),
('su-student206','Ifrah Aden',undefined,'undefined','undefined','Academic English I'),
('su-student207','Ubax Yusuf',undefined,'undefined','undefined','University Mathematics I'),
('su-student208','Nur Mohamed',undefined,'undefined','undefined','University Mathematics I'),
('su-student209','Sagal Ismail',undefined,'undefined','undefined','University Mathematics I'),
('su-student210','Dahir Mohamed',undefined,'undefined','undefined','Academic English I'),
('su-student211','Hodan Mohamed',undefined,'undefined','undefined','Introduction to Computing'),
('su-student212','Ayaan Osman',undefined,'undefined','undefined','Principles of Economics I'),
('su-student213','Nimco Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student214','Sagal Mire',undefined,'undefined','undefined','Academic English I'),
('su-student215','Hassan Ali',undefined,'undefined','undefined','Principles of Economics I'),
('su-student216','Ifrah Ismail',undefined,'undefined','undefined','Arabic Language I'),
('su-student217','Khalid Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student218','Sahra Ali',undefined,'undefined','undefined','Academic English I'),
('su-student219','Omar Farah',undefined,'undefined','undefined','University Mathematics I'),
('su-student220','Zakariye Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student221','Ahmed Mire',undefined,'undefined','undefined','Principles of Economics I'),
('su-student222','Jamal Aden',undefined,'undefined','undefined','Principles of Economics I'),
('su-student223','Farah Gedi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student224','Abdullahi Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student225','Zahra Isse',undefined,'undefined','undefined','University Mathematics I'),
('su-student226','Fadumo Barre',undefined,'undefined','undefined','Academic English I'),
('su-student227','Zahra Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student228','Warsame Ali',undefined,'undefined','undefined','Academic English I'),
('su-student229','Abdullahi Osman',undefined,'undefined','undefined','Arabic Language I'),
('su-student230','Khadija Gedi',undefined,'undefined','undefined','Academic English I'),
('su-student231','Mustaf Hassan',undefined,'undefined','undefined','University Mathematics I'),
('su-student232','Bashir Osman',undefined,'undefined','undefined','Introduction to Computing'),
('su-student233','Sharmarke Mire',undefined,'undefined','undefined','Principles of Economics I'),
('su-student234','Warsame Egal',undefined,'undefined','undefined','Principles of Economics I'),
('su-student235','Zahra Hassan',undefined,'undefined','undefined','Academic English I'),
('su-student236','Hussein Farah',undefined,'undefined','undefined','Academic English I'),
('su-student237','Farah Osman',undefined,'undefined','undefined','Academic English I'),
('su-student238','Fadumo Samatar',undefined,'undefined','undefined','Arabic Language I'),
('su-student239','Yusuf Nuur',undefined,'undefined','undefined','Arabic Language I'),
('su-student240','Warsame Farah',undefined,'undefined','undefined','Principles of Economics I'),
('su-student241','Mohamed Osman',undefined,'undefined','undefined','Academic English I'),
('su-student242','Kaafi Hersi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student243','Nimco Hussein',undefined,'undefined','undefined','Introduction to Computing'),
('su-student244','Iman Hersi',undefined,'undefined','undefined','Arabic Language I'),
('su-student245','Ifrah Elmi',undefined,'undefined','undefined','Academic English I'),
('su-student246','Hodan Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student247','Ahmed Hussein',undefined,'undefined','undefined','Principles of Economics I'),
('su-student248','Hibo Sheikh',undefined,'undefined','undefined','Introduction to Computing'),
('su-student249','Sagal Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student250','Nimco Isse',undefined,'undefined','undefined','Academic English I'),
('su-student251','Omar Jama',undefined,'undefined','undefined','Arabic Language I'),
('su-student252','Filsan Barre',undefined,'undefined','undefined','Academic English I'),
('su-student253','Ismail Gedi',undefined,'undefined','undefined','Academic English I'),
('su-student254','Bashir Elmi',undefined,'undefined','undefined','University Mathematics I'),
('su-student255','Liban Elmi',undefined,'undefined','undefined','Arabic Language I'),
('su-student256','Farhiya Awale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student257','Jawahir Samatar',undefined,'undefined','undefined','University Mathematics I'),
('su-student258','Amina Osman',undefined,'undefined','undefined','Academic English I'),
('su-student259','Yusuf Ali',undefined,'undefined','undefined','Academic English I'),
('su-student260','Amina Yusuf',undefined,'undefined','undefined','Arabic Language I'),
('su-student261','Zakariye Barre',undefined,'undefined','undefined','Principles of Economics I'),
('su-student262','Nur Barre',undefined,'undefined','undefined','Principles of Economics I'),
('su-student263','Yasmin Hersi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student264','Layla Hussein',undefined,'undefined','undefined','Academic English I'),
('su-student265','Farhiya Ismail',undefined,'undefined','undefined','Academic English I'),
('su-student266','Ayaan Farah',undefined,'undefined','undefined','Principles of Economics I'),
('su-student267','Abdullahi Guleed',undefined,'undefined','undefined','Arabic Language I'),
('su-student268','Bashir Barre',undefined,'undefined','undefined','Academic English I'),
('su-student269','Nimco Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student270','Hodan Barre',undefined,'undefined','undefined','Academic English I'),
('su-student271','Sagal Ali',undefined,'undefined','undefined','Arabic Language I'),
('su-student272','Hamdi Awale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student273','Mustaf Hussein',undefined,'undefined','undefined','Academic English I'),
('su-student274','Kaafi Isse',undefined,'undefined','undefined','Academic English I'),
('su-student275','Omar Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student276','Sagal Gedi',undefined,'undefined','undefined','University Mathematics I'),
('su-student277','Maryan Duale',undefined,'undefined','undefined','Academic English I'),
('su-student278','Elmi Gedi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student279','Halima Jama',undefined,'undefined','undefined','University Mathematics I'),
('su-student280','Farah Hersi',undefined,'undefined','undefined','Arabic Language I'),
('su-student281','Yasmin Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student282','Sahra Hassan',undefined,'undefined','undefined','Arabic Language I'),
('su-student283','Khalid Duale',undefined,'undefined','undefined','University Mathematics I'),
('su-student284','Mustaf Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student285','Yasmin Yusuf',undefined,'undefined','undefined','University Mathematics I'),
('su-student286','Zahra Nuur',undefined,'undefined','undefined','Introduction to Computing'),
('su-student287','Sahra Hersi',undefined,'undefined','undefined','University Mathematics I'),
('su-student288','Awil Hussein',undefined,'undefined','undefined','Academic English I'),
('su-student289','Halima Farah',undefined,'undefined','undefined','Principles of Economics I'),
('su-student290','Layla Elmi',undefined,'undefined','undefined','University Mathematics I'),
('su-student291','Farah Hussein',undefined,'undefined','undefined','Principles of Economics I'),
('su-student292','Ayaan Hersi',undefined,'undefined','undefined','Academic English I'),
('su-student293','Farhiya Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student294','Bashir Ismail',undefined,'undefined','undefined','Introduction to Computing'),
('su-student295','Zahra Mire',undefined,'undefined','undefined','Arabic Language I'),
('su-student296','Farhiya Duale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student297','Naima Gedi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student298','Ubax Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student299','Zahra Awale',undefined,'undefined','undefined','University Mathematics I'),
('su-student300','Ismail Warsame',undefined,'undefined','undefined','Principles of Economics I'),
('su-student301','Khalid Yusuf',undefined,'undefined','undefined','Academic English I'),
('su-student302','Iman Osman',undefined,'undefined','undefined','Academic English I'),
('su-student303','Awil Elmi',undefined,'undefined','undefined','Arabic Language I'),
('su-student304','Hodan Ismail',undefined,'undefined','undefined','Academic English I'),
('su-student305','Bashir Jama',undefined,'undefined','undefined','Principles of Economics I'),
('su-student306','Rahma Osman',undefined,'undefined','undefined','Principles of Economics I'),
('su-student307','Ayaan Isse',undefined,'undefined','undefined','Principles of Economics I'),
('su-student308','Halima Hersi',undefined,'undefined','undefined','Academic English I'),
('su-student309','Liban Hassan',undefined,'undefined','undefined','Principles of Economics I'),
('su-student310','Fadumo Hersi',undefined,'undefined','undefined','University Mathematics I'),
('su-student311','Nimco Awale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student312','Hussein Barre',undefined,'undefined','undefined','Academic English I'),
('su-student313','Farhiya Sheikh',undefined,'undefined','undefined','Arabic Language I'),
('su-student314','Ayaan Duale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student315','Sharmarke Barre',undefined,'undefined','undefined','Academic English I'),
('su-student316','Mohamed Farah',undefined,'undefined','undefined','Academic English I'),
('su-student317','Ahmed Abdi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student318','Amina Awale',undefined,'undefined','undefined','Academic English I'),
('su-student319','Hodan Jama',undefined,'undefined','undefined','Introduction to Computing'),
('su-student320','Jawahir Hussein',undefined,'undefined','undefined','Principles of Economics I'),
('su-student321','Omar Yusuf',undefined,'undefined','undefined','Arabic Language I'),
('su-student322','Liban Awale',undefined,'undefined','undefined','Arabic Language I'),
('su-student323','Yusuf Aden',undefined,'undefined','undefined','Academic English I'),
('su-student324','Iman Warsame',undefined,'undefined','undefined','Academic English I'),
('su-student325','Abdullahi Mire',undefined,'undefined','undefined','Arabic Language I'),
('su-student326','Khadija Awale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student327','Awil Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student328','Nur Sheikh',undefined,'undefined','undefined','Principles of Economics I'),
('su-student329','Zakariye Isse',undefined,'undefined','undefined','Arabic Language I'),
('su-student330','Zakariye Nuur',undefined,'undefined','undefined','Principles of Economics I'),
('su-student331','Amina Hassan',undefined,'undefined','undefined','University Mathematics I'),
('su-student332','Farhiya Jama',undefined,'undefined','undefined','Principles of Economics I'),
('su-student333','Sagal Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student334','Abdi Egal',undefined,'undefined','undefined','Academic English I'),
('su-student335','Layla Barre',undefined,'undefined','undefined','Introduction to Computing'),
('su-student336','Yasmin Elmi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student337','Amina Samatar',undefined,'undefined','undefined','Introduction to Computing'),
('su-student338','Bashir Egal',undefined,'undefined','undefined','University Mathematics I'),
('su-student339','Abdullahi Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student340','Zahra Mohamed',undefined,'undefined','undefined','Academic English I'),
('su-student341','Ifrah Mire',undefined,'undefined','undefined','Arabic Language I'),
('su-student342','Sharmarke Guleed',undefined,'undefined','undefined','Principles of Economics I'),
('su-student343','Warsame Sheikh',undefined,'undefined','undefined','University Mathematics I'),
('su-student344','Hamdi Mohamed',undefined,'undefined','undefined','Arabic Language I'),
('su-student345','Maryan Mire',undefined,'undefined','undefined','University Mathematics I'),
('su-student346','Ahmed Mohamed',undefined,'undefined','undefined','Academic English I'),
('su-student347','Hassan Yusuf',undefined,'undefined','undefined','Principles of Economics I'),
('su-student348','Nasra Hussein',undefined,'undefined','undefined','Arabic Language I'),
('su-student349','Hussein Elmi',undefined,'undefined','undefined','Academic English I'),
('su-student350','Nimco Aden',undefined,'undefined','undefined','Academic English I'),
('su-student351','Hibo Mohamed',undefined,'undefined','undefined','Introduction to Computing'),
('su-student352','Nimco Nuur',undefined,'undefined','undefined','Introduction to Computing'),
('su-student353','Guled Elmi',undefined,'undefined','undefined','Arabic Language I'),
('su-student354','Farah Duale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student355','Jawahir Duale',undefined,'undefined','undefined','Arabic Language I'),
('su-student356','Iman Duale',undefined,'undefined','undefined','Academic English I'),
('su-student357','Guled Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student358','Khadija Duale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student359','Layla Jama',undefined,'undefined','undefined','Principles of Economics I'),
('su-student360','Hibo Egal',undefined,'undefined','undefined','Arabic Language I'),
('su-student361','Hassan Nuur',undefined,'undefined','undefined','Arabic Language I'),
('su-student362','Mustaf Ismail',undefined,'undefined','undefined','Principles of Economics I'),
('su-student363','Farhiya Hersi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student364','Ifrah Duale',undefined,'undefined','undefined','Academic English I'),
('su-student365','Sharmarke Egal',undefined,'undefined','undefined','Introduction to Computing'),
('su-student366','Zakariye Ali',undefined,'undefined','undefined','University Mathematics I'),
('su-student367','Ifrah Hassan',undefined,'undefined','undefined','Principles of Economics I'),
('su-student368','Yusuf Samatar',undefined,'undefined','undefined','Arabic Language I'),
('su-student369','Khalid Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student370','Amina Hersi',undefined,'undefined','undefined','Arabic Language I'),
('su-student371','Sharmarke Ali',undefined,'undefined','undefined','Academic English I'),
('su-student372','Iman Isse',undefined,'undefined','undefined','Arabic Language I'),
('su-student373','Sagal Sheikh',undefined,'undefined','undefined','Arabic Language I'),
('su-student374','Hamdi Duale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student375','Nur Yusuf',undefined,'undefined','undefined','Arabic Language I'),
('su-student376','Maryan Yusuf',undefined,'undefined','undefined','Introduction to Computing'),
('su-student377','Ifrah Gedi',undefined,'undefined','undefined','Academic English I'),
('su-student378','Sagal Isse',undefined,'undefined','undefined','University Mathematics I'),
('su-student379','Ubax Aden',undefined,'undefined','undefined','Arabic Language I'),
('su-student380','Abdi Jama',undefined,'undefined','undefined','Introduction to Computing'),
('su-student381','Zahra Egal',undefined,'undefined','undefined','Academic English I'),
('su-student382','Jawahir Yusuf',undefined,'undefined','undefined','Academic English I'),
('su-student383','Liban Isse',undefined,'undefined','undefined','Introduction to Computing'),
('su-student384','Guled Jama',undefined,'undefined','undefined','Principles of Economics I'),
('su-student385','Kaafi Elmi',undefined,'undefined','undefined','Academic English I'),
('su-student386','Iman Hassan',undefined,'undefined','undefined','Arabic Language I'),
('su-student387','Farhiya Farah',undefined,'undefined','undefined','Academic English I'),
('su-student388','Khalid Hassan',undefined,'undefined','undefined','Academic English I'),
('su-student389','Hodan Sheikh',undefined,'undefined','undefined','Academic English I'),
('su-student390','Farah Yusuf',undefined,'undefined','undefined','Academic English I'),
('su-student391','Abdi Guleed',undefined,'undefined','undefined','University Mathematics I'),
('su-student392','Farah Sheikh',undefined,'undefined','undefined','Academic English I'),
('su-student393','Dahir Yusuf',undefined,'undefined','undefined','Introduction to Computing'),
('su-student394','Omar Awale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student395','Filsan Ismail',undefined,'undefined','undefined','Principles of Economics I'),
('su-student396','Khadija Ali',undefined,'undefined','undefined','Introduction to Computing'),
('su-student397','Zakariye Gedi',undefined,'undefined','undefined','Arabic Language I'),
('su-student398','Ayaan Nuur',undefined,'undefined','undefined','Principles of Economics I'),
('su-student399','Filsan Farah',undefined,'undefined','undefined','Academic English I'),
('su-student400','Farhiya Isse',undefined,'undefined','undefined','University Mathematics I');
INSERT INTO tmp_su_profiles (username, display_name, age, gender, city, course_type) VALUES
('su-student401','Mustaf Duale',undefined,'undefined','undefined','University Mathematics I'),
('su-student402','Mustaf Mohamed',undefined,'undefined','undefined','Academic English I'),
('su-student403','Filsan Nuur',undefined,'undefined','undefined','Arabic Language I'),
('su-student404','Deeqa Gedi',undefined,'undefined','undefined','Academic English I'),
('su-student405','Ismail Abdi',undefined,'undefined','undefined','Arabic Language I'),
('su-student406','Nur Awale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student407','Nasra Elmi',undefined,'undefined','undefined','Academic English I'),
('su-student408','Guled Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student409','Hibo Jama',undefined,'undefined','undefined','Arabic Language I'),
('su-student410','Layla Sheikh',undefined,'undefined','undefined','Principles of Economics I'),
('su-student411','Amina Ismail',undefined,'undefined','undefined','Introduction to Computing'),
('su-student412','Zakariye Jama',undefined,'undefined','undefined','University Mathematics I'),
('su-student413','Amina Guleed',undefined,'undefined','undefined','Introduction to Computing'),
('su-student414','Yusuf Hersi',undefined,'undefined','undefined','Academic English I'),
('su-student415','Yusuf Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student416','Deeqa Sheikh',undefined,'undefined','undefined','Introduction to Computing'),
('su-student417','Abdullahi Yusuf',undefined,'undefined','undefined','University Mathematics I'),
('su-student418','Elmi Yusuf',undefined,'undefined','undefined','Academic English I'),
('su-student419','Deeqa Isse',undefined,'undefined','undefined','Academic English I'),
('su-student420','Hodan Abdi',undefined,'undefined','undefined','University Mathematics I'),
('su-student421','Farhiya Aden',undefined,'undefined','undefined','University Mathematics I'),
('su-student422','Zahra Guleed',undefined,'undefined','undefined','Academic English I'),
('su-student423','Sahra Farah',undefined,'undefined','undefined','Academic English I'),
('su-student424','Filsan Hussein',undefined,'undefined','undefined','Academic English I'),
('su-student425','Mohamed Hassan',undefined,'undefined','undefined','University Mathematics I'),
('su-student426','Guled Ismail',undefined,'undefined','undefined','Principles of Economics I'),
('su-student427','Ismail Nuur',undefined,'undefined','undefined','Principles of Economics I'),
('su-student428','Farah Barre',undefined,'undefined','undefined','Academic English I'),
('su-student429','Ismail Mohamed',undefined,'undefined','undefined','Introduction to Computing'),
('su-student430','Fadumo Hassan',undefined,'undefined','undefined','Arabic Language I'),
('su-student431','Ahmed Aden',undefined,'undefined','undefined','Introduction to Computing'),
('su-student432','Khalid Nuur',undefined,'undefined','undefined','Academic English I'),
('su-student433','Ifrah Warsame',undefined,'undefined','undefined','Academic English I'),
('su-student434','Elmi Ismail',undefined,'undefined','undefined','Academic English I'),
('su-student435','Ayaan Gedi',undefined,'undefined','undefined','University Mathematics I'),
('su-student436','Farhiya Barre',undefined,'undefined','undefined','Principles of Economics I'),
('su-student437','Zakariye Duale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student438','Ifrah Egal',undefined,'undefined','undefined','Principles of Economics I'),
('su-student439','Hussein Osman',undefined,'undefined','undefined','University Mathematics I'),
('su-student440','Hamza Ismail',undefined,'undefined','undefined','Arabic Language I'),
('su-student441','Deeqa Osman',undefined,'undefined','undefined','Introduction to Computing'),
('su-student442','Sagal Farah',undefined,'undefined','undefined','Academic English I'),
('su-student443','Khalid Farah',undefined,'undefined','undefined','Arabic Language I'),
('su-student444','Yusuf Jama',undefined,'undefined','undefined','Academic English I'),
('su-student445','Mohamed Aden',undefined,'undefined','undefined','Principles of Economics I'),
('su-student446','Omar Aden',undefined,'undefined','undefined','Arabic Language I'),
('su-student447','Sahra Hussein',undefined,'undefined','undefined','University Mathematics I'),
('su-student448','Abdi Ismail',undefined,'undefined','undefined','Arabic Language I'),
('su-student449','Nur Aden',undefined,'undefined','undefined','Arabic Language I'),
('su-student450','Abdullahi Ali',undefined,'undefined','undefined','Arabic Language I'),
('su-student451','Mohamed Hersi',undefined,'undefined','undefined','Academic English I'),
('su-student452','Hamza Awale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student453','Rahma Samatar',undefined,'undefined','undefined','Introduction to Computing'),
('su-student454','Awil Gedi',undefined,'undefined','undefined','Principles of Economics I'),
('su-student455','Mohamed Warsame',undefined,'undefined','undefined','Arabic Language I'),
('su-student456','Ayaan Samatar',undefined,'undefined','undefined','Academic English I'),
('su-student457','Awil Aden',undefined,'undefined','undefined','Principles of Economics I'),
('su-student458','Yasmin Isse',undefined,'undefined','undefined','Arabic Language I'),
('su-student459','Sahra Aden',undefined,'undefined','undefined','Academic English I'),
('su-student460','Ismail Duale',undefined,'undefined','undefined','Arabic Language I'),
('su-student461','Ayaan Mohamed',undefined,'undefined','undefined','Academic English I'),
('su-student462','Khalid Egal',undefined,'undefined','undefined','Arabic Language I'),
('su-student463','Zakariye Samatar',undefined,'undefined','undefined','Principles of Economics I'),
('su-student464','Hibo Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student465','Liban Aden',undefined,'undefined','undefined','Arabic Language I'),
('su-student466','Maryan Ismail',undefined,'undefined','undefined','University Mathematics I'),
('su-student467','Filsan Isse',undefined,'undefined','undefined','University Mathematics I'),
('su-student468','Elmi Ali',undefined,'undefined','undefined','University Mathematics I'),
('su-student469','Jamal Awale',undefined,'undefined','undefined','Academic English I'),
('su-student470','Mohamed Ali',undefined,'undefined','undefined','Introduction to Computing'),
('su-student471','Jawahir Osman',undefined,'undefined','undefined','Arabic Language I'),
('su-student472','Hamza Hersi',undefined,'undefined','undefined','Arabic Language I'),
('su-student473','Jawahir Isse',undefined,'undefined','undefined','Arabic Language I'),
('su-student474','Sharmarke Gedi',undefined,'undefined','undefined','Introduction to Computing'),
('su-student475','Abdullahi Mohamed',undefined,'undefined','undefined','Principles of Economics I'),
('su-student476','Mohamed Duale',undefined,'undefined','undefined','Principles of Economics I'),
('su-student477','Dahir Barre',undefined,'undefined','undefined','Academic English I'),
('su-student478','Kaafi Hassan',undefined,'undefined','undefined','Introduction to Computing'),
('su-student479','Ismail Mire',undefined,'undefined','undefined','Academic English I'),
('su-student480','Filsan Awale',undefined,'undefined','undefined','Introduction to Computing'),
('su-student481','Hamza Osman',undefined,'undefined','undefined','Arabic Language I'),
('su-student482','Hamdi Warsame',undefined,'undefined','undefined','Principles of Economics I'),
('su-student483','Awil Barre',undefined,'undefined','undefined','Academic English I'),
('su-student484','Hussein Aden',undefined,'undefined','undefined','Arabic Language I'),
('su-student485','Hamdi Ismail',undefined,'undefined','undefined','Principles of Economics I'),
('su-student486','Bashir Guleed',undefined,'undefined','undefined','Principles of Economics I'),
('su-student487','Naima Yusuf',undefined,'undefined','undefined','Arabic Language I'),
('su-student488','Ayaan Ali',undefined,'undefined','undefined','Introduction to Computing'),
('su-student489','Maryan Abdi',undefined,'undefined','undefined','Academic English I'),
('su-student490','Jamal Ali',undefined,'undefined','undefined','Academic English I'),
('su-student491','Jawahir Gedi',undefined,'undefined','undefined','Academic English I'),
('su-student492','Hassan Isse',undefined,'undefined','undefined','Academic English I'),
('su-student493','Omar Gedi',undefined,'undefined','undefined','Academic English I'),
('su-student494','Jawahir Guleed',undefined,'undefined','undefined','Arabic Language I'),
('su-student495','Dahir Hussein',undefined,'undefined','undefined','University Mathematics I'),
('su-student496','Yasmin Hassan',undefined,'undefined','undefined','Principles of Economics I'),
('su-student497','Ifrah Farah',undefined,'undefined','undefined','Introduction to Computing'),
('su-student498','Sahra Nuur',undefined,'undefined','undefined','Academic English I'),
('su-student499','Kaafi Egal',undefined,'undefined','undefined','Introduction to Computing'),
('su-student500','Amina Jama',undefined,'undefined','undefined','Arabic Language I');

INSERT INTO mdlgx_local_prequran_student_profile
  (userid, workspaceid, student_display_name, current_level, course_type,
   status, gender, age_years, city, country, timezone, primary_language,
   live_class_consent, recording_consent, createdby, timecreated, timemodified)
SELECT u.id, @workspaceid, t.display_name, 'year_1', t.course_type,
       'active', t.gender, t.age, t.city, 'Somalia', 'Africa/Mogadishu', 'Somali',
       'yes', 'yes', 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()
FROM tmp_su_profiles t
JOIN mdlgx_user u ON u.username = t.username AND u.deleted = 0
WHERE NOT EXISTS (SELECT 1 FROM mdlgx_local_prequran_student_profile sp WHERE sp.userid = u.id);

DROP TEMPORARY TABLE IF EXISTS tmp_su_profiles;

COMMIT;

-- CLEANUP (when the demo is over; uncomment to use)
-- DELETE sp FROM mdlgx_local_prequran_student_profile sp JOIN mdlgx_user u ON u.id = sp.userid
--   WHERE u.username LIKE 'su-%';
