-- Somali University: student profiles for pickers and portals
-- Run AFTER workspace-link.sql. MySQL/MariaDB. Prefix from DB_PREFIX (mdlgx_).
-- Safe to re-run (skips users that already have a profile). If an insert
-- fails with "Unknown column", remove that column and its value, re-run.

SET @workspaceid := 15;

START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS tmp_su_profiles;
CREATE TEMPORARY TABLE tmp_su_profiles (
  username VARCHAR(100) PRIMARY KEY,
  display_name VARCHAR(255),
  age INT,
  gender VARCHAR(20),
  city VARCHAR(120),
  course_type VARCHAR(255)
);
INSERT INTO tmp_su_profiles (username, display_name, age, gender, city, course_type) VALUES
('su-student001','Liban Abdi',18,'male','Jowhar','University Mathematics I'),
('su-student002','Yusuf Farah',24,'male','Garowe','Academic English I'),
('su-student003','Zahra Ismail',18,'female','Kismayo','Academic English I'),
('su-student004','Layla Hassan',20,'female','Berbera','Introduction to Computing'),
('su-student005','Bashir Duale',24,'male','Hargeisa','Arabic Language I'),
('su-student006','Hamdi Egal',18,'female','Jowhar','Principles of Economics I'),
('su-student007','Farah Farah',19,'male','Hargeisa','Introduction to Computing'),
('su-student008','Hodan Nuur',26,'female','Baidoa','Academic English I'),
('su-student009','Jamal Guleed',21,'male','Kismayo','University Mathematics I'),
('su-student010','Yasmin Samatar',20,'female','Kismayo','Introduction to Computing'),
('su-student011','Rahma Hersi',21,'female','Berbera','Arabic Language I'),
('su-student012','Hibo Hassan',21,'female','Kismayo','University Mathematics I'),
('su-student013','Jawahir Elmi',27,'female','Jowhar','University Mathematics I'),
('su-student014','Hibo Osman',19,'female','Hargeisa','Introduction to Computing'),
('su-student015','Abdullahi Hussein',26,'male','Kismayo','Introduction to Computing'),
('su-student016','Hamdi Ali',23,'female','Garowe','Arabic Language I'),
('su-student017','Nur Samatar',22,'male','Garowe','Introduction to Computing'),
('su-student018','Rahma Elmi',24,'female','Berbera','Academic English I'),
('su-student019','Maryan Hassan',26,'female','Kismayo','Arabic Language I'),
('su-student020','Iman Aden',22,'female','Beledweyne','Principles of Economics I'),
('su-student021','Khadija Mohamed',20,'female','Berbera','University Mathematics I'),
('su-student022','Yasmin Ismail',24,'female','Jowhar','Principles of Economics I'),
('su-student023','Ifrah Samatar',28,'female','Hargeisa','Arabic Language I'),
('su-student024','Hodan Egal',26,'female','Hargeisa','Academic English I'),
('su-student025','Rahma Egal',22,'female','Jowhar','Academic English I'),
('su-student026','Dahir Samatar',25,'male','Mogadishu','Principles of Economics I'),
('su-student027','Yasmin Egal',28,'female','Hargeisa','Academic English I'),
('su-student028','Mustaf Awale',27,'male','Mogadishu','Arabic Language I'),
('su-student029','Abdullahi Farah',24,'male','Garowe','Introduction to Computing'),
('su-student030','Sahra Osman',21,'female','Beledweyne','University Mathematics I'),
('su-student031','Khalid Barre',20,'male','Berbera','Introduction to Computing'),
('su-student032','Sharmarke Sheikh',24,'male','Jowhar','University Mathematics I'),
('su-student033','Amina Elmi',18,'female','Garowe','Academic English I'),
('su-student034','Ubax Isse',18,'female','Jowhar','Academic English I'),
('su-student035','Jamal Jama',22,'male','Hargeisa','Introduction to Computing'),
('su-student036','Liban Farah',23,'male','Garowe','Academic English I'),
('su-student037','Yasmin Farah',25,'female','Kismayo','Arabic Language I'),
('su-student038','Omar Sheikh',25,'male','Baidoa','Principles of Economics I'),
('su-student039','Farhiya Nuur',24,'female','Mogadishu','Principles of Economics I'),
('su-student040','Filsan Jama',24,'female','Kismayo','Arabic Language I'),
('su-student041','Omar Egal',21,'male','Berbera','Academic English I'),
('su-student042','Mohamed Hussein',21,'male','Beledweyne','Academic English I'),
('su-student043','Khadija Barre',25,'female','Baidoa','Arabic Language I'),
('su-student044','Elmi Abdi',19,'male','Kismayo','Academic English I'),
('su-student045','Filsan Samatar',28,'female','Berbera','Arabic Language I'),
('su-student046','Mohamed Barre',28,'male','Beledweyne','Academic English I'),
('su-student047','Nimco Abdi',27,'female','Baidoa','Introduction to Computing'),
('su-student048','Jawahir Mire',18,'female','Berbera','Principles of Economics I'),
('su-student049','Sagal Mohamed',20,'female','Berbera','Principles of Economics I'),
('su-student050','Sharmarke Hassan',23,'male','Jowhar','Introduction to Computing'),
('su-student051','Amina Warsame',21,'female','Berbera','University Mathematics I'),
('su-student052','Sharmarke Nuur',26,'male','Berbera','Arabic Language I'),
('su-student053','Nasra Warsame',21,'female','Kismayo','Arabic Language I'),
('su-student054','Jawahir Aden',18,'female','Garowe','Arabic Language I'),
('su-student055','Awil Guleed',19,'male','Mogadishu','Academic English I'),
('su-student056','Zahra Warsame',23,'female','Beledweyne','Introduction to Computing'),
('su-student057','Deeqa Abdi',27,'female','Berbera','Principles of Economics I'),
('su-student058','Yusuf Mire',21,'male','Kismayo','Arabic Language I'),
('su-student059','Kaafi Nuur',19,'male','Mogadishu','University Mathematics I'),
('su-student060','Dahir Osman',18,'male','Baidoa','University Mathematics I'),
('su-student061','Mohamed Mire',18,'male','Jowhar','Academic English I'),
('su-student062','Hibo Barre',23,'female','Mogadishu','Principles of Economics I'),
('su-student063','Iman Gedi',21,'female','Berbera','University Mathematics I'),
('su-student064','Jawahir Barre',28,'female','Baidoa','Introduction to Computing'),
('su-student065','Fadumo Nuur',19,'female','Berbera','Introduction to Computing'),
('su-student066','Amina Egal',28,'female','Berbera','Principles of Economics I'),
('su-student067','Hamza Mohamed',23,'male','Kismayo','Arabic Language I'),
('su-student068','Abdi Abdi',20,'male','Hargeisa','University Mathematics I'),
('su-student069','Amina Barre',20,'female','Berbera','Introduction to Computing'),
('su-student070','Kaafi Hussein',20,'male','Beledweyne','Academic English I'),
('su-student071','Warsame Isse',22,'male','Baidoa','Introduction to Computing'),
('su-student072','Sahra Warsame',18,'female','Berbera','Academic English I'),
('su-student073','Zakariye Hersi',25,'male','Kismayo','Principles of Economics I'),
('su-student074','Ahmed Guleed',25,'male','Berbera','Academic English I'),
('su-student075','Ifrah Barre',26,'female','Baidoa','University Mathematics I'),
('su-student076','Guled Mohamed',23,'male','Hargeisa','Arabic Language I'),
('su-student077','Elmi Hersi',18,'male','Jowhar','Academic English I'),
('su-student078','Hamdi Hussein',25,'female','Garowe','University Mathematics I'),
('su-student079','Deeqa Ali',19,'female','Hargeisa','Arabic Language I'),
('su-student080','Omar Hersi',27,'male','Beledweyne','Principles of Economics I'),
('su-student081','Warsame Samatar',18,'male','Garowe','Introduction to Computing'),
('su-student082','Abdullahi Awale',23,'male','Berbera','Principles of Economics I'),
('su-student083','Ismail Ismail',21,'male','Garowe','University Mathematics I'),
('su-student084','Hibo Awale',20,'female','Baidoa','University Mathematics I'),
('su-student085','Ifrah Nuur',22,'female','Kismayo','Principles of Economics I'),
('su-student086','Omar Osman',21,'male','Mogadishu','Principles of Economics I'),
('su-student087','Nasra Samatar',20,'female','Baidoa','Academic English I'),
('su-student088','Hamdi Abdi',20,'female','Kismayo','University Mathematics I'),
('su-student089','Deeqa Ismail',19,'female','Baidoa','Principles of Economics I'),
('su-student090','Halima Guleed',24,'female','Jowhar','Academic English I'),
('su-student091','Awil Farah',21,'male','Hargeisa','Principles of Economics I'),
('su-student092','Liban Ali',19,'male','Berbera','Introduction to Computing'),
('su-student093','Awil Ali',19,'male','Berbera','Academic English I'),
('su-student094','Warsame Guleed',18,'male','Jowhar','Introduction to Computing'),
('su-student095','Sahra Guleed',25,'female','Beledweyne','Academic English I'),
('su-student096','Ahmed Samatar',23,'male','Mogadishu','Academic English I'),
('su-student097','Iman Awale',20,'female','Kismayo','Introduction to Computing'),
('su-student098','Halima Hassan',22,'female','Beledweyne','Introduction to Computing'),
('su-student099','Nur Ismail',24,'male','Berbera','Principles of Economics I'),
('su-student100','Zahra Elmi',25,'female','Hargeisa','Principles of Economics I'),
('su-student101','Abdi Gedi',19,'male','Kismayo','Principles of Economics I'),
('su-student102','Kaafi Osman',26,'male','Kismayo','Introduction to Computing'),
('su-student103','Hamza Guleed',23,'male','Mogadishu','Academic English I'),
('su-student104','Liban Jama',23,'male','Mogadishu','Introduction to Computing'),
('su-student105','Zahra Gedi',20,'female','Kismayo','Arabic Language I'),
('su-student106','Sagal Barre',25,'female','Jowhar','Arabic Language I'),
('su-student107','Rahma Hussein',21,'female','Kismayo','Principles of Economics I'),
('su-student108','Warsame Aden',25,'male','Berbera','Academic English I'),
('su-student109','Jamal Hassan',23,'male','Beledweyne','Academic English I'),
('su-student110','Hodan Duale',23,'female','Baidoa','Academic English I'),
('su-student111','Naima Barre',18,'female','Jowhar','University Mathematics I'),
('su-student112','Naima Jama',22,'female','Baidoa','Arabic Language I'),
('su-student113','Khadija Farah',20,'female','Beledweyne','Arabic Language I'),
('su-student114','Iman Nuur',18,'female','Baidoa','Introduction to Computing'),
('su-student115','Guled Isse',21,'male','Beledweyne','Academic English I'),
('su-student116','Omar Ali',19,'male','Garowe','Arabic Language I'),
('su-student117','Hussein Hussein',27,'male','Berbera','Arabic Language I'),
('su-student118','Hamdi Sheikh',28,'female','Jowhar','Academic English I'),
('su-student119','Nasra Isse',22,'female','Jowhar','Principles of Economics I'),
('su-student120','Khadija Hassan',22,'female','Mogadishu','Academic English I'),
('su-student121','Omar Mohamed',23,'male','Kismayo','Arabic Language I'),
('su-student122','Rahma Abdi',19,'female','Hargeisa','Introduction to Computing'),
('su-student123','Layla Farah',26,'female','Garowe','Arabic Language I'),
('su-student124','Hussein Awale',24,'male','Mogadishu','Academic English I'),
('su-student125','Yusuf Mohamed',23,'male','Hargeisa','Principles of Economics I'),
('su-student126','Nur Hersi',24,'male','Garowe','Arabic Language I'),
('su-student127','Nur Duale',23,'male','Hargeisa','Arabic Language I'),
('su-student128','Jawahir Hassan',22,'female','Kismayo','University Mathematics I'),
('su-student129','Jamal Isse',20,'male','Baidoa','Introduction to Computing'),
('su-student130','Hassan Abdi',26,'male','Beledweyne','Principles of Economics I'),
('su-student131','Hassan Barre',28,'male','Beledweyne','Principles of Economics I'),
('su-student132','Rahma Mire',20,'female','Jowhar','Academic English I'),
('su-student133','Zahra Ali',26,'female','Beledweyne','Arabic Language I'),
('su-student134','Mustaf Aden',26,'male','Berbera','University Mathematics I'),
('su-student135','Amina Nuur',25,'female','Garowe','Principles of Economics I'),
('su-student136','Awil Egal',27,'male','Beledweyne','Introduction to Computing'),
('su-student137','Jamal Mohamed',19,'male','Baidoa','Arabic Language I'),
('su-student138','Liban Hersi',25,'male','Jowhar','Academic English I'),
('su-student139','Filsan Elmi',22,'female','Kismayo','Introduction to Computing'),
('su-student140','Sharmarke Elmi',22,'male','Berbera','Academic English I'),
('su-student141','Dahir Abdi',28,'male','Berbera','Academic English I'),
('su-student142','Warsame Barre',19,'male','Kismayo','Introduction to Computing'),
('su-student143','Rahma Nuur',27,'female','Beledweyne','Academic English I'),
('su-student144','Ismail Sheikh',22,'male','Hargeisa','Academic English I'),
('su-student145','Halima Nuur',20,'female','Kismayo','Academic English I'),
('su-student146','Hussein Jama',20,'male','Beledweyne','Arabic Language I'),
('su-student147','Hamdi Samatar',23,'female','Berbera','Arabic Language I'),
('su-student148','Hamdi Osman',24,'female','Jowhar','Introduction to Computing'),
('su-student149','Halima Sheikh',27,'female','Berbera','University Mathematics I'),
('su-student150','Dahir Duale',25,'male','Kismayo','Academic English I'),
('su-student151','Hamza Jama',23,'male','Kismayo','Arabic Language I'),
('su-student152','Abdi Osman',23,'male','Mogadishu','Arabic Language I'),
('su-student153','Nimco Hassan',21,'female','Jowhar','Principles of Economics I'),
('su-student154','Mustaf Nuur',21,'male','Baidoa','Principles of Economics I'),
('su-student155','Ifrah Abdi',26,'female','Garowe','Academic English I'),
('su-student156','Jawahir Nuur',21,'female','Mogadishu','University Mathematics I'),
('su-student157','Mustaf Barre',22,'male','Kismayo','Arabic Language I'),
('su-student158','Ayaan Egal',28,'female','Beledweyne','Academic English I'),
('su-student159','Deeqa Awale',26,'female','Beledweyne','Principles of Economics I'),
('su-student160','Ubax Hussein',18,'female','Berbera','Principles of Economics I'),
('su-student161','Mustaf Warsame',23,'male','Berbera','University Mathematics I'),
('su-student162','Hodan Hassan',19,'female','Garowe','Introduction to Computing'),
('su-student163','Hibo Warsame',23,'female','Berbera','Arabic Language I'),
('su-student164','Guled Osman',20,'male','Baidoa','Introduction to Computing'),
('su-student165','Guled Hussein',28,'male','Jowhar','Academic English I'),
('su-student166','Khalid Mire',18,'male','Baidoa','Academic English I'),
('su-student167','Awil Jama',23,'male','Beledweyne','Academic English I'),
('su-student168','Zakariye Hussein',19,'male','Garowe','Introduction to Computing'),
('su-student169','Naima Samatar',18,'female','Garowe','Academic English I'),
('su-student170','Khalid Hersi',22,'male','Berbera','University Mathematics I'),
('su-student171','Ayaan Hassan',23,'female','Kismayo','Arabic Language I'),
('su-student172','Layla Guleed',24,'female','Jowhar','Introduction to Computing'),
('su-student173','Rahma Barre',22,'female','Jowhar','Academic English I'),
('su-student174','Maryan Egal',22,'female','Kismayo','Academic English I'),
('su-student175','Naima Hassan',27,'female','Kismayo','Introduction to Computing'),
('su-student176','Zakariye Elmi',19,'male','Kismayo','University Mathematics I'),
('su-student177','Liban Warsame',21,'male','Kismayo','Introduction to Computing'),
('su-student178','Layla Nuur',27,'female','Jowhar','Arabic Language I'),
('su-student179','Farah Mire',20,'male','Berbera','Introduction to Computing'),
('su-student180','Rahma Guleed',24,'female','Berbera','Arabic Language I'),
('su-student181','Ubax Awale',19,'female','Hargeisa','Arabic Language I'),
('su-student182','Yusuf Barre',27,'male','Hargeisa','University Mathematics I'),
('su-student183','Jawahir Farah',19,'female','Baidoa','University Mathematics I'),
('su-student184','Omar Hassan',22,'male','Hargeisa','University Mathematics I'),
('su-student185','Dahir Isse',19,'male','Mogadishu','Introduction to Computing'),
('su-student186','Jamal Barre',20,'male','Berbera','Academic English I'),
('su-student187','Farah Mohamed',24,'male','Jowhar','Introduction to Computing'),
('su-student188','Dahir Warsame',19,'male','Baidoa','Arabic Language I'),
('su-student189','Ayaan Sheikh',28,'female','Baidoa','Arabic Language I'),
('su-student190','Jamal Gedi',18,'male','Berbera','Principles of Economics I'),
('su-student191','Hamdi Jama',27,'female','Mogadishu','University Mathematics I'),
('su-student192','Sagal Warsame',27,'female','Hargeisa','Arabic Language I'),
('su-student193','Iman Farah',18,'female','Jowhar','Principles of Economics I'),
('su-student194','Farhiya Abdi',27,'female','Kismayo','University Mathematics I'),
('su-student195','Amina Mohamed',28,'female','Berbera','Arabic Language I'),
('su-student196','Jamal Samatar',28,'male','Jowhar','Arabic Language I'),
('su-student197','Khalid Warsame',18,'male','Garowe','Arabic Language I'),
('su-student198','Abdullahi Ismail',25,'male','Hargeisa','University Mathematics I'),
('su-student199','Fadumo Ali',19,'female','Beledweyne','Principles of Economics I'),
('su-student200','Farah Aden',28,'male','Kismayo','Principles of Economics I');
INSERT INTO tmp_su_profiles (username, display_name, age, gender, city, course_type) VALUES
('su-student201','Mohamed Sheikh',22,'male','Hargeisa','Principles of Economics I'),
('su-student202','Hussein Mohamed',27,'male','Jowhar','Arabic Language I'),
('su-student203','Naima Abdi',21,'female','Beledweyne','Introduction to Computing'),
('su-student204','Naima Hersi',18,'female','Jowhar','Academic English I'),
('su-student205','Jawahir Ali',24,'female','Berbera','Academic English I'),
('su-student206','Ifrah Aden',21,'female','Mogadishu','Academic English I'),
('su-student207','Ubax Yusuf',19,'female','Mogadishu','University Mathematics I'),
('su-student208','Nur Mohamed',19,'male','Berbera','University Mathematics I'),
('su-student209','Sagal Ismail',18,'female','Kismayo','University Mathematics I'),
('su-student210','Dahir Mohamed',21,'male','Kismayo','Academic English I'),
('su-student211','Hodan Mohamed',19,'female','Garowe','Introduction to Computing'),
('su-student212','Ayaan Osman',22,'female','Berbera','Principles of Economics I'),
('su-student213','Nimco Samatar',20,'female','Kismayo','Academic English I'),
('su-student214','Sagal Mire',23,'female','Hargeisa','Academic English I'),
('su-student215','Hassan Ali',24,'male','Jowhar','Principles of Economics I'),
('su-student216','Ifrah Ismail',18,'female','Baidoa','Arabic Language I'),
('su-student217','Khalid Abdi',25,'male','Hargeisa','Academic English I'),
('su-student218','Sahra Ali',24,'female','Garowe','Academic English I'),
('su-student219','Omar Farah',23,'male','Jowhar','University Mathematics I'),
('su-student220','Zakariye Abdi',28,'male','Berbera','Academic English I'),
('su-student221','Ahmed Mire',20,'male','Baidoa','Principles of Economics I'),
('su-student222','Jamal Aden',23,'male','Kismayo','Principles of Economics I'),
('su-student223','Farah Gedi',27,'male','Baidoa','Introduction to Computing'),
('su-student224','Abdullahi Hassan',24,'male','Garowe','Introduction to Computing'),
('su-student225','Zahra Isse',27,'female','Berbera','University Mathematics I'),
('su-student226','Fadumo Barre',23,'female','Baidoa','Academic English I'),
('su-student227','Zahra Samatar',25,'female','Kismayo','Academic English I'),
('su-student228','Warsame Ali',20,'male','Hargeisa','Academic English I'),
('su-student229','Abdullahi Osman',27,'male','Kismayo','Arabic Language I'),
('su-student230','Khadija Gedi',26,'female','Garowe','Academic English I'),
('su-student231','Mustaf Hassan',26,'male','Jowhar','University Mathematics I'),
('su-student232','Bashir Osman',18,'male','Beledweyne','Introduction to Computing'),
('su-student233','Sharmarke Mire',18,'male','Hargeisa','Principles of Economics I'),
('su-student234','Warsame Egal',24,'male','Jowhar','Principles of Economics I'),
('su-student235','Zahra Hassan',22,'female','Hargeisa','Academic English I'),
('su-student236','Hussein Farah',23,'male','Kismayo','Academic English I'),
('su-student237','Farah Osman',19,'male','Baidoa','Academic English I'),
('su-student238','Fadumo Samatar',24,'female','Garowe','Arabic Language I'),
('su-student239','Yusuf Nuur',24,'male','Baidoa','Arabic Language I'),
('su-student240','Warsame Farah',26,'male','Mogadishu','Principles of Economics I'),
('su-student241','Mohamed Osman',22,'male','Kismayo','Academic English I'),
('su-student242','Kaafi Hersi',18,'male','Beledweyne','Principles of Economics I'),
('su-student243','Nimco Hussein',24,'female','Garowe','Introduction to Computing'),
('su-student244','Iman Hersi',26,'female','Berbera','Arabic Language I'),
('su-student245','Ifrah Elmi',24,'female','Garowe','Academic English I'),
('su-student246','Hodan Warsame',22,'female','Hargeisa','Arabic Language I'),
('su-student247','Ahmed Hussein',19,'male','Berbera','Principles of Economics I'),
('su-student248','Hibo Sheikh',27,'female','Garowe','Introduction to Computing'),
('su-student249','Sagal Guleed',26,'female','Berbera','Academic English I'),
('su-student250','Nimco Isse',22,'female','Berbera','Academic English I'),
('su-student251','Omar Jama',23,'male','Jowhar','Arabic Language I'),
('su-student252','Filsan Barre',18,'female','Berbera','Academic English I'),
('su-student253','Ismail Gedi',21,'male','Kismayo','Academic English I'),
('su-student254','Bashir Elmi',19,'male','Jowhar','University Mathematics I'),
('su-student255','Liban Elmi',28,'male','Beledweyne','Arabic Language I'),
('su-student256','Farhiya Awale',20,'female','Garowe','Introduction to Computing'),
('su-student257','Jawahir Samatar',27,'female','Mogadishu','University Mathematics I'),
('su-student258','Amina Osman',20,'female','Mogadishu','Academic English I'),
('su-student259','Yusuf Ali',28,'male','Hargeisa','Academic English I'),
('su-student260','Amina Yusuf',19,'female','Mogadishu','Arabic Language I'),
('su-student261','Zakariye Barre',23,'male','Garowe','Principles of Economics I'),
('su-student262','Nur Barre',23,'male','Berbera','Principles of Economics I'),
('su-student263','Yasmin Hersi',24,'female','Baidoa','Introduction to Computing'),
('su-student264','Layla Hussein',22,'female','Hargeisa','Academic English I'),
('su-student265','Farhiya Ismail',21,'female','Baidoa','Academic English I'),
('su-student266','Ayaan Farah',25,'female','Jowhar','Principles of Economics I'),
('su-student267','Abdullahi Guleed',25,'male','Berbera','Arabic Language I'),
('su-student268','Bashir Barre',21,'male','Jowhar','Academic English I'),
('su-student269','Nimco Mohamed',27,'female','Kismayo','Arabic Language I'),
('su-student270','Hodan Barre',24,'female','Baidoa','Academic English I'),
('su-student271','Sagal Ali',27,'female','Hargeisa','Arabic Language I'),
('su-student272','Hamdi Awale',26,'female','Mogadishu','Principles of Economics I'),
('su-student273','Mustaf Hussein',18,'male','Baidoa','Academic English I'),
('su-student274','Kaafi Isse',27,'male','Baidoa','Academic English I'),
('su-student275','Omar Warsame',26,'male','Jowhar','Arabic Language I'),
('su-student276','Sagal Gedi',23,'female','Garowe','University Mathematics I'),
('su-student277','Maryan Duale',28,'female','Baidoa','Academic English I'),
('su-student278','Elmi Gedi',26,'male','Baidoa','Introduction to Computing'),
('su-student279','Halima Jama',20,'female','Mogadishu','University Mathematics I'),
('su-student280','Farah Hersi',23,'male','Jowhar','Arabic Language I'),
('su-student281','Yasmin Guleed',20,'female','Beledweyne','Academic English I'),
('su-student282','Sahra Hassan',23,'female','Jowhar','Arabic Language I'),
('su-student283','Khalid Duale',26,'male','Garowe','University Mathematics I'),
('su-student284','Mustaf Abdi',19,'male','Jowhar','Academic English I'),
('su-student285','Yasmin Yusuf',25,'female','Garowe','University Mathematics I'),
('su-student286','Zahra Nuur',27,'female','Hargeisa','Introduction to Computing'),
('su-student287','Sahra Hersi',23,'female','Baidoa','University Mathematics I'),
('su-student288','Awil Hussein',22,'male','Hargeisa','Academic English I'),
('su-student289','Halima Farah',23,'female','Hargeisa','Principles of Economics I'),
('su-student290','Layla Elmi',27,'female','Kismayo','University Mathematics I'),
('su-student291','Farah Hussein',28,'male','Hargeisa','Principles of Economics I'),
('su-student292','Ayaan Hersi',22,'female','Beledweyne','Academic English I'),
('su-student293','Farhiya Mohamed',24,'female','Hargeisa','Arabic Language I'),
('su-student294','Bashir Ismail',28,'male','Jowhar','Introduction to Computing'),
('su-student295','Zahra Mire',18,'female','Baidoa','Arabic Language I'),
('su-student296','Farhiya Duale',26,'female','Beledweyne','Principles of Economics I'),
('su-student297','Naima Gedi',18,'female','Kismayo','Principles of Economics I'),
('su-student298','Ubax Abdi',26,'female','Beledweyne','University Mathematics I'),
('su-student299','Zahra Awale',18,'female','Beledweyne','University Mathematics I'),
('su-student300','Ismail Warsame',28,'male','Hargeisa','Principles of Economics I'),
('su-student301','Khalid Yusuf',18,'male','Hargeisa','Academic English I'),
('su-student302','Iman Osman',20,'female','Berbera','Academic English I'),
('su-student303','Awil Elmi',23,'male','Mogadishu','Arabic Language I'),
('su-student304','Hodan Ismail',25,'female','Hargeisa','Academic English I'),
('su-student305','Bashir Jama',23,'male','Baidoa','Principles of Economics I'),
('su-student306','Rahma Osman',28,'female','Baidoa','Principles of Economics I'),
('su-student307','Ayaan Isse',26,'female','Hargeisa','Principles of Economics I'),
('su-student308','Halima Hersi',28,'female','Hargeisa','Academic English I'),
('su-student309','Liban Hassan',18,'male','Garowe','Principles of Economics I'),
('su-student310','Fadumo Hersi',24,'female','Berbera','University Mathematics I'),
('su-student311','Nimco Awale',27,'female','Garowe','Principles of Economics I'),
('su-student312','Hussein Barre',24,'male','Baidoa','Academic English I'),
('su-student313','Farhiya Sheikh',26,'female','Kismayo','Arabic Language I'),
('su-student314','Ayaan Duale',27,'female','Kismayo','Introduction to Computing'),
('su-student315','Sharmarke Barre',21,'male','Hargeisa','Academic English I'),
('su-student316','Mohamed Farah',24,'male','Berbera','Academic English I'),
('su-student317','Ahmed Abdi',25,'male','Baidoa','Introduction to Computing'),
('su-student318','Amina Awale',25,'female','Garowe','Academic English I'),
('su-student319','Hodan Jama',22,'female','Berbera','Introduction to Computing'),
('su-student320','Jawahir Hussein',27,'female','Jowhar','Principles of Economics I'),
('su-student321','Omar Yusuf',28,'male','Baidoa','Arabic Language I'),
('su-student322','Liban Awale',19,'male','Garowe','Arabic Language I'),
('su-student323','Yusuf Aden',21,'male','Garowe','Academic English I'),
('su-student324','Iman Warsame',28,'female','Garowe','Academic English I'),
('su-student325','Abdullahi Mire',21,'male','Kismayo','Arabic Language I'),
('su-student326','Khadija Awale',27,'female','Berbera','Introduction to Computing'),
('su-student327','Awil Hassan',20,'male','Baidoa','Introduction to Computing'),
('su-student328','Nur Sheikh',26,'male','Garowe','Principles of Economics I'),
('su-student329','Zakariye Isse',19,'male','Beledweyne','Arabic Language I'),
('su-student330','Zakariye Nuur',25,'male','Baidoa','Principles of Economics I'),
('su-student331','Amina Hassan',20,'female','Beledweyne','University Mathematics I'),
('su-student332','Farhiya Jama',26,'female','Beledweyne','Principles of Economics I'),
('su-student333','Sagal Abdi',21,'female','Kismayo','University Mathematics I'),
('su-student334','Abdi Egal',21,'male','Mogadishu','Academic English I'),
('su-student335','Layla Barre',25,'female','Baidoa','Introduction to Computing'),
('su-student336','Yasmin Elmi',20,'female','Hargeisa','Principles of Economics I'),
('su-student337','Amina Samatar',28,'female','Berbera','Introduction to Computing'),
('su-student338','Bashir Egal',24,'male','Garowe','University Mathematics I'),
('su-student339','Abdullahi Samatar',21,'male','Kismayo','Academic English I'),
('su-student340','Zahra Mohamed',23,'female','Berbera','Academic English I'),
('su-student341','Ifrah Mire',26,'female','Hargeisa','Arabic Language I'),
('su-student342','Sharmarke Guleed',19,'male','Jowhar','Principles of Economics I'),
('su-student343','Warsame Sheikh',27,'male','Mogadishu','University Mathematics I'),
('su-student344','Hamdi Mohamed',21,'female','Garowe','Arabic Language I'),
('su-student345','Maryan Mire',19,'female','Berbera','University Mathematics I'),
('su-student346','Ahmed Mohamed',28,'male','Hargeisa','Academic English I'),
('su-student347','Hassan Yusuf',24,'male','Berbera','Principles of Economics I'),
('su-student348','Nasra Hussein',24,'female','Mogadishu','Arabic Language I'),
('su-student349','Hussein Elmi',21,'male','Berbera','Academic English I'),
('su-student350','Nimco Aden',24,'female','Hargeisa','Academic English I'),
('su-student351','Hibo Mohamed',25,'female','Berbera','Introduction to Computing'),
('su-student352','Nimco Nuur',18,'female','Beledweyne','Introduction to Computing'),
('su-student353','Guled Elmi',22,'male','Kismayo','Arabic Language I'),
('su-student354','Farah Duale',23,'male','Mogadishu','Introduction to Computing'),
('su-student355','Jawahir Duale',21,'female','Beledweyne','Arabic Language I'),
('su-student356','Iman Duale',28,'female','Jowhar','Academic English I'),
('su-student357','Guled Samatar',19,'male','Mogadishu','Academic English I'),
('su-student358','Khadija Duale',27,'female','Garowe','Introduction to Computing'),
('su-student359','Layla Jama',26,'female','Kismayo','Principles of Economics I'),
('su-student360','Hibo Egal',24,'female','Garowe','Arabic Language I'),
('su-student361','Hassan Nuur',25,'male','Jowhar','Arabic Language I'),
('su-student362','Mustaf Ismail',25,'male','Jowhar','Principles of Economics I'),
('su-student363','Farhiya Hersi',20,'female','Beledweyne','Principles of Economics I'),
('su-student364','Ifrah Duale',22,'female','Mogadishu','Academic English I'),
('su-student365','Sharmarke Egal',21,'male','Kismayo','Introduction to Computing'),
('su-student366','Zakariye Ali',22,'male','Baidoa','University Mathematics I'),
('su-student367','Ifrah Hassan',27,'female','Mogadishu','Principles of Economics I'),
('su-student368','Yusuf Samatar',20,'male','Garowe','Arabic Language I'),
('su-student369','Khalid Samatar',20,'male','Berbera','Academic English I'),
('su-student370','Amina Hersi',18,'female','Kismayo','Arabic Language I'),
('su-student371','Sharmarke Ali',21,'male','Kismayo','Academic English I'),
('su-student372','Iman Isse',26,'female','Mogadishu','Arabic Language I'),
('su-student373','Sagal Sheikh',26,'female','Mogadishu','Arabic Language I'),
('su-student374','Hamdi Duale',26,'female','Garowe','Introduction to Computing'),
('su-student375','Nur Yusuf',24,'male','Baidoa','Arabic Language I'),
('su-student376','Maryan Yusuf',20,'female','Berbera','Introduction to Computing'),
('su-student377','Ifrah Gedi',20,'female','Kismayo','Academic English I'),
('su-student378','Sagal Isse',22,'female','Mogadishu','University Mathematics I'),
('su-student379','Ubax Aden',21,'female','Mogadishu','Arabic Language I'),
('su-student380','Abdi Jama',23,'male','Baidoa','Introduction to Computing'),
('su-student381','Zahra Egal',18,'female','Hargeisa','Academic English I'),
('su-student382','Jawahir Yusuf',18,'female','Beledweyne','Academic English I'),
('su-student383','Liban Isse',24,'male','Jowhar','Introduction to Computing'),
('su-student384','Guled Jama',27,'male','Mogadishu','Principles of Economics I'),
('su-student385','Kaafi Elmi',25,'male','Berbera','Academic English I'),
('su-student386','Iman Hassan',18,'female','Jowhar','Arabic Language I'),
('su-student387','Farhiya Farah',21,'female','Baidoa','Academic English I'),
('su-student388','Khalid Hassan',20,'male','Hargeisa','Academic English I'),
('su-student389','Hodan Sheikh',19,'female','Mogadishu','Academic English I'),
('su-student390','Farah Yusuf',27,'male','Garowe','Academic English I'),
('su-student391','Abdi Guleed',23,'male','Kismayo','University Mathematics I'),
('su-student392','Farah Sheikh',18,'male','Kismayo','Academic English I'),
('su-student393','Dahir Yusuf',25,'male','Berbera','Introduction to Computing'),
('su-student394','Omar Awale',25,'male','Mogadishu','Principles of Economics I'),
('su-student395','Filsan Ismail',19,'female','Hargeisa','Principles of Economics I'),
('su-student396','Khadija Ali',25,'female','Hargeisa','Introduction to Computing'),
('su-student397','Zakariye Gedi',18,'male','Garowe','Arabic Language I'),
('su-student398','Ayaan Nuur',28,'female','Berbera','Principles of Economics I'),
('su-student399','Filsan Farah',25,'female','Jowhar','Academic English I'),
('su-student400','Farhiya Isse',19,'female','Mogadishu','University Mathematics I');
INSERT INTO tmp_su_profiles (username, display_name, age, gender, city, course_type) VALUES
('su-student401','Mustaf Duale',20,'male','Hargeisa','University Mathematics I'),
('su-student402','Mustaf Mohamed',24,'male','Garowe','Academic English I'),
('su-student403','Filsan Nuur',28,'female','Baidoa','Arabic Language I'),
('su-student404','Deeqa Gedi',21,'female','Baidoa','Academic English I'),
('su-student405','Ismail Abdi',25,'male','Garowe','Arabic Language I'),
('su-student406','Nur Awale',19,'male','Mogadishu','Introduction to Computing'),
('su-student407','Nasra Elmi',23,'female','Garowe','Academic English I'),
('su-student408','Guled Warsame',20,'male','Garowe','Arabic Language I'),
('su-student409','Hibo Jama',19,'female','Jowhar','Arabic Language I'),
('su-student410','Layla Sheikh',18,'female','Mogadishu','Principles of Economics I'),
('su-student411','Amina Ismail',28,'female','Baidoa','Introduction to Computing'),
('su-student412','Zakariye Jama',24,'male','Jowhar','University Mathematics I'),
('su-student413','Amina Guleed',22,'female','Kismayo','Introduction to Computing'),
('su-student414','Yusuf Hersi',21,'male','Berbera','Academic English I'),
('su-student415','Yusuf Abdi',21,'male','Baidoa','University Mathematics I'),
('su-student416','Deeqa Sheikh',28,'female','Kismayo','Introduction to Computing'),
('su-student417','Abdullahi Yusuf',24,'male','Berbera','University Mathematics I'),
('su-student418','Elmi Yusuf',23,'male','Kismayo','Academic English I'),
('su-student419','Deeqa Isse',27,'female','Baidoa','Academic English I'),
('su-student420','Hodan Abdi',27,'female','Hargeisa','University Mathematics I'),
('su-student421','Farhiya Aden',20,'female','Hargeisa','University Mathematics I'),
('su-student422','Zahra Guleed',27,'female','Berbera','Academic English I'),
('su-student423','Sahra Farah',19,'female','Kismayo','Academic English I'),
('su-student424','Filsan Hussein',27,'female','Berbera','Academic English I'),
('su-student425','Mohamed Hassan',25,'male','Berbera','University Mathematics I'),
('su-student426','Guled Ismail',21,'male','Garowe','Principles of Economics I'),
('su-student427','Ismail Nuur',20,'male','Mogadishu','Principles of Economics I'),
('su-student428','Farah Barre',21,'male','Beledweyne','Academic English I'),
('su-student429','Ismail Mohamed',18,'male','Garowe','Introduction to Computing'),
('su-student430','Fadumo Hassan',18,'female','Baidoa','Arabic Language I'),
('su-student431','Ahmed Aden',23,'male','Beledweyne','Introduction to Computing'),
('su-student432','Khalid Nuur',25,'male','Berbera','Academic English I'),
('su-student433','Ifrah Warsame',19,'female','Hargeisa','Academic English I'),
('su-student434','Elmi Ismail',24,'male','Garowe','Academic English I'),
('su-student435','Ayaan Gedi',20,'female','Mogadishu','University Mathematics I'),
('su-student436','Farhiya Barre',22,'female','Kismayo','Principles of Economics I'),
('su-student437','Zakariye Duale',24,'male','Jowhar','Principles of Economics I'),
('su-student438','Ifrah Egal',22,'female','Beledweyne','Principles of Economics I'),
('su-student439','Hussein Osman',21,'male','Berbera','University Mathematics I'),
('su-student440','Hamza Ismail',22,'male','Hargeisa','Arabic Language I'),
('su-student441','Deeqa Osman',26,'female','Hargeisa','Introduction to Computing'),
('su-student442','Sagal Farah',20,'female','Hargeisa','Academic English I'),
('su-student443','Khalid Farah',20,'male','Kismayo','Arabic Language I'),
('su-student444','Yusuf Jama',26,'male','Mogadishu','Academic English I'),
('su-student445','Mohamed Aden',19,'male','Hargeisa','Principles of Economics I'),
('su-student446','Omar Aden',23,'male','Berbera','Arabic Language I'),
('su-student447','Sahra Hussein',25,'female','Hargeisa','University Mathematics I'),
('su-student448','Abdi Ismail',20,'male','Beledweyne','Arabic Language I'),
('su-student449','Nur Aden',27,'male','Baidoa','Arabic Language I'),
('su-student450','Abdullahi Ali',22,'male','Mogadishu','Arabic Language I'),
('su-student451','Mohamed Hersi',28,'male','Garowe','Academic English I'),
('su-student452','Hamza Awale',21,'male','Baidoa','Principles of Economics I'),
('su-student453','Rahma Samatar',24,'female','Hargeisa','Introduction to Computing'),
('su-student454','Awil Gedi',25,'male','Hargeisa','Principles of Economics I'),
('su-student455','Mohamed Warsame',26,'male','Mogadishu','Arabic Language I'),
('su-student456','Ayaan Samatar',21,'female','Berbera','Academic English I'),
('su-student457','Awil Aden',24,'male','Beledweyne','Principles of Economics I'),
('su-student458','Yasmin Isse',22,'female','Hargeisa','Arabic Language I'),
('su-student459','Sahra Aden',28,'female','Jowhar','Academic English I'),
('su-student460','Ismail Duale',25,'male','Berbera','Arabic Language I'),
('su-student461','Ayaan Mohamed',24,'female','Baidoa','Academic English I'),
('su-student462','Khalid Egal',27,'male','Berbera','Arabic Language I'),
('su-student463','Zakariye Samatar',19,'male','Mogadishu','Principles of Economics I'),
('su-student464','Hibo Abdi',18,'female','Jowhar','Academic English I'),
('su-student465','Liban Aden',25,'male','Jowhar','Arabic Language I'),
('su-student466','Maryan Ismail',26,'female','Kismayo','University Mathematics I'),
('su-student467','Filsan Isse',18,'female','Berbera','University Mathematics I'),
('su-student468','Elmi Ali',26,'male','Garowe','University Mathematics I'),
('su-student469','Jamal Awale',25,'male','Baidoa','Academic English I'),
('su-student470','Mohamed Ali',26,'male','Beledweyne','Introduction to Computing'),
('su-student471','Jawahir Osman',19,'female','Garowe','Arabic Language I'),
('su-student472','Hamza Hersi',27,'male','Jowhar','Arabic Language I'),
('su-student473','Jawahir Isse',28,'female','Berbera','Arabic Language I'),
('su-student474','Sharmarke Gedi',23,'male','Berbera','Introduction to Computing'),
('su-student475','Abdullahi Mohamed',19,'male','Jowhar','Principles of Economics I'),
('su-student476','Mohamed Duale',20,'male','Berbera','Principles of Economics I'),
('su-student477','Dahir Barre',26,'male','Beledweyne','Academic English I'),
('su-student478','Kaafi Hassan',21,'male','Mogadishu','Introduction to Computing'),
('su-student479','Ismail Mire',28,'male','Jowhar','Academic English I'),
('su-student480','Filsan Awale',22,'female','Garowe','Introduction to Computing'),
('su-student481','Hamza Osman',21,'male','Berbera','Arabic Language I'),
('su-student482','Hamdi Warsame',22,'female','Baidoa','Principles of Economics I'),
('su-student483','Awil Barre',26,'male','Kismayo','Academic English I'),
('su-student484','Hussein Aden',24,'male','Garowe','Arabic Language I'),
('su-student485','Hamdi Ismail',24,'female','Beledweyne','Principles of Economics I'),
('su-student486','Bashir Guleed',26,'male','Berbera','Principles of Economics I'),
('su-student487','Naima Yusuf',28,'female','Mogadishu','Arabic Language I'),
('su-student488','Ayaan Ali',20,'female','Garowe','Introduction to Computing'),
('su-student489','Maryan Abdi',19,'female','Kismayo','Academic English I'),
('su-student490','Jamal Ali',27,'male','Jowhar','Academic English I'),
('su-student491','Jawahir Gedi',22,'female','Beledweyne','Academic English I'),
('su-student492','Hassan Isse',22,'male','Mogadishu','Academic English I'),
('su-student493','Omar Gedi',24,'male','Kismayo','Academic English I'),
('su-student494','Jawahir Guleed',27,'female','Hargeisa','Arabic Language I'),
('su-student495','Dahir Hussein',28,'male','Baidoa','University Mathematics I'),
('su-student496','Yasmin Hassan',24,'female','Berbera','Principles of Economics I'),
('su-student497','Ifrah Farah',20,'female','Jowhar','Introduction to Computing'),
('su-student498','Sahra Nuur',19,'female','Hargeisa','Academic English I'),
('su-student499','Kaafi Egal',26,'male','Baidoa','Introduction to Computing'),
('su-student500','Amina Jama',22,'female','Kismayo','Arabic Language I');

INSERT INTO mdlgx_local_prequran_student_profile
  (userid, workspaceid, student_display_name, current_level, course_type,
   status, gender, age_years, city, country, timezone, primary_language,
   live_class_consent, recording_consent, createdby, timecreated, timemodified)
SELECT u.id, @workspaceid, t.display_name, 'year_1', t.course_type,
       'active', t.gender, t.age, t.city, 'Somalia', 'Africa/Mogadishu', 'Somali',
       'yes', 'yes', 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()
FROM tmp_su_profiles t
JOIN mdlgx_user u ON u.username = t.username AND u.deleted = 0
WHERE NOT EXISTS (SELECT 1 FROM mdlgx_local_prequran_student_profile sp WHERE sp.userid = u.id);

DROP TEMPORARY TABLE IF EXISTS tmp_su_profiles;

COMMIT;

-- CLEANUP (when the demo is over; uncomment to use)
-- DELETE sp FROM mdlgx_local_prequran_student_profile sp JOIN mdlgx_user u ON u.id = sp.userid
--   WHERE u.username LIKE 'su-%';
