# -*- coding: utf-8 -*-
"""Lesson 13 - The Moon.

0097 Stage 3: 3ESs.01 the Moon's regular change in position and appearance;
3ESs.02 the relative movement of the Earth and Moon; 3ESs.03 the Earth,
Sun and Moon as approximately spherical; 3TWSm.02 make and use a physical
model; with 3TWSp.02, 3TWSp.03, 3TWSa.03 and 3SIC.01.
"""
from _kit import explain, step, opt, q, part, word, home, cando

LESSON = {
    "slug": "the-moon",
    "title": "The Moon",
    "blurb": "See that the Earth, the Sun and the Moon are all spheres, watch the Moon change through a month, put its phases in order, build a model of the Moon going round the Earth, and find out what people used to think.",
    "steps": [
        step("demo", "Three spheres", "\U0001F30D", "Three balls", ["3ESs.03", "3SIC.01", "3TWSm.02"],
             "The Earth, the Sun and the Moon are all shaped like balls. Press <b>Next</b>, then make a model now, with a grown-up: you need a lamp and a ball on a stick.",
             explain(
                 ["A sphere is a ball shape.", "The Earth, the Sun and the Moon are all roughly spheres."],
                 ["The Earth looks flat from where you stand because it is so big.", "From space it is a blue ball.", "The Moon is a smaller grey ball.", "The Sun is a huge ball of hot, glowing gas.", "Make a model now with a lamp and a ball on a stick: one half of the ball is lit, one half dark."],
                 ["Children think the Moon is a flat disc because it looks flat.", "It is a ball. The line between its lit part and its dark part curves, as it does on a ball lit by a lamp."],
                 ["Press Next through all six, and make the model with a grown-up as you go."]),
             {"frames": [
                 {"scene": {"id": "globe", "state": 0}, "cap": "The <b>Earth</b>: a sphere, seen from space.", "say": "The Earth is a sphere: a ball. It looks flat from where you stand because it is so big, but from space it is a round blue ball."},
                 {"pic": "\U0001F315", "cap": "The <b>Moon</b>: a smaller sphere of rock.", "say": "The Moon is a sphere too, a smaller ball of grey rock. Look at a crescent Moon: the line between the lit part and the dark part is curved. Only a ball lit from one side looks like that."},
                 {"scene": {"id": "sky", "state": 3}, "cap": "The <b>Sun</b>: a huge sphere of hot, glowing gas.", "say": "The Sun is a sphere as well, a huge ball of hot, glowing gas, far bigger than the Earth. Never look straight at it."},
                 {"pic": "\U0001F4DC", "cap": "Long ago, many people thought the Earth was <b>flat</b>. Ships, shadows and, later, photographs from space showed it is a sphere.", "say": "Long ago, many people thought the Earth was flat. Sailors noticed ships disappear bottom first over the horizon. In an eclipse, the Earth's shadow on the Moon is always curved. And now we have photographs from space. The Earth is a sphere."},
                 {"pic": "\U0001F4A1", "cap": "Make a <b>physical model</b> now, with a grown-up. Push a pencil into a small ball: a ball on a stick. The ball is the Moon. A grown-up sets up a lamp in a dark room: the Sun. Do not touch the bulb. One half of the ball is lit, the other half dark.", "say": "Now make a model you can hold, with a grown-up. Push a pencil into a small ball, so it is a ball on a stick. The ball is the Moon. A grown-up sets up a lamp in a dark room. The lamp is the Sun, and you do not touch the bulb. Look: one half of the ball is lit and the other half is dark, just like the real Moon."},
                 {"pic": "\U0001F317", "cap": "Use the model: hold the stick so the ball is a little above your head, and turn slowly on the spot. You see a crescent, a half and a full ball of light. The ball <b>never changes shape</b>.", "say": "Use your model. Your head is the Earth. Hold the stick at arm's length, so the ball is a little above your head, and turn slowly on the spot. You see a thin crescent, then a half, then the whole lit face. The ball never changed shape. Only how much of its lit half you could see changed."},
             ]},
             "Earth, Sun and Moon: three spheres."),

        step("experiment", "The Moon through a month", "\U0001F319", "Moon watch", ["3ESs.01", "3TWSp.03", "3TWSa.03", "3TWSp.02"],
             "Watch the Moon every few nights for a month. Predict what you will see.",
             explain(
                 ["The Moon looks different every night, and the changes repeat every month.", "That is observing over time."],
                 ["New Moon: dark.", "Crescent: a thin slice.", "Half Moon.", "Full Moon: the whole face lit.", "Then back down to new."],
                 ["Children think the Moon really changes shape.", "It is always a ball. We see different amounts of its sunlit side."],
                 ["Predict, watch the month, say what happened, then conclude."]),
             {"sim": "moonPhases",
              "predict": {"ask": "Over a month, what will the Moon do?",
                          "opts": [opt("More of it will look lit each night, then less", True), opt("Look exactly the same every night", False), opt("Disappear for good", False)]},
              "plan": {"ask": "How shall we find out how the Moon changes? Which way is fair?",
                        "opts": [opt("Look at the same time of night, every few nights, and draw what you see", True), opt("Look once at the start of the month and once at the end", False), opt("Look whenever you remember, and try to recall the last one", False)],
                        "why": "Watching the same thing over time is one of the five enquiries. Two looks miss the pattern in between, and remembering is not recording."},
              "runAsk": "Press Three days later, eight times, and watch the Moon change.",
              "happened": {"ask": "What happened to the <b>lit part</b> night after night?",
                           "opts": [opt("More of it was lit each night until it was full, then less each night, back to new", True), opt("It stayed a full circle all month", False), opt("It changed colour", False)],
                           "why": "New, crescent, half, gibbous, full, and back again. Growing is called <b>waxing</b> and shrinking is called <b>waning</b>. A regular pattern, about four weeks long."},
              "conclude": {"ask": "Does the Moon really change shape?",
                           "opts": [opt("No. It is always a sphere; we see different amounts of its sunlit side", True), opt("Yes, it grows and shrinks", False), opt("Yes, it is a different Moon each week", False)],
                           "why": "The Moon is a ball lit by the Sun. As it goes round the Earth, we see more or less of the lit half."}},
             "The Moon's shape seems to change in a regular pattern, every month."),

        step("order", "The phases in order", "\U0001F311", "Moon phases", ["3ESs.01"],
             "Put the Moon's phases in order, starting from the new Moon.",
             explain(
                 ["The phases always come in the same order."],
                 ["New Moon: dark.", "Crescent: a thin lit curve.", "Half Moon: half of the face lit.", "Full Moon: all lit."],
                 ["Children put the full Moon first.", "Start from new, when it is dark, and watch it grow."],
                 ["Tap the new Moon first."]),
             {"items": [
                 {"pic": "\U0001F311", "label": "new Moon", "say": "New Moon. The side facing us is dark. You can hardly see it."},
                 {"pic": "\U0001F312", "label": "crescent", "say": "A crescent: a thin lit curve."},
                 {"pic": "\U0001F313", "label": "half Moon", "say": "Half Moon: half of the face is lit."},
                 {"pic": "\U0001F315", "label": "full Moon", "say": "Full Moon: the whole face is lit. Then it shrinks back to new."},
             ]},
             "New, crescent, half, full. Then back again."),

        step("build", "Build a model: Earth and Moon", "\U0001F527", "Moon model", ["3ESs.02", "3ESs.03", "3TWSm.03"],
             "Build a model on the screen. Tap the Earth, the Moon and the Moon's path, then make it move.",
             explain(
                 ["The Moon goes round the Earth. The Earth spins.", "A model shows both clearly."],
                 ["Add the Earth.", "Add the Moon.", "Add the path the Moon follows.", "Turn one month: the Moon goes right round the Earth.", "Spin one day: the Earth turns once."],
                 ["Children think the Moon goes round once a day.", "It takes about four weeks. It is the Earth that turns once a day."],
                 ["Tap the three parts, then press both buttons."]),
             {"sim": "earthMoon",
              "parts": [
                  {"id": "earth", "label": "the Earth", "pic": "\U0001F30D"},
                  {"id": "moon", "label": "the Moon", "pic": "\U0001F315"},
                  {"id": "orbit", "label": "the Moon's path", "pic": "\U0001F504"},
              ]},
             "The Moon goes round the Earth once a month. The Earth spins once a day."),

        step("context", "What people thought about the sky", "\U0001F4DC", "Sky history", ["3SIC.01", "3ESs.02"],
             "Ideas about the Earth, Sun and Moon have changed. Tap each one.",
             explain(
                 ["What people know changes when they look more carefully."],
                 ["People thought the Earth was flat.", "People thought the Sun went round the Earth.", "Telescopes showed the Moon is a rocky ball with mountains.", "Astronauts stood on the Moon and looked back at the round Earth."],
                 [],
                 ["Tap each one."]),
             {"items": [
                 {"pic": "\U0001F5FA️", "label": "a flat Earth", "say": "Long ago, many people thought the Earth was flat, like a plate, because that is how it looks from the ground."},
                 {"pic": "☀️", "label": "the Sun going round us", "say": "People watched the Sun cross the sky and thought it went round the Earth. It is the Earth that turns. It took careful measuring to prove it."},
                 {"pic": "\U0001F52D", "label": "the telescope", "say": "About four hundred years ago, telescopes showed the Moon is a rocky ball with mountains and craters, not a smooth disc."},
                 {"pic": "\U0001F468\U0001F3FE‍\U0001F680", "label": "astronauts", "say": "In 1969 astronauts stood on the Moon and photographed the Earth: a round blue ball hanging in space."},
             ], "need": 4,
              "then": {"ask": "Why did people think the Earth was flat?",
                       "opts": [opt("Because it looks flat from the ground, and they had not looked from space", True), opt("Because it was flat then", False), opt("Because the Moon told them", False)],
                       "why": "It looks flat because it is so big. Better looking changed the idea."}},
             "Better looking changes what we know."),

        step("questions", "Moon check", "✅", "Moon check", ["3ESs.01", "3ESs.02", "3ESs.03"],
             "Tap the answer.",
             explain(
                 ["Spheres, phases, and who goes round whom."],
                 [],
                 [],
                 ["Read the question, then tap."]),
             {"label": "Question", "items": [
                 q("What shape are the Earth, the Sun and the Moon?", "\U0001F30D", "spheres, like balls", ["flat discs", "cubes"], "All three are spheres."),
                 q("What goes round what?", "\U0001F504", "the Moon goes round the Earth", ["the Earth goes round the Moon", "neither moves"], "The Moon orbits the Earth."),
                 q("How long does the Moon take to go round the Earth once?", "\U0001F319", "about a month", ["one day", "one year"], "About four weeks."),
                 q("Which phase comes after the new Moon?", "\U0001F312", "a crescent", ["a full Moon", "a half Moon"], "A thin curve first."),
                 q("Why does the Moon seem to change shape?", "\U0001F315", "we see different amounts of its sunlit side", ["it really grows and shrinks", "clouds cover it"], "Always a ball, differently lit."),
                 q("The Sun and the Moon look about the same size in the sky. Are they?", "\u2600\uFE0F", "No. The Sun is enormous and very far away.", ["Yes, that is why they look the same", "Yes, the Moon is slightly bigger"],
                   "The Sun is more than a hundred times wider than the Earth; the Moon is a quarter of the Earth's width. Distance makes them look alike."),
                 q("Would an astronaut on the Moon float away?", "\U0001F680", "No. The Moon's gravity pulls them back down, more gently.", ["Yes, there is no gravity on the Moon", "Yes, unless they hold on"],
                   "Astronauts walk and jump on the Moon and come down again. The Moon's gravity is weaker than the Earth's, not missing."),
                 q("Can you ever see the Moon in the daytime?", "\U0001F319", "Yes. It is often up in the day, just harder to spot.", ["No, the Moon only comes up at night", "Only during an eclipse"],
                   "Look for a pale Moon in a blue sky. It is there far more often than people notice."),
                 q("The Moon looks like a thin crescent tonight. Has it changed shape?", "\U0001F311", "No. It is always a ball; we see only the lit part.", ["Yes, the Moon changes shape each week", "Yes, the Earth's shadow cuts it"],
                   "How much of the lit half faces us changes. In a daytime crescent you can often make out the dark part too."),
             ],
              "support": [
                 q("Is the Moon nearer to us than the Sun?", "\U0001F319", "Yes", ["No"],
                   "The Moon is far closer. The Sun only looks that size because it is enormous and very far away."),
                 q("Is the Earth a sphere?", "\u26AA", "Yes", ["No"],
                   "The Earth, the Sun and the Moon are all spheres."),
                 q("Has anybody ever walked on the Moon?", "\U0001F45F", "Yes", ["No"],
                   "Astronauts have, and their footprints are still there."),
                 q("Is the Sun bigger than the Moon?", "\u2600\uFE0F", "Yes", ["No"],
                   "Enormously bigger. It only looks the same size because it is so far away."),
              ],
              "extension": [
                 q("You look for the Moon at the same clock time each night for a week. Is it in the same place?", "\U0001F30C", "no - it has moved along its circle, so it is somewhere different", ["yes, exactly the same place every night", "it never moves at all"],
                   "The Moon is travelling round us all the while. Where it sits at eight o'clock tonight is not where it sat last night."),
                 q("Astronauts left footprints on the Moon fifty years ago and they are still there. Why?", "\U0001F45F", "there is no wind or rain on the Moon to wear them away", ["the dust there is unusually sticky", "somebody looks after them"],
                   "Footprints on Earth are washed and blown away. The Moon has no air and no weather, so nothing disturbs them."),
                 q("Half the Moon is always in sunlight. So why can we sometimes see none of it?", "\U0001F311", "at that point the lit half is facing away from us", ["the Sun stops shining on it", "the Earth's shadow covers all of it"],
                   "The Moon is never unlit. What changes is how much of the lit side is turned our way."),
                 q("Why is the Moon easier to study with a telescope than the Sun?", "\U0001F52D", "you can look at the Moon safely, and you must never look at the Sun", ["the Moon is bigger", "the Sun is further away than the Moon"],
                   "The Moon is only reflecting light. The Sun's own light would damage your eyes at once."),
              ]},
             "You know your Moon.",
             mis=["6.1-m1", "6.1-m2", "6.2-m1", "6.3-m1"]),

        step("quiz", "Show what you know", "⭐", "Star scientist", ["3ESs.01", "3ESs.02", "3ESs.03", "3TWSm.02", "3SIC.01"],
             "Time to show what you know. Tap the answer.",
             explain(
                 ["No new ideas here.", "Every question uses something you have already done in this lesson."],
                 [],
                 [],
                 ["Take your time. Read it, look at it, then tap."]),
             {"items": [
                 q("Why does the Earth look flat from the ground?", "\U0001F5FA️", "because it is so big", ["because it is flat", "because of the clouds"], "A huge ball looks flat up close."),
                 q("Put in order, starting from the new Moon: full Moon, new Moon, crescent.", "\U0001F311", "new Moon, crescent, full Moon", ["full Moon, new Moon, crescent", "crescent, full Moon, new Moon"], "New, crescent, half, full."),
                 q("What lights the Moon?", "☀️", "the Sun", ["the Earth", "its own fire"], "The Moon shines back the Sun's light."),
                 q("How long does the Earth take to spin round once?", "\U0001F30D", "one day", ["one month", "one year"], "Once a day: that makes day and night."),
                 q("What did you build on the screen?", "\U0001F527", "a model of the Earth and the Moon", ["a real Moon", "a diagram of the Sun"], "A model you could make move."),
                 q("While the Moon goes round the Earth once, how often does the Earth spin?", "\U0001F504", "once every day, for about a month", ["only once", "once a year"], "A day is one spin, and the Moon takes about a month to go round."),
                 q("What did telescopes show about the Moon?", "\U0001F52D", "it is a rocky ball with mountains and craters", ["it is made of cheese", "it is flat"], "Better looking, better knowing."),
                 q("Which is the biggest?", "☀️", "the Sun", ["the Earth", "the Moon"], "The Sun is far bigger than the Earth."),
                 q("In the lamp-and-ball model, why does the ball sometimes look like a crescent?", "\U0001F312", "you can see only a thin part of its lit half", ["the ball has shrunk", "the lamp is broken"], "The ball is always a ball. Where it is decides how much of the lit half you can see."),
                 q("The Moon takes about a month to go round the Earth. If you watch it for two months, how many full Moons will you see?", "\U0001F315", "about two", ["about one", "about sixty"], "One trip round the Earth, one full Moon. Two months, two trips."),
                 q("In the lamp-and-ball model, what does the lamp stand for, and why?", "\U0001F4A1", "the Sun, because it gives the light", ["the Moon, because it is round", "the Earth, because we live on it"], "The lamp lights the ball, as the Sun lights the Moon."),
             ],
              "support": [
                 q("Is the Moon a ball or a flat disc?", "\u26AA", "a ball", ["a flat disc"],
                   "The Moon is spherical, like the Earth."),
                 q("Does the Moon make its own light?", "\U0001F319", "No", ["Yes"],
                   "The Moon shines back the Sun's light."),
                 q("Does the Earth spin round once a day?", "\U0001F30D", "Yes", ["No"],
                   "Once a day, and that is what gives us day and night."),
                 q("Which is bigger, the Earth or the Moon?", "\U0001F30D", "the Earth", ["the Moon"],
                   "The Earth is much the bigger of the two."),
              ],
              "extension": [
                 q("The same side of the Moon always faces us. So what had nobody ever seen until a spacecraft went round it?", "\U0001F6F0\uFE0F", "the far side of the Moon", ["the lit side of the Moon", "the Moon's craters"],
                   "The Moon turns once for each trip round the Earth, so one face is always towards us. The far side was first photographed in 1959."),
                 q("A model of the Moon's phases uses a ball and a lamp. What does it get right that a drawing cannot?", "\U0001F315", "that the lit part changes because of WHERE you look from", ["the colour of the Moon", "how far away the Moon is"],
                   "Walk round the lit ball and the shape you see changes, with nothing about the ball changing. That is the whole idea."),
                 q("The Moon has one sixth of Earth's gravity. What would that change about walking on it?", "\U0001F45F", "each step would carry you much further, and you would still come back down", ["you would float away altogether", "nothing would feel different"],
                   "Weaker gravity, not no gravity. The astronauts bounced; they did not drift off."),
                 q("People once thought the Earth was flat and now nobody does. What changed their minds?", "\U0001F30E", "evidence - ships, shadows, photographs from space", ["somebody simply decided otherwise", "nothing changed, it was always known"],
                   "Ideas in science change when the evidence changes, not when opinions do."),
              ]},
             "That is the whole lesson finished, and the whole of Grade 3 Science."),
    ],
}

LESSON["about"] = [
    "Say that the Earth, the Sun and the Moon are spheres.",
    "Describe how the Moon's appearance changes through a month, in order.",
    "Say how the Earth and the Moon move.",
    "Make and use a lamp-and-ball model of the Moon, and build a model of the Earth and the Moon on the screen.",
]

LESSON["warmup"] = [
    q("Where is a fossil found?", "\U0001F41F", "in rock", ["in a cloud", "in the sky"], "A fossil is a shape kept in rock for a very long time."),
    q("When is the Moon easiest to see?", "\U0001F319", "at night", ["at lunchtime", "never"], "The Moon is easiest to see in the dark night sky."),
    q("A material that lets no light through at all is called...", "\U0001F944", "opaque", ["transparent", "translucent"],
      "No light through means opaque."),
    q("Which keeps its own shape, a solid or a liquid?", "\U0001F9F1", "a solid", ["a liquid"],
      "A solid keeps its shape. A liquid takes the shape of its container."),
]

LESSON["lecture"] = [
    part("\U0001F30D", "Three spheres",
         "The Earth, the Sun and the Moon are all shaped like balls: spheres. The Earth looks flat from where you stand because it is so big. From space it is a round blue ball."),
    part("\U0001F319", "The Moon's month",
         "Look at the Moon every night and it seems to change. A thin crescent, then a half Moon, then a full circle, then back down to nothing. It takes about four weeks and then it starts again."),
    part("\U0001F315", "Always a ball",
         "The Moon does not really change shape. It is always a ball, and the Sun lights one half of it. As the Moon goes round the Earth, we see more or less of that lit half."),
    part("\U0001F504", "Round and round",
         "The Moon goes round the Earth once a month. The Earth spins once a day, and that gives us day and night. Today you will build a model that does both."),
    part("\U0001F4DC", "What people used to think",
         "Long ago people thought the Earth was flat and the Sun went round it. Careful measuring, telescopes and finally photographs from space changed all that. Science changes when people look more carefully."),
]

LESSON["words"] = [
    word("sphere", "\U0001F30D", "A ball shape.",
         ["The Earth is a sphere.", "The Moon is a smaller sphere."]),
    word("Moon", "\U0001F315", "The ball of rock that goes round the Earth once a month.",
         ["The Moon shines back the Sun's light.", "The Moon goes round the Earth."]),
    word("phase", "\U0001F313", "How much of the Moon looks lit on one night: new, crescent, half, full.",
         ["Tonight's phase is a crescent.", "The phases repeat every month."]),
    word("crescent", "\U0001F312", "A thin curved slice of lit Moon.",
         ["A crescent Moon came after the new Moon.", "The crescent grew into a half Moon."]),
    word("full Moon", "\U0001F315", "The phase when the whole face of the Moon is lit.",
         ["A full Moon lit up the garden.", "After the full Moon it shrinks again."]),
    word("orbit", "\U0001F504", "The path something takes going round something else.",
         ["The Moon's orbit round the Earth takes a month.", "We drew the orbit as a dotted line."]),
    word("spin", "\U0001F30D", "To turn round on the spot. The Earth spins once a day.",
         ["The Earth spins, so we get day and night.", "Spin the globe slowly."]),
    word("spherical", "\u26AA", "Shaped like a ball.",
         ["The Earth is spherical.", "The Sun and the Moon are spherical too."]),
    word("crater", "\U0001F311", "A dent in the surface of a moon or a planet, made by a rock from space.",
         ["The Moon is covered in craters.", "A crater is a hole made by a rock hitting the surface."]),
    word("gibbous", "\U0001F314", "The phase when we can see more than half of the lit Moon, but not all of it.",
         ["A gibbous Moon is bigger than a half Moon.", "Gibbous comes between half and full."]),
    word("waxing", "\U0001F312", "Growing. More of the Moon is lit each night.",
         ["A waxing Moon is getting bigger.", "The Moon waxes from new to full."]),
    word("waning", "\U0001F318", "Shrinking. Less of the Moon is lit each night.",
         ["A waning Moon is getting smaller.", "The Moon wanes from full back to new."]),
]

LESSON["cando"] = [
    cando("I can describe the shape of the Earth, the Sun and the Moon.", "3ESs.03"),
    cando("I can describe how the Moon moves.", "3ESs.02"),
    cando("I can describe the phases of the Moon.", "3ESs.01"),
    cando("I can explain why the Moon seems to change shape when it does not.", "3ESs.01"),
    cando("I can learn science from a model, and say what the model leaves out.", "3TWSm.02"),
    cando("I can make a model of something I cannot hold.", "3TWSm.03"),
    cando("I can name the five types of scientific enquiry.", "3TWSp.02"),
    cando("I can record what I saw in a table.", "3TWSa.03"),
    cando("I can say how people's ideas about the sky have changed.", "3SIC.01"),
]

LESSON["home"] = [
    home("Moon diary", "A clear night sky, a grown-up, a notebook, a pencil",
         ["With a grown-up, look at the Moon every night you can see it. Draw its shape and write the date.",
          "Keep going for about a month.",
          "Look at the row of drawings."],
         "New, crescent, half, full, and back. Observing over time."),
    home("A lamp and a ball", "A lamp in a dark room, a ball on a stick, a grown-up to set up the lamp",
         ["Stand with the lamp on one side. The lamp is the Sun; the ball is the Moon; you are the Earth.",
          "Hold the ball a little above your head and turn slowly on the spot.",
          "Watch how much of the lit side of the ball you can see."],
         "The ball is always a ball. You see a crescent, a half, a full, just like the Moon."),
    home("Day and night with a lamp", "A lamp in a dark room, a ball or an orange, a small sticker, a grown-up to set up the lamp",
         ["The lamp is the Sun and the ball is the Earth. Put the sticker on the ball: that is where you live.",
          "Hold the ball near the lamp, without touching the bulb, and turn it slowly.",
          "Watch the sticker move from the lit half into the dark half, and back."],
         "Half the ball is always lit and half is dark. As the Earth spins, you go from day into night. That is a physical model."),
]
