# -*- coding: utf-8 -*-
"""Lesson 8 - Energy Everywhere.

0097 Stage 4: 4Pf.01 energy is in all matter and in sound, light and heat;
4Pf.02 energy cannot be made or destroyed, only transferred; 4Pf.03 energy
is needed for any movement or action; 4Pf.04 some energy is transferred to
the surroundings as sound, light or heat; with 4TWSp.03, 4TWSa.01,
4TWSa.03, 4TWSa.04 and 4TWSc.08.
"""
from _kit import explain, step, opt, q, part, word, home, cando

LESSON = {
    "slug": "energy-everywhere",
    "title": "Energy Everywhere",
    "blurb": "Find energy in everything around you, drop a ball and track where its energy goes bounce by bounce, record it, chart it, and learn the rule: energy is never made or lost, only transferred.",
    "steps": [
        step("explore", "Where energy is", "⚡", "Energy hunt", ["4Pf.01", "4Pf.03"],
             "Energy is in everything. Tap each one.",
             explain(
                 ["Energy is what makes things happen. It is in every material, and in sound, light and heat.", "Nothing moves, changes or happens without it."],
                 ["A moving ball has energy.", "A stretched band has energy waiting.", "Sound is energy travelling through air.", "Light and heat are energy from the Sun."],
                 ["Children think energy is only electricity.", "Electricity is one way energy travels. A hot cup, a loud drum and a rolling ball all have it too."],
                 ["Tap all six."]),
             {"items": [
                 {"pic": "⚽", "label": "a moving ball", "sub": "movement energy", "say": "A moving ball has energy. That is why it can knock things over. The faster it goes, the more it has."},
                 {"pic": "\u27B0", "label": "a stretched band", "sub": "stored energy", "say": "A stretched elastic band has energy stored in it, waiting. Let go and it becomes movement."},
                 {"pic": "\U0001F50A", "label": "sound", "sub": "energy in the air", "say": "Sound is energy travelling through the air as vibrations. A loud drum has more of it than a whisper."},
                 {"pic": "☀️", "label": "light", "sub": "energy from the Sun", "say": "Light is energy. It travels from the Sun to Earth and plants catch it to make food."},
                 {"pic": "\U0001F525", "label": "heat", "sub": "energy in warm things", "say": "Heat is energy. A hot cup has more than a cold one, and it passes into your hands."},
                 {"pic": "\U0001F34E", "label": "food", "sub": "stored energy", "say": "Food has energy stored in it. Your body takes it out to move, grow and stay warm. No food, no action."},
             ], "need": 6,
              "then": {"ask": "What is needed for any movement or action to happen?",
                       "opts": [opt("energy", True), opt("electricity", False), opt("water", False)],
                       "why": "Every action needs energy. Electricity is only one way to carry it."}},
             "Energy is in everything, and every action needs it."),

        step("experiment", "Where does the energy go?", "⚽", "Bounce tracker", ["4Pf.02", "4Pf.04", "4TWSp.03", "4TWSa.01", "4TWSa.03"],
             "Drop a ball three times. Predict what happens to its bounces.",
             explain(
                 ["Energy cannot be made or destroyed. It can only be transferred: moved from one thing, or one form, to another.", "Held up high, the ball has stored energy. As it falls, that becomes movement energy. Each bounce, some of it goes into sound and heat in the surroundings."],
                 ["Bounce one: 3 marks high, with a thud.", "Bounce two: 2 marks. Some energy left as sound and warmth.", "Bounce three: 1 mark.", "None of it vanished. The bars always add up to the same total. It is in the room now."],
                 ["Children say the energy is used up.", "It is never used up. It is transferred somewhere less useful."],
                 ["Predict, drop it three times, say what happened, then conclude."]),
             {"sim": "energyDrop",
              "predict": {"ask": "What will happen to the bounces?",
                          "opts": [opt("Each bounce will be lower than the last", True), opt("Every bounce will be the same height", False), opt("The bounces will get higher", False)]},
              "plan": {"ask": "How shall we find out how the bounce height changes? Which way is fair?",
                        "opts": [opt("Drop the same ball from the same height onto the same floor, and measure every bounce", True), opt("Drop it from a different height each time", False), opt("Drop it once and measure only the first bounce", False)],
                        "why": "Same ball, same height, same floor - then the only thing left to change is the bounce number, which is what you are studying."},
              "runAsk": "Press Drop the ball three times. Read each bounce height on the marked scale, and watch the bars.",
              "happened": {"ask": "What happened to each <b>bounce</b>?",
                           "opts": [opt("Each bounce was lower; the movement energy fell as the sound and warmth rose", True), opt("Every bounce was the same", False), opt("The ball bounced higher each time", False)],
                           "why": "The ball's movement energy was transferred, bounce by bounce, into sound you heard and a little warmth in the ball and floor."},
              "conclude": {"ask": "Where did the ball's energy go?",
                           "opts": [opt("It was transferred to the surroundings as sound and heat; none was destroyed", True), opt("It was used up and disappeared", False), opt("It stayed in the ball", False)],
                           "why": "Energy cannot be destroyed. It was transferred out of the ball's movement into the room."}},
             "Energy is never lost. It is transferred, often as sound and heat.",
             mis=["2.3-m1"]),

        step("record", "Record the bounces", "\U0001F4CB", "Bounce table", ["4TWSc.08", "4Pf.04"],
             "Fill in the table. How high was the <b>%s</b>?",
             explain(
                 ["The heights you read off the marked scale, in a table."],
                 ["First bounce: 3 marks.", "Second: 2.", "Third: 1."],
                 [],
                 ["Tap the height for each bounce."]),
             {"ask": "How high was the %s?",
              "columns": ["Bounce", "Height in marks"],
              "rows": [
                  {"pic": "1️⃣", "label": "first bounce", "answer": "3", "why": "the first bounce reached three marks."},
                  {"pic": "2️⃣", "label": "second bounce", "answer": "2", "why": "the second reached two: some energy had gone into sound and heat."},
                  {"pic": "3️⃣", "label": "third bounce", "answer": "1", "why": "the third reached one mark."},
              ],
              "choices": [{"id": "3", "t": "3 marks", "pic": "📏"}, {"id": "2", "t": "2 marks", "pic": "📏"}, {"id": "1", "t": "1 mark", "pic": "📏"}],
              "read": [
                  {"ask": "Read your table. Which bounce was the highest?",
                   "opts": [opt("the first", True), opt("the second", False), opt("the third", False)],
                   "why": "Each bounce is lower than the one before it."},
                  {"ask": "Each bounce is lower than the last. Where is the energy going?",
                   "opts": [opt("into sound and warmth, and into the floor", True), opt("it is being destroyed", False), opt("into making the ball heavier", False)],
                   "why": "You hear each bounce - that is some of the energy leaving as sound. None of it is destroyed."},
              ]},
             "Three, two, one. Each bounce lower."),

        step("graph", "Chart the bounces", "\U0001F4CA", "Bounce chart", ["4TWSa.04", "4TWSa.02", "4Pf.04"],
             "Turn the table into a bar chart, then read the pattern.",
             explain(
                 ["A bar chart shows the three heights side by side against a scale."],
                 ["Tap until each bar is right.", "Then say the pattern."],
                 [],
                 ["Build the bars, then answer."]),
             {"columns_label": "Bounce", "value_label": "Height in marks", "unit": "marks", "bar": True,
              "columns": [{"pic": "1️⃣", "label": "first", "value": 3}, {"pic": "2️⃣", "label": "second", "value": 2}, {"pic": "3️⃣", "label": "third", "value": 1}],
              "pattern": {"ask": "What is the pattern?",
                          "opts": [opt("Each bounce is lower than the one before, as energy is transferred away", True), opt("Each bounce is higher", False), opt("There is no pattern", False)],
                          "why": "A falling staircase: three, two, one. Energy leaving the ball each bounce."},
              "read": [
                  {"ask": "Read the chart. How many marks lower was the third bounce than the first?",
                   "opts": [opt("two marks", True), opt("one mark", False), opt("the third was higher", False)],
                   "why": "Three marks, then two, then one. Each bounce loses energy as sound and warmth, so each bar is shorter."},
                  {"ask": "If you let it bounce ten times, what would the chart look like?",
                   "opts": [opt("the bars would keep getting shorter until it stopped", True), opt("the bars would level out and stay the same", False), opt("the bars would start growing again", False)],
                   "why": "It loses energy at every bounce, so it never gets back to where it started and in the end it stops."},
              ]},
             "A falling staircase: energy transferred away each bounce."),

        step("demo", "Energy on the move", "\U0001F504", "Transfers", ["4Pf.02", "4Pf.03", "4Pf.04"],
             "Energy is always being transferred from one thing to another. Press <b>Next</b> to follow it.",
             explain(
                 ["Energy moves. It goes from food into your muscles, from your foot into a ball, from a lamp into light.", "And some always leaks into the surroundings as sound, light or heat."],
                 ["Food to muscle.", "Muscle to ball.", "Ball to sound and heat on the floor.", "A lamp: electricity in, light out, and the bulb gets a little warm."],
                 ["Children think a warm bulb is a broken bulb.", "Every transfer warms something. The warmth is energy that went to the surroundings."],
                 ["Press Next through all five."]),
             {"frames": [
                 {"pic": "\U0001F34E", "cap": "Energy stored in your breakfast.", "say": "Energy starts stored in your breakfast."},
                 {"pic": "\U0001F9B5", "cap": "Your muscles transfer it into movement when you kick.", "say": "Your muscles take it out of the food and transfer it into movement: a kick."},
                 {"pic": "⚽", "cap": "The kick transfers it into the ball, which flies.", "say": "The kick transfers the energy into the ball, which flies across the pitch."},
                 {"pic": "\U0001F50A", "cap": "The ball hits the wall: some energy becomes <b>sound</b>, some <b>warms</b> the wall. It was not lost.", "say": "The ball hits the wall. Thump. Some of its energy became sound, and some warmed the wall a tiny bit. None of it was lost. It was transferred to the surroundings."},
                 {"pic": "\U0001F4A1", "cap": "A lamp: electricity in, light out, and the bulb gets a little warm. Every transfer leaks a little.", "say": "A lamp is the same. Electricity goes in, light comes out, and the bulb gets a little warm. Every transfer leaks some energy to the surroundings as heat, light or sound."},
             ]},
             "Energy is transferred from thing to thing, and some always leaks out as sound, light or heat."),

        step("questions", "Energy near you", "\U0001F3D8\uFE0F", "Energy near you", ["4SIC.02", "4SIC.05"],
             "Where is science used near you, and what does it do to the environment? Tap the answer.",
             explain(
                 ["Science and technology are all around where you live.", "They can help the environment, harm it, or both at once."],
                 ["Solar panels on a roof turn light into electricity.", "Wind turbines make electricity without burning anything.",
                  "Cars burn fuel, and the fumes pollute the air."],
                 ["Children think a technology is simply good or simply bad.", "A new road gets people to school faster and takes away a habitat. Both are true."],
                 ["Think about your own street, then tap."]),
             {"label": "Question", "items": [
                 q("Where might you see science making electricity near where you live?", "\u2600\uFE0F", "solar panels on a roof", ["a sandcastle", "a skipping rope"], "Solar panels turn light energy into electrical energy."),
                 q("A town builds wind turbines instead of burning coal. What is good about that for the environment?", "\U0001F32C\uFE0F", "less smoke and pollution in the air", ["more rubbish in the sea", "fewer trees can grow"], "Wind turbines make electricity without burning anything."),
                 q("Cars carry people quickly from place to place. What is one bad effect on the environment?", "\U0001F697", "their fumes pollute the air", ["the roads get longer", "the cars get heavier"], "Burning fuel makes fumes. A technology can help and harm."),
                 q("A new road is built across a field near your school. Which is a bad effect?", "\U0001F6A7", "animals lose their habitat", ["people get to school faster", "the shops get more customers"], "The other two are good effects. One change can have both."),
             ],
              "support": [
                 q("Do solar panels need the Sun?", "\u2600\uFE0F", "Yes", ["No"],
                   "A solar panel turns sunlight into electricity, so it needs the Sun."),
                 q("Does burning coal make smoke?", "\U0001F3ED", "Yes", ["No"],
                   "Burning coal puts smoke and pollution into the air."),
                 q("Does a wind turbine need wind?", "\U0001F32C\uFE0F", "Yes", ["No"],
                   "No wind, no turning, no electricity."),
                 q("Do car fumes make the air dirtier?", "\U0001F697", "Yes", ["No"],
                   "They pollute the air, which is one of a car's bad effects."),
              ],
              "extension": [
                 q("A wind turbine makes no smoke, and some people still do not want one near their house. Name a reason that is not about pollution.", "\U0001F32C\uFE0F", "the noise it makes, or how it looks on the skyline", ["there is no such reason", "it would use up all the wind"],
                   "Weighing up a technology means listing every effect, not only the one you set out to fix."),
                 q("Solar panels make no electricity at night. What does a town have to do about that?", "\U0001F319", "get its electricity another way at night, or store some from the day", ["go without electricity after dark", "nothing - panels work in the dark too"],
                   "Every way of making electricity has a limit, which is why places rarely rely on only one."),
                 q("A town could build wind turbines or burn more coal. Name one thing to weigh on each side.", "\u2696\uFE0F", "turbines make no smoke but need wind; coal works any time and pollutes", ["there is nothing to weigh - turbines always win", "coal has no bad effects"],
                   "Weighing means naming the cost of the option you prefer, not only the cost of the other one."),
                 q("Streetlights help people see and confuse moths and bats. Should they be switched off?", "\U0001F4A1", "it is a decision about both effects, not a fact science can settle alone", ["yes, the moths matter most", "no, the moths do not matter"],
                   "Science can tell you what happens. What to do about it is a choice people make with that evidence."),
              ]},
             "Science is used near you, and it can help or harm the environment."),

        step("questions", "Energy check", "✅", "Energy check", ["4Pf.01", "4Pf.02", "4Pf.03", "4Pf.04"],
             "Tap the answer.",
             explain(
                 ["Energy everywhere, never lost, always needed, always leaking a little."],
                 [],
                 [],
                 ["Read the question, then tap."]),
             {"label": "Question", "items": [
                 q("Which of these has energy?", "⚡", "all of them: a moving ball, a hot cup and a loud drum", ["only the moving ball, not the others", "only the hot cup, not the others"], "Energy is in everything."),
                 q("Can energy be destroyed?", "\U0001F6D1", "no, only transferred", ["yes, when it is used", "yes, in the cold"], "The rule."),
                 q("Each bounce of the ball was lower because...", "⚽", "energy was transferred to sound and heat", ["the ball got heavier", "the ball got tired"], "Transferred, not lost."),
                 q("A lamp gets warm. Why?", "\U0001F4A1", "some energy leaks to the surroundings as heat", ["the bulb must be broken", "light makes things colder"], "Every transfer leaks."),
                 q("What does every movement need?", "\U0001F3C3\U0001F3FE", "energy", ["light", "sound"], "No energy, no action."),
                 q("Could you hold a handful of energy?", "\u26A1", "No - things HAVE energy, and it is not made of stuff", ["Yes, there is some in a battery", "Yes, with the right gloves"],
                   "You cannot put energy in a jar. You see what it does - movement, heat, light, sound - and that is how you know it is there."),
             ],
              "support": [
                 q("Does a hot cup of tea have energy?", "\u2615", "Yes", ["No"],
                   "Anything hot has energy, and so does anything moving."),
                 q("Does your food give you energy?", "\U0001F34E", "Yes", ["No"],
                   "The energy to run or kick a ball comes from what you eat."),
                 q("Does a hot oven have energy?", "\U0001F373", "Yes", ["No"],
                   "Anything hot has energy, whether it is moving or not."),
                 q("Can energy be made out of nothing?", "\u26A1", "No", ["Yes"],
                   "It can only be transferred from somewhere else."),
              ],
              "extension": [
                 q("Two identical balls are dropped from the same height, one onto carpet and one onto tiles. Which bounces higher?", "\U0001F3C0", "the one on tiles - the carpet takes more of the energy as it squashes", ["the one on carpet", "both exactly the same"],
                   "A soft surface takes a bigger share of the movement energy, so there is less left to bounce with."),
                 q("A ball is held still, high above the floor. Does it have any energy before you let go?", "\U0001FA80", "yes - stored energy, simply because of how high it is", ["no, because it is not moving", "only once it hits the floor"],
                   "Height is a store. Letting go turns that store into movement, which is why a higher drop bounces higher."),
                 q("A lamp gets warm as well as bright. Is the warmth wasted?", "\U0001F4A1", "it is energy that went somewhere useless to you, and it was not destroyed", ["yes, it vanishes completely", "no, the warmth is the point of a lamp"],
                   "Nothing is lost. Some of it simply ends up somewhere you had no use for."),
                 q("A drum is hit and the sound dies away. Where did the energy of the sound go?", "\U0001F941", "spread out into the air and the room as tiny amounts of warmth", ["it was destroyed by the air", "back into the drum"],
                   "Energy spreads out until it is too thinly spread to notice. That is what 'dying away' is."),
              ]},
             "You know where energy goes.",
             mis=["2.1-m1"]),

        step("quiz", "Show what you know", "⭐", "Star scientist", ["4Pf.01", "4Pf.02", "4Pf.03", "4Pf.04", "4TWSa.04"],
             "Time to show what you know. Tap the answer.",
             explain(
                 ["No new ideas here.", "Every question uses something you have already done in this lesson."],
                 [],
                 [],
                 ["Take your time. Read it, look at it, then tap."]),
             {"items": [
                 q("Where does the energy to kick a ball come from?", "⚽", "your food", ["the ball", "the air"], "Stored in food, taken out by muscles."),
                 q("Sound is...", "\U0001F50A", "energy travelling through the air", ["not a kind of energy at all", "a kind of light you can hear"], "Vibrations carrying energy."),
                 q("A stretched elastic band has...", "\u27B0", "stored energy", ["no energy until it moves", "only sound energy"], "Let go and it moves."),
                 q("Energy cannot be made or destroyed. It can only be...", "\U0001F504", "transferred", ["hidden", "eaten"], "Moved from thing to thing."),
                 q("Which chart did you draw of the bounces?", "\U0001F4CA", "a bar chart, three bars getting shorter", ["a map of the room", "a pie chart in three slices"], "A falling staircase."),
                 q("A ball thumps into a wall. The thump is...", "\U0001F50A", "some of the ball's energy transferred as sound", ["the wall making brand new energy", "nothing to do with energy"], "Sound is energy."),
                 q("Why can a ball never bounce back to the exact height it was dropped from?", "⚽", "some energy always leaks away as sound and heat", ["gravity gets stronger after each bounce", "the ball gets heavier as it bounces"], "Every transfer leaks."),
                 q("Which has more energy?", "\U0001F321️", "a hot cup of tea", ["a cold cup of tea"], "Heat is energy."),
                 q("A wind-up toy runs until it stops. Where did the energy stored in its spring go?", "\U0001F914", "into movement, then sound and heat in the room", ["it was destroyed when the toy stopped", "it went back into the key"], "Energy is never destroyed. The spring's stored energy became movement, and the movement leaked away as sound and heat."),
                 q("Predict: a ball is dropped from higher up. How will its first bounce change?", "\u26BD", "it bounces higher, because it started with more energy", ["it bounces lower, because it falls further", "it bounces the same, because it is the same ball"], "Higher up, the ball has more stored energy to begin with."),
                 q("Why does your hand get warm when you rub it on a table?", "\u270B", "some energy of the movement is transferred as heat", ["the table makes new energy", "the energy of the movement is destroyed"], "Energy is never made or destroyed. The movement's energy becomes heat."),
             ],
              "support": [
                 q("Does a moving ball have energy?", "\U0001F3D0", "Yes", ["No"],
                   "Anything moving has energy."),
                 q("Can energy be destroyed?", "\u26A1", "No", ["Yes"],
                   "It can only be passed on or spread out."),
                 q("Does a stretched spring hold stored energy?", "\u27B0", "Yes", ["No"],
                   "Stored, and it does nothing until something lets it go."),
                 q("Is sound a kind of energy?", "\U0001F50A", "Yes", ["No"],
                   "Sound is energy travelling through the air."),
              ],
              "extension": [
                 q("Someone says they have built a wheel that spins for ever with nothing pushing it. Why can that not work?", "\u2699\uFE0F", "a little energy leaves as sound and heat every turn, so it must slow down", ["the wheel would need to be much bigger", "it would work, but only out in space"],
                   "Every transfer leaks a little energy into the surroundings. Nothing keeps all of it, so nothing can run for ever."),
                 q("A phone battery goes flat. What has really happened?", "\U0001F50B", "its stored energy has been passed on to light, sound and heat", ["the energy inside it was used up and destroyed", "the energy leaked out of the case"],
                   "'Flat' is everyday language, not science. The energy went into the screen, the speaker and the warmth of the phone in your hand."),
                 q("A ball dropped from 1 metre bounces to 60 cm, and from 2 metres to 120 cm. What is the pattern?", "\U0001F3C0", "it bounces back to about the same fraction of whatever height it started at", ["it always bounces to 60 cm", "there is no pattern"],
                   "A pattern lets you predict a drop you have not tried. Notice it is a fraction, not a fixed height."),
                 q("Why can no machine keep going for ever without being fed energy?", "\u2699\uFE0F", "some energy always leaves as sound and warmth, so it has to be replaced", ["machines could, if they were built well enough", "energy is destroyed inside a machine"],
                   "Nothing is destroyed. It leaks away where the machine cannot use it, and that is enough to stop it."),
              ]},
             "That is the whole lesson finished. Energy is everywhere, and it is never lost.",
             mis=["2.1-m2", "2.2-m1"]),
    ],
}

LESSON["about"] = [
    "Say where energy is: in everything, and in sound, light and heat.",
    "Say the rule: energy is never made or destroyed, only transferred.",
    "Track where a bouncing ball's energy goes.",
    "Record it in a table and chart it as a bar chart.",
]

LESSON["warmup"] = [
    q("Vinegar poured on bicarbonate of soda fizzes. What is made?", "\U0001F9EA", "a new gas", ["more vinegar", "nothing new at all"], "From the last lesson: a chemical reaction makes a new substance."),
    q("What makes a toy car start to move?", "\U0001F697", "a push or a pull", ["its colour", "being left alone"], "A push or a pull makes things start to move."),
]

LESSON["lecture"] = [
    part("⚡", "Energy everywhere",
         "Energy is what makes things happen. A moving ball has it. A stretched band has it stored. Sound carries it through the air. Light and heat carry it from the Sun. Your food has it. Energy is in everything."),
    part("\U0001F3C3\U0001F3FE", "Nothing moves without it",
         "Every movement, every action, needs energy. Your muscles take it from your food. A lamp takes it from electricity. A plant takes it from light. No energy, and nothing happens at all."),
    part("\U0001F504", "Never made, never lost",
         "Here is the big rule. Energy cannot be made, and it cannot be destroyed. It can only be transferred: moved from one thing to another, or from one form to another. Food to muscle. Muscle to ball."),
    part("⚽", "Where it goes",
         "Drop a ball. Thud. It bounces, but lower. Some of its movement energy became sound, and some warmed the ball and the floor a tiny bit. Bounce by bounce, the energy leaks into the room. It is not lost. It has moved."),
    part("\U0001F4A1", "Leaking out",
         "Every transfer leaks a little into the surroundings as sound, light or heat. That is why a bulb gets a little warm and a bouncing ball stops. Today you track it, record it and chart it."),
]

LESSON["words"] = [
    word("energy", "⚡", "What makes things happen. It is in everything, and every action needs it.",
         ["A moving ball has energy.", "Food gives you energy."]),
    word("transfer", "\U0001F504", "To move energy from one thing to another, or one form to another.",
         ["The kick transfers energy to the ball.", "Energy is transferred, never lost."]),
    word("stored energy", "\u27B0", "Energy kept ready in something, like a stretched band or food.",
         ["A stretched band has stored energy.", "Food is stored energy."]),
    word("movement energy", "⚽", "The energy a moving thing has.",
         ["A rolling ball has movement energy.", "Faster means more movement energy."]),
    word("surroundings", "\U0001F3E0", "Everything around a thing: the air, the floor, the room.",
         ["Some energy leaks to the surroundings.", "The bounce warmed the surroundings a little."]),
    word("sound", "\U0001F50A", "Energy travelling through the air as vibrations.",
         ["The thud was sound energy.", "A drum makes sound energy."]),
    word("heat", "\U0001F525", "Energy in warm things. It passes from hot to cold.",
         ["Heat leaks from the bulb.", "A hot cup has heat energy."]),
]

LESSON["cando"] = [
    cando("I know that energy is in everything, and in sound, light and heat.", "4Pf.01"),
    cando("I know that energy cannot be made or destroyed, only passed on.", "4Pf.02"),
    cando("I know that nothing happens at all without energy.", "4Pf.03"),
    cando("I know that some energy always spreads out into the surroundings.", "4Pf.04"),
    cando("I can find a pattern in my results.", "4TWSa.02"),
    cando("I can present my results in a table and a bar chart.", "4TWSa.04"),
    cando("I can say how science is used where I live.", "4SIC.02"),
    cando("I can talk about the good and bad effects of using science.", "4SIC.05"),
]

LESSON["home"] = [
    home("Bounce count", "A ball, a hard floor, a wall with marks or a tape measure",
         ["Drop the ball from shoulder height and watch the first bounce. Mark how high.",
          "Watch the second and third bounces and mark those.",
          "Draw a bar chart of the three heights."],
         "A falling staircase. Say where the energy went after each bounce."),
    home("Feel the leak", "Your hands, a grown-up, and something electrical that has been on for a while: a lamp, a television or a laptop",
         ["Rub your hands together hard for twenty seconds. Feel them.",
          "With a grown-up, hold your hand near, not on, the lamp, the back of the television or the bottom of the laptop. Feel for warmth.",
          "Say what energy went in, and what came out."],
         "Movement became heat. Electricity became light, sound and heat. Modern LED bulbs waste very little energy as heat, so a lamp may feel only a little warm, but every transfer leaks some."),
    home("Energy trail", "Paper and a pencil, one thing you did today",
         ["Pick something you did: ran, kicked, rode a bike.",
          "Draw the energy trail: Sun, plant, food, you, the action, then sound and heat.",
          "Put an arrow on each step."],
         "Every action traces back to the Sun."),
]
