# -*- coding: utf-8 -*-
"""Grade 4's "How do you know?" claims, read by
../lesson-app-tools/add-reasoning-step.py (build-all.sh runs it after every
build - these pages are generated).

Each item: a claim that is TRUE, the reason that explains it, two reasons that
do not, and what makes the difference. Every wrong reason is either the
mistake the lesson teaches against, or something true that explains nothing -
"7 add 5 is 12" offered as the reason two odd numbers ALWAYS make an even one
is the kind this step exists for: one example is not a reason.
"""

BANKS = {
"big-numbers-below-zero": [
 ("In 4,072 there are no hundreds.",
  "The hundreds column holds a 0.",
  ["4,072 is less than 5,000.", "The 7 is next to the 0."],
  "Read each column. A 0 means there is none of that place."),
 ("34 times 10 is 340.",
  "Every digit moves one place left, so 3 tens become 3 hundreds and 4 ones become 4 tens.",
  ["You put a 0 on the end.", "10 is a round number."],
  "Putting a 0 on the end gives the right digits here, but moving every digit is what really happens."),
 ("Minus 2 is bigger than minus 9.",
  "On the number line, minus 2 is further right than minus 9.",
  ["Both numbers are below zero.", "Minus 2 uses fewer digits."],
  "Both are below zero is true, and it does not say which is bigger. Further right is bigger."),
 ("4,630 rounds to 4,600 to the nearest hundred.",
  "It is 30 past 4,600 and 70 short of 4,700, so 4,600 is nearer.",
  ["It has a 6 in the hundreds.", "4,600 is a round number."],
  "Compare the distances to the two neighbours. The nearer one wins."),
 ("4,208 is the same as 3 thousands, 12 hundreds and 8 ones.",
  "One thousand was swapped for ten hundreds, and 3,000 add 1,200 add 8 is 4,208.",
  ["Both have an 8 in the ones.", "12 is more than 2."],
  "Regrouping changes how a number is stored, not how big it is."),
 ("It is 3 degrees and it gets 5 degrees colder, so now it is minus 2.",
  "Counting down 5 from 3 goes 2, 1, 0, minus 1, minus 2.",
  ["5 take away 3 is 2.", "Cold weather is below zero."],
  "5 take away 3 is 2 is true, but the temperature started at 3 and went down past zero."),
],
"patterns-and-squares": [
 ("An odd number add an odd number is always even.",
  "Each odd number has one left over, and the two leftovers make a pair.",
  ["7 add 5 is 12.", "Odd numbers end in 1, 3, 5, 7 or 9."],
  "7 add 5 is 12 is one example, and one example cannot show it always happens."),
 ("If triangle take away 14 is 30, the triangle is 44.",
  "The triangle is the whole, so put the parts back together: 30 add 14 is 44.",
  ["30 take away 14 is 16.", "44 is bigger than 30."],
  "The shape comes first, so it stands for the whole amount."),
 ("5, 12, 19, 26 is a linear sequence.",
  "Every step is add 7, the same each time.",
  ["It keeps getting bigger.", "The first step is add 7."],
  "One step is not enough. Every step must be the same."),
 ("16 is a square number.",
  "16 dots make a 4 by 4 square.",
  ["16 is an even number.", "16 is 8 add 8."],
  "Even, and 8 add 8, are both true, and neither makes a square. Four rows of four do."),
 ("Growing a 6 by 6 square into a 7 by 7 square adds 13 dots.",
  "You add 6 along one side, 6 along the other, and 1 in the corner.",
  ["13 is an odd number.", "7 is one more than 6."],
  "Both are true and neither counts the dots. The L along two edges does."),
 ("If square add square add square is 24, each square is 8.",
  "The same shape is the same number, so 24 splits into 3 equal parts of 8.",
  ["24 is in the 8 times table.", "There are 3 squares, and 8 is bigger than 3."],
  "24 is in the 8 times table, but it is in the 6 and the 4 times tables too."),
],
"ways-to-calculate": [
 ("347 add 185 is 532.",
  "The ones make 12, carry a ten. The tens make 13, carry a hundred. The hundreds make 5.",
  ["It is about 500, because 300 and 200 make 500.", "347 and 185 are both odd."],
  "An estimate tells you roughly. Only the exact working tells you it is 532."),
 ("623 take away 187 is 436.",
  "Exchange a ten and then a hundred: 13 take away 7 is 6, 11 take away 8 is 3, and 5 take away 1 is 4.",
  ["Take the smaller digit from the bigger in each column.", "436 is less than 623."],
  "Taking the smaller digit from the bigger gives 564. Exchanging is what makes each column work."),
 ("16 times 25 is the same as 8 times 50.",
  "Halving one number and doubling the other leaves the answer the same.",
  ["Both have a 5 in them.", "8 and 50 are easier numbers."],
  "Easier numbers is why you would do it, not why the answer stays the same."),
 ("342 times 6 is 2,052.",
  "300 times 6 is 1,800, 40 times 6 is 240, and 2 times 6 is 12, which add up to 2,052.",
  ["300 times 6 is 1,800, and 2 times 6 is 12.", "342 is close to 350."],
  "Every part must be multiplied. Leaving out the 40 leaves you 240 short."),
 ("87 divided by 5 is 17 remainder 2.",
  "17 fives are 85, and the 2 left over is less than 5.",
  ["87 ends in 7, and 7 take away 5 is 2.", "17 is an odd number."],
  "Check it by putting it back together: 17 fives and 2 more make 87."),
 ("24 is a multiple of 6.",
  "6 times 4 is 24.",
  ["24 is bigger than 6.", "24 is an even number."],
  "A bigger number is not always a multiple. 25 is bigger than 6, and it is not a multiple of 6."),
],
"parts-of-a-whole": [
 ("One eighth is smaller than one quarter.",
  "The same whole cut into 8 pieces has smaller pieces than when it is cut into 4.",
  ["8 is bigger than 4.", "Both are unit fractions."],
  "Both are unit fractions is true and explains nothing. More pieces make each piece smaller."),
 ("3 cakes shared between 4 children gives each child three quarters of a cake.",
  "3 divided by 4 is three quarters.",
  ["4 take away 3 is 1.", "There are more children than cakes."],
  "More children than cakes tells you each gets less than a whole cake, but not how much."),
 ("One fifth of 20 is 4.",
  "Make 5 equal groups from 20, and each group holds 4.",
  ["20 divided by 4 is 5.", "4 is less than 20."],
  "The bottom number says how many groups to make. The answer is what is in one of them."),
 ("One half and four eighths are worth the same.",
  "Four eighths cover exactly the same part of the whole as one half.",
  ["Both have even numbers in them.", "Both are less than one."],
  "Put the two bars side by side. If they end in the same place, they are worth the same."),
 ("25 per cent is the same as one quarter.",
  "25 out of 100 is the same share as 1 out of 4.",
  ["25 is less than 100.", "A quarter is a small part."],
  "Per cent means out of a hundred, and a quarter of 100 is 25."),
 ("Two fifths add one fifth is three fifths.",
  "The pieces are all fifths, so you count them: 2 and 1 make 3.",
  ["You add the tops and the bottoms.", "3 is bigger than 2."],
  "Adding the bottoms would say the pieces had changed size, and they have not."),
],
"telling-the-time": [
 ("180 minutes is 3 hours.",
  "Every hour is 60 minutes, and 180 divided by 60 is 3.",
  ["180 is 100 add 80.", "Hours are longer than minutes."],
  "Hours are longer is true, but you need to know it is 60 minutes each to get 3."),
 ("3:30 pm is 15:30.",
  "Afternoon hours have 12 added, and 3 add 12 is 15.",
  ["15 is 3 times 5.", "Both times have 30 minutes."],
  "Both have 30 minutes is true, but the hour is what changes, and it changes by 12."),
 ("12:20 am is 00:20.",
  "12 am is midnight, and the first hour after midnight is written 00.",
  ["There is no 12 in 24 hour time.", "20 minutes is the same in both."],
  "Midday is 12:00, so 12 does appear. It is the hour after midnight that is 00."),
 ("From 10:40 to 12:15 is 1 hour and 35 minutes.",
  "20 minutes to 11:00, 1 hour to 12:00 and 15 minutes to 12:15 make 1 hour and 35 minutes.",
  ["12:15 take away 10:40 is 1:75.", "Both times are before lunch."],
  "Time does not go in hundreds. Count on to the whole hour first."),
 ("To be at the library by 09:30, catch the bus that arrives at 09:25.",
  "It is the latest bus that still arrives before 09:30.",
  ["It is the first bus.", "09:25 is close to 09:30."],
  "09:45 is close to 09:30 too, and it is late. The latest bus that is still in time is the one."),
 ("9 days after 28 April is 7 May.",
  "2 days reach 30 April, and the other 7 days go into May.",
  ["28 add 9 is 37.", "May comes after April."],
  "28 add 9 is 37 is true, but April has only 30 days."),
],
"shape-and-measures": [
 ("A cube has 6 faces.",
  "It has a top, a bottom and 4 sides, and each one is a flat square face.",
  ["It has 12 edges.", "A dice is a cube."],
  "12 edges is true, but edges are not faces. Count the flat squares."),
 ("Six squares joined in a cross fold up into a cube.",
  "Each square becomes one face, and no two of them land on the same side.",
  ["A cube has 6 faces.", "The cross is symmetrical."],
  "A cube needs 6 faces, but not every six squares fold into one. They must not overlap when folded."),
 ("A rectangle has 2 lines of symmetry, not 4.",
  "Only the fold down the middle and the fold across the middle make the halves match.",
  ["It has 4 sides.", "It is not a square."],
  "It is not a square is true, but you still have to test the diagonals to know."),
 ("An angle of 120 degrees is obtuse.",
  "It is bigger than a right angle, 90 degrees, and smaller than a straight line.",
  ["120 is a big number.", "Its arms are long."],
  "The arms can be any length. Only the turn compared with 90 degrees decides."),
 ("A rectangle 5 squares wide and 3 squares high has an area of 15 squares.",
  "It has 3 rows of 5 squares, and 3 times 5 is 15.",
  ["5 add 3 is 8.", "It is wider than it is tall."],
  "Area counts every square inside, so it is the rows times the squares in each row."),
 ("Circles cannot tile a floor.",
  "However you pack circles together, there are always gaps between them.",
  ["Circles have no corners.", "Circles are round."],
  "No corners is true, and it is the gaps between them that stop a tiling."),
],
"where-things-are": [
 ("A quarter turn clockwise from north faces east.",
  "Clockwise goes north, east, south, west, and a quarter turn moves on one point.",
  ["East is where the sun rises.", "North is at the top of a map."],
  "Where the sun rises is true, and it does not tell you which way you turned."),
 ("North-east is between north and east.",
  "Its name joins the two points it sits between.",
  ["It starts with N.", "It is written NE."],
  "Written NE is true, and it is written that way because it joins north and east."),
 ("The point 2, 6 is not the same place as 6, 2.",
  "The first number is along and the second is up, so they land in different places.",
  ["They use different numbers.", "6 is bigger than 2."],
  "They use the SAME numbers, in a different order, and a different order is a different place."),
 ("A rectangle with corners at 1, 1 and 4, 3 has another corner at 4, 1.",
  "It takes its along from 4, 3 and its up from 1, 1.",
  ["4 and 1 are both in the question.", "It is at the bottom of the grid."],
  "Each missing corner takes its along from one corner and its up from the other."),
 ("A square 3 away from the mirror line has its reflection 3 away on the other side.",
  "A reflection is always the same distance from the mirror line.",
  ["3 is a small number.", "Mirrors show you the same thing."],
  "The distance stays the same. Only the side changes."),
 ("Going 3 east and then 2 north lands 3 squares right and 2 squares up.",
  "East moves along to the right and north moves up, one square for each step.",
  ["3 add 2 is 5.", "East comes before north."],
  "The two moves change different things, so they are not added together."),
],
"asking-sorting-chance": [
 ("To find the class favourite fruit, you collect names, not numbers.",
  "The answers are groups you can name, like mango and banana.",
  ["Fruit is good for you.", "There are lots of different fruits."],
  "Decide what kind of answer the question needs before you collect anything."),
 ("Four tally gates and 2 more marks make 22.",
  "Each gate is 5, so four gates are 20, and 2 more make 22.",
  ["There are 6 groups of marks.", "22 is an even number."],
  "Count the gates in fives, then count on the loose marks."),
 ("12 goes where the even hoop and the more than 10 hoop overlap.",
  "12 is even, and 12 is more than 10, so it belongs in both hoops.",
  ["12 is a big number.", "12 is in the 2 times table."],
  "The overlap is for numbers where the answer to both questions is yes."),
 ("Rolling a 7 on an ordinary dice is impossible.",
  "An ordinary dice only has the numbers 1 to 6.",
  ["7 is an odd number.", "A dice is a cube."],
  "Impossible means it can never happen, however many times you roll."),
 ("After 1000 spins, each quarter of the spinner comes up close to 250 times.",
  "Each part is a quarter of the spinner, and a quarter of 1000 is 250.",
  ["1000 is a lot of spins.", "The spinner has 4 colours."],
  "4 colours is true, but the parts must also be equal for each to come up a quarter of the time."),
 ("In Class 4B, the bus is the most common way to school.",
  "11 of the 22 children come by bus, more than any other way.",
  ["Buses are big.", "There are 22 children in the class."],
  "The data answers it, not what you think about buses."),
],
}
