# -*- coding: utf-8 -*-
"""Lesson 1 - Alive or Never Alive.

0097 Stage 1: 1Bp.01 living things and things that have never been alive;
1Bp.02 animals need air, water and suitable food; 1Bp.03 plants need light
and water (the water half - light is Lesson 2's experiment); with 1TWSp.01,
1TWSp.02, 1TWSc.01, 1TWSc.04, 1TWSc.05, 1TWSa.01 and 1SIC.04 exercised on
the way.
"""
from _kit import explain, step, opt, q, part, word, home, cando

LESSON = {
    "slug": "alive-or-never-alive",
    "title": "Alive or Never Alive",
    "blurb": "Sort the living things from the things that were never alive, find out what animals and plants need, and do your first real experiment.",
    "steps": [
        step("demo", "What makes something alive?", "\U0001F410", "Alive!", ["1Bp.01"],
             "Press <b>Next</b> and watch the goat. Living things do four things.",
             explain(
                 ["Alive means a thing grows, needs food, needs water and can have young.", "A thing that was never alive does none of those."],
                 ["Look at the goat.", "It grew from a baby goat, called a kid, into a big goat.", "It needs food, so it eats grass.", "It needs water, so it drinks.", "And it can have a baby goat of its own.",
                  "A plant needs food too. It makes its own food in its leaves, using light.",
                  "Now look at the stone.", "It never grows, never needs food or water, and never has a baby stone."],
                 ["Children think anything that moves is alive.", "A car moves and a river moves, but they were never alive.", "Moving is not the test. Growing, needing food and water, and having young are."],
                 ["So press Next, and each time ask: does the goat do this? Does the stone?"]),
             {"frames": [
                 {"pic": "\U0001F410", "cap": "This is a goat. Is it alive? Let us check.", "say": "This is a goat. Is it alive? Let us check four things."},
                 {"pic": "\U0001F410➡️\U0001F410", "cap": "It <b>grows</b>. A baby goat, called a kid, grows into a big goat.", "say": "One. It grows. A baby goat, called a kid, grows into a big goat."},
                 {"pic": "\U0001F410\U0001F33F", "cap": "It <b>needs food</b>. It eats grass.", "say": "Two. It needs food. The goat eats grass. A plant needs food too, but it makes its own, using sunlight."},
                 {"pic": "\U0001F410\U0001F4A7", "cap": "It <b>needs water</b>. It drinks.", "say": "Three. It needs water. The goat drinks. A plant takes in water through its roots."},
                 {"pic": "\U0001F410\U0001F410", "cap": "It can have <b>young</b>: baby goats.", "say": "Four. It can have young. A goat has baby goats, called kids. So the goat is alive!"},
                 {"pic": "\U0001FAA8", "cap": "A stone never grows, needs no food or water, and has no young. It was <b>never alive</b>.", "say": "Now a stone. Does it grow? No. Does it need food or water? No. Can it have young? No. A stone was never alive."},
             ]},
             "Alive means it grows, needs food and water, and can have young. A stone does none of these."),

        step("explore", "Alive, or never alive?", "\U0001F50D", "Looked closely", ["1Bp.01"],
             "Tap each picture and hear whether it is alive.",
             explain(
                 ["Most things you see are alive, or were never alive. Some, like a fallen leaf, were alive once."],
                 ["Tap the mango tree.", "A tree does not walk, but it takes in water, it makes its own food from sunlight, it grows taller every year, and it makes seeds that grow into new trees.", "So a tree is alive.",
                  "Tap the spoon.", "It never grows, needs no food or water, and never has baby spoons.", "It was never alive."],
                 ["Children say a tree is not alive because it does not move about.", "Plants are alive.", "They grow and they make seeds, and that is enough.",
                  "The other slip is about water and the Sun.", "Children say water is alive because plants need it, and the Sun is alive because plants need its light.",
                  "Helping a living thing to live does not make a thing alive.",
                  "A biscuit keeps you alive. Is the biscuit alive? No.", "Water does not grow, eat or have young. Nor does the Sun."],
                 ["Tap every picture and listen for the reason each time."]),
             {"items": [
                 {"pic": "\U0001F415", "label": "dog", "say": "A dog is alive. It grows, needs food and water, and can have puppies."},
                 {"pic": "\U0001F333", "label": "mango tree", "say": "A mango tree is alive. It grows tall, needs water, makes its own food from sunlight, and makes seeds for new trees."},
                 {"pic": "\U0001FAA8", "label": "stone", "say": "A stone was never alive. It does not grow, and it needs no food or water."},
                 {"pic": "\U0001F944", "label": "spoon", "say": "A spoon was never alive. Somebody made it. It never grows."},
                 {"pic": "\U0001F425", "label": "chick", "say": "A chick is alive. It eats seeds, drinks and grows into a chicken."},
                 {"pic": "\U0001F697", "label": "car", "say": "A car moves, but it was never alive. It does not eat, grow or have babies."},
                 {"pic": "\U0001F33B", "label": "sunflower", "say": "A sunflower is alive. It grows from a seed and takes in water through its roots."},
                 {"pic": "\U0001F9F8", "label": "teddy bear", "say": "A teddy bear was never alive. It looks like a bear, but it never eats or grows."},
                 {"pic": "\U0001F4A7", "label": "water", "say": "Water was never alive. Plants need water to live, but that does not make the water alive. It never grows, eats or has young."},
                 {"pic": "☀️", "label": "the Sun", "say": "The Sun was never alive. Plants need its light to live, but the Sun does not grow, eat or have young. A biscuit keeps you alive, and a biscuit is not alive either."},
             ], "need": 10},
             "You looked closely at ten things. Now you can sort them.",
             mis=["1.1-m2"]),

        step("sort", "Sort them into three bins", "\U0001F5C2️", "Sorted it", ["1Bp.01", "1TWSc.01"],
             "Is it <b>alive</b>, did it <b>use to be alive</b>, or was it <b>never alive</b>? Tap the right bin.",
             explain(
                 ["Sorting means putting things into groups by looking at what is the same about them.",
                  "This time there are three groups, because some things are tricky."],
                 ["Look at the thing in the box.", "Ask the four questions: does it grow? Does it need food? Does it need water? Can it have young?",
                  "If yes, tap Alive.",
                  "If no, ask one more question: was it ever alive?",
                  "A hen eats, drinks, grows and lays eggs, so hen goes in Alive.",
                  "A fallen leaf does none of those now, but it grew on a tree, so it goes in Used to be alive.",
                  "A cup was never alive at all, so cup goes in Never alive."],
                 ["Children put a cloud or a river in Alive because it moves.", "Moving is not the test.",
                  "A river does not eat or have babies.",
                  "And children put a wooden spoon in Never alive.", "Wood comes from a tree, and the tree was alive.",
                  "Ask: did this come from something that was once living?"],
                 ["Take your time with each one and say the reason out loud before you tap."]),
             {"ask": "Alive, used to be alive, or never alive?",
              "bins": [{"id": "alive", "label": "Alive", "pic": "\U0001F331"},
                       {"id": "was", "label": "Used to be alive", "pic": "\U0001F342"},
                       {"id": "never", "label": "Never alive", "pic": "\U0001FAA8"}],
              "items": [
                  {"pic": "\U0001F414", "label": "hen", "bin": "alive", "why": "A hen eats, drinks, grows and lays eggs."},
                  {"pic": "☕", "label": "cup", "bin": "never", "why": "A cup never eats or grows. It was never alive."},
                  {"pic": "\U0001F342", "label": "fallen leaf", "bin": "was", "why": "A fallen leaf is not alive now, but it grew on a tree. It used to be alive."},
                  {"pic": "\U0001F41F", "label": "fish", "bin": "alive", "why": "A fish eats, grows and has baby fish."},
                  {"pic": "\U0001F30A", "label": "river", "bin": "never", "why": "A river moves, but it does not eat, grow or have babies."},
                  {"pic": "\U0001F334", "label": "palm tree", "bin": "alive", "why": "A palm tree takes in water, grows and makes seeds."},
                  {"pic": "\U0001F9F1", "label": "brick", "bin": "never", "why": "A brick was never alive. It does not grow."},
                  {"pic": "\U0001F41D", "label": "bee", "bin": "alive", "why": "A bee eats and grows, and baby bees grow in the hive."},
                  {"pic": "☁️", "label": "cloud", "bin": "never", "why": "A cloud moves in the sky, but it does not eat or have babies."},
                  {"pic": "\U0001F944", "label": "wooden spoon", "bin": "was", "why": "A wooden spoon is made of wood, and wood comes from a tree. The tree used to be alive."},
                  {"pic": "\U0001F33F", "label": "grass", "bin": "alive", "why": "Grass grows. Cut it and it grows back. It is alive."},
                  {"pic": "\U0001F9F8", "label": "toy bear", "bin": "never", "why": "A toy bear was made in a factory. It never eats or grows."},
                  {"pic": "\U0001F41A", "label": "seashell", "bin": "was", "why": "A shell was the home of a little sea animal. That animal used to be alive."},
              ]},
             "Alive, used to be alive, or never alive. Three groups, and you can tell them apart.",
             mis=["1.1-m1", "1.1-m3"]),

        step("ask", "Ask a science question", "❓", "Asked why", ["1TWSp.01"],
             "Look at the puppy. Scientists start with a question. Tap one you would like to ask.",
             explain(
                 ["Science starts with a question about the world.", "Then scientists work out how to find the answer."],
                 ["Look at the puppy.", "You could ask: why does it sleep so much?", "Or: what does it eat?", "Any of those is a good science question.",
                  "Then ask: how could we find out?", "The best way is to watch the puppy carefully and see."],
                 ["Children think a question has to be answered by a grown-up.", "Often the best answer comes from looking carefully yourself."],
                 ["Tap a question, then tap the best way to find its answer."]),
             {"pic": "\U0001F436",
              "questions": ["Why does the puppy sleep so much?", "What does the puppy like to eat?", "How big will the puppy grow?"],
              "findOut": {"ask": "How could we find out the answer?",
                          "opts": [opt("Watch the puppy carefully every day and see", True), opt("Just guess", False), opt("Ask the puppy", False)],
                          "why": "Watching carefully is called observing. Scientists find answers by observing."}},
             "A good scientist asks a question, then watches carefully to find out."),

        step("demo", "What animals need", "\U0001F431", "Air, water, food", ["1Bp.02"],
             "Press <b>Next</b>. Every animal, and you, needs three things to stay alive.",
             explain(
                 ["Animals need air, water and the right food to stay alive.", "People are animals too, so you need them as well."],
                 ["Take a breath in.", "That is air going into your body, and you need it every minute.",
                  "When you feel thirsty, your body is asking for water.", "When you feel hungry, your body is asking for food.",
                  "A cat needs the same three things.", "It breathes air, drinks water and eats cat food."],
                 ["Children say a cat needs a toy or a bed.", "Those are nice, but a cat can live without them.", "It cannot live without air, water and food.",
                  "Children also say that people are not animals.", "In science, people ARE animals.",
                  "You need air, water and food, just as a cat does. You are a very special animal, and still an animal.",
                  "And about the right food: eating well does not mean never having a cake again.",
                  "A cake or a sweet is a treat, once or twice a week. It is eating a lot of them, every day, that is not good for you."],
                 ["Press Next and say the three needs with me: air, water, food."]),
             {"frames": [
                 {"pic": "\U0001F431", "cap": "A cat is an animal. What does it need to stay alive?", "say": "A cat is an animal. What does it need to stay alive? Three things."},
                 {"pic": "\U0001F32C️", "cap": "<b>Air.</b> It breathes in and out all day.", "say": "Air. The cat breathes in and out all day, even when it is asleep."},
                 {"pic": "\U0001F4A7", "cap": "<b>Water.</b> It drinks when it is thirsty.", "say": "Water. The cat drinks when it is thirsty."},
                 {"pic": "\U0001F41F", "cap": "<b>The right food.</b> Cat food, not sweets.", "say": "The right food. A cat eats cat food, not sweets. Every animal has food that is right for it."},
                 {"pic": "\U0001F9D2", "cap": "You are an animal too. You need <b>air, water and food</b>.", "say": "You are an animal too. In science, people are animals. You need air, water and food, just like the cat."},
                 {"pic": "\U0001F34E\U0001F370", "cap": "Most days: food that helps you grow. <b>Now and then</b>: a treat.", "say": "The right food for you is food that helps you grow, most days. A cake or a sweet is a treat, now and then. Eating well does not mean never having one."},
             ]},
             "Every animal needs air, water and the right food. You are an animal too.",
             mis=["5.4-m1", "5.4-m3"]),

        step("sort", "What does the cat need?", "\U0001F37D️", "Needs it", ["1Bp.02", "1TWSc.01"],
             "Does the cat <b>need</b> this to stay alive? Tap the right bin.",
             explain(
                 ["Need means cannot live without it.", "Want means it would be nice to have."],
                 ["Water: can the cat live without water? No. So it is a need.", "A ball of wool: fun, but the cat can live without it. So it is not a need."],
                 ["Children put a bed in Needs because the cat sleeps in it.", "A cat can sleep on the floor. The bed is not a need."],
                 ["For each thing ask: could the cat stay alive without it?"]),
             {"ask": "Does the cat need this to stay alive?",
              "bins": [{"id": "need", "label": "Needs it", "pic": "✅"}, {"id": "want", "label": "Does not need it", "pic": "❌"}],
              "items": [
                  {"pic": "\U0001F4A7", "label": "water", "bin": "need", "why": "A cat cannot live without water."},
                  {"pic": "\U0001F9F6", "label": "ball of wool", "bin": "want", "why": "Fun to chase, but a cat can live without it."},
                  {"pic": "\U0001F32C️", "label": "air", "bin": "need", "why": "A cat has to breathe air every minute."},
                  {"pic": "\U0001F6CF️", "label": "cat bed", "bin": "want", "why": "Cosy, but a cat can sleep anywhere."},
                  {"pic": "\U0001F41F", "label": "cat food", "bin": "need", "why": "A cat cannot live without the right food."},
                  {"pic": "\U0001F380", "label": "ribbon", "bin": "want", "why": "A ribbon is pretty, but a cat does not need it."},
                  {"pic": "\U0001F4FA", "label": "television", "bin": "want", "why": "A cat does not need a television."},
              ]},
             "Air, water and the right food. Everything else is a want."),

        step("experiment", "Does a plant need water?", "\U0001F9EA", "Experiment!", ["1Bp.03", "1TWSp.02", "1TWSc.04", "1TWSa.01"],
             "Two plants. We will <b>water one</b> and give the other <b>no water</b>. First, predict!",
             explain(
                 ["This experiment is a fair test.", "Two plants that are the same, and we change only one thing: the water."],
                 ["First you predict.", "That means you say what you think will happen before we start.",
                  "Then we water one plant every day and give the other nothing, and we wait five days.",
                  "Then you say what happened, and whether it matched your prediction."],
                 ["Children think a wrong prediction means they did badly.", "It does not.", "Scientists are wrong all the time.",
                  "When your prediction is wrong, that is the moment you learn something new. Real scientists have found new things that way.",
                  "So say what really happened, even when it is not what you said would happen. Never change your prediction to match.",
                  "One more thing, about how much water. This plant gets none at all, and that is the test.",
                  "It does not mean a plant needs a lot of water every day.", "Plants outside do not get rain every day, and the soil in a pot stays damp for several days."],
                 ["Tap your prediction, then press the button once for each day and watch both plants."]),
             {"sim": "plantWater",
              "predict": {"ask": "What do you think will happen to the plant with <b>no water</b>?",
                          "opts": [opt("It will droop and go yellow", True), opt("It will grow bigger than the other one", False), opt("Nothing will change", False)]},
              "plan": {"ask": "How shall we find out whether a plant needs water? Which way is <b>fair</b>?",
                       "opts": [opt("Two plants the same. Water one, give the other none. Keep everything else the same", True),
                                opt("Water one plant and put the other one in a dark cupboard", False),
                                opt("Water a big plant and give a tiny plant none", False)],
                       "why": "A fair test changes ONE thing. Change the water and nothing else, and then you know it was the water."},
              "runAsk": "Press the button once for each day. Watch the plant with no water.",
              "happened": {"ask": "What happened to the plant with no water?",
                           "opts": [opt("It drooped and went yellow", True), opt("It grew taller", False), opt("It stayed exactly the same", False)],
                           "why": "Without water the plant drooped and its leaves went yellow. Plants need water to stay alive."},
              "conclude": {"ask": "So what did we find out?",
                           "opts": [opt("Plants need water to stay alive", True),
                                    opt("Plants do not need water", False),
                                    opt("Only big plants need water", False)],
                           "why": "One plant had water and stayed green. The other had none and drooped. So plants need water."}},
             "Plants need water. Without it they droop and go yellow.",
             mis=["1.4-m1", "5.4-m2"]),

        step("record", "Record what you saw", "\U0001F4DD", "Recorded it", ["1TWSc.05", "1Bp.03"],
             "Scientists write down what happened. Fill in the table for <b>%s</b>.",
             explain(
                 ["A table is a tidy way to write down what you saw, so you do not forget and so other people can read it."],
                 ["Each row is one plant.", "The second column is what it looked like after five days.",
                  "The watered plant was fresh and green.", "The plant with no water was droopy and yellow.", "Tap the row, then tap the picture that matches."],
                 ["Children write down what they expected instead of what they saw.", "A table only holds what really happened."],
                 ["Think back to the experiment and fill in each row."]),
             {"ask": "After five days, what did the %s look like?",
              "columns": ["Plant", "After 5 days"],
              "rows": [
                  {"pic": "\U0001F4A7", "label": "watered plant", "answer": "fresh", "why": "the watered plant stayed fresh and green."},
                  {"pic": "\U0001F6AB", "label": "plant with no water", "answer": "droopy", "why": "the plant with no water drooped and went yellow."},
              ],
              "choices": [{"id": "fresh", "t": "Fresh and green", "pic": "\U0001F33F"}, {"id": "droopy", "t": "Droopy and yellow", "pic": "\U0001F940"}],
              "read": [
                  {"ask": "Look at your table. Which plant was <b>droopy and yellow</b>?",
                   "opts": [opt("the plant with no water", True), opt("the watered plant", False), opt("both of them", False)],
                   "why": "Your table says it: the row for the plant with no water."},
                  {"ask": "Your table has two rows. What was <b>different</b> between the two plants?",
                   "opts": [opt("one got water and the other got none", True),
                            opt("one was bigger to start with", False),
                            opt("one was in the dark", False)],
                   "why": "Only the water was different. That is what made it a fair test."},
              ]},
             "That is a real science table, and you filled it in."),

        step("context", "Caring for living things", "\U0001F49A", "I care", ["1SIC.04", "1Bp.02", "1Bp.03"],
             "Living things need us to look after them. Tap each picture to hear how.",
             explain(
                 ["Because we know what living things need, we can look after them, and we can stop hurting them by mistake."],
                 ["A plant in a pot cannot walk to a river.", "Somebody has to water it.",
                  "A goat in a pen cannot open the food sack.", "Somebody has to feed it.",
                  "Rubbish thrown in a river can hurt the fish that live there."],
                 ["Children think nature looks after itself.", "The living things near people depend on people."],
                 ["Tap each picture, then answer the question."]),
             {"items": [
                 {"pic": "\U0001FAB4", "label": "water the plant", "say": "A plant in a pot cannot find its own water. Water it and it stays green."},
                 {"pic": "\U0001F410", "label": "feed the goat", "say": "A goat in a pen needs somebody to bring food and clean water every day."},
                 {"pic": "\U0001F41F", "label": "keep the river clean", "say": "Rubbish in a river can hurt the fish. Keeping it clean keeps them alive."},
                 {"pic": "\U0001F333", "label": "plant a tree", "say": "A new tree gives shade, and a home for birds. Science tells us what it needs to grow."},
             ], "need": 4,
              "then": {"ask": "Your pot plant is drooping. What does it most likely need?",
                       "opts": [opt("Water", True), opt("A bigger pot", False), opt("A toy", False)],
                       "why": "You saw it in the experiment: a plant with no water droops. Water it."}},
             "Knowing what living things need helps us look after them."),

        step("quiz", "Show what you know", "⭐", "Star scientist", ["1Bp.01", "1Bp.02", "1Bp.03"],
             "Time to show what you know. Tap the answer.",
             explain(
                 ["No new ideas here.", "Every question uses something you have already done in this lesson."],
                 ["If it asks whether a thing is alive, ask the four questions: does it grow, need food, need water, have young?",
                  "If it asks what an animal needs, think air, water, food.", "If it asks about plants, think water and light."],
                 [],
                 ["Take your time. Read it, look at it, then tap."]),
             {"items": [
                 q("Which one is alive?", "❓", "a camel", ["a rock", "a metal spoon", "a plastic cup"], "A camel eats, drinks, grows and can have babies. It is alive."),
                 q("Which one was never alive?", "❓", "a stone", ["a mango tree", "a goat", "a bird"], "A stone never eats, grows or has babies. It was never alive."),
                 q("A car moves along the road. Is it alive?", "\U0001F697", "No. Moving is not enough. It never eats or grows.", ["Yes, because it moves", "Yes, because it is big"], "Moving is not the test. A car never eats, grows or has baby cars."),
                 q("What does a cat need to stay alive?", "\U0001F431", "air, water and food", ["a bed and a toy", "a television", "a ribbon"], "Every animal needs air, water and the right food."),
                 q("You feel thirsty. What is your body asking for?", "\U0001F9D2", "water", ["a toy", "a nap", "a hat"], "Thirsty means your body needs water. You are a living thing."),
                 q("A plant gets no water for five days. What happens?", "\U0001FAB4", "it droops and goes yellow", ["it grows bigger", "it turns into a tree", "nothing changes"], "You saw it in the experiment. Plants need water."),
                 q("A mango tree does not walk about. Is it alive?", "\U0001F333", "Yes. It grows, takes in water and makes seeds.", ["No, because it does not move", "No, because it is made of wood"], "Plants are alive. They grow, need water, make their own food and make new seeds."),
                 q("A hen has chicks. What does that tell you?", "\U0001F414", "The hen is alive, because living things can have babies.", ["The hen is a plant", "The hen was never alive"], "Only living things can have young."),
                 q("What would happen to a pet fish if nobody ever fed it?", "\U0001F41F", "It could not stay alive, because animals need food", ["It would grow bigger", "Nothing, because fish do not need food"], "Every animal needs the right food. A fish with no food cannot stay alive, so somebody has to feed it."),
                 q("A leaf has fallen off a tree. Which group does it go in?", "\U0001F342", "used to be alive", ["alive", "never alive"], "It is not alive now, but it grew on a tree, so it used to be alive."),
                 q("Is a person an animal?", "\U0001F9D2", "Yes. In science, people are animals.", ["No, people are plants", "No, only pets are animals"], "You need air, water and food like every other animal. You are a very special animal, and still an animal."),
                 q("Arun predicted the plant with no water would grow taller. It drooped. What should he write down?", "\U0001F4DD", "that it drooped, and that his prediction was wrong", ["that it grew taller, like he said", "nothing at all"], "Write down what really happened. A wrong prediction is how you learn something new, and scientists get them wrong too."),
                 q("Water is not alive. Why not?", "\U0001F4A7", "it never grows, eats or has young", ["because it moves", "because plants need it"], "Plants need water, but that does not make water alive. It never grows, eats or has young."),
             ],
              "support": [
                 q("Which one is alive?", "\U0001F415", "a dog", ["a stone"],
                   "A dog eats, drinks and grows. A stone does none of those."),
                 q("A plant gets no water. Does it stay green?", "\U0001FAB4", "No, it droops", ["Yes, it stays green"],
                   "You saw it. With no water the plant drooped and went yellow."),
                 q("Does a fish need food?", "\U0001F41F", "Yes", ["No"],
                   "Every animal needs food to stay alive."),
                 q("Do plants need air?", "\U0001F32C\uFE0F", "Yes", ["No"],
                   "Plants need air as well as water and light."),
              ],
              "extension": [
                 q("A wooden spoon, a fallen leaf and a stone. Which TWO used to be alive?", "\U0001F944", "the spoon and the leaf", ["the leaf and the stone", "the spoon and the stone"],
                   "Wood comes from a tree and a leaf grew on one. Both used to be alive. A stone never was."),
                 q("A cactus in a desert gets rain only a few times a year. Is it alive?", "\U0001F335", "Yes. It still needs water, just very little of it.", ["No, because it hardly ever drinks", "No, because it does not move"],
                   "It grows, takes in water and makes seeds. Needing only a little water does not stop a thing being alive."),
                 q("You plant a dry seed and it grows. Was the dry seed alive?", "\U0001F331", "Yes - it was alive and waiting for water", ["No, it was dry", "It came alive when the water touched it"],
                   "A seed is alive and resting. Water and warmth wake it up."),
                 q("An egg sits in a nest and a chick hatches out. Was the egg alive before it hatched?", "\U0001F423", "Yes - the chick was growing inside all the time", ["No, it was only a shell", "Only once it cracked"],
                   "Growing is one of the things living things do, and the chick was growing where nobody could see it."),
              ]
             },
             "That is the whole lesson finished. You know what alive means."),
    ],
}


# ---- the unit shell (drawn by lesson-kit/_shell.py): what this lesson is about,
#      the lecture, its science words, and things to do at home ----------------
LESSON["about"] = [
    "Say whether something is alive or was never alive.",
    "Name what every animal needs: air, water and the right food.",
    "Do an experiment with a plant and say what happened.",
    "Fill in a science table.",
]

LESSON["warmup"] = [
    q("Is a tree alive?", "\U0001F333", "yes", ["no"], "A tree grows, needs water and makes seeds, so it is alive."),
    q("Which of these grows?", "\U0001F331", "a seedling", ["a stone", "a spoon"], "A seedling grows into a big plant. Growing is one sign that a thing is alive."),
]

LESSON["lecture"] = [
    part("\U0001F410", "What alive means",
         "Look at a goat. A baby goat, called a kid, grows into a big goat. It needs food, so it eats grass. It needs water, so it drinks. It can have young. Anything that grows, needs food and water, and can have young is alive."),
    part("\U0001FAA8", "Never alive",
         "Now look at a stone. It needs no food. It needs no water. It never grows and it never has babies. A stone was never alive. Neither was a spoon, a car or a teddy bear."),
    part("\U0001F431", "What animals need",
         "Every animal needs three things to stay alive. Air to breathe. Water to drink. And the right food. A cat does not need a ball of wool. It wants one. That is different."),
    part("\U0001F331", "What plants need",
         "Plants are alive too. They do not eat like animals, but they still need food: they make their own in their leaves, using light from the Sun. They need water from the soil, and air. Today you will find out what happens to a plant with no water."),
    part("\U0001F52C", "Being a scientist",
         "A scientist looks closely, asks a question, tries something, and writes down what happened. That is what you will do in this lesson. Ready? Let us go."),
]

LESSON["words"] = [
    word("alive", "\U0001F423", "Something that grows, needs food and water, and can have young.",
         ["A chick is alive. It eats, drinks and grows.", "My cat is alive, but my toy cat is not."]),
    word("never alive", "\U0001FAA8", "Not alive now, and not alive ever. It does not grow, need food or have young.",
         ["A stone was never alive.", "A cup was never alive."]),
    word("non-living", "\U0001F5FB", "Not alive. Some non-living things used to be alive, like a fallen leaf, and some never were, like a rock.",
         ["A rock is non-living.", "Sort the pictures into living and non-living."]),
    word("used to be alive", "\U0001F342", "Not alive now, but it was once. It grew, or it came from something that grew.",
         ["A fallen leaf used to be alive.", "A wooden spoon came from a tree, so it used to be alive."]),
    word("observe", "\U0001F50D", "To look very carefully to find something out. Scientists observe before they say anything.",
         ["Observe the plant every day.", "I observed that the leaves went yellow."]),
    word("animal", "\U0001F415", "A living thing that moves about and eats to stay alive.",
         ["A dog is an animal.", "Every animal needs air, water and food."]),
    word("plant", "\U0001F331", "A living thing that grows in soil and makes its own food from sunlight.",
         ["A sunflower is a plant.", "The plant needs water, or it droops."]),
    word("need", "\U0001F4A7", "Something you must have to stay alive.",
         ["Water is a need. A toy is not.", "A cat needs air, water and food."]),
    word("grow", "\U0001F4C8", "To get bigger and change over time.",
         ["A baby goat grows into a big goat.", "The plant grew taller after we watered it."]),
    word("experiment", "\U0001F9EA", "A test you do to find out an answer.",
         ["Our experiment showed that a plant needs water.", "Predict first, then do the experiment."]),
    word("gills", "\U0001F41F", "The parts a fish breathes with. A fish takes in air from the water through its gills.",
         ["A fish has gills instead of lungs.", "You can see the gills behind its head."]),
    word("healthy", "\U0001F34E", "Good for your body. Healthy food helps you grow.",
         ["An apple is a healthy snack.", "Running about keeps you healthy."]),
    word("unhealthy", "\U0001F370", "Not good for your body if you have a lot of it. A treat, not an every-day food.",
         ["Sweets are unhealthy if you eat a lot.", "One cake is fine; a cake every day is unhealthy."]),
    word("water", "\U0001F4A7", "The liquid in seas, rivers and taps, that every living thing needs.",
         ["A plant needs water to grow.", "You drink water every day."]),
    word("air", "\U0001F32C\uFE0F", "The material all around us that we breathe.",
         ["Air is all around you, even though you cannot see it.", "A fish takes air out of water with its gills."]),
    word("breathe", "\U0001F443", "To take air in and let it out again.",
         ["You breathe through your nose and mouth.", "A fish breathes with gills."]),
    word("scientist", "\U0001F52C", "Somebody who finds things out by looking, testing and asking questions.",
         ["A scientist writes down what she sees.", "You are being a scientist when you test something."]),
    word("group", "\U0001F5C2\uFE0F", "Things put together because they are alike in some way.",
         ["Put the leaves into groups by shape.", "Animals with feathers make one group."]),
]

LESSON["cando"] = [
    cando("I can name four or more things that are living.", "1Bp.01"),
    cando("I can name four or more things that have never been alive.", "1Bp.01"),
    cando("I can tell a thing that used to be alive from one that never was.", "1TWSc.01"),
    cando("I can say what animals need to stay alive: air, water and food.", "1Bp.02"),
    cando("I can say what I think will happen before I try it.", "1TWSp.02"),
    cando("I can say whether what happened was what I predicted.", "1TWSa.01"),
    cando("I can write what I saw in a table.", "1TWSc.05"),
    cando("I can ask a science question and say how to find the answer.", "1TWSp.01"),
]

LESSON["home"] = [
    home("Two plants, one watering can", "Two small plants or two cuttings in cups, water, a sunny windowsill",
         ["Put both plants on the windowsill.",
          "Water one plant every day. Give the other no water at all.",
          "Look at both plants every day for a week, and say what you see."],
         "Which plant droops and goes yellow, and how many days it takes."),
    home("Alive or never alive hunt", "A garden or a park, a grown-up, paper and a pencil",
         ["Walk round slowly with a grown-up and point at ten things.",
          "For each one, ask: does it grow, need food and water, or have young?",
          "Make two lists: alive, and never alive."],
         "Things that trick you, like a fallen leaf. It was alive once."),
    home("Feed a pet, or a bird", "A pet, or a bird table with seeds and a dish of water",
         ["Put out food and water.",
          "Watch from a window, without moving, for five minutes.",
          "Say which needs you gave: water, food, or both."],
         "Whether the animal eats, drinks, or both."),
]
