# -*- coding: utf-8 -*-
"""Lesson 2 - Parts of a Plant.

0097 Stage 1: 1Bs.01 roots, leaves, stems and flowers; 1Bp.03 plants need
light and water (the light half); with 1TWSp.01, 1TWSp.02, 1TWSc.02,
1TWSc.03, 1TWSc.04, 1TWSc.05, 1TWSa.01 and 1SIC.03.
"""
from _kit import explain, step, opt, q, part, word, home, cando, icon

PLANT_PARTS = [
    {"id": "roots", "label": "roots", "say": "The roots hide in the soil. They hold the plant steady and drink up water."},
    {"id": "stem", "label": "stem", "say": "The stem stands up tall. It holds the plant up and carries water to the leaves."},
    {"id": "leaves", "label": "leaves", "say": "The leaves are green. They catch the sunlight and make food for the plant."},
    {"id": "flower", "label": "flower", "say": "The flower is the colourful part. It makes the seeds for new plants."},
]

LESSON = {
    "slug": "parts-of-a-plant",
    "title": "Parts of a Plant",
    "blurb": "Watch a seed grow day by day, name the roots, stem, leaves and flower, and find out what happens to a plant kept in the dark.",
    "steps": [
        step("demo", "A seed grows", "\U0001F331", "Seed to flower", ["1Bs.01", "1Bp.03"],
             "Press <b>Next day</b> and watch the seed. Which part grows first?",
             explain(
                 ["A tiny baby plant, and food for it, are packed inside a seed.", "Give it water and it starts to grow."],
                 ["Day one: a seed in the soil.", "First a root grows down, to drink water.", "Then a shoot grows up, towards the light.",
                  "Then leaves open out to catch the sun.", "The stem grows taller, and at last a flower opens."],
                 ["Children think the shoot comes first because that is the part they can see.", "The root comes first, hidden in the soil."],
                 ["Press Next day and say the name of each new part as it appears."]),
             {"button": "Next day ▶", "frames": [
                 {"scene": {"id": "plant", "state": 0}, "cap": "Day 1. A <b>seed</b> in the soil, with water.", "say": "Day one. A seed in the soil. We give it water."},
                 {"scene": {"id": "plant", "state": 1}, "cap": "Day 3. A <b>root</b> grows down first, to drink.", "say": "Day three. A root grows down first. It drinks water from the soil."},
                 {"scene": {"id": "plant", "state": 2}, "cap": "Day 5. A <b>shoot</b> pushes up towards the light.", "say": "Day five. A shoot pushes up out of the soil, towards the light."},
                 {"scene": {"id": "plant", "state": 3}, "cap": "Day 7. <b>Leaves</b> open to catch the sunlight.", "say": "Day seven. Leaves open out to catch the sunlight."},
                 {"scene": {"id": "plant", "state": 4}, "cap": "Day 14. The <b>stem</b> grows taller and more leaves grow.", "say": "Day fourteen. The stem grows taller and more leaves grow."},
                 {"scene": {"id": "plant", "state": 5}, "cap": "Day 30. A <b>flower</b> opens. It will make new seeds.", "say": "Day thirty. A flower opens. The flower will make new seeds, and it all starts again."},
             ]},
             "Root, shoot, leaves, stem, flower. That is how a seed grows."),

        step("label", "Tap the part", "\U0001F33C", "Named the parts", ["1Bs.01"],
             "Find each part of the plant. Tap the <b>%s</b>.",
             explain(
                 ["A flowering plant has four main parts: roots, stem, leaves and flower."],
                 ["The roots are at the bottom, in the soil.", "The stem is the tall stalk in the middle.",
                  "The leaves are the flat green parts that stick out from the stem.", "The flower is the colourful part at the top."],
                 ["Children tap a leaf when asked for the stem, because the leaf is joined to it.", "The stem is the stalk itself, not what grows out of it.",
                  "Two more slips, both about the word plant.", "Children say the whole thing is a flower.", "The flower is only one part of it.",
                  "And children think plant means the small ones in pots.", "A tree is a plant. Grass is a plant. A bush is a plant.",
                  "Every green living thing that makes its own food is a plant, however big it is."],
                 ["Listen for the part, look for it, then tap it."]),
             {"figure": "plant", "ask": "Tap the %s.", "parts": PLANT_PARTS},
             "Roots, stem, leaves and flower. You can find them all.",
             mis=["1.2-m1", "1.2-m3"]),

        step("explore", "What does each part do?", "\U0001F9E0", "Part jobs", ["1Bs.01"],
             "Every part has a job. Tap each one to hear it.",
             explain(
                 ["Each part of a plant does a different job, and the plant needs all four."],
                 ["Roots hold the plant in the soil and drink water.", "Water goes in through the roots, never through the leaves.",
                  "The stem carries that water up to the leaves.",
                  "Leaves catch light and make the plant's food.", "The flower makes seeds for new plants."],
                 ["Children think plants eat soil.", "Plants make their own food in their leaves, using light. The soil gives them water and something to hold on to.",
                  "Some children think the roots suck up the plant's food.", "The roots take in water. The food is made up in the leaves.",
                  "And shops sell bottles called plant food.", "A plant does not need it to live, because it makes its own. Plant food only helps it stay healthy.",
                  "One more: children think the water goes in through the leaves, because that is where the watering can points.", "It soaks into the soil and the roots drink it."],
                 ["Tap all four and say each job out loud."]),
             {"items": [
                 {"pic": icon("roots"), "label": "roots", "sub": "hold and drink", "say": "The roots hold the plant in the soil and drink up water, like straws."},
                 {"pic": "\U0001F33F", "label": "stem", "sub": "holds up, carries water", "say": "The stem holds the plant up and carries water from the roots to the leaves."},
                 {"pic": "\U0001F343", "label": "leaves", "sub": "make food from sunlight", "say": "The leaves catch sunlight and use it to make the plant's food."},
                 {"pic": "\U0001F33C", "label": "flower", "sub": "makes seeds", "say": "The flower makes seeds. Each seed can grow into a new plant."},
             ], "need": 4},
             "Roots drink, the stem carries, leaves make food, the flower makes seeds.",
             mis=["1.2-m2", "1.3-m2", "1.4-m2"]),

        step("questions", "Which part?", "✅", "Which part?", ["1Bs.01"],
             "Which part of the plant does the job? Tap it.",
             explain(
                 ["Now you know the four parts and their jobs, you can work out which part is being talked about."],
                 ["If it says drinking water from the soil, that is the roots.", "If it says catching sunlight, that is the leaves.",
                  "If it says making seeds, that is the flower.", "If it says holding the plant up, that is the stem."],
                 [],
                 ["Read the question, think about the job, then tap the part."]),
             {"label": "Question", "items": [
                 q("Which part drinks water from the soil?", "\U0001F4A7", "roots", ["leaves", "flower", "stem"], "The roots are in the soil and drink up the water."),
                 q("Caterpillars have eaten every one of a plant's leaves. What will the plant find hard to do?", "\U0001F41B", "make its own food", ["drink water", "stand up straight"], "Food is made in the leaves. With no leaves the plant cannot make any, even though its roots can still drink."),
                 q("Which part makes the seeds?", "\U0001F330", "flower", ["roots", "leaves", "stem"], "The flower makes seeds for new plants."),
                 q("Which part holds the plant up tall?", "\U0001F33F", "stem", ["roots", "flower", "leaves"], "The stem is the stalk that holds the plant up."),
                 q("Which part is hidden under the soil?", icon("soil"), "roots", ["flower", "leaves", "stem"], "The roots grow down into the soil."),
                 q("Which part is usually the most colourful?", "\U0001F3A8", "flower", ["roots", "stem", "leaves"], "Flowers are colourful to attract bees and other insects."),
                 q("You water a plant. Which part takes the water in?", "\U0001F4A7", "the roots", ["the leaves", "the flower"], "The water soaks into the soil, and the roots drink it up. Water does not go in through the leaves."),
                 q("Which of these is a <b>plant</b>?", "\U0001F333", "all of them: a tree, some grass and a daisy", ["only the daisy", "only the tree"], "A tree is a plant. Grass is a plant. A daisy is a plant. They are all green living things that make their own food."),
                 q("Where does a plant get its food?", "\U0001F343", "it makes its own, in its leaves", ["it eats the soil", "a grown-up feeds it", "it drinks it through the roots"], "A plant makes its own food in its leaves, using light. The roots take in water, not food."),
             ],
              "support": [
                 q("Which part of a plant is under the soil?", "\U0001F331", "the roots", ["the flower"],
                   "Roots grow down into the soil."),
                 q("Does a plant need its roots?", "\U0001F4A7", "Yes", ["No"],
                   "Without roots it cannot drink."),
              ],
              "extension": [
                 q("Why are so many flowers brightly coloured?", "\U0001F41D", "to bring insects, which help the plant make seeds", ["to look pretty for people", "to soak up more light than leaves do"],
                   "A bright flower attracts insects. They carry pollen from flower to flower, and that is how seeds get made."),
                 q("A plant cannot walk. So what are its seeds for?", "\U0001F330", "getting new plants started somewhere else", ["feeding the parent plant", "holding the flower up"],
                   "A plant stays where it is all its life. Its seeds are the part that can travel, and that is how a plant reaches new ground."),
              ]},
             "You know the parts of a plant and what each one does."),

        step("experiment", "Does a plant need light?", "\U0001F9EA", "Light test", ["1Bp.03", "1TWSp.02", "1TWSc.04", "1TWSa.01"],
             "Two plants. One <b>by the window</b>, one <b>in a dark cupboard</b>. Both get water. Predict first!",
             explain(
                 ["This is a fair test.", "Both plants get water. Only one thing is different: the light.",
                  "Plants need <b>light</b>. It does not have to come from the Sun."],
                 ["Predict first: what will happen to the plant in the dark?",
                  "Then wait a day at a time and look at both.", "At the end, say what happened and whether it matched your prediction."],
                 ["Children think that because both plants have water, both will be fine.", "Water is not enough. Leaves need light to make food.",
                  "And children think the light must come from the Sun.", "It does not.",
                  "A plant under a bright lamp grows well, which is how plants grow indoors and in shops with no window near them."],
                 ["Tap your prediction, then press Wait a day and watch the plant in the cupboard."]),
             {"sim": "plantLight",
              "predict": {"ask": "What do you think will happen to the plant in the <b>dark cupboard</b>?",
                          "opts": [opt("It will go pale and droopy", True), opt("It will grow big and green", False), opt("It will stay the same", False)]},
              "plan": {"ask": "How shall we find out whether a plant needs light? Which way is <b>fair</b>?",
                       "opts": [opt("Two plants the same. One by the window, one in a dark cupboard. Both get water", True),
                                opt("One by the window with water, one in the cupboard with no water", False),
                                opt("One by the window today, and a different plant next week", False)],
                       "why": "A fair test changes ONE thing. Both plants get water, so the only difference is the light."},
              "runAsk": "Press Wait a day. Look at the plant in the dark cupboard.",
              "happened": {"ask": "What happened to the plant in the dark?",
                           "opts": [opt("It went pale, thin and droopy", True), opt("It grew greener than the window plant", False), opt("Nothing changed", False)],
                           "why": "Without light the plant went pale and droopy, even with water. Plants need light and water."},
              "conclude": {"ask": "So what did we find out?",
                           "opts": [opt("Plants need light as well as water", True),
                                    opt("Plants only need water", False),
                                    opt("Plants grow better in the dark", False)],
                           "why": "Both plants had water. Only the one with light stayed green. So a plant needs light too."}},
             "Plants need light and water. Both.",
             mis=["1.3-m1"]),

        step("record", "My plant diary", "\U0001F4D3", "Plant diary", ["1TWSc.05", "1Bs.01"],
             "A plant diary is a table. Fill in what you saw on <b>%s</b>.",
             explain(
                 ["Scientists keep a diary of what they see, day by day, so they can look back at how something changed."],
                 ["Think back to the seed you watched grow.", "On day one there was just a seed.", "On day three a root.", "On day five a shoot.", "On day seven, leaves.",
                  "Tap each day and choose the picture that matches."],
                 ["Children fill in what they think should happen.", "A diary only holds what you actually saw."],
                 ["Fill in each row of the diary."]),
             {"ask": "What did you see on %s?",
              "columns": ["Day", "What I saw"],
              "rows": [
                  {"pic": "1️⃣", "label": "day 1", "answer": "seed", "why": "on day one there was just the seed in the soil."},
                  {"pic": "3️⃣", "label": "day 3", "answer": "root", "why": "on day three a root had grown down."},
                  {"pic": "5️⃣", "label": "day 5", "answer": "shoot", "why": "on day five a shoot had pushed up."},
                  {"pic": "7️⃣", "label": "day 7", "answer": "leaves", "why": "on day seven the leaves had opened."},
              ],
              "choices": [{"id": "seed", "t": "a seed", "pic": "\U0001F330"}, {"id": "root", "t": "a root", "pic": icon("roots")},
                          {"id": "shoot", "t": "a shoot", "pic": "\U0001F331"}, {"id": "leaves", "t": "leaves", "pic": "\U0001F33F"}],
              "read": [
                  {"ask": "Look at your diary. On which day did the <b>root</b> appear?",
                   "opts": [opt("day 3", True), opt("day 1", False), opt("day 7", False)],
                   "why": "Your diary shows the root on day three."},
                  {"ask": "Your diary reads: seed, root, shoot, leaves. What does that tell you?",
                   "opts": [opt("the root grows before the shoot", True),
                            opt("the leaves grow first", False),
                            opt("everything grows on the same day", False)],
                   "why": "Read the days in order and the root comes first, before anything you can see above the soil."},
              ]},
             "Your plant diary is complete."),

        step("measure", "How tall is the plant?", "\U0001F4CF", "Measured it", ["1TWSc.03"],
             "Measure <b>%s</b> in cubes. Press to stack a cube each time.",
             explain(
                 ["You can measure how tall something is by counting cubes stacked beside it."],
                 ["Put down one cube. Say one.", "Put down another. Say two.", "Keep going until the cubes reach the top of the plant.",
                  "The last number you say is how tall the plant is, in cubes."],
                 ["Children stop stacking before they reach the top, or keep going past it.", "Stop exactly when the cubes reach the top."],
                 ["Stack cubes for each plant, then say which is taller."]),
             {"ask": "How tall is %s? Stack cubes until you reach the top.",
              "unit": {"name": "cubes", "singular": "cube", "pic": "\U0001F7E9", "button": "Add a cube"},
              "objects": [
                  {"pic": "\U0001F331", "label": "the seedling", "units": 3},
                  {"pic": "\U0001F33B", "label": "the sunflower", "units": 8},
              ],
              "compare": {"ask": "The seedling is 3 cubes. The sunflower is 8 cubes. Which is taller?",
                          "opts": [opt("the sunflower", True), opt("the seedling", False), opt("they are the same", False)],
                          "why": "8 cubes is more than 3 cubes, so the sunflower is taller."}},
             "You measured in cubes. That is measuring like a scientist."),

        step("explore", "Use the tools safely", "\U0001F9E4", "Safe hands", ["1TWSc.02", "1TWSc.04"],
             "Scientists use tools carefully. Tap each tool to hear how to use it.",
             explain(
                 ["Every tool has a right way to use it, and using it that way keeps you and the plant safe."],
                 ["A watering can pours gently at the soil, not on the flower.", "A magnifying glass goes close to your eye, and you move the leaf, not the glass.",
                  "A trowel digs a small hole, held by the handle.", "Gloves keep soil off your hands, and you wash your hands after anyway."],
                 ["Children point a magnifying glass at the sun to see it better.", "Never do that. It can burn."],
                 ["Tap every tool and listen to the rule."]),
             {"items": [
                 {"pic": icon("wateringcan"), "label": "watering can", "say": "Pour gently at the soil, near the roots. Not on the flower. Stop when the soil is damp."},
                 {"pic": "\U0001F50D", "label": "magnifying glass", "say": "Hold it near your eye and move the leaf closer until it looks sharp. Never point it at the sun."},
                 {"pic": icon("trowel"), "label": "trowel", "say": "Hold the handle and dig a small hole. Keep it pointing down, away from other people."},
                 {"pic": "\U0001F9E4", "label": "gloves", "say": "Gloves keep soil off your hands. Wash your hands afterwards anyway."},
                 {"pic": "\U0001F4CF", "label": "ruler", "say": "Put the zero end at the bottom of the plant and read the number at the top."},
             ], "need": 5,
              "then": {"ask": "You want to look closely at a leaf. Which tool?",
                       "opts": [opt("magnifying glass", True), opt("trowel", False), opt("watering can", False)],
                       "why": "A magnifying glass makes small things look big."}},
             "The right tool, used the right way, keeps everyone safe."),

        step("context", "People who use science", "\U0001F468‍\U0001F33E", "Science jobs", ["1SIC.03"],
             "Some people use plant science every day at work. Tap each one.",
             explain(
                 ["Everyone uses science, and some people use it as their job."],
                 ["A farmer knows plants need water and light, so they plant in sunny fields and water in dry weather.",
                  "A gardener knows which part is the root, so they plant it the right way up.", "A florist keeps flowers in water so they stay fresh."],
                 ["Children think science only happens in a laboratory.", "A farmer in a field is doing science too."],
                 ["Tap each person and hear how they use what you learned today."]),
             {"items": [
                 {"pic": "\U0001F469‍\U0001F33E", "label": "farmer", "say": "A farmer knows that plants need light and water, so the crops are planted in the sun and watered when it is dry."},
                 {"pic": "\U0001F9D1‍\U0001F33E", "label": "gardener", "say": "A gardener knows the roots grow down into the soil and the stem grows up towards the light."},
                 {"pic": "\U0001F490", "label": "florist", "say": "A florist keeps cut flowers standing in water, because the stem still carries water up to the petals."},
                 {"pic": "\U0001F52C", "label": "plant scientist", "say": "A plant scientist grows seeds in a laboratory to find out what helps them grow best."},
             ], "need": 4,
              "then": {"ask": "A farmer plants seeds in a sunny field and waters them. Why?",
                       "opts": [opt("Because plants need light and water", True), opt("Because the field looks nice", False), opt("Because seeds like to be busy", False)],
                       "why": "The farmer is using plant science: light and water."}},
             "Everyone uses science. Some people use it all day at work."),

        step("ask", "Ask a question about a plant", "❓", "Asked why", ["1TWSp.01"],
             "Look at the flower. Tap a question you would like to ask about it.",
             explain(
                 ["Every experiment begins with somebody asking a question."],
                 ["You could ask why bees visit the flower.", "Or whether it would grow in sand.", "Then think how to find out.",
                  "For most questions about plants, the answer is to try it and watch."],
                 [],
                 ["Tap a question, then tap the best way to find its answer."]),
             {"pic": "\U0001F33A",
              "questions": ["Why do bees visit the flower?", "Would the plant grow in sand instead of soil?", "Does a bigger seed make a bigger plant?"],
              "findOut": {"ask": "How could we find out?",
                          "opts": [opt("Try it, and watch carefully for a few days", True), opt("Ask the flower", False), opt("Say the first answer that comes into your head", False)],
                          "why": "Trying it and watching is an experiment. That is how scientists answer questions."}},
             "Ask, then try it and watch. That is what scientists do."),

        step("quiz", "Show what you know", "⭐", "Star scientist", ["1Bs.01", "1Bp.03", "1TWSc.03"],
             "Time to show what you know. Tap the answer.",
             explain(
                 ["No new ideas here.", "Every question uses something you have already done in this lesson."],
                 ["If it asks about a part, picture the plant: roots at the bottom, then stem, leaves, flower at the top.",
                  "If it asks what a plant needs, think light and water."],
                 [],
                 ["Take your time. Read it, look at it, then tap."]),
             {"items": [
                 q("Which part holds the plant in the soil?", icon("roots"), "roots", ["leaves", "flower", "stem"], "The roots grow down into the soil and hold the plant steady."),
                 q("Which part makes food using light?", "☀️", "leaves", ["roots", "stem", "flower"], "The green leaves catch light and make food."),
                 q("A new plant grows from a...", "\U0001F330", "seed", ["stone", "shell", "flower"], "A seed holds a tiny new plant inside it."),
                 q("What do plants need to stay alive?", "\U0001F331", "light and water", ["sweets and toys", "only soil", "only air"], "Plants need light and water. You tested both."),
                 q("Which part carries water up to the leaves?", "\U0001F33F", "the stem", ["the flower", "the roots", "the petals"], "The stem carries water from the roots up to the leaves."),
                 q("A plant is kept in a dark cupboard with water. What happens?", "\U0001F6AA", "it goes pale and droopy", ["it grows big and green", "it turns into a flower", "nothing changes"], "You saw it in the experiment. Without light a plant goes pale."),
                 q("Which grew first from the seed?", "\U0001F331", "the root", ["the flower", "the leaves", "the stem"], "The root grows down first, to drink water."),
                 q("You measured a plant as 6 cubes last week and 9 cubes today. What does that tell you?", "\U0001F4CF", "it has grown 3 cubes", ["it has shrunk", "it stayed the same"], "9 cubes is 3 more than 6 cubes, so it grew. Measuring the same plant twice shows you the change."),
                 q("What would happen to a plant if all its roots were cut off?", "\U0001F33F", "It could not take in water, so it would droop", ["It would grow faster", "It would make more flowers"], "The roots take in water for the plant. With no roots it gets no water, and a plant with no water droops."),
                 q("A plant stands in a room with no window, under a bright lamp all day. What happens?", "\U0001F4A1", "it grows well, because a lamp gives light", ["it goes pale, because light must come from the Sun", "it dies at once"], "Plants need light. The light does not have to come from the Sun. A bright lamp works, which is how plants grow indoors."),
                 q("Sofia says the whole plant is called a flower. Is she right?", "\U0001F33C", "No, the flower is only one part of the plant", ["Yes, plants are called flowers", "Yes, if it is a small plant"], "The flower is one part, like the roots and the stem. The whole thing is a plant."),
             ],
              "support": [
                 q("Which part of the plant is in the soil?", "\U0001F331", "the roots", ["the flower"],
                   "The roots grow down into the soil."),
                 q("Do plants need light?", "☀️", "Yes", ["No"],
                   "You tested it. The plant in the dark cupboard went pale and droopy."),
              ],
              "extension": [
                 q("A plant on a sunny windowsill is never watered. Another is watered daily but kept in a dark cupboard. Which lives longer?", "\U0001F4A1", "neither lasts - each is missing something a plant must have", ["the windowsill one, because it has light", "the cupboard one, because it has water"],
                   "A plant needs light AND water. Take either one away and it cannot live, so there is no winner here."),
                 q("Two plants get the same water and the same light. One grows in a tiny pot and one in a big pot. Is that a fair test of whether pot size matters?", "\U0001FAB4", "Yes, because only the pot is different", ["No, pots are never fair", "No, you must change the water too"],
                   "A fair test changes ONE thing. Here only the pot changes, so it is fair."),
              ]
             },
             "That is the whole lesson finished. You know a plant from root to flower."),
    ],
}


# ---- the unit shell (drawn by lesson-kit/_shell.py): what this lesson is about,
#      the lecture, its science words, and things to do at home ----------------
LESSON["about"] = [
    "Name the roots, stem, leaves and flower of a plant.",
    "Say what each part does.",
    "Do an experiment to find out whether a plant needs light.",
    "Measure how tall a plant is in cubes.",
]

LESSON["warmup"] = [
    q("Where do a plant's roots grow?", "\U0001F331", "under the soil", ["up in the air", "on the flower"], "Roots grow down into the soil, where they take in water."),
    q("What colour are most leaves?", "\U0001F343", "green", ["blue", "black"], "Most leaves are green. Green leaves catch the sunlight."),
]

LESSON["lecture"] = [
    part("\U0001F330", "A seed wakes up",
         "A seed looks dead, but it is not. Give it water and warmth and it wakes up. A root pushes down first. Then a shoot pushes up, towards the light."),
    part("\U0001F33F", "Roots and stem",
         "The roots hold the plant in the soil and drink up water. The stem holds the plant up and carries the water to every part."),
    part("\U0001F343", "Leaves and flower",
         "Leaves catch sunlight and use it to make the plant's food. The flower makes seeds, so there can be new plants next year."),
    part("\u2600\uFE0F", "Light and water",
         "A plant needs water and light. Take away the water and it droops. Take away the light and it goes pale and thin. You will test that today."),
    part("\U0001F4CF", "Tools and measuring",
         "Scientists use tools. A magnifying glass to look closely. A ruler or cubes to measure. Gloves to keep hands safe. You will measure a plant in cubes."),
]

LESSON["words"] = [
    word("roots", icon("roots"), "The parts of a plant under the soil. They hold it in the soil and take in water.",
         ["The roots grow down into the soil.", "Pull up a weed and you can see its roots."]),
    word("stem", "\U0001F331", "The part that holds a plant up and carries water to the leaves.",
         ["A sunflower has a tall stem.", "Water goes up the stem to the leaves."]),
    word("leaf", "\U0001F343", "The flat green part of a plant. Leaves make the plant's food from sunlight.",
         ["A leaf catches sunlight.", "This tree has lost its leaves."]),
    word("flower", "\U0001F338", "The part of a plant that makes seeds.",
         ["The flower is red.", "Bees visit the flower."]),
    word("seed", "\U0001F330", "The small thing a new plant grows from.",
         ["We planted a seed.", "A bean is a seed."]),
    word("shoot", "\U0001F331", "The first green stem that pushes up out of a seed.",
         ["The shoot came up on day five.", "A shoot grows towards the light."]),
    word("measure", "\U0001F4CF", "To find out how long, tall or heavy something is.",
         ["We measure the plant in cubes.", "Measure it again next week."]),
    word("investigation", "\U0001F9EA", "A test you do to answer a question. You predict, you try it, and you say what happened.",
         ["Our investigation showed that a plant needs light.", "We did an investigation with two plants."]),
    word("practical", "\U0001F9E4", "A hands-on piece of science. You do it yourself instead of just reading about it.",
         ["Today's practical is planting a bean.", "Wash your hands after a practical."]),
    word("model", "\U0001F30D", "A small copy of something, or a drawing of it, that helps you see how it works.",
         ["A globe is a model of Earth.", "We made a model of a plant out of paper."]),
    word("magnifying glass", "\U0001F50D", "A lens that makes small things look bigger.",
         ["Look at the seed with a magnifying glass.", "A magnifying glass shows the tiny hairs on a root."]),
    word("label", "\U0001F3F7\uFE0F", "A word written on a picture to name one part of it.",
         ["Put a label on each part of the plant.", "The diagram has five labels."]),
]

LESSON["cando"] = [
    cando("I can name the roots, stem, leaves and flower of a plant.", "1Bs.01"),
    cando("I can say what each part of a plant does.", "1Bs.01"),
    cando("I can say what happens to a plant with no light.", "1Bp.03"),
    cando("I can measure how tall a plant is in cubes.", "1TWSc.03"),
    cando("I can keep a diary of what I saw, day by day.", "1TWSc.05"),
    cando("I can use the science tools safely.", "1TWSc.02"),
    cando("I can name people who use science in their work.", "1SIC.03"),
]

LESSON["home"] = [
    home("Grow a bean in a cup", "A clear plastic cup, a broad bean (do not eat it), kitchen paper, water, a grown-up",
         ["With a grown-up, line the cup with wet kitchen paper and push the bean between the paper and the side of the cup.",
          "Keep the paper damp and the cup on a windowsill.",
          "Look every day. Draw what you see."],
         "The root comes first, going down. Then the shoot, going up."),
    home("Plant in the dark", "Two small plants, a cupboard, water",
         ["Put one plant on a sunny windowsill and one inside a dark cupboard.",
          "Water both the same.",
          "After four days, put them side by side."],
         "The plant from the dark is pale, thin and floppy."),
    home("Measure a plant in cubes", "A plant, some building cubes or sugar cubes",
         ["Stand the cubes in a tower next to the plant.",
          "Count the cubes up to the top leaf.",
          "Do it again in a week."],
         "Did the number go up? By how many?"),
]
