<?php
defined('MOODLE_INTERNAL') || die();

$tasks = [
    [
        'classname' => 'local_prequran\task\safenet_schedule',
        'blocking' => 0,
        'minute' => '*/2',
        'hour' => '*',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        'classname' => 'local_prequran\task\live_session_reminders',
        'blocking' => 0,
        'minute' => '*/15',
        'hour' => '*',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        'classname' => 'local_prequran\task\live_recording_automation',
        'blocking' => 0,
        'minute' => '17',
        'hour' => '*',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        'classname' => 'local_prequran\task\workspace_weekly_digest',
        'blocking' => 0,
        'minute' => '10',
        'hour' => '8',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '1',
    ],
    [
        'classname' => 'local_prequran\task\course_request_digest',
        'blocking' => 0,
        'minute' => '25',
        'hour' => '8',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '1',
    ],
    [
        'classname' => 'local_prequran\task\course_data_maintenance',
        'blocking' => 0,
        'minute' => '40',
        'hour' => '2',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        'classname' => 'local_prequran\task\transcript_maintenance',
        'blocking' => 0,
        'minute' => '55',
        'hour' => '2',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        'classname' => 'local_prequran\task\finance_operations_refresh',
        'blocking' => 0,
        'minute' => '20',
        'hour' => '3',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        'classname' => 'local_prequran\task\finance_api_hardening',
        'blocking' => 0,
        'minute' => '35',
        'hour' => '3',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        'classname' => 'local_prequran\task\support_sla_monitor',
        'blocking' => 0,
        'minute' => '*/10',
        'hour' => '*',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        // Ehel Academy: catalog.json -> categories, courses (by idnumber), grade items.
        'classname' => 'local_prequran\task\catalog_sync',
        'blocking' => 0,
        'minute' => '10',
        'hour' => '3',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
    [
        // Ehel Academy: cohorts.json -> cohorts, memberships, cohort enrolments.
        // Runs after catalog_sync so the courses exist.
        'classname' => 'local_prequran\task\cohort_sync',
        'blocking' => 0,
        'minute' => '25',
        'hour' => '3',
        'day' => '*',
        'month' => '*',
        'dayofweek' => '*',
    ],
];
