# -*- coding: utf-8 -*-
"""Grade 1's "How do you know?" claims, read by
../../lesson-app-tools/add-reasoning-step.py (rebuild-g1v2.py runs it).

Each item: a claim that is TRUE, the reason that explains it, two reasons that
do not, and what makes the difference. Every wrong reason is either the
mistake the lesson teaches against - "big things are always heavy", "two
pieces means halves" - or something perfectly true that explains nothing, like
"they are all even" offered as the reason 2, 4, 6, 8 goes on to 10. Being even
is true of all of them and does not say what comes next; the jump of two does.
That second kind is what the step exists for.

GRADE 1 IS FIVE AND SIX YEARS OLD, so these are shorter and more concrete than
Grades 2 to 4: one clause per reason wherever it can be done, numbers to 20
only, and nothing that needs a word the lesson has not already taught. The
claims are drawn from each lesson's own steps - counting in twos, making ten,
equal parts, the repeating part, turning a square, reading both hands, the
sorting rule - so the step revisits the lesson rather than adding a topic.
"""

BANKS = {
"counting-to-twenty": [
 ("14 is more than 9.",
  "When you count up you reach 9 first and keep going to 14.",
  ["14 has a 1 and a 4.", "Both numbers are less than 20."],
  "Where a number comes when you count tells you which is bigger."),
 ("8 is an even number.",
  "You can put 8 into pairs with none left over.",
  ["8 comes after 7.", "8 is less than 10."],
  "Even means it splits into twos with nothing left over."),
 ("7 is an odd number.",
  "When you pair up 7, one is left on its own.",
  ["7 is smaller than 8.", "7 comes after 6."],
  "Odd means one is left over when you make pairs."),
 ("There are zero apples in the empty basket.",
  "Zero means there are none at all.",
  ["The basket is small.", "Zero is round like a circle."],
  "Zero is a number for none. It is not about the shape or the basket."),
 ("Counting in tens goes 10, 20, 30.",
  "Each jump adds one more ten.",
  ["The numbers all end in 0.", "Tens are easy to say."],
  "Ending in 0 is true, and the jump of ten is what makes the pattern."),
 ("Twelve is written 12.",
  "It is one ten and two ones.",
  ["It sounds like twelve.", "12 has two digits."],
  "The 1 stands for a ten and the 2 stands for two ones."),
],
"adding-and-taking-away": [
 ("6 add 4 makes 10.",
  "Counting on four from six lands on ten.",
  ["6 and 4 are both even.", "10 is a round number."],
  "Counting on from six is what gets you to ten."),
 ("Double 7 is 14.",
  "Seven and another seven is fourteen.",
  ["7 is an odd number.", "14 is bigger than 7."],
  "Double means the same number twice."),
 ("9 take away 3 leaves 6.",
  "Counting back three from nine lands on six.",
  ["9 is bigger than 3.", "6 sits between 3 and 9."],
  "Counting back is what takes the three away."),
 ("8 add 5 is more than 10.",
  "Eight and two more make ten, and there are still three more to add.",
  ["5 is a big number.", "8 is nearly 10."],
  "Making ten first shows how far past ten you land."),
 ("You need 4 more to get from 6 to 10.",
  "Count on from six: seven, eight, nine, ten. That is four.",
  ["6 and 10 are both even.", "4 is less than 6."],
  "Counting on tells you how many more you need."),
 ("5p and 5p makes 10p.",
  "Two fives are ten.",
  ["Both coins are the same size.", "A 10p coin is bigger."],
  "It is the numbers that add up, not the size of the coins."),
],
"halves-and-wholes": [
 ("This cake is cut in half.",
  "The two pieces are exactly the same size.",
  ["There are two pieces.", "The cut is straight."],
  "Two pieces are only halves when they are equal."),
 ("This shape is NOT cut in half.",
  "One piece is bigger than the other.",
  ["It has two pieces.", "The line is wobbly."],
  "Halves must be equal, however the line looks."),
 ("Half of 10 is 5.",
  "Ten shared into two equal groups gives five in each.",
  ["5 is smaller than 10.", "10 is an even number."],
  "Halving means two equal groups."),
 ("Half of 8 apples is 4 apples.",
  "Sharing eight between two people gives four each.",
  ["4 comes before 8.", "8 is a big number."],
  "Share into two equal groups to halve."),
 ("Two halves make one whole.",
  "Put the two equal parts back together and you have all of it.",
  ["Two is more than one.", "Halves are small."],
  "The parts fit back together to make the whole."),
 ("There are 2 halves in one whole.",
  "A whole splits into two equal parts.",
  ["Half is written with a 2.", "Two is a small number."],
  "Count the equal parts the whole splits into."),
],
"what-comes-next": [
 ("The next shape is a circle.",
  "The pattern goes square, circle, square, circle, so a circle comes next.",
  ["Circles are round.", "There are lots of circles."],
  "Find the part that repeats, then say what follows."),
 ("In 2, 4, 6, 8 the next number is 10.",
  "Each number is two more than the one before.",
  ["They are all even.", "10 comes after 8."],
  "All even is true of every one of them, and the jump of two is what makes the next number."),
 ("This pattern repeats in threes.",
  "Red, blue, green comes round again and again.",
  ["There are three colours.", "The pattern is long."],
  "The repeating part decides, not how many colours there are."),
 ("In 5, 10, 15 the jump is five.",
  "Each number is five more than the one before.",
  ["They all end in 5 or 0.", "There is a 5 in every number."],
  "Take one number away from the next to find the jump."),
 ("This is a growing pattern.",
  "Each step has one more than the step before.",
  ["It gets longer.", "There are lots of blocks."],
  "A growing pattern adds the same amount every time."),
 ("The missing number is 7.",
  "The pattern counts on by one, and 7 sits between 6 and 8.",
  ["7 is an odd number.", "7 is a good number."],
  "Use the numbers on each side to find the missing one."),
],
"shapes-and-sizes": [
 ("This shape is a triangle.",
  "It has three straight sides.",
  ["It is pointy.", "It is small."],
  "Count the straight sides."),
 ("It is still a square when you turn it.",
  "It still has four equal sides and four corners.",
  ["It looks like a diamond now.", "It is still the same colour."],
  "Turning a shape does not change its sides or its corners."),
 ("A ball is a solid shape.",
  "You can pick it up and it takes up space.",
  ["It is round.", "You can throw it."],
  "Flat shapes are drawn on paper. Solid shapes you can hold."),
 ("The pencil is longer than the rubber.",
  "Line them up at the same end and the pencil reaches further.",
  ["Pencils are for writing.", "The rubber is pink."],
  "Compare from the same starting line."),
 ("A big box can be lighter than a small box.",
  "A big box of feathers weighs less than a small box of stones.",
  ["Big things are always heavy.", "Boxes come in sizes."],
  "Size does not tell you how heavy something is. You have to weigh it."),
 ("A jug is the right tool for measuring water.",
  "It holds the water and has marks to read.",
  ["It is made of plastic.", "It has a handle."],
  "Choose the tool that measures the thing you need."),
],
"days-months-and-clocks": [
 ("There are 7 days in a week.",
  "Monday to Sunday is seven days.",
  ["A week is short.", "7 is an odd number."],
  "Count the days from Monday to Sunday."),
 ("December comes after November.",
  "It is the next month when you say the year in order.",
  ["December is cold.", "December has 31 days."],
  "Say the months in order to find what comes next."),
 ("The clock shows half past 3.",
  "The long hand points to 6 and the short hand is between 3 and 4.",
  ["There is a 3 on the clock.", "Both hands are moving."],
  "Read both hands. The long hand on 6 says half past."),
 ("The clock shows 9 o'clock.",
  "The long hand points straight up to 12 and the short hand points to 9.",
  ["It is morning.", "There is a 9 on the clock."],
  "O'clock means the long hand is pointing at 12."),
 ("Brushing your teeth takes a short time.",
  "It is finished in about two minutes.",
  ["Teeth are small.", "You do it every day."],
  "Compare how long it lasts, not how often you do it."),
 ("A school year is longer than a school day.",
  "A year holds many days, and a day is only one of them.",
  ["School is busy.", "Years have numbers."],
  "Compare how much time each one holds."),
],
"asking-and-sorting": [
 ("More children chose red than blue.",
  "The red tower has more blocks than the blue tower.",
  ["Red is a bright colour.", "Red comes first on the graph."],
  "Compare how tall the towers are, not the colour or the order."),
 ("Six children like cats.",
  "There are six pictures in the cat row.",
  ["Cats are popular.", "The cat row is long."],
  "Count the pictures in that row."),
 ("This table shows what everyone said.",
  "Every child's answer has its own mark in a row.",
  ["The table is neat.", "Tables have lines."],
  "A table holds one mark for each person who answered."),
 ("This shape does not belong in the hoop.",
  "The hoop is for red shapes and this shape is blue.",
  ["It is a different size.", "The hoop is full."],
  "Check the sorting rule, not anything else about the shape."),
 ("This shape goes in the middle of the Venn diagram.",
  "It is red and it is a circle, so it follows both rules.",
  ["It is in the middle of the table.", "It is the biggest shape."],
  "The middle is for the things that follow both rules at once."),
 ("Asking everyone gives a fair answer.",
  "Every person in the class is counted once.",
  ["Asking is fun.", "The class is big."],
  "A fair count leaves nobody out."),
],
}
