# -*- coding: utf-8 -*-
"""Lesson 9 - Rocks and the Earth.

0097 Stage 2 Planet Earth, all three: 2ESp.01 describe and compare rocks;
2ESp.02 rock is extracted from quarries, mines and riverbeds; 2ESp.03 human
activity affects the environment; with 2Cp.03, 2TWSc.01, 2TWSc.03, 2TWSc.05,
2TWSc.06, 2TWSp.01 and 2SIC.04.
"""
from _kit import explain, step, opt, q, part, word, home, icon, cando

LESSON = {
    "slug": "rocks-and-the-earth",
    "title": "Rocks and the Earth",
    "blurb": "Compare six kinds of rock by testing them, measure a rock in cubes, see how rock is taken out of the ground, and sort what people do to the land into help and harm.",
    "steps": [
        step("explore", "Not all rock is the same", "\U0001FAA8", "Rock kinds", ["2ESp.01"],
             "There are many kinds of rock. Tap each one and hear what it is like.",
             explain(
                 ["Rock is the hard stuff the land is made of, under the soil, and there are many different kinds."],
                 ["Granite is very hard and speckled.", "Chalk is soft and white; you can write with it.", "Sandstone is grainy, like sand stuck together.",
                  "Marble is smooth and shiny when polished.", "Slate splits into flat sheets.", "Pumice is full of holes and so light it floats."],
                 ["Children think all rock is grey and hard.", "Chalk crumbles in your hand. Pumice floats. Rocks are as different as materials."],
                 ["Tap all six and say one thing about each."]),
             {"items": [
                 {"pic": "\U0001FAA8", "label": "granite", "sub": "hard, speckled", "say": "Granite. Very hard, with speckles of different colours. Kitchen worktops are often granite."},
                 {"pic": icon("chalk"), "label": "chalk", "sub": "soft, white", "say": "Chalk. Soft and white. It crumbles, and you can draw with it."},
                 {"pic": "\U0001F3DC️", "label": "sandstone", "sub": "grainy", "say": "Sandstone. Grains of sand stuck together. Rub it and grains come off."},
                 {"pic": "\U0001F3DB️", "label": "marble", "sub": "smooth, shiny", "say": "Marble. Smooth, and shiny when it is polished. Statues are often marble."},
                 {"pic": "\U0001F3E0", "label": "slate", "sub": "splits into sheets", "say": "Slate. Dark, and it splits into thin flat sheets, which is why roofs are made of it."},
                 {"pic": "\U0001F30B", "label": "pumice", "sub": "full of holes, light", "say": "Pumice comes from a volcano. It is full of holes and so light that it floats on water."},
             ], "need": 6},
             "Granite, chalk, sandstone, marble, slate, pumice. Six rocks, six sets of properties."),

        step("tester", "Test the rocks", "\U0001F52C", "Rock tester", ["2ESp.01", "2Cp.03", "2TWSc.02"],
             "Test each rock the way a geologist does. Press each test on at least <b>four</b> rocks.",
             explain(
                 ["Rocks can be tested for their properties, just like any material."],
                 ["Scratch it with a coin: does it scratch, or is it too hard?", "Look with a hand lens: grains, or smooth?", "Drop water on it: does it soak in?", "Rub it: do bits come off?"],
                 ["Children scratch too gently and call everything hard.", "Press the coin properly; chalk and sandstone will scratch."],
                 ["Test four rocks with all four tests and watch the badges."]),
             {"need": 4,
              "tests": [
                  {"id": "scratch", "label": "Scratch with a coin", "pic": "\U0001FA99", "anim": "translateX(6px)", "sound": "click", "say": "Scratch the %m with a coin. It is %r."},
                  {"id": "look", "label": "Look with a hand lens", "pic": "\U0001F50D", "anim": "scale(1.3)", "sound": "click", "say": "Look at the %m through the lens. It is %r."},
                  {"id": "water", "label": "Drop water on it", "pic": "\U0001F4A7", "anim": "translateY(8px)", "sound": "splash", "say": "Drop water on the %m. It %r."},
                  {"id": "rub", "label": "Rub it", "pic": "✋", "anim": "rotate(10deg)", "sound": "shake", "say": "Rub the %m. It is %r."},
              ],
              "materials": [
                  {"id": "granite", "pic": "\U0001FAA8", "label": "granite", "props": {"scratch": "too hard to scratch", "look": "speckled with crystals", "water": "does not soak it up", "rub": "hard, nothing comes off"}},
                  {"id": "chalk", "pic": icon("chalk"), "label": "chalk", "props": {"scratch": "soft, it scratches easily", "look": "smooth and powdery", "water": "soaks it up", "rub": "crumbly, white powder comes off"}},
                  {"id": "sandstone", "pic": "\U0001F3DC️", "label": "sandstone", "props": {"scratch": "fairly soft, it scratches", "look": "grainy, like sand", "water": "soaks it up", "rub": "grainy, sand comes off"}},
                  {"id": "marble", "pic": "\U0001F3DB️", "label": "marble", "props": {"scratch": "hard, it barely scratches", "look": "smooth with faint stripes", "water": "does not soak it up", "rub": "smooth, nothing comes off"}},
                  {"id": "slate", "pic": "\U0001F3E0", "label": "slate", "props": {"scratch": "hard, it barely scratches", "look": "flat layers", "water": "does not soak it up", "rub": "smooth, nothing comes off"}},
                  {"id": "pumice", "pic": "\U0001F30B", "label": "pumice", "props": {"scratch": "rough; the coin does not scratch it, but bits break off", "look": "full of tiny holes", "water": "soaks it up", "rub": "rough, bits come off"}},
              ]},
             "Every rock has its own properties, and testing finds them."),

        step("record", "Record: does water soak in?", "\U0001F4DD", "Rock table", ["2TWSc.06", "2ESp.01"],
             "Put your water test into the table. Did water soak into <b>%s</b>?",
             explain(
                 ["A table compares one property across every rock."],
                 ["Chalk and sandstone soaked the water up.", "Granite and marble did not."],
                 [],
                 ["Fill in each row from your test."]),
             {"ask": "Did water soak into %s?",
              "columns": ["Rock", "Soaks up water?"],
              "rows": [
                  {"pic": "\U0001FAA8", "label": "granite", "answer": "no", "why": "the water sat on top of the granite."},
                  {"pic": icon("chalk"), "label": "chalk", "answer": "yes", "why": "the chalk soaked it up."},
                  {"pic": "\U0001F3DC️", "label": "sandstone", "answer": "yes", "why": "the sandstone soaked it up between its grains."},
                  {"pic": "\U0001F3DB️", "label": "marble", "answer": "no", "why": "the water ran off the marble."},
              ],
              "choices": [{"id": "yes", "t": "Yes, it soaks in", "pic": "\U0001F4A7"}, {"id": "no", "t": "No, it runs off", "pic": "☔"}],
              "read": [
                  {"ask": "Read your table. Did water soak into the <b>marble</b>?",
                   "opts": [opt("No", True), opt("Yes", False)],
                   "why": "The marble row of your table says No."},
                  {"ask": "Two rocks soaked water up and two did not. What does your table show?",
                   "opts": [opt("rocks are not all the same - they have different properties", True),
                            opt("all rocks soak up water", False), opt("no rock soaks up water", False)],
                   "why": "That is why we test rocks instead of guessing about them."},
              ]},
             "Chalk and sandstone soak up water; granite and marble do not."),

        step("measure", "How big is the rock?", "\U0001F4CF", "Measured it", ["2TWSc.03"],
             "Measure <b>%s</b> in cubes. Press to lay a cube along it each time.",
             explain(
                 ["You can measure a rock by laying cubes along it and counting."],
                 ["Lay a cube. One.", "Lay the next, touching. Two.", "Stop when the cubes reach the end of the rock."],
                 ["Children leave gaps between cubes.", "Each cube touches the last one."],
                 ["Measure both rocks, then say which is longer."]),
             {"ask": "How long is %s? Lay cubes along it.",
              "unit": {"name": "cubes", "singular": "cube", "pic": "\U0001F7E9", "button": "Lay a cube"},
              "objects": [
                  {"pic": "\U0001FAA8", "label": "the granite rock", "units": 7},
                  {"pic": icon("chalk"), "label": "the piece of chalk", "units": 4},
              ],
              "compare": {"ask": "The granite is 7 cubes and the chalk is 4 cubes. Which is longer?",
                          "opts": [opt("the granite rock", True), opt("the piece of chalk", False), opt("they are the same", False)],
                          "why": "7 cubes is more than 4, so the granite is longer."}},
             "You measured rocks in cubes."),

        step("demo", "Where rock comes from", "⛏️", "Rock getters", ["2ESp.02"],
             "Rock is taken out of the Earth in different ways. Press <b>Next</b> to see three.",
             explain(
                 ["The rock in buildings, roads and roofs was dug out of the ground somewhere."],
                 ["A quarry is a huge open pit where rock is cut and blasted out.", "A mine goes underground in tunnels.", "Smooth pebbles and gravel are scooped from riverbeds."],
                 ["Children think rock is made in a factory.", "It is dug up. Only bricks and concrete are made."],
                 ["Press Next and see each place."]),
             {"button": "Next place ▶", "frames": [
                 {"scene": {"id": "extract", "state": 0}, "cap": "A <b>quarry</b>: a huge open pit. Rock is cut and blasted out in blocks.", "say": "A quarry. A huge open pit dug into a hillside. Rock is cut and blasted out in blocks and carried away in lorries."},
                 {"scene": {"id": "extract", "state": 1}, "cap": "A <b>mine</b>: tunnels dug underground to reach the rock.", "say": "A mine. Tunnels dug deep underground, where miners with lamps dig the rock out."},
                 {"scene": {"id": "extract", "state": 2}, "cap": "A <b>riverbed</b>: smooth pebbles and gravel scooped from the water.", "say": "A riverbed. The river has worn the rock into smooth pebbles and gravel, which are scooped out."},
                 {"pic": "\U0001F3E0", "cap": "Roofs, walls, roads and worktops all began in a quarry, a mine or a river.", "say": "The slate on a roof, the stone in a wall, the gravel on a path: all of it was taken out of the Earth."},
             ]},
             "Quarries, mines and riverbeds: three ways rock is taken from the Earth."),

        step("lookup", "Look it up: rock facts", "\U0001F4D6", "Fact finder", ["2TWSc.05", "2ESp.02"],
             "Read the fact card, then answer <b>from the card</b>.",
             explain(
                 ["A fact card is a secondary source: somebody found this out and wrote it down for you."],
                 ["Find the question's words in the card, and the answer is next to them."],
                 [],
                 ["Read the card, then find each answer in it."]),
             {"source": {"title": "Rock facts",
                         "lines": ["<b>Granite</b> is one of the hardest rocks. It is cut into blocks in quarries and used for kitchen worktops and steps.",
                                   "<b>Slate</b> splits into thin flat sheets, so it is used for roof tiles. Slate mines go deep underground.",
                                   "<b>Chalk</b> is soft and white. Sticks of chalk for writing are made from it.",
                                   "River <b>pebbles</b> are smooth because the water has rolled them against each other for thousands of years.",
                                   "A quarry can be as deep as a <b>fifty-storey building</b> is tall.",
                                   "When a quarry is finished it is sometimes filled with water to make a <b>lake</b> for wildlife."]},
              "items": [
                  {"ask": "Why is slate used for roof tiles?", "opts": [opt("it splits into thin flat sheets", True), opt("it is soft", False), opt("it floats", False)], "why": "The card says slate splits into thin flat sheets."},
                  {"ask": "Why are river pebbles smooth?", "opts": [opt("the water rolled them against each other for thousands of years", True), opt("people polish them", False), opt("they are made of glass", False)], "why": "Rolling in the river wears them smooth."},
                  {"ask": "What happens to some quarries when they are finished?", "opts": [opt("they are filled with water to make a lake", True), opt("they are turned into mines", False), opt("they float away", False)], "why": "The card says a finished quarry can become a lake for wildlife."},
                  {"ask": "Which rock is used for kitchen worktops?", "opts": [opt("granite", True), opt("chalk", False), opt("pumice", False)], "why": "Granite is hard, so it is cut for worktops."},
              ]},
             "You found every answer in the card."),

        step("sort", "Helping the land, or harming it?", "\U0001F5C2️", "Land carer", ["2ESp.03", "2SIC.04", "2TWSc.01"],
             "What people do can change the land, the water and the air. Does this <b>help</b> or <b>harm</b>?",
             explain(
                 ["Digging rock out, building, farming and throwing things away all change the environment.", "Some of what we do helps, and some harms."],
                 ["Filling an old quarry with water for wildlife: helps.", "Dumping rubbish in a river: harms.", "Planting trees: helps.", "Smoke from burning rubbish: harms."],
                 ["Children think a quarry is only bad.", "We need the rock; the question is what we do afterwards."],
                 ["Ask: is the land, water or air better or worse after this?"]),
             {"ask": "Helps the environment, or harms it?",
              "bins": [{"id": "help", "label": "Helps", "pic": "\U0001F49A"}, {"id": "harm", "label": "Harms", "pic": "\U0001F6AB"}],
              "items": [
                  {"pic": "\U0001F5D1️", "label": "dumping rubbish in a river", "bin": "harm", "why": "Rubbish poisons the water and the animals in it."},
                  {"pic": "\U0001F333", "label": "planting trees", "bin": "help", "why": "Trees give shade, homes for animals and clean air."},
                  {"pic": "\U0001F3DE️", "label": "turning an old quarry into a lake", "bin": "help", "why": "A flooded quarry becomes a habitat."},
                  {"pic": "\U0001F4A8", "label": "smoke from burning rubbish", "bin": "harm", "why": "Smoke dirties the air everyone breathes."},
                  {"pic": "♻️", "label": "recycling glass and cans", "bin": "help", "why": "Recycling means less rock and sand have to be dug up."},
                  {"pic": "\U0001F6E3️", "label": "covering a meadow with concrete", "bin": "harm", "why": "The plants and animals that lived there lose their habitat."},
                  {"pic": "\U0001F6B0", "label": "keeping streams clean", "bin": "help", "why": "Clean water keeps fish, frogs and people healthy."},
                  {"pic": "\U0001F5D1️", "label": "leaving litter on the beach", "bin": "harm", "why": "Litter harms sea birds and turtles."},
              ]},
             "What people do changes the environment, for better or worse."),

        step("ask", "Ask a question about rock", "❓", "Asked why", ["2TWSp.01"],
             "Look at the pebble. Tap a question you would like to ask.",
             explain(
                 ["Geologists, the scientists who study rock, started with questions like these."],
                 ["Why is it smooth? What is inside it? How old is it?", "Some you can test, some you look up."],
                 [],
                 ["Tap a question, then tap the best way to find its answer."]),
             {"pic": "\U0001FAA8",
              "questions": ["Why is this pebble so smooth?", "What would I see if I cut it in half?", "How old is this rock?"],
              "findOut": {"ask": "You want to know what is inside the pebble. How could you find out?",
                          "opts": [opt("Ask a grown-up to break one open and look with a hand lens", True), opt("Guess", False), opt("Ask the pebble", False)],
                          "why": "Looking closely at the inside is observing. Testing and looking are how geologists find out."}},
             "Ask, then look closely or look it up."),

        step("questions", "Rock check", "✅", "Rock check", ["2ESp.01", "2ESp.02", "2ESp.03"],
             "Tap the answer.",
             explain(
                 ["Kinds of rock, where rock comes from, and helping the land."],
                 [],
                 [],
                 ["Read the question, then tap."]),
             {"label": "Question", "items": [
                 q("Which rock is hard and speckled?", "\U0001F50D", "granite", ["chalk", "pumice"], "Granite is very hard, with speckles of different colours."),
                 q("Which rock is grainy, like sand stuck together?", "\u270B", "sandstone", ["marble", "slate"], "Rub sandstone and grains of sand come off."),
                 q("You drop water on granite. What happens?", "\U0001F4A7", "it runs off", ["it soaks in", "the granite crumbles"], "Granite does not soak up water. The water sits on top."),
                 q("Where do miners dig rock out in tunnels underground?", "\U0001F573\uFE0F", "in a mine", ["in a quarry", "in a riverbed"], "A mine goes deep underground. A quarry is an open pit."),
                 q("Which of these helps the environment?", "\U0001F49A", "planting trees", ["leaving litter on the beach", "dumping rubbish in a river"], "Trees give shade, homes for animals and clean air."),
                 q("Is a single grain of sand <b>rock</b>?", "\U0001F3D6️", "Yes. Rock comes in every size.", ["No, rock has to be big and heavy", "No, sand is soil"], "Sand is rock broken into tiny grains. Being small does not stop it being rock."),
                 q("Rocks, stones and pebbles. How many different materials is that?", "\U0001FAA8", "one - they are all rock", ["three different things", "two, because pebbles are smooth"], "The words only tell you how big the piece is and how smooth it is. All three are rock."),
                 q("Is a brick a rock?", "\U0001F9F1", "No. People make bricks.", ["Yes, it is hard like rock", "Yes, it has stones in it"], "Bricks and concrete are made by people. You would not find them in a natural place unless somebody put them there."),
             ],
              "support": [
                 q("Is granite hard or soft?", "\U0001FAA8", "hard", ["soft"],
                   "Granite is so hard it is used for kitchen worktops."),
                 q("Is sand made of rock?", "\U0001F3D6\uFE0F", "Yes", ["No"],
                   "Sand is rock broken into tiny grains."),
                 q("Is slate smooth and flat, or lumpy?", "\U0001FAA8", "smooth and flat", ["lumpy"],
                   "Slate splits into flat sheets, which is why it makes good roof tiles."),
                 q("Does water soak into chalk?", "\U0001F9F4", "Yes", ["No"],
                   "Chalk is soft and full of tiny holes, so it drinks water."),
              ],
              "extension": [
                 q("A stone statue outdoors has lost its face after two hundred years. What wore it away?", "\U0001F5FF", "rain, wind and frost, very slowly", ["people rubbing it as they pass", "the stone was badly made"],
                   "Water seeps into tiny cracks and freezes, and freezing water pushes. Over centuries that breaks even hard rock apart."),
                 q("Sandstone soaks water up and granite does not. Which would you build a wall with, and why?", "\U0001F9F1", "granite, because water running off keeps the wall dry", ["sandstone, because it is easier to find", "either one, it makes no difference"],
                   "Test a rock and use what you find. A stone that drinks is a stone that cracks when the water inside it freezes."),
                 q("Two rocks look almost the same. How would you find out which is harder without guessing?", "\U0001F50D", "try to scratch each one with the same thing and compare", ["look at their colour", "weigh them both"],
                   "A property is something you test. The same test on both is what makes the comparison fair."),
                 q("A gravestone from 200 years ago is easy to read and one from the same year is worn blank. Why the difference?", "\U0001F5FF", "they are different rocks, and one wears away faster than the other", ["one is much older than it says", "somebody cleaned one of them"],
                   "Rocks differ in how well they stand up to rain, wind and frost. That is a property too."),
              ]},
             "You can tell your rocks apart.",
             mis=["1.4-m1", "rtg-19", "1.4-m2"]),

        step("quiz", "Show what you know", "⭐", "Star scientist", ["2ESp.01", "2ESp.02", "2ESp.03"],
             "Time to show what you know. Tap the answer.",
             explain(
                 ["No new ideas here.", "Every question uses something you have already done in this lesson."],
                 [],
                 [],
                 ["Take your time. Read it, look at it, then tap."]),
             {"items": [
                 q("Which rock is soft, white and crumbly?", icon("chalk"), "chalk", ["granite", "marble", "slate"], "Chalk is soft; you can write with it."),
                 q("Which rock is so full of holes that it floats?", "\U0001F30B", "pumice", ["granite", "marble", "chalk"], "Pumice comes from a volcano and floats."),
                 q("Which rock splits into flat sheets for roofs?", "\U0001F3E0", "slate", ["sandstone", "chalk", "pumice"], "Slate splits into thin sheets."),
                 q("Which rock soaked up the water in your test?", "\U0001F4A7", "chalk", ["granite", "marble"], "Chalk and sandstone soak up water; granite and marble do not."),
                 q("A huge open pit where rock is cut out is a...", "⛏️", "quarry", ["mine", "riverbed", "factory"], "A quarry is an open pit; a mine is underground."),
                 q("Where do smooth pebbles come from?", "\U0001FAA8", "a riverbed, where water rolled them smooth", ["a factory", "the Moon"], "Rivers roll rock into smooth pebbles."),
                 q("Which of these harms the environment?", "\U0001F6AB", "dumping rubbish in a river", ["planting trees", "recycling cans", "making an old quarry a lake"], "Rubbish poisons water and animals."),
                 q("How do we find out a rock's properties?", "\U0001F52C", "test it: scratch, look, drop water, rub", ["guess from its name", "ask the rock"], "Rocks are tested like any material."),
                 q("Why is granite, not chalk, used for kitchen worktops?", icon("rock"), "granite is hard and does not soak up water; chalk is soft and crumbles", ["chalk is too heavy to lift", "granite is softer than chalk"], "A worktop has to stay hard and dry. Chalk would crumble and soak up every spill."),
             ],
              "support": [
                 q("Is chalk soft or hard?", "\U0001F9F1", "soft", ["hard"],
                   "A fingernail scratches chalk."),
                 q("Is sand made of rock?", "\U0001F3D6\uFE0F", "Yes", ["No"],
                   "Sand is rock broken into tiny grains."),
                 q("Did people make granite, or did they dig it up?", "\u26CF\uFE0F", "dug it up", ["made it"],
                   "Rock comes out of the ground. A brick is the one people make."),
                 q("Does pumice float?", "\U0001F6A2", "Yes", ["No"],
                   "Pumice is so full of holes that it floats."),
              ],
              "extension": [
                 q("Chalk is made from the crushed shells of tiny sea animals. So where did it form?", "\U0001F41A", "on the floor of a sea", ["in a desert", "inside a volcano"],
                   "Chalk built up on an ancient sea floor from countless tiny shells. A rock carries the story of the place it formed in."),
                 q("Pumice floats and granite sinks, and both are rock. What does that tell a scientist?", "\U0001F30B", "rocks have different properties, so each one has to be tested", ["pumice is not really rock", "granite is heavier than every other rock"],
                   "Pumice is full of holes from a volcano. Testing is how you find out, never guessing."),
                 q("Chalk and granite are both rock, and one crumbles in your fingers. Does that make chalk not a rock?", "\U0001FAA8", "no - rocks differ enormously, and soft is still rock", ["yes, real rock is always hard", "chalk is a manufactured material"],
                   "Rock is where it comes from, not how hard it is."),
                 q("A quarry is filled with water when it closes and becomes a lake. Good or bad for wildlife?", "\U0001F3DE\uFE0F", "good - it makes a new habitat where there was a bare pit", ["bad, because the rock has gone", "it makes no difference either way"],
                   "Taking rock out does harm. What happens afterwards is a choice, and this one gives something back."),
              ]},
             "That is the whole lesson finished. You know your rocks."),
    ],
}


# ---- the unit shell (drawn by lesson-kit/_shell.py): what this lesson is about,
#      the lecture, its science words, and things to do at home ----------------
LESSON["about"] = [
    "Say that not all rock is the same, and name some kinds.",
    "Test rocks and record their properties.",
    "Say where rock is taken from the Earth.",
    "Say how what people do helps or harms the land.",
]

LESSON["warmup"] = [
    q("Which of these is a kind of rock?", "❓", "a pebble", ["a leaf", "a feather"], "A pebble is a small piece of rock, worn smooth by water."),
    q("Which is the hardest?", "❓", "a stone", ["a sponge", "a slice of bread"], "A stone is a piece of rock, and most rock is hard."),
]

LESSON["lecture"] = [
    part("\U0001FAA8", "Many kinds of rock",
         "Granite is hard and speckled. Chalk is soft and white. Sandstone is grainy. Marble is smooth and shiny. Slate splits into sheets. Pumice is full of holes and floats. Not all rock is the same."),
    part("\U0001F50D", "Testing rocks",
         "Scratch it: is it hard or soft? Drip water on it: does it soak in? Look closely: is it grainy, smooth or full of holes? Every rock has its own properties."),
    part("\u26CF\uFE0F", "Where rock comes from",
         "A quarry is a huge pit where rock is cut from a hillside. A mine is tunnels deep underground. A riverbed is where water has worn rock into pebbles."),
    part("\U0001F3E0", "Rock all around",
         "Slate on roofs. Stone in walls. Gravel on paths. Marble on floors. Chalk on the board. Rock is everywhere you look."),
    part("\U0001F333", "Helping or harming",
         "Dumping rubbish, smoke, covering a meadow with concrete: these harm the land. Planting trees, recycling, keeping streams clean: these help. What we do changes the Earth."),
]

LESSON["words"] = [
    word("rock", "\U0001FAA8", "The hard material the Earth is made of under the soil.",
         ["Granite is a hard rock.", "Rock is dug from a quarry."]),
    word("pebble", "\u26AA", "A small, smooth piece of rock, worn smooth by water.",
         ["I found a pebble on the beach.", "The river makes pebbles smooth."]),
    word("quarry", "\u26CF\uFE0F", "A big open pit where rock is dug from the ground.",
         ["Stone for the wall came from a quarry.", "A quarry is cut into a hillside."]),
    word("mine", "\U0001F573\uFE0F", "Tunnels dug deep underground to take out rock or metal.",
         ["Miners work in a mine.", "Coal comes from a mine."]),
    word("soak", "\U0001F4A7", "To take in water.",
         ["Chalk soaks up water.", "Marble does not soak up water."]),
    word("grainy", "\U0001F7E4", "Made of tiny grains you can see or feel.",
         ["Sandstone is grainy.", "The grainy rock felt rough."]),
    word("environment", "\U0001F30D", "Everything around us: the land, the water, the air and the living things.",
         ["Litter harms the environment.", "Planting trees helps the environment."]),
    word("sand", "\U0001F3D6\uFE0F", "Rock broken into tiny grains.",
         ["A beach is covered in sand.", "Sand is rock, only very small."]),
    word("stones", "\u26F0\uFE0F", "Small pieces of rock. Stones, pebbles and rocks are all the same material.",
         ["The stones in the wall are rock.", "A pebble is a stone that water has made smooth."]),
    word("smooth", "\u270B", "Flat to touch, not bumpy. The opposite of rough.",
         ["A pebble is smooth.", "Rub it: smooth means your finger slides."]),
    word("gravel", "\U0001FAA8", "Small broken pieces of rock.",
         ["Gravel crunches under your feet.", "Gravel is rock broken into little stones."]),
    word("rough", "\U0001F9F1", "Bumpy, not smooth.",
         ["A rough rock feels bumpy.", "The pebble was smooth and the brick was rough."]),
]

LESSON["cando"] = [
    cando("I can describe rocks and compare them.", "2ESp.01"),
    cando("I can say three ways rock is taken out of the Earth.", "2ESp.02"),
    cando("I can talk about how digging rock changes the environment.", "2ESp.03"),
    cando("I can test a rock to find out its properties.", "2Cp.03"),
    cando("I can measure a rock with cubes.", "2TWSc.03"),
    cando("I can find an answer on a fact card.", "2TWSc.05"),
    cando("I can record what I found in a table.", "2TWSc.06"),
    cando("I can say how digging rock out of the ground changes the land.", "2SIC.04"),
]

LESSON["home"] = [
    home("Rock collection", "A bag, a walk outside with a grown-up, a magnifying glass",
         ["Go for a walk with a grown-up and collect five different stones.",
          "Look at each with the magnifying glass. Grainy, smooth, speckled, holes?",
          "Sort them by one property.",
          "Wash your hands afterwards."],
         "No two are quite the same."),
    home("The drip test on rocks", "Your five stones, a dropper or a spoon, water",
         ["Put one drop of water on each stone.",
          "Watch for one minute.",
          "Say which soaked it up and which stayed wet on top."],
         "Soft, grainy rocks soak. Hard, smooth ones do not."),
    home("Rock spotting walk", "A grown-up, a street, paper and a pencil",
         ["Walk along a street with a grown-up. Find rock used in five places: a wall, a roof, a path, a step, a kerb.",
          "Say what kind it might be.",
          "Draw the one you like best."],
         "Rock is all around, doing jobs."),
]
