# -*- coding: utf-8 -*-
"""Lesson 5 - Changing Materials.

0097 Stage 2: 2Cc.01 some changes turn a material into a different material;
2Cp.03 testing; with 2TWSp.02, 2TWSa.01, 2TWSc.01, 2TWSc.04, 2TWSc.06 and
2SIC.01.
"""
from _kit import explain, step, opt, q, part, word, home, cando, icon

LESSON = {
    "slug": "changing-materials",
    "title": "Changing Materials",
    "blurb": "Cook an egg and try to un-cook it, sort changes that make a new material from ones that do not, and learn the safety rules for anything hot.",
    "steps": [
        step("demo", "Same material, or a new one?", "\U0001F373", "New or same", ["2Cc.01"],
             "Some changes make a <b>new material</b>. Some do not. Press <b>Next</b>.",
             explain(
                 ["When ice melts it is still water. Freeze it and you get ice back. The material did not change.",
                  "When an egg cooks, the runny egg becomes solid white. You cannot get the runny egg back. A new material has been made."],
                 ["Ice to water to ice: the same material.", "Raw egg to cooked egg: a new material.", "Wood to ash in a fire: a new material.", "Dough to bread in the oven: a new material."],
                 ["Children think every change makes something new.", "Ask: can you get the first material back? If yes, it is the same material."],
                 ["Press Next and ask each time: can you get it back?"]),
             {"frames": [
                 {"pic": "\U0001F9CA➡️\U0001F4A7", "cap": "Ice melts into water. Freeze it: ice again. <b>Same material.</b>", "say": "Ice melts into water. Put the water in the freezer and it is ice again. Same material, water, all along."},
                 {"pic": "\U0001F95A➡️\U0001F373", "cap": "A raw egg cooks. Can you un-cook it? No. <b>A new material.</b>", "say": "A raw egg cooks and goes white and solid. Can you un-cook it by cooling it down? No. Cooking made a new material."},
                 {"pic": "\U0001FAB5➡️\U0001F525", "cap": "Wood burns into ash and smoke. <b>A new material.</b>", "say": "Wood burns. What is left is ash and smoke. You cannot turn ash back into wood. A new material."},
                 {"pic": "\U0001F35E", "cap": "Dough bakes into bread. <b>A new material.</b>", "say": "Soft dough goes into the oven and bread comes out. A new material; there is no going back to dough."},
                 {"pic": "\U0001F36B➡️\U0001F36B", "cap": "Chocolate melts and sets again. <b>Same material.</b>", "say": "Chocolate melts in the sun and sets hard again in the fridge. Same chocolate. Same material."},
             ]},
             "If you can get the first material back, it is the same material. If you cannot, a new one was made."),

        step("experiment", "Cook an egg, then try to un-cook it", "\U0001F9EA", "Egg test", ["2Cc.01", "2TWSp.02", "2TWSc.04", "2TWSa.01"],
             "Heat the egg until it is cooked, then cool it down. Predict first: will cooling turn it back into a raw egg?",
             explain(
                 ["This experiment asks one question: once the egg is cooked, can you get the raw egg back?"],
                 ["Predict.", "Then press Heat three times and watch the clear runny part turn white and solid.", "Then press Cool it down and look."],
                 ["Children expect cooling to undo heating, because melting and freezing work that way.", "Cooking is different. Cooking makes a new material."],
                 ["Tap your prediction, then heat, then cool, then say what happened."]),
             {"sim": "newMaterial",
              "predict": {"ask": "After the egg is cooked, what will happen when you <b>cool it down</b>?",
                          "opts": [opt("It will stay cooked", True), opt("It will turn back into a raw runny egg", False), opt("It will turn into an ice cube", False)]},
              "plan": {"ask": "How shall we find out whether cooking makes a <b>new</b> material? Which way is <b>fair</b>?",
                       "opts": [opt("Heat the egg, then cool it right down again and see if it goes back", True),
                                opt("Heat the egg and then eat it", False),
                                opt("Heat one egg and freeze a different egg", False)],
                       "why": "The test for a NEW material is whether you can get the first one back. So you have to try to undo it."},
              "runAsk": "Press Heat it three times. Then press Cool it down.",
              "happened": {"ask": "What happened when the cooked egg cooled down?",
                           "opts": [opt("It stayed cooked. It did not go back to raw", True), opt("It went runny and raw again", False), opt("It disappeared", False)],
                           "why": "Cooling did not undo the cooking. Cooking made a new material, and there is no going back."},
              "conclude": {"ask": "So what did we find out about <b>cooking</b>?",
                           "opts": [opt("Cooking makes a new material that you cannot change back", True),
                                    opt("Cooking only changes the shape", False),
                                    opt("Cooling always undoes cooking", False)],
                           "why": "The egg would not go back however cold it got. When you cannot get the first material back, a new one has been made."}},
             "Cooking makes a new material. Cooling cannot undo it."),

        step("sort", "New material, or the same one back?", "\U0001F5C2️", "Change sorter", ["2Cc.01", "2TWSc.01"],
             "Does this change make a <b>new material</b>, or can you get the same material back? Tap the bin.",
             explain(
                 ["Two kinds of change.", "Melting and freezing, and bending and squashing, keep the material.", "Cooking and burning make a new material."],
                 ["Ice melting: same.", "Bread toasting brown: new.", "Clay squashed: same, still clay.", "A candle burning: new."],
                 ["Children put melting chocolate in New because it looks so different.", "Let it set and it is chocolate again. Same."],
                 ["Ask: could you get the first material back?"]),
             {"ask": "A new material, or the same one back?",
              "bins": [{"id": "new", "label": "New material", "pic": "\U0001F525"}, {"id": "same", "label": "Same material back", "pic": "\U0001F504"}],
              "items": [
                  {"pic": "\U0001F9CA", "label": "ice melting", "bin": "same", "why": "Melted ice is water; freeze it and it is ice again."},
                  {"pic": "\U0001F35E", "label": "bread toasting brown", "bin": "new", "why": "Toast cannot go back to being bread. A new material."},
                  {"pic": "\U0001F7E4", "label": "clay squashed flat", "bin": "same", "why": "Squashed clay is still clay. Roll it back into a ball."},
                  {"pic": "\U0001F56F️", "label": "a candle burning", "bin": "new", "why": "The burning wax becomes gas and smoke. It cannot come back."},
                  {"pic": "\U0001F36B", "label": "chocolate melting", "bin": "same", "why": "Melted chocolate sets again. Same chocolate."},
                  {"pic": "\U0001F95A", "label": "an egg frying", "bin": "new", "why": "A fried egg cannot become raw again. You saw it."},
                  {"pic": "\U0001F4C4", "label": "paper folded", "bin": "same", "why": "Folded paper is still paper. Unfold it."},
                  {"pic": "\U0001F525", "label": "wood burning", "bin": "new", "why": "Ash and smoke cannot be turned back into wood."},
                  {"pic": "\U0001F4A7", "label": "water freezing", "bin": "same", "why": "Ice melts back into water. Same material."},
                  {"pic": "\U0001F370", "label": "cake mix baking", "bin": "new", "why": "A baked cake cannot go back to being runny mix."},
              ]},
             "Melting, freezing and squashing keep the material. Cooking and burning make a new one."),

        step("record", "Record what heating did", "\U0001F4DD", "Recorded it", ["2TWSc.06", "2Cc.01"],
             "Record what happened to each thing when it was heated. What happened to <b>%s</b>?",
             explain(
                 ["A table holds what happened to each material, side by side."],
                 ["The egg: cooked into a new material.", "The ice: melted, same material.", "The chocolate: melted, same.", "The dough: baked into a new material."],
                 [],
                 ["Fill in each row."]),
             {"ask": "When %s was heated, what happened?",
              "columns": ["Heated", "What happened"],
              "rows": [
                  {"pic": "\U0001F95A", "label": "the egg", "answer": "new", "why": "the egg cooked into a new material."},
                  {"pic": "\U0001F9CA", "label": "the ice", "answer": "melt", "why": "the ice melted, and it was still water."},
                  {"pic": "\U0001F36B", "label": "the chocolate", "answer": "melt", "why": "the chocolate melted, and it was still chocolate."},
                  {"pic": "\U0001F35E", "label": "the dough", "answer": "new", "why": "the dough baked into bread, a new material."},
              ],
              "choices": [{"id": "melt", "t": "Melted, same material", "pic": "\U0001F4A7"}, {"id": "new", "t": "Became a new material", "pic": "\U0001F525"}],
              "read": [
                  {"ask": "Look at your table. Which two rows gave you the <b>same material back</b>?",
                   "opts": [opt("the ice and the chocolate - both only melted", True), opt("the egg and the dough", False), opt("all four of them", False)],
                   "why": "The ice melted to water and the chocolate melted to chocolate: both still the same material. The egg and the dough became new materials."},
                  {"ask": "Two rows say it melted and two say a new material. What does that tell you?",
                   "opts": [opt("some changes make a new material and some do not", True),
                            opt("every change makes a new material", False),
                            opt("no change ever makes a new material", False)],
                   "why": "It depends on the change. That is the whole point of the table."},
              ]},
             "Your table shows which changes made something new."),

        step("explore", "Safe with heat", "\U0001F9E4", "Safe hands", ["2TWSc.04", "2TWSc.02"],
             "Heating changes materials, and heat can hurt. Tap each rule.",
             explain(
                 ["Experiments with heat are done with a grown-up, and there are rules that keep everyone safe."],
                 ["A grown-up uses the cooker.", "Leave anything hot for a grown-up to move.", "Never touch a pan to see if it is hot.", "Long hair tied back.", "Wait for things to cool before you pick them up."],
                 ["Children think a pan that has stopped steaming is cool.", "Metal stays hot long after it stops steaming."],
                 ["Tap every rule and listen."]),
             {"items": [
                 {"pic": "\U0001F9D1‍\U0001F373", "label": "a grown-up handles the heat", "say": "A grown-up uses the cooker, the kettle and the oven. You watch and record."},
                 {"pic": "\U0001F9E4", "label": "leave it for a grown-up", "say": "Anything that has been heated, even if it looks cool, is for a grown-up to move with oven gloves. Leave it, or wait until it is cool."},
                 {"pic": "✋", "label": "never touch to test", "say": "Never touch a pan or a tray to find out if it is hot. Ask, or wait."},
                 {"pic": "\U0001F487", "label": "hair tied back", "say": "Long hair tied back and sleeves rolled up, away from the heat."},
                 {"pic": "⏳", "label": "wait for it to cool", "say": "Metal stays hot long after it stops steaming. Wait before picking anything up."},
             ], "need": 5,
              "then": {"ask": "The pan has stopped steaming. Is it safe to pick up with bare hands?",
                       "opts": [opt("No. Metal stays hot long after it stops steaming", True), opt("Yes, no steam means it is cool", False), opt("Yes, if you are quick", False)],
                       "why": "No steam does not mean no heat. Leave it for a grown-up to move, or wait until it is cool."}},
             "Heat changes materials, and heat rules keep hands safe."),

        step("context", "Long ago, and now", "\U0001F56F️", "Long ago", ["2SIC.01"],
             "What people knew about materials has changed. Tap each picture.",
             explain(
                 ["People have always changed materials, by cooking and by fire, long before they knew why."],
                 ["Long ago people found that heating clay made it hard, and made pots.", "Long ago people thought some materials could be turned into gold by heating them. Now we know they cannot.",
                  "Now scientists know exactly what happens inside a material when it is heated."],
                 [],
                 ["Tap each picture and compare then with now."]),
             {"items": [
                 {"pic": "\U0001F3FA", "label": "the first pots", "say": "Thousands of years ago, people found that soft clay baked in a fire became hard and held water. They did not know why. Now we know heating makes it a new material."},
                 {"pic": "\U0001F9EA", "label": "turning things to gold", "say": "Long ago some people spent their lives heating and mixing materials to make gold. They never could, because gold cannot be made from other materials. But their experiments were the beginning of chemistry."},
                 {"pic": "\U0001F52C", "label": "now", "say": "Now scientists can say exactly which changes make a new material and which do not, and they use that to make medicines, plastics and glass."},
                 {"pic": "\U0001F35E", "label": "bread then and now", "say": "People baked bread thousands of years ago and still do. The science is the same; now we understand it."},
             ], "need": 4,
              "then": {"ask": "Long ago, people tried to turn ordinary materials into gold by heating them. What do we know now?",
                       "opts": [opt("Gold cannot be made from other materials, but the experiments started chemistry", True), opt("It worked, and that is where gold comes from", False), opt("Nobody ever tried", False)],
                       "why": "What people knew changed. The trying was not wasted: it was the start of chemistry."}},
             "What people knew has changed, and it changed by testing."),

        step("questions", "Same or new?", "✅", "Same or new", ["2Cc.01"],
             "Does the change make a new material? Tap the answer.",
             explain(
                 ["One question answers every one of these: can you get the first material back?"],
                 ["Melting, freezing, bending, squashing: yes, same material.", "Cooking, baking, burning: no, new material."],
                 [],
                 ["Read the change, ask the question, then tap."]),
             {"label": "Question", "items": [
                 q("Butter melts in a hot pan. Can you get solid butter back?", "\U0001F9C8", "Yes, let it cool. Same material.", ["No, it is a new material", "No, it turns to water"], "Melted butter sets again when it cools."),
                 q("A marshmallow is toasted brown over a fire. Same material?", "\U0001F525", "No. Toasting made a new material.", ["Yes, it is the same", "Yes, it just melted"], "The brown toasted part cannot go back to being white marshmallow."),
                 q("A snowman melts in the sun. What is the water?", "⛄", "the same material as the snow", ["a new material", "gone for ever"], "Snow is frozen water. Melted snow is water. Same material."),
                 q("A match is struck and burns. Same material after?", "\U0001F525", "No. Burning made ash and smoke, new materials.", ["Yes, it is still a match", "Yes, it just got warm"], "Burning always makes new materials."),
                 q("You roll a flat sheet of paper into a tube. The tube is stiff. Did the <b>material</b> change?", "\U0001F4C4", "No. The object changed shape; the paper is as bendy as ever.", ["Yes, it became a stiff material", "Yes, rolling makes new paper"], "Unroll it and it is the same bendy paper. The OBJECT changed, not the material."),
                 q("Sofia says toast is just bread with a brown top, so it is still bread. Is she right?", "\U0001F35E", "No. The brown is a new material, and no cooling turns toast back into bread.", ["Yes, it is still bread underneath", "Yes, if you scrape the brown off"], "Scraping the brown off does not give you a fresh slice back, and cooling gives you cold toast. Toasting made something new."),
                 q("Are all inventors and scientists people from long ago?", "\U0001F52C", "No. Scientists are discovering new things today.", ["Yes, they all lived long ago", "Yes, they are all very old"], "There are scientists at work right now, finding out things nobody knew last year. Some of them are quite young."),
             ],
              "support": [
                 q("Does toast ever go back to being bread?", "\U0001F35E", "No", ["Yes"],
                   "Toasting makes a new material, and it does not go back."),
                 q("Can you un-burn a burnt match?", "\U0001F525", "No", ["Yes"],
                   "Burning makes new materials that will not go back."),
                 q("Does ice melt into water?", "\U0001F9CA", "Yes", ["No"],
                   "Ice and water are the same material, warm or cold."),
                 q("Does a candle get shorter as it burns?", "\U0001F56F\uFE0F", "Yes", ["No"],
                   "The wax burns away into new materials that go off into the air."),
              ],
              "extension": [
                 q("You mix flour and water into a dough. A new material, or a mixture?", "\U0001F35A", "a mixture - the flour and the water are both still in there", ["a new material, because it looks different", "neither of the two"],
                   "Looking different is not the test. Ask whether the materials you started with are still there."),
                 q("Bread goes hard and stale after a week. Same material, or new?", "\U0001F956", "the same bread, only dried out", ["a new material", "it has turned itself into toast"],
                   "Drying out is a change you can see, and it makes nothing new. Toasting the same slice would."),
                 q("You tear a sheet of paper into twenty pieces. Have you made a new material?", "\U0001F4C4", "no - twenty pieces of paper are still paper", ["yes, because it looks different now", "yes, because you cannot put it back"],
                   "Not being able to undo something is not the test. Ask whether the material itself has changed."),
                 q("Milk left out for a week smells sour and goes lumpy. Same material, or new?", "\U0001F95B", "new - and no amount of cooling turns it back into fresh milk", ["the same milk, only warmer", "the same milk, only older"],
                   "Souring makes new materials. That is why it cannot be undone, and why the smell changes."),
              ]},
             "Melt, freeze, squash: same. Cook, bake, burn: new.",
             mis=["3.5-m1", "rtg-11", "rtg-12"]),

        step("quiz", "Show what you know", "⭐", "Star scientist", ["2Cc.01", "2TWSc.04"],
             "Time to show what you know. Tap the answer.",
             explain(
                 ["No new ideas here.", "Every question uses something you have already done in this lesson."],
                 ["Ask: can you get the first material back?"],
                 [],
                 ["Take your time. Read it, look at it, then tap."]),
             {"items": [
                 q("You cook an egg. Can you cool it back into a raw egg?", "\U0001F373", "No. Cooking made a new material.", ["Yes, put it in the fridge", "Yes, if you are quick"], "You tried it. Cooling does not undo cooking."),
                 q("Ice melts. Is the water a new material?", "\U0001F9CA", "No. It is the same water, and can freeze again.", ["Yes, water is new", "Yes, it can never be ice"], "Melting and freezing keep the material."),
                 q("Which change makes a new material?", "\U0001F525", "burning wood", ["melting chocolate", "folding paper", "squashing clay"], "Burning turns wood into ash and smoke, which cannot become wood again."),
                 q("Which change keeps the same material?", "\U0001F504", "melting butter", ["baking a cake", "frying an egg", "burning a candle"], "Melted butter sets again."),
                 q("Dough goes in the oven. What comes out?", "\U0001F35E", "bread, a new material", ["dough, the same", "water"], "Baking makes a new material."),
                 q("Who works the cooker in a heating experiment?", "\U0001F9D1‍\U0001F373", "a grown-up", ["the fastest child", "nobody"], "Heat is a grown-up's job; you watch and record."),
                 q("The pan has stopped steaming. What do you do?", "\U0001F9E4", "leave it for a grown-up to move, or wait until it is cool", ["pick it up with bare hands", "touch it to check"], "Metal stays hot long after the steam stops."),
                 q("Long ago people tried to make gold by heating other materials. What happened?", "\U0001F9EA", "It never worked, but it started chemistry", ["They made lots of gold", "They gave up straight away"], "What people knew changed by testing."),
                 q("Why can you get chocolate back after it melts, but not bread back after it is toasted?", "\U0001F36B", "melting keeps the same material; toasting makes a new one", ["chocolate is brown", "bread is bigger than chocolate"], "Melted chocolate sets into chocolate again. Toasting changes bread into a new material that cannot go back."),
             ],
              "support": [
                 q("You melt chocolate and let it go cold. Is it chocolate again?", "\U0001F36B", "Yes", ["No"],
                   "Melting and setting give the same material back."),
                 q("Can you un-cook a cooked egg?", "\U0001F373", "No", ["Yes, by freezing it"],
                   "Cooking makes a new material that will not go back."),
                 q("Does cooking an egg make a new material?", "\U0001F373", "Yes", ["No"],
                   "A cooked egg will never go back to being raw."),
                 q("Who should handle a hot pan?", "\U0001F9D1", "a grown-up", ["you, carefully"],
                   "Heating is a grown-up's job in every experiment."),
              ],
              "extension": [
                 q("Water freezes hard, then melts again. Has a <b>new material</b> been made?", "\u2744\uFE0F", "No - it is the same water, and you can always get it back", ["Yes, ice is a new material", "Only while it stays frozen"],
                   "The test is whether you can get the first material back. With ice you always can."),
                 q("A nail left outdoors for a year goes brown and flaky. Same material, or new?", icon("nail"),"new - and no washing turns the flakes back into a shiny nail", ["the same, it is only dirty", "the same, it just needs a rub"],
                   "Rust is a different material from the metal it came from. Like cooking, it does not go back."),
                 q("A candle is lit and gets shorter. Where has the wax gone?", "\U0001F56F\uFE0F", "it burned into new materials that went off into the air", ["it melted onto the table", "it shrank into itself"],
                   "Burning is not disappearing. The wax became something new that you cannot see."),
                 q("Wet clothes dry on a line. Is drying the same kind of change as toasting bread?", "\U0001F455", "no - drying makes nothing new, and toasting does", ["yes, both make something new", "yes, both can be undone"],
                   "The water left the cloth and is still water. Toast is a material that was not there before."),
              ]},
             "That is the whole lesson finished. You know which changes make something new."),
    ],
}


# ---- the unit shell (drawn by lesson-kit/_shell.py): what this lesson is about,
#      the lecture, its science words, and things to do at home ----------------
LESSON["about"] = [
    "Say whether a change makes a new material or keeps the same one.",
    "Cook an egg and try to un-cook it.",
    "Record what heating did to four materials.",
    "Say the safety rules for anything hot.",
]

LESSON["warmup"] = [
    q("What happens to an ice cube on a warm day?", "\U0001F9CA", "it melts into water", ["it grows bigger", "it turns into wood"], "Warmth melts ice into water."),
    q("What does a toaster do to bread?", "\U0001F35E", "makes it brown and crisp", ["turns it back into dough", "makes it cold and wet"], "Heat changes bread into toast."),
    q("Which teeth do the chewing at the back of your mouth?", "\U0001F9B7", "the molars", ["the incisors", "the canines"],
      "Molars are the big flat grinders at the back."),
]

LESSON["lecture"] = [
    part("\U0001F9CA", "Same material back",
         "Ice melts into water. Put the water in the freezer and it is ice again. Melting and freezing keep the same material. You can get it back."),
    part("\U0001F373", "A new material",
         "The egg white is runny and clear. Cook it and it goes white and solid. Cool it down and it stays cooked. Cooking made a new material. You cannot get the egg back."),
    part("\U0001F525", "Burning",
         "Wood burns. What is left is ash and smoke. You cannot turn ash back into wood. Burning always makes a new material."),
    part("\U0001F35E", "Baking",
         "Soft dough goes into the oven. Bread comes out. A new material: the dough is gone for good. Cake mix does the same."),
    part("\U0001F9E4", "Safe with heat",
         "A grown-up handles the heating. Leave hot things for a grown-up to move. Never touch to test if it is hot. Tie back hair. Wait for things to cool. Heat changes materials, and heat rules keep hands safe."),
]

LESSON["words"] = [
    word("melt", "\U0001F9CA", "To change from solid to liquid when heated.",
         ["Ice melts in the sun.", "Chocolate melts in your hand."]),
    word("freeze", "\u2744\uFE0F", "To change from liquid to solid when cooled.",
         ["Water freezes into ice.", "Juice freezes into an ice lolly."]),
    word("heat", "\U0001F525", "To make something hotter.",
         ["We heat the pan.", "Heat cooks the egg."]),
    word("cool", "\U0001F32C\uFE0F", "To make something colder.",
         ["Let the pan cool before you touch it.", "Cool the egg and it stays cooked."]),
    word("cook", "\U0001F373", "To heat food until it changes into something new.",
         ["We cook the egg.", "Cooking makes a new material."]),
    word("burn", "\U0001F56F\uFE0F", "To be on fire and turn into ash and smoke.",
         ["The candle burns.", "Wood burns to ash."]),
    word("reversible", "\u21A9\uFE0F", "A change you can undo, getting the same material back.",
         ["Melting ice is reversible.", "Freezing water is reversible too."]),
    word("solid", "\U0001F9F1", "A material that keeps its own shape and does not flow.",
         ["Ice is a solid.", "A brick is a solid."]),
    word("liquid", "\U0001F4A7", "A material that flows and can be poured.",
         ["Water is a liquid.", "Melted chocolate is a liquid."]),
    word("safe", "\u2705", "It will not hurt you. The opposite of dangerous.",
         ["Ask a grown-up before you go near anything hot, to stay safe.", "Oven gloves make it safe to hold a hot tray."]),
    word("mixture", "\U0001F963", "Two or more materials put together that you can separate again.",
         ["Sand and water make a mixture.", "In a mixture each material keeps its own properties."]),
]

LESSON["cando"] = [
    cando("I can describe how some materials can be changed.", "2Cc.01"),
    cando("I can say which changes make a new material and which do not.", "2Cc.01"),
    cando("I can say what I think will happen before I try it.", "2TWSp.02"),
    cando("I can say whether what happened matched my prediction.", "2TWSa.01"),
    cando("I can keep myself safe when I work with something hot.", "2TWSc.04"),
    cando("I can record what happened in a table.", "2TWSc.06"),
    cando("I can say how what people thought long ago is different from what we know now.", "2SIC.01"),
]

LESSON["home"] = [
    home("Melt it, freeze it", "An ice cube, a plate, an ice tray, a freezer",
         ["Put an ice cube on a plate in a warm room and watch it melt.",
          "Pour the water into the ice tray and put it in the freezer.",
          "Look the next morning."],
         "The same water came back as ice. Reversible."),
    home("Cook an egg with a grown-up", "An egg, a pan, a hob, a grown-up",
         ["Crack the egg into a bowl. Look: the egg white is runny and clear.",
          "Wash your hands after touching raw egg.",
          "A grown-up cooks it in the pan. Watch it change.",
          "Let it cool. Is it runny again?"],
         "It stays cooked. A new material. You cannot get the egg back."),
    home("Toast test", "A slice of bread, a toaster, a grown-up",
         ["Look at the bread. Soft and pale.",
          "A grown-up toasts it.",
          "Let it cool and look again."],
         "Brown and crisp, and cooling does not make it bread again."),
]
