# -*- coding: utf-8 -*-
"""Lesson 4 - Natural or Made?

0097 Stage 2: 2Cm.01 natural and manufactured materials; 2Cp.01 a property
is a characteristic and a material has more than one; 2Cp.02 why a material
is chosen for a purpose; 2Cp.03 materials can be tested for their properties;
with 2TWSc.01, 2TWSc.02, 2TWSc.06 and 2SIC.02.
"""
from _kit import explain, step, opt, q, part, word, home, icon, cando

LESSON = {
    "slug": "natural-or-made",
    "title": "Natural or Made?",
    "blurb": "Sort materials that come from nature from ones people make, test materials to find their properties, and work out why the right material was chosen for each job.",
    "steps": [
        step("explore", "Where does it come from?", "\U0001F333", "Natural or made", ["2Cm.01"],
             "Some materials come straight from nature. Others are <b>manufactured</b>: made by people. Tap each one.",
             explain(
                 ["A natural material is found in nature: it grows, or it is dug up.", "A manufactured material is made by people in a factory, usually out of natural ones."],
                 ["Wood grows on trees: natural.", "Wool grows on sheep: natural.", "Stone is dug from the ground: natural.",
                  "Plastic is made in a factory from oil: manufactured.", "Glass is made by melting sand: manufactured."],
                 ["Children think anything in a shop is manufactured.", "A wooden spoon in a shop is still made of a natural material. Ask where the material came from."],
                 ["Tap every card and say natural or manufactured."]),
             {"items": [
                 {"pic": "\U0001FAB5", "label": "wood", "sub": "natural", "say": "Wood grows on trees. Natural."},
                 {"pic": "\U0001F411", "label": "wool", "sub": "natural", "say": "Wool grows on a sheep and is cut off and spun. Natural."},
                 {"pic": "\U0001FAA8", "label": "stone", "sub": "natural", "say": "Stone is dug out of the ground. Natural."},
                 {"pic": "\U0001F9F4", "label": "plastic", "sub": "manufactured", "say": "Plastic is made in a factory, from oil. Manufactured."},
                 {"pic": "\U0001FA9F", "label": "glass", "sub": "manufactured", "say": "Glass is made by melting sand very hot. Manufactured, from a natural material."},
                 {"pic": "\U0001F9F5", "label": "cotton", "sub": "natural", "say": "Cotton is the fluffy seed hair of a plant. Natural."},
                 {"pic": "\U0001F9F1", "label": "brick", "sub": "manufactured", "say": "A brick is clay shaped and baked hard in a kiln. Manufactured."},
                 {"pic": "\U0001F4C4", "label": "paper", "sub": "manufactured", "say": "Paper is made in a factory by mashing wood into pulp. Manufactured, from wood."},
             ], "need": 8},
             "Natural materials grow or are dug up. Manufactured ones are made by people."),

        step("sort", "Natural, or manufactured?", "\U0001F5C2️", "Sorted it", ["2Cm.01", "2TWSc.01"],
             "Does this material come from nature, or did people make it? Tap the right bin.",
             explain(
                 ["Ask one question: could you find this material in nature, without a factory?"],
                 ["Sand on a beach: yes, natural.", "A plastic bag: no, manufactured.", "Leather from a cow's skin: natural.", "Rubber from a tree: natural, though tyres are manufactured from it."],
                 ["Children mix up the object and the material.", "A glass jar is an object; glass, the material, is manufactured from sand."],
                 ["Look at the material, decide where it came from, then tap."]),
             {"ask": "Natural, or manufactured?",
              "bins": [{"id": "nat", "label": "Natural", "pic": "\U0001F333"}, {"id": "man", "label": "Manufactured", "pic": "\U0001F3ED"}],
              "items": [
                  {"pic": "\U0001F3D6️", "label": "sand", "bin": "nat", "why": "Sand is tiny bits of rock. Natural."},
                  {"pic": "\U0001F6CD️", "label": "plastic bag", "bin": "man", "why": "Plastic is made in a factory from oil."},
                  {"pic": "\U0001F45E", "label": "leather", "bin": "nat", "why": "Leather is animal skin. Natural."},
                  {"pic": "\U0001F95B", "label": "glass", "bin": "man", "why": "Glass is made by melting sand. Manufactured."},
                  {"pic": "\U0001F9F6", "label": "wool", "bin": "nat", "why": "Wool grows on sheep. Natural."},
                  {"pic": "\U0001F9F1", "label": "brick", "bin": "man", "why": "Clay baked in a kiln by people. Manufactured."},
                  {"pic": "\U0001FAB5", "label": "wood", "bin": "nat", "why": "Wood grows on trees. Natural."},
                  {"pic": "\U0001F4C4", "label": "paper", "bin": "man", "why": "Made in a factory from wood pulp. Manufactured."},
                  {"pic": "\U0001F944", "label": "steel", "bin": "man", "why": "Steel is made by heating iron rock in a furnace. Manufactured."},
                  {"pic": "\U0001F331", "label": "cotton", "bin": "nat", "why": "Cotton grows on a plant. Natural."},
              ]},
             "Natural or manufactured: you can tell by asking where it came from."),

        step("tester", "Test the materials", "\U0001F52C", "Material tester", ["2Cp.01", "2Cp.03", "2TWSc.02"],
             "A <b>property</b> is what a material is like. Every material has several. Press each test on at least <b>four</b> materials.",
             explain(
                 ["A property is a characteristic of a material: hard, bendy, waterproof, absorbent, see-through, strong.", "One material has lots of properties at once, and you can test for each one."],
                 ["Choose glass.", "Press it: hard.", "Bend it: stiff. Another word for stiff is rigid.", "Hold it up: see-through. Another word for see-through is transparent.", "Pour water: waterproof.", "Four properties, one material.",
                  "Now choose wool and see how different its answers are.", "Wool bends easily. Another word for bendy is flexible."],
                 ["Children think one test tells you everything.", "Each test finds one property. A material has many."],
                 ["Test four materials with all four tests."]),
             {"need": 4,
              "tests": [
                  {"id": "press", "label": "Press it", "pic": "\U0001F447", "anim": "scale(1.15, 0.7)", "sound": "thud", "say": "Press the %m. It is %r."},
                  {"id": "bend", "label": "Bend it", "pic": "↩️", "anim": "rotate(-25deg) skewX(18deg)", "sound": "boing", "say": "Try to bend the %m. It is %r."},
                  {"id": "light", "label": "Hold it to the light", "pic": "\U0001F526", "anim": "scale(1.25)", "sound": "click", "say": "Hold the %m up to the light. It is %r."},
                  {"id": "water", "label": "Pour water on it", "pic": "\U0001F4A7", "anim": "translateY(8px)", "sound": "splash", "say": "Pour water on the %m. It is %r."},
              ],
              "materials": [
                  {"id": "glass", "pic": "\U0001F95B", "label": "glass", "props": {"press": "hard", "bend": "stiff", "light": "see-through", "water": "waterproof"}, "animates": {"bend": False}},
                  {"id": "wool", "pic": "\U0001F9F6", "label": "wool", "props": {"press": "soft", "bend": "bendy", "light": "not see-through", "water": "soaks up water"}},
                  {"id": "wood", "pic": "\U0001FAB5", "label": "wood", "props": {"press": "hard", "bend": "stiff", "light": "not see-through", "water": "soaks it up slowly"}, "animates": {"bend": False}},
                  {"id": "plastic", "pic": "\U0001F9F4", "label": "thin plastic", "props": {"press": "soft", "bend": "bendy", "light": "see-through", "water": "waterproof"}},
                  {"id": "metal", "pic": "\U0001F944", "label": "metal", "props": {"press": "hard", "bend": "stiff", "light": "not see-through", "water": "waterproof"}, "animates": {"bend": False}},
                  {"id": "sponge", "pic": "\U0001F9FD", "label": "sponge", "props": {"press": "soft", "bend": "bendy", "light": "not see-through", "water": "soaks up water"}},
              ]},
             "Every material has several properties, and each test finds one of them."),

        step("record", "Record: is it waterproof?", "\U0001F4DD", "Recorded it", ["2TWSc.06", "2Cp.03"],
             "Put your water test into the table. Was <b>%s</b> waterproof?",
             explain(
                 ["A results table holds one property for every material, so you can compare them."],
                 ["Glass: waterproof.", "Wool: soaked up the water.", "Metal: waterproof.", "Sponge: soaked it up."],
                 [],
                 ["Fill in each row from what the test showed."]),
             {"ask": "Was %s waterproof?",
              "columns": ["Material", "Waterproof?"],
              "rows": [
                  {"pic": "\U0001F95B", "label": "glass", "answer": "yes", "why": "the water ran off the glass."},
                  {"pic": "\U0001F9F6", "label": "wool", "answer": "no", "why": "the wool soaked the water up."},
                  {"pic": "\U0001F944", "label": "metal", "answer": "yes", "why": "the water ran off the metal."},
                  {"pic": "\U0001F9FD", "label": "sponge", "answer": "no", "why": "the sponge soaked the water up."},
                  {"pic": "\U0001F9F4", "label": "thin plastic", "answer": "yes", "why": "the water ran off the plastic."},
              ],
              "choices": [{"id": "yes", "t": "Yes, waterproof", "pic": "☔"}, {"id": "no", "t": "No, it soaks it up", "pic": "\U0001F4A7"}],
              "read": [
                  {"ask": "Read your table. How many of the five materials were <b>waterproof</b>?",
                   "opts": [opt("three", True), opt("two", False), opt("all five", False)],
                   "why": "Glass, metal and the thin plastic let the water run off. The wool and the sponge soaked it up. Three of five."},
                  {"ask": "Three of them were waterproof. Which would you pick for an umbrella?",
                   "opts": [opt("the thin plastic", True), opt("the glass, because water runs off it", False), opt("the wool, because it is soft", False)],
                   "why": "All three of glass, metal and thin plastic kept the water off. Only the plastic is also light and bendy enough to fold up. Waterproof is not the only property the job needs."},
              ]},
             "Your table compares five materials on one property."),

        step("questions", "The right material for the job", "\U0001F3E0", "Right material", ["2Cp.02", "2Cp.01"],
             "Why was this material chosen? Tap the property that made it the right one.",
             explain(
                 ["People choose a material for a job because of its properties.", "A property is what a material is like, and one material has several properties at once."],
                 ["A window is glass because glass is see-through.", "A saucepan is metal because metal is hard and does not burn.",
                  "A jumper is wool because wool is soft and warm.", "A raincoat is plastic because plastic is waterproof."],
                 ["Children answer with the object's name instead of a property.", "The question is why: which property does the job?"],
                 ["Think about what the object has to do, then tap the property."]),
             {"label": "Question", "items": [
                 q("Why is a window made of glass?", "\U0001FA9F", "glass is see-through", ["glass is soft", "glass is warm", "glass soaks up water"], "A window has to let light through and let you see out."),
                 q("Why is a saucepan made of metal?", "\U0001F373", "metal is hard and does not burn", ["metal is soft", "metal is see-through", "metal is bendy"], "A saucepan sits on a hot cooker; metal does not burn or melt there."),
                 q("Why is a jumper made of wool?", "\U0001F9F6", "wool is soft and warm", ["wool is hard", "wool is see-through", "wool is waterproof"], "A jumper has to be soft on your skin and keep you warm."),
                 q("Why are wellington boots made of rubber?", "\U0001F462", "rubber is waterproof", ["rubber is see-through", "rubber soaks up water", "rubber is hard and stiff"], "Boots for puddles have to keep your feet dry."),
                 q("Why is a towel made of cotton?", icon("towel"), "cotton soaks up water", ["cotton is waterproof", "cotton is hard", "cotton is see-through"], "A towel has to soak the water off you."),
                 q("Why is a bicycle frame made of metal?", "\U0001F6B2", "metal is strong and stiff", ["metal is soft", "metal soaks up water", "metal is bendy"], "A bicycle has to hold a person up without bending."),
                 q("Would a sponge make a good window?", "\U0001F9FD", "No. A sponge is not see-through", ["Yes, it is soft", "Yes, it soaks up rain"], "A window needs to be see-through, and a sponge is not."),
                 q("Glass is hard, see-through and waterproof. What are those three words?", "\U0001FA9F", "three properties of one material", ["three kinds of glass", "three names for a window"], "Each word says what glass is like. One material can have many properties."),
                 q("Which of these words is a property of a material?", "❓", "bendy", ["spoon", "factory"], "A property says what a material is like. Bendy is a property; a spoon is an object and a factory is a place."),
                 q("In science, what does the word <b>material</b> mean?", "\U0001F9F1", "whatever a thing is made of", ["cloth", "only hard things"], "Cloth has its own word: fabric. Material means wood, glass, metal, rock - whatever a thing is made of."),
                 q("A glass window. Which word is the <b>material</b>?", "\U0001FA9F", "glass", ["window", "shiny", "see-through"], "Window is the object. Glass is what it is made of."),
                 q("A sponge squashes easily. Is it <b>smooth</b>?", "\U0001F9FD", "No. It is soft and full of holes.", ["Yes, soft things are smooth", "Yes, if it is wet"], "Soft means it squashes. Smooth means no bumps or holes. A sponge is one and not the other."),
                 q("A thin plastic ruler does not squash, but it snaps. Is it <b>hard</b>, or <b>strong</b>?", "\U0001F4CF", "hard but not strong", ["strong but not hard", "both"], "Hard means it does not squash. Strong means it does not break. They are two different properties."),
             ],
              "support": [
                 q("Is metal hard or soft?", "\U0001F944", "hard", ["soft"],
                   "Metal does not squash, which is why a saucepan is made of it."),
                 q("Is a jumper soft or hard?", "\U0001F9F6", "soft", ["hard"],
                   "Wool is soft, which is why it is comfortable to wear."),
              ],
              "extension": [
                 q("Wool comes from a sheep and cotton from a plant. Are both natural?", "\U0001F411", "Yes - one from an animal, one from a plant, and neither made by people", ["only the wool, because a sheep is alive", "only the cotton, because plants grow"],
                   "Natural means it grows or is dug out of the ground. It does not have to come from a plant."),
                 q("A raincoat and a towel are both cloth. Why does one keep water out and the other soak it up?", "\U0001F9E5", "they are different materials, picked for opposite properties", ["the towel is simply older", "the raincoat is only thicker"],
                   "Cloth is not one material. Cotton drinks water and coated plastic sheds it. The job decides which you pick."),
              ]},
             "A material is chosen for its properties.",
             mis=["3.1-m1", "3.1-m2", "3.2-m1", "3.2-m2"]),

        step("context", "The science in everyday things", "\U0001F527", "How it works", ["2SIC.02", "2Cp.02"],
             "Science explains why everyday objects are made the way they are. Tap each one.",
             explain(
                 ["Every object around you was made of a material somebody chose on purpose."],
                 ["A kettle is metal on the outside because metal is strong, and the handle is plastic because plastic does not carry the heat to your hand.",
                  "A tyre is rubber because rubber grips and bends.", "A pencil is wood around a soft grey core, because wood is easy to sharpen."],
                 [],
                 ["Tap each object and hear which property does which job."]),
             {"items": [
                 {"pic": icon("kettle"), "label": "kettle", "say": "The body is metal, which is strong and does not melt. The handle is plastic, because plastic does not carry the heat to your hand."},
                 {"pic": "\U0001F6B2", "label": "bicycle tyre", "say": "A tyre is rubber. Rubber bends over bumps and grips the road."},
                 {"pic": "✏️", "label": "pencil", "say": "A pencil is wood around a soft grey core. Wood is easy to sharpen and light to hold."},
                 {"pic": "\U0001FA9F", "label": "window", "say": "Glass is see-through, hard and waterproof. Light comes in and the rain stays out."},
             ], "need": 4,
              "then": {"ask": "Why is a kettle's handle plastic when its body is metal?",
                       "opts": [opt("Plastic does not carry the heat to your hand", True), opt("Plastic is see-through", False), opt("Plastic is heavier", False)],
                       "why": "Metal carries heat; plastic does not, so the handle stays cool."}},
             "Science explains why things are made the way they are."),

        step("quiz", "Show what you know", "⭐", "Star scientist", ["2Cm.01", "2Cp.01", "2Cp.02", "2Cp.03"],
             "Time to show what you know. Tap the answer.",
             explain(
                 ["No new ideas here.", "Every question uses something you have already done in this lesson."],
                 ["Natural grows or is dug up; manufactured is made by people.", "A property is what a material is like, and a material has several.", "Materials are chosen for their properties."],
                 [],
                 ["Take your time. Read it, look at it, then tap."]),
             {"items": [
                 q("Which material is natural?", "\U0001F333", "wood", ["plastic", "glass", "brick"], "Wood grows on trees."),
                 q("Which material is manufactured?", "\U0001F3ED", "plastic", ["wool", "stone", "cotton"], "Plastic is made in a factory from oil."),
                 q("What is a property?", "❓", "what a material is like, such as hard or bendy", ["the name of an object", "a kind of factory", "a colour only"], "A property is a characteristic of a material."),
                 q("How many properties can one material have?", "\U0001F52C", "several at once", ["only one", "none"], "Glass is hard, stiff, see-through and waterproof all at once."),
                 q("How do we find out if a material is waterproof?", "\U0001F4A7", "test it: pour water on it and watch", ["guess from its colour", "ask the material"], "Materials can be tested for their properties."),
                 q("Why is a raincoat made of plastic?", "\U0001F9E5", "plastic is waterproof", ["plastic is soft and warm", "plastic soaks up water"], "A raincoat's job is to keep the rain off."),
                 q("Glass is made by melting...", "\U0001FA9F", "sand", ["wood", "wool", "water"], "Sand melted very hot becomes glass: a manufactured material from a natural one."),
                 q("Which is the best material for a towel?", icon("towel"), "cotton, because it soaks up water", ["glass, because it is see-through", "metal, because it is hard"], "A towel has to soak water up."),
                 q("What would happen if a raincoat were made of wool?", "\U0001F9E5", "the wool would soak up the rain and you would get wet", ["you would stay dry", "the rain would bounce off"], "Wool soaks up water. A raincoat needs a waterproof material, like plastic."),
                 q("Cotton thread is spun in a factory. Is cotton still <b>natural</b>?", "\U0001F9F5", "Yes. The factory only changed its shape, not the material.", ["No, factories make manufactured things", "Only before it goes in"], "Some factories change one material into a different one. Others just change the shape. Cotton comes out of the factory still cotton, like wood is still wood after a chair is made."),
                 q("Which of these did nobody make?", "\U0001FAB5", "wood", ["plastic", "glass", "a brick"], "Wood, rock, wool and cotton are natural. People only shape them. Plastic, glass and bricks are manufactured."),
                 q("A shiny red pencil looks like plastic. How could you tell what it is really made of?", "✏️", "look at the sharpened end", ["weigh it", "look at its colour"], "Paint makes a thin shiny layer that looks like plastic. The sharpened end shows the wood underneath."),
                 q("Two coats are both called waterproof. Is one able to be <b>more</b> waterproof than the other?", "\U0001F9E5", "Yes, and even a waterproof one soaks up a little if water sits on it long enough", ["No, waterproof means waterproof", "No, only the colour differs"], "Waterproof is not simply on or off. You can test which fabric holds water off for longest."),
             ],
              "support": [
                 q("Is wood natural or manufactured?", "\U0001FAB5", "natural", ["manufactured"],
                   "Wood grows on trees."),
                 q("Can you see through glass?", "\U0001F453", "Yes", ["No"],
                   "Glass is see-through. That is why windows are made of it."),
              ],
              "extension": [
                 q("Wood is stronger than glass. So why would you not use it for a window?", "\U0001F3E0", "a window has to be see-through, and wood is not", ["wood is not strong enough", "wood costs too little"],
                   "A material is chosen for the property the job needs. Strength is not the property a window needs most."),
                 q("Paper is made from wood, and wood is natural. So which is paper?", "\U0001F4C4", "manufactured - people turned the wood into a new material", ["natural, because it starts in a tree", "both at once"],
                   "Paper is a different material from wood. When a factory makes one material into another, the result is manufactured."),
              ]},
             "That is the whole lesson finished. You know your materials and why they are chosen.",
             mis=["3.1-m3", "rtg-09", "3.3-m1", "3.4-m1"]),
    ],
}


# ---- the unit shell (drawn by lesson-kit/_shell.py): what this lesson is about,
#      the lecture, its science words, and things to do at home ----------------
LESSON["about"] = [
    "Tell a natural material from a manufactured one.",
    "Test materials to find their properties.",
    "Record which materials are waterproof in a table.",
    "Say why the right material was chosen for a job.",
]

LESSON["warmup"] = [
    q("Where does wood come from?", "\U0001F333", "trees", ["a factory", "the sea"], "Wood grows on trees. It is a natural material."),
    q("Which of these can you see through?", "❓", "a glass window", ["a brick wall", "a wooden door"], "Light goes through glass, so you can see through it."),
]

LESSON["lecture"] = [
    part("\U0001FAB5", "Natural materials",
         "Wood comes from trees. Wool comes from sheep. Stone is dug out of the ground. A natural material grows or is dug up. People do not make it."),
    part("\U0001F3ED", "Manufactured materials",
         "Plastic, glass, brick and paper are made by people, in factories. Glass is made by melting sand. Paper is made from mashed-up wood. These are manufactured."),
    part("\U0001F50D", "Testing for properties",
         "Is it hard? Does it bend? Does water go through it? Can you see through it? Each test finds one property. A material has several."),
    part("\U0001F4A7", "Waterproof or not",
         "Drip water on glass and it runs off. Drip it on wool and it soaks in. Glass is waterproof. Wool is absorbent. You will record that in a table."),
    part(icon("kettle"), "Chosen for the job",
         "A kettle is metal because metal does not melt when it gets hot. A tyre is rubber because rubber grips and bends. Every material is chosen for its properties."),
]

LESSON["words"] = [
    word("natural", "\U0001FAB5", "Comes from nature: it grows, or is dug from the ground.",
         ["Wood is a natural material.", "Wool is natural. It comes from sheep."]),
    word("manufactured", "\U0001F3ED", "Made by people, usually in a factory.",
         ["Plastic is manufactured.", "Glass is manufactured from sand."]),
    word("property", "\U0001F50D", "Something a material is like: hard, bendy, shiny, waterproof.",
         ["Being waterproof is a property of glass.", "Test to find each property."]),
    word("waterproof", "\u2614", "Water does not go through it.",
         ["Plastic is waterproof.", "A sponge is not waterproof."]),
    word("transparent", "\U0001FA9F", "You can see through it.",
         ["Glass is transparent.", "A window must be transparent."]),
    word("flexible", "\U0001F9F6", "Bends easily without breaking.",
         ["Wool is flexible.", "A rubber tyre is flexible."]),
    word("rigid", "\U0001F9F1", "Stiff. Does not bend.",
         ["Brick is rigid.", "A rigid ruler draws a straight line."]),
    word("material", "\U0001F4E6", "What a thing is made of.",
         ["Glass is a material.", "A window is the object; glass is the material."]),
    word("object", "\U0001F9F8", "A thing you can see or touch, made out of a material.",
         ["A cup is an object.", "Name the object, then name its material."]),
    word("absorbent", "\U0001F9FD", "It soaks water up. The opposite of waterproof.",
         ["A sponge is absorbent.", "A towel is absorbent, so it dries you."]),
    word("cotton", "\U0001F455", "A soft material that comes from a plant and is made into cloth.",
         ["A T-shirt is cotton.", "Cotton is absorbent, so towels are made of it."]),
    word("water", "\U0001F4A7", "A clear liquid material we drink. The sea and rivers are water.",
         ["Water takes the shape of its container.", "Every living thing needs water."]),
    word("wood", "\U0001FAB5", "A material that comes from the trunk of a tree.",
         ["Wood is natural, not manufactured.", "A wooden spoon does not get hot."]),
    word("glass", "\U0001FA9F", "A clear, hard material we use for windows.",
         ["Glass is transparent, so light goes through.", "Glass is made from sand."]),
    word("plastic", "\U0001F9F4", "A manufactured material that comes in many colours and shapes.",
         ["A plastic bottle is waterproof.", "Plastic is made in a factory, so it is manufactured."]),
    word("paper", "\U0001F4C4", "A thin material we write on, made from wood.",
         ["Paper soaks up water, so it is absorbent.", "Paper is made from trees."]),
    word("rubber", "\U0001F388", "A material that bends and stretches easily.",
         ["A balloon is made of rubber.", "Rubber comes from the sap of a tree."]),
    word("oil", "\U0001F6E2\uFE0F", "A liquid material found deep underground.",
         ["Oil is pumped out of the ground.", "Plastic is made from oil."]),
    word("strong", "\U0001F9F1", "Not easy to break.",
         ["A brick is strong.", "We chose a strong material for the wall."]),
    word("weak", "\U0001F343", "Easy to break. The opposite of strong.",
         ["Thin paper is weak.", "A weak material would not hold the weight."]),
]

LESSON["cando"] = [
    cando("I can say where some materials come from.", "2Cm.01"),
    cando("I can name two natural materials and two manufactured ones.", "2Cm.01"),
    cando("I can name more than one property of the same material.", "2Cp.01"),
    cando("I can say why a material was chosen to make something.", "2Cp.02"),
    cando("I can test a material to find out its properties.", "2Cp.03"),
    cando("I can record what I found in a table.", "2TWSc.06"),
    cando("I can say how science explains the everyday things I use.", "2SIC.02"),
]

LESSON["home"] = [
    home("Natural or manufactured hunt", "Paper and a pencil, your house",
         ["Find ten things and ask: did this grow, get dug up, or get made in a factory?",
          "Draw two lists.",
          "Find one thing made of a natural material and a manufactured one, like a wooden table with a plastic top."],
         "Most things are manufactured. Which natural ones did you find?"),
    home("Drip test", "A tray, water, small pieces of paper, fabric, plastic, foil, cardboard, a leaf",
         ["Lay each piece on the tray.",
          "Drip water on each one and wait a minute.",
          "Write a table: material, and waterproof yes or no."],
         "Which soaked it up, and which let it run off?"),
    home("Why this material?", "A kitchen, a grown-up",
         ["Pick five things: a pan, a cup, a spoon, a chopping board, a cloth.",
          "Say what each is made of.",
          "Say one property that makes it right for the job."],
         "The pan is metal because it does not melt. What about the cloth?"),
]
