CREATE TABLE mdlgx_local_prequran_speakrec (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  userid BIGINT(20) NOT NULL,
  lessonid VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  unitid VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  step_id VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'speak',
  letter_key VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  letter_name VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  letter_text VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  attempt_no BIGINT(20) NOT NULL DEFAULT 1,
  duration_ms BIGINT(20) NOT NULL DEFAULT 0,
  mime_type VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'audio/webm',
  filesize BIGINT(20) NOT NULL DEFAULT 0,
  filename VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  bunny_path VARCHAR(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  status VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'submitted',
  score DECIMAL(10,2) NULL DEFAULT NULL,
  teacher_feedback LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  timecreated BIGINT(20) NOT NULL,
  timemodified BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  KEY mdlgx_lpreqspk_user_idx (userid),
  KEY mdlgx_lpreqspk_unit_idx (unitid),
  KEY mdlgx_lpreqspk_status_idx (status),
  KEY mdlgx_lpreqspk_created_idx (timecreated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
