-- Public parent intake request table.
-- Replace mdlgx_ with your Moodle database prefix if needed.

CREATE TABLE IF NOT EXISTS mdlgx_local_prequran_intake_request (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    parent_name VARCHAR(255) NOT NULL DEFAULT '',
    parent_email VARCHAR(255) NOT NULL DEFAULT '',
    parent_phone VARCHAR(100) NOT NULL DEFAULT '',
    student_firstname VARCHAR(100) NOT NULL DEFAULT '',
    student_lastname VARCHAR(100) NOT NULL DEFAULT '',
    student_display_name VARCHAR(255) NOT NULL DEFAULT '',
    student_email VARCHAR(255) NOT NULL DEFAULT '',
    date_of_birth VARCHAR(20) NOT NULL DEFAULT '',
    age_years BIGINT(10) NOT NULL DEFAULT 0,
    gender VARCHAR(40) NOT NULL DEFAULT '',
    special_needs VARCHAR(10) NOT NULL DEFAULT 'no',
    course_type VARCHAR(60) NOT NULL DEFAULT 'pre_quraan',
    country VARCHAR(100) NOT NULL DEFAULT '',
    city VARCHAR(100) NOT NULL DEFAULT '',
    timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',
    primary_language VARCHAR(100) NOT NULL DEFAULT '',
    other_languages LONGTEXT NULL,
    current_level VARCHAR(100) NOT NULL DEFAULT '',
    learning_base VARCHAR(100) NOT NULL DEFAULT '',
    availability_json LONGTEXT NULL,
    availability_summary LONGTEXT NULL,
    parent_preferences LONGTEXT NULL,
    live_class_consent TINYINT(1) NOT NULL DEFAULT 0,
    recording_consent TINYINT(1) NOT NULL DEFAULT 0,
    consent_notes LONGTEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'new',
    matched_groupid BIGINT(20) NOT NULL DEFAULT 0,
    transferred_userid BIGINT(20) NOT NULL DEFAULT 0,
    transferred_profileid BIGINT(20) NOT NULL DEFAULT 0,
    admin_notes LONGTEXT NULL,
    reviewedby BIGINT(20) NOT NULL DEFAULT 0,
    reviewedat BIGINT(20) NOT NULL DEFAULT 0,
    timecreated BIGINT(20) NOT NULL DEFAULT 0,
    timemodified BIGINT(20) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY mdlgx_preq_intreq_status_ix (status, timecreated),
    KEY mdlgx_preq_intreq_parent_ix (parent_email),
    KEY mdlgx_preq_intreq_match_ix (course_type, timezone, primary_language, current_level),
    KEY mdlgx_preq_intreq_transfer_ix (transferred_userid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
