-- Public parent intake request table.
-- Replace mdlgx_ with your Moodle database prefix if needed.

CREATE TABLE IF NOT EXISTS mdlgx_local_prequran_intake_request (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    parent_name VARCHAR(255) NOT NULL DEFAULT '',
    parent_email VARCHAR(255) NOT NULL DEFAULT '',
    parent_phone VARCHAR(100) NOT NULL DEFAULT '',
    student_firstname VARCHAR(100) NOT NULL DEFAULT '',
    student_middle_name VARCHAR(100) NOT NULL DEFAULT '',
    student_lastname VARCHAR(100) NOT NULL DEFAULT '',
    student_display_name VARCHAR(255) NOT NULL DEFAULT '',
    student_access_type VARCHAR(40) NOT NULL DEFAULT 'managed',
    student_email VARCHAR(255) NOT NULL DEFAULT '',
    date_of_birth VARCHAR(20) NOT NULL DEFAULT '',
    age_years BIGINT(10) NOT NULL DEFAULT 0,
    gender VARCHAR(40) NOT NULL DEFAULT '',
    current_grade VARCHAR(80) NOT NULL DEFAULT '',
    school_curriculum VARCHAR(120) NOT NULL DEFAULT '',
    current_school_name VARCHAR(255) NOT NULL DEFAULT '',
    student_lives_with VARCHAR(80) NOT NULL DEFAULT '',
    primary_learning_goal VARCHAR(255) NOT NULL DEFAULT '',
    medical_safety_notes LONGTEXT NULL,
    preferred_class_format VARCHAR(80) NOT NULL DEFAULT '',
    preferred_group_size VARCHAR(80) NOT NULL DEFAULT '',
    preferred_teacher_gender VARCHAR(40) NOT NULL DEFAULT '',
    school_term VARCHAR(80) NOT NULL DEFAULT '',
    islamic_program_interest VARCHAR(80) NOT NULL DEFAULT '',
    quran_reading_level VARCHAR(80) NOT NULL DEFAULT '',
    tajweed_level VARCHAR(80) NOT NULL DEFAULT '',
    memorization_status VARCHAR(80) NOT NULL DEFAULT '',
    memorized_portion VARCHAR(255) NOT NULL DEFAULT '',
    arabic_reading_ability VARCHAR(80) NOT NULL DEFAULT '',
    prior_islamic_studies LONGTEXT NULL,
    islamic_learning_goal VARCHAR(255) NOT NULL DEFAULT '',
    previous_learning_method VARCHAR(80) NOT NULL DEFAULT '',
    tafsir_level VARCHAR(80) NOT NULL DEFAULT '',
    islamic_notes LONGTEXT NULL,
    christian_program_interest VARCHAR(80) NOT NULL DEFAULT '',
    bible_reading_level VARCHAR(80) NOT NULL DEFAULT '',
    bible_knowledge_level VARCHAR(80) NOT NULL DEFAULT '',
    christian_studies_level VARCHAR(80) NOT NULL DEFAULT '',
    prior_christian_studies LONGTEXT NULL,
    christian_previous_learning_method VARCHAR(80) NOT NULL DEFAULT '',
    christian_learning_goal VARCHAR(255) NOT NULL DEFAULT '',
    christian_notes LONGTEXT NULL,
    higher_application_level VARCHAR(80) NOT NULL DEFAULT '',
    higher_program_field VARCHAR(255) NOT NULL DEFAULT '',
    higher_specialization VARCHAR(255) NOT NULL DEFAULT '',
    higher_highest_qualification VARCHAR(80) NOT NULL DEFAULT '',
    higher_previous_institution VARCHAR(255) NOT NULL DEFAULT '',
    higher_qualification_title VARCHAR(255) NOT NULL DEFAULT '',
    higher_completion_year VARCHAR(20) NOT NULL DEFAULT '',
    higher_academic_result VARCHAR(120) NOT NULL DEFAULT '',
    higher_academic_status VARCHAR(80) NOT NULL DEFAULT '',
    higher_admission_route VARCHAR(80) NOT NULL DEFAULT '',
    higher_transfer_credits VARCHAR(20) NOT NULL DEFAULT '',
    higher_study_mode VARCHAR(40) NOT NULL DEFAULT '',
    higher_study_load VARCHAR(40) NOT NULL DEFAULT '',
    higher_preferred_intake VARCHAR(120) NOT NULL DEFAULT '',
    higher_research_interest LONGTEXT NULL,
    higher_funding_method VARCHAR(80) NOT NULL DEFAULT '',
    higher_financial_aid_interest VARCHAR(20) NOT NULL DEFAULT '',
    higher_support_needs LONGTEXT NULL,
    technical_program VARCHAR(80) NOT NULL DEFAULT '',
    technical_specialization VARCHAR(255) NOT NULL DEFAULT '',
    technical_training_level VARCHAR(80) NOT NULL DEFAULT '',
    technical_previous_experience VARCHAR(80) NOT NULL DEFAULT '',
    technical_previous_learning_method VARCHAR(80) NOT NULL DEFAULT '',
    technical_experience_duration VARCHAR(40) NOT NULL DEFAULT '',
    technical_employment_status VARCHAR(80) NOT NULL DEFAULT '',
    technical_employer_workshop VARCHAR(255) NOT NULL DEFAULT '',
    technical_training_goal VARCHAR(80) NOT NULL DEFAULT '',
    technical_certification_sought VARCHAR(255) NOT NULL DEFAULT '',
    technical_training_format VARCHAR(80) NOT NULL DEFAULT '',
    technical_training_schedule VARCHAR(40) NOT NULL DEFAULT '',
    technical_tools_experience LONGTEXT NULL,
    technical_tool_access VARCHAR(40) NOT NULL DEFAULT '',
    technical_digital_skill_level VARCHAR(40) NOT NULL DEFAULT '',
    technical_safety_training VARCHAR(20) NOT NULL DEFAULT '',
    technical_protective_equipment VARCHAR(40) NOT NULL DEFAULT '',
    technical_support_needs LONGTEXT NULL,
    technical_notes LONGTEXT NULL,
    professional_area VARCHAR(80) NOT NULL DEFAULT '',
    professional_topic_skill VARCHAR(255) NOT NULL DEFAULT '',
    professional_current_role VARCHAR(255) NOT NULL DEFAULT '',
    professional_industry VARCHAR(80) NOT NULL DEFAULT '',
    professional_employment_status VARCHAR(80) NOT NULL DEFAULT '',
    professional_employer VARCHAR(255) NOT NULL DEFAULT '',
    professional_experience_years VARCHAR(40) NOT NULL DEFAULT '',
    professional_responsibility_level VARCHAR(80) NOT NULL DEFAULT '',
    professional_development_goal VARCHAR(80) NOT NULL DEFAULT '',
    professional_skill_level VARCHAR(40) NOT NULL DEFAULT '',
    professional_credential_sought VARCHAR(255) NOT NULL DEFAULT '',
    professional_certification_deadline VARCHAR(20) NOT NULL DEFAULT '',
    professional_learning_format VARCHAR(80) NOT NULL DEFAULT '',
    professional_learning_schedule VARCHAR(40) NOT NULL DEFAULT '',
    professional_course_intensity VARCHAR(80) NOT NULL DEFAULT '',
    professional_employer_sponsored VARCHAR(40) NOT NULL DEFAULT '',
    professional_cpd_required VARCHAR(20) NOT NULL DEFAULT '',
    professional_cpd_credits VARCHAR(40) NOT NULL DEFAULT '',
    professional_workplace_outcome LONGTEXT NULL,
    professional_support_needs LONGTEXT NULL,
    professional_notes LONGTEXT NULL,
    adult_learning_area VARCHAR(80) NOT NULL DEFAULT '',
    adult_subject_skill VARCHAR(255) NOT NULL DEFAULT '',
    adult_education_level VARCHAR(80) NOT NULL DEFAULT '',
    adult_literacy_level VARCHAR(80) NOT NULL DEFAULT '',
    adult_numeracy_level VARCHAR(80) NOT NULL DEFAULT '',
    adult_digital_skill_level VARCHAR(40) NOT NULL DEFAULT '',
    adult_previous_experience VARCHAR(80) NOT NULL DEFAULT '',
    adult_previous_learning_method VARCHAR(80) NOT NULL DEFAULT '',
    adult_learning_goal VARCHAR(80) NOT NULL DEFAULT '',
    adult_employment_status VARCHAR(80) NOT NULL DEFAULT '',
    adult_learning_format VARCHAR(80) NOT NULL DEFAULT '',
    adult_learning_pace VARCHAR(40) NOT NULL DEFAULT '',
    adult_class_arrangement VARCHAR(40) NOT NULL DEFAULT '',
    adult_childcare_impact VARCHAR(40) NOT NULL DEFAULT '',
    adult_work_impact VARCHAR(20) NOT NULL DEFAULT '',
    adult_access_limitations VARCHAR(40) NOT NULL DEFAULT '',
    adult_learning_confidence VARCHAR(40) NOT NULL DEFAULT '',
    adult_support_needs LONGTEXT NULL,
    adult_notes LONGTEXT NULL,
    special_needs VARCHAR(10) NOT NULL DEFAULT 'no',
    course_type VARCHAR(60) NOT NULL DEFAULT 'pre_quraan',
    country VARCHAR(100) NOT NULL DEFAULT '',
    city VARCHAR(100) NOT NULL DEFAULT '',
    timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',
    primary_language VARCHAR(100) NOT NULL DEFAULT '',
    preferred_teaching_language VARCHAR(100) NOT NULL DEFAULT '',
    other_languages LONGTEXT NULL,
    current_level VARCHAR(100) NOT NULL DEFAULT '',
    tajweed_sub_level VARCHAR(40) NOT NULL DEFAULT '',
    learning_base VARCHAR(100) NOT NULL DEFAULT '',
    availability_json LONGTEXT NULL,
    availability_summary LONGTEXT NULL,
    parent_preferences LONGTEXT NULL,
    parent_email_enabled TINYINT(1) NOT NULL DEFAULT 1,
    live_class_consent TINYINT(1) NOT NULL DEFAULT 0,
    recording_consent TINYINT(1) NOT NULL DEFAULT 0,
    consent_notes LONGTEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'new',
    matched_groupid BIGINT(20) NOT NULL DEFAULT 0,
    transferred_userid BIGINT(20) NOT NULL DEFAULT 0,
    transferred_profileid BIGINT(20) NOT NULL DEFAULT 0,
    admin_notes LONGTEXT NULL,
    reviewedby BIGINT(20) NOT NULL DEFAULT 0,
    reviewedat BIGINT(20) NOT NULL DEFAULT 0,
    timecreated BIGINT(20) NOT NULL DEFAULT 0,
    timemodified BIGINT(20) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY mdlgx_preq_intreq_status_ix (status, timecreated),
    KEY mdlgx_preq_intreq_parent_ix (parent_email),
    KEY mdlgx_preq_intreq_match_ix (course_type, timezone, primary_language, current_level),
    KEY mdlgx_preq_intreq_transfer_ix (transferred_userid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
