CREATE TABLE mdlgx_local_prequran_live_session (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  cohortid BIGINT(20) NOT NULL DEFAULT 0,
  teacherid BIGINT(20) NOT NULL,
  lessonid VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  unitid VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  title VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  description LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  scheduled_start BIGINT(20) NOT NULL,
  scheduled_end BIGINT(20) NOT NULL,
  timezone VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UTC',
  status VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'scheduled',
  recording_enabled TINYINT(1) NOT NULL DEFAULT 0,
  recording_consent_required TINYINT(1) NOT NULL DEFAULT 1,
  parent_observer_allowed TINYINT(1) NOT NULL DEFAULT 0,
  max_participants INT(10) NOT NULL DEFAULT 12,
  bbb_meeting_id VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  bbb_internal_meeting_id VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  bbb_created TINYINT(1) NOT NULL DEFAULT 0,
  bbb_create_time BIGINT(20) NOT NULL DEFAULT 0,
  bbb_last_error LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  createdby BIGINT(20) NOT NULL DEFAULT 0,
  cancelledby BIGINT(20) NOT NULL DEFAULT 0,
  cancellation_reason LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  timecreated BIGINT(20) NOT NULL,
  timemodified BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY mdlgx_lpreqlive_session_bbb_uix (bbb_meeting_id),
  KEY mdlgx_lpreqlive_session_teacher_time_ix (teacherid, scheduled_start),
  KEY mdlgx_lpreqlive_session_cohort_time_ix (cohortid, scheduled_start),
  KEY mdlgx_lpreqlive_session_status_time_ix (status, scheduled_start),
  KEY mdlgx_lpreqlive_session_lesson_unit_ix (lessonid, unitid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mdlgx_local_prequran_live_participant (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  sessionid BIGINT(20) NOT NULL,
  userid BIGINT(20) NOT NULL,
  role VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'student',
  studentid BIGINT(20) NOT NULL DEFAULT 0,
  status VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  displayname VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  invitedby BIGINT(20) NOT NULL DEFAULT 0,
  timecreated BIGINT(20) NOT NULL,
  timemodified BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY mdlgx_lpreqlive_part_session_user_role_uix (sessionid, userid, role),
  KEY mdlgx_lpreqlive_part_user_ix (userid),
  KEY mdlgx_lpreqlive_part_student_ix (studentid),
  KEY mdlgx_lpreqlive_part_role_status_ix (role, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mdlgx_local_prequran_live_attendance (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  sessionid BIGINT(20) NOT NULL,
  userid BIGINT(20) NOT NULL,
  studentid BIGINT(20) NOT NULL DEFAULT 0,
  join_time BIGINT(20) NOT NULL DEFAULT 0,
  leave_time BIGINT(20) NOT NULL DEFAULT 0,
  attendance_status VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'absent',
  participation_status VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  technical_issue TINYINT(1) NOT NULL DEFAULT 0,
  notes LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  markedby BIGINT(20) NOT NULL DEFAULT 0,
  timecreated BIGINT(20) NOT NULL,
  timemodified BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY mdlgx_lpreqlive_att_session_student_uix (sessionid, studentid),
  KEY mdlgx_lpreqlive_att_user_ix (userid),
  KEY mdlgx_lpreqlive_att_status_ix (attendance_status),
  KEY mdlgx_lpreqlive_att_markedby_ix (markedby)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mdlgx_local_prequran_live_note (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  sessionid BIGINT(20) NOT NULL,
  studentid BIGINT(20) NOT NULL,
  teacherid BIGINT(20) NOT NULL,
  strengths LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  needs_practice LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  homework LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  parent_summary LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  private_note LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  visible_to_parent TINYINT(1) NOT NULL DEFAULT 1,
  timecreated BIGINT(20) NOT NULL,
  timemodified BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY mdlgx_lpreqlive_note_session_student_uix (sessionid, studentid),
  KEY mdlgx_lpreqlive_note_student_ix (studentid),
  KEY mdlgx_lpreqlive_note_teacher_ix (teacherid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mdlgx_local_prequran_live_recording (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  sessionid BIGINT(20) NOT NULL,
  bbb_record_id VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  bbb_meeting_id VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  name VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  playback_url LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  playback_format VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  duration_minutes INT(10) NOT NULL DEFAULT 0,
  published TINYINT(1) NOT NULL DEFAULT 0,
  visible_to_parent TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'available',
  reviewedby BIGINT(20) NOT NULL DEFAULT 0,
  reviewedat BIGINT(20) NOT NULL DEFAULT 0,
  expiresat BIGINT(20) NOT NULL DEFAULT 0,
  raw_metadata LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  timecreated BIGINT(20) NOT NULL,
  timemodified BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY mdlgx_lpreqlive_rec_record_uix (bbb_record_id),
  KEY mdlgx_lpreqlive_rec_session_ix (sessionid),
  KEY mdlgx_lpreqlive_rec_meeting_ix (bbb_meeting_id),
  KEY mdlgx_lpreqlive_rec_parent_status_ix (visible_to_parent, status),
  KEY mdlgx_lpreqlive_rec_expires_ix (expiresat)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mdlgx_local_prequran_live_consent (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  studentid BIGINT(20) NOT NULL,
  guardianid BIGINT(20) NOT NULL,
  consent_type VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'live_session',
  granted TINYINT(1) NOT NULL DEFAULT 0,
  version VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '1',
  consent_source VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  details LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  timecreated BIGINT(20) NOT NULL,
  timemodified BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY mdlgx_lpreqlive_cons_student_guard_type_uix (studentid, guardianid, consent_type),
  KEY mdlgx_lpreqlive_cons_guardian_ix (guardianid),
  KEY mdlgx_lpreqlive_cons_type_granted_ix (consent_type, granted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE mdlgx_local_prequran_live_audit (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  sessionid BIGINT(20) NOT NULL DEFAULT 0,
  actorid BIGINT(20) NOT NULL DEFAULT 0,
  action VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  targettype VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  targetid BIGINT(20) NOT NULL DEFAULT 0,
  details LONGTEXT COLLATE utf8mb4_unicode_ci NULL,
  timecreated BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  KEY mdlgx_lpreqlive_audit_session_time_ix (sessionid, timecreated),
  KEY mdlgx_lpreqlive_audit_actor_time_ix (actorid, timecreated),
  KEY mdlgx_lpreqlive_audit_action_time_ix (action, timecreated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
