// Names of Allah Unit - Unit Authoring Config
// Populated from Names of Allah.docx with noa_ keys.

const __PQ_NORMALIZE_UNIT_CONFIG__ = (
  (typeof window !== 'undefined' && window.PQUnitConfigNormalizer) ||
  (typeof globalThis !== 'undefined' && globalThis.PQUnitConfigNormalizer)
);

if (!__PQ_NORMALIZE_UNIT_CONFIG__ || typeof __PQ_NORMALIZE_UNIT_CONFIG__.normalize !== 'function') {
  throw new Error('PQUnitConfigNormalizer must load before unit.config.js');
}

const UNIT_CFG = __PQ_NORMALIZE_UNIT_CONFIG__.normalize({
  "schemaVersion": 1,
  "identity": {
    "lessonId": "extras",
    "unitId": "names_of_allah",
    "unitKey": "names-of-allah",
    "storagePrefix": "names_of_allah",
    "keyPrefix": "noa_",
    "prefKey": "prequran_names_of_allah_state_v1"
  },
  "moodle": {
    "wsGetFunction": "local_prequran_get_names_of_allah_state",
    "wsSetFunction": "local_prequran_set_names_of_allah_state"
  },
  "release": {
    "version": "0.1.0",
    "assetVersion": "names-of-allah-clone-20260529d"
  },
  "localization": {
    "defaultLanguage": "en",
    "fallbackLanguage": "en",
    "defaultScope": "both",
    "supportedLanguages": [
      "en",
      "ar",
      "so",
      "sw",
      "pa",
      "ur"
    ],
    "translations": {
      "ar": {},
      "so": {},
      "sw": {},
      "pa": {},
      "ur": {}
    }
  },
  "assets": {
    "cdnRoot": "/pre_quraan",
    "unitMediaRoot": "/lessons/names-of-allah/media",
    "filePrefix": "noa_",
    "mediaPadWidth": 2,
    "audioExt": ".mp3",
    "soundAudioExt": ".mp3",
    "videoFilePrefix": "noa_"
  },
  "routes": {
    "academyHomeUrl": "https://quraan.academy/"
  },
  "messaging": {
    "useConfigStepMessages": true,
    "disableLegacyCompletionFeedback": true
  },
  "messageUi": {
    "titleText": "Message",
    "continueText": "Continue",
    "clap": {
      "enabled": true,
      "visual": true,
      "audio": "",
      "delayMs": 120
    }
  },
  "stepNavigation": {
    "previous": {
      "enabled": true,
      "label": "← Step Back",
      "title": "Go back one step",
      "confirmTitle": "Go back one step?",
      "confirmText": "This will move you back to {previousStep}. Your progress for {currentStep} and {previousStep} will be reset so you can try again.",
      "confirmContinueText": "Yes, go back",
      "confirmCancelText": "Stay here"
    }
  },
  "steps": [
    {
      "id": "lecture",
      "type": "lecture",
      "label": "Lecture",
      "arabicLabel": "شرح",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    },
    {
      "id": "listen",
      "type": "playlist",
      "label": "Listen",
      "arabicLabel": "استمع",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    },
    {
      "id": "watch",
      "type": "video_playlist",
      "label": "Watch",
      "arabicLabel": "شاهد",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    },
    {
      "id": "repeat",
      "type": "playlist",
      "label": "Repeat",
      "arabicLabel": "كرر",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    },
    {
      "id": "match",
      "type": "match",
      "label": "Match",
      "arabicLabel": "طابق",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    },
    {
      "id": "animate",
      "type": "animate",
      "label": "Animate",
      "arabicLabel": "شاهد الكتابة",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    },
    {
      "id": "write",
      "type": "write",
      "label": "Write",
      "arabicLabel": "اكتب",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    },
    {
      "id": "submit",
      "type": "submit",
      "label": "Submit",
      "arabicLabel": "أرسل",
      "passFilters": [
        "all"
      ],
      "filter": "all"
    }
  ],
  "filterSets": {
    "all": [
      "noa_01",
      "noa_02",
      "noa_03",
      "noa_04",
      "noa_05",
      "noa_06",
      "noa_07",
      "noa_08",
      "noa_09",
      "noa_10",
      "noa_11",
      "noa_12",
      "noa_13",
      "noa_14",
      "noa_15",
      "noa_16",
      "noa_17",
      "noa_18",
      "noa_19",
      "noa_20",
      "noa_21",
      "noa_22",
      "noa_23",
      "noa_24",
      "noa_25",
      "noa_26",
      "noa_27",
      "noa_28",
      "noa_29",
      "noa_30",
      "noa_31",
      "noa_32",
      "noa_33",
      "noa_34",
      "noa_35",
      "noa_36",
      "noa_37",
      "noa_38",
      "noa_39",
      "noa_40",
      "noa_41",
      "noa_42",
      "noa_43",
      "noa_44",
      "noa_45",
      "noa_46",
      "noa_47",
      "noa_48",
      "noa_49",
      "noa_50",
      "noa_51",
      "noa_52",
      "noa_53",
      "noa_54",
      "noa_55",
      "noa_56",
      "noa_57",
      "noa_58",
      "noa_59",
      "noa_60",
      "noa_61",
      "noa_62",
      "noa_63",
      "noa_64",
      "noa_65",
      "noa_66",
      "noa_67",
      "noa_68",
      "noa_69",
      "noa_70",
      "noa_71",
      "noa_72",
      "noa_73",
      "noa_74",
      "noa_75",
      "noa_76",
      "noa_77",
      "noa_78",
      "noa_79",
      "noa_80",
      "noa_81",
      "noa_82",
      "noa_83",
      "noa_84",
      "noa_85",
      "noa_86",
      "noa_87",
      "noa_88",
      "noa_89",
      "noa_90",
      "noa_91",
      "noa_92",
      "noa_93",
      "noa_94",
      "noa_95",
      "noa_96",
      "noa_97",
      "noa_98",
      "noa_99"
    ]
  },
  "layout": {
    "layoutMode": "flow-span",
    "browserGridCols": 4,
    "mobileGridCols": 2,
    "sepFontSize": 22,
    "cellAspectRatio": "1 / 1"
  },
  "focusBadge": {
    "label": "Try to Focus",
    "icon": "✨"
  },
  "rewardBar": {
    "progressLabel": "Progress",
    "unitsDoneLabel": "Units Done",
    "totalStarsLabel": "Total Stars",
    "thisUnitLabel": "This Unit"
  },
  "stepperUi": {
    "stepPrefix": "Step",
    "progressLabel": "Progress"
  },
  "match": {
    "lives": 5,
    "maxGames": 3,
    "completeWhenMaxGamesUsed": true,
    "correctDwellMs": 900,
    "wrongDwellMs": 900,
    "autoAdvanceMs": 0,
    "shuffle": true,
    "reshuffleEvery": 3,
    "maxWrongPerLetter": 3,
    "autoPlayPrompt": true,
    "failEndsStep": false,
    "soundFeedback": true,
    "soundVolume": 0.35,
    "showCorrectTargetOnWrong": true,
    "showStatusText": true,
    "showPopups": true,
    "popupDwellMs": 1400,
    "minCorrectToPass": 0.6,
    "messages": {
      "outOfLives": "You used all your lives. Let us try again.",
      "restarting": "Starting again...",
      "completed": "Great job! Match complete."
    },
    "audioMessages": {
      "outOfLives": "",
      "completed": ""
    }
  },
  "playback": {
    "letterAudioMode": "both",
    "letterAudioSequenceGapMs": 120,
    "steps": {
      "listen": {
        "letterAudioMode": "both",
        "beforeStartMs": 500,
        "betweenLettersMs": 900,
        "afterCompleteMs": 500
      },
      "watch": {
        "letterAudioMode": "both",
        "beforeStartMs": 500,
        "betweenLettersMs": 900,
        "afterCompleteMs": 500
      },
      "repeat": {
        "letterAudioMode": "both",
        "beforeStartMs": 500,
        "betweenLettersMs": 900,
        "afterCompleteMs": 500
      },
      "animate": {
        "letterAudioMode": "both",
        "beforeStartMs": 500,
        "betweenLettersMs": 700,
        "afterCompleteMs": 500
      },
      "write": {
        "letterAudioMode": "both"
      },
      "submit": {
        "recordingUpload": {
          "enabled": true,
          "required": true,
          "wsFunction": "local_prequran_save_submit_recording",
          "maxBytes": 6000000
        }
      }
    }
  },
  "messages": {
    "base": "/pre_quraan/messages/unit_steps/names-of-allah/",
    "manifest": "./unit.messages.js",
    "version": "names-of-allah-messages-v0.1.0",
    "entry": {},
    "entryPasses": {},
    "completion": {}
  },
  "media": {
    "lectureUrl": "/pre_quraan/messages/lectures/names-of-allah_lecture.mp4",
    "voiceBases": {
      "child_boy": "/pre_quraan/lessons/names-of-allah/media/audio/male/",
      "child_girl": "/pre_quraan/lessons/names-of-allah/media/audio/male/",
      "adult_male": "/pre_quraan/lessons/names-of-allah/media/audio/male/",
      "adult_female": "/pre_quraan/lessons/names-of-allah/media/audio/male/"
    },
    "adultMaleAlphaBase": "/pre_quraan/lessons/names-of-allah/media/audio/male/",
    "l6Base": "/pre_quraan/lessons/names-of-allah/media/audio/male/",
    "audioBase": "/pre_quraan/lessons/names-of-allah/media/audio/male/",
    "fallbackAudioBase": "/pre_quraan/lessons/names-of-allah/media/audio/male/",
    "fallbackWatchBase": "/pre_quraan/lessons/names-of-allah/media/video/",
    "watchBase": "/pre_quraan/lessons/names-of-allah/media/video/",
    "animateBase": "/pre_quraan/lessons/names-of-allah/media/video/"
  },
  "write": {
    "chunkSize": 32,
    "chunks": [
      32,
      32,
      32,
      29
    ],
    "rows": 8,
    "cols": 4,
    "wideWords": [],
    "spanWords": {},
    "minPassesRequired": 125,
    "adapter": {
      "unitKey": "names_of_allah",
      "buttonId": "btnTrace",
      "displayLabel": "Write"
    },
    "canvas": {
      "width": 800,
      "height": 320,
      "borderColor": "#e7dbc1",
      "borderRadius": "10px",
      "inkColor": "#0d223a",
      "inkWidth": 8,
      "guide": {
        "top": 110,
        "mid": 150,
        "base": 205,
        "bottom": 260,
        "sidePadding": 24,
        "topColor": "#e8e2cf",
        "midColor": "#e0d6bc",
        "baseColor": "#d5c8a2",
        "bottomColor": "#e8e2cf",
        "midDash": [
          14,
          10
        ]
      },
      "ghostText": {
        "color": "#10223a",
        "alpha": 0.18,
        "normalFontPx": 74,
        "wideFontPx": 50
      }
    }
  },
  "listenPlus": {
    "enabled": false,
    "imageBase": "/pre_quraan/lessons/names-of-allah/media/listen_plus/animals/images/",
    "audioBase": "/pre_quraan/lessons/names-of-allah/media/listen_plus/animals/audio/",
    "imageExt": ".png",
    "audioExt": ".mp3",
    "title": "Listen+",
    "subtitle": "Arabic sound + animal sound",
    "map": {}
  },
  "words": {
    "enabled": false,
    "imageBase": "/pre_quraan/lessons/names-of-allah/media/words/images/",
    "audioBase": "/pre_quraan/lessons/names-of-allah/media/words/audio/",
    "imageExt": ".png",
    "audioExt": ".mp3",
    "title": "Words",
    "subtitle": "Arabic letter + Arabic word",
    "map": {}
  },
  "writeLabelMap": [
    {
      "from": "Trace1",
      "to": "Write"
    },
    {
      "from": "Trace 1",
      "to": "Write"
    },
    {
      "from": "Trace",
      "to": "Write"
    }
  ],
  "activeTileEffect": {
    "enabled": true,
    "mode": "bounceGlow",
    "durationMs": 900,
    "glow": true,
    "bounce": true,
    "dimOthers": false
  },
  "activeAudioAnimation": {
    "enabled": true,
    "type": "magic-ring-pop",
    "speedMs": 850,
    "scale": 1.14,
    "ringColor": "#ffb300"
  },
  "ui": {
    "pageTitle": "PQ Unit - Names of Allah Unit",
    "headerTitle": "Names of Allah Unit",
    "headerArabicTitle": "????? ???? ??????",
    "aboutLabel": "About Names of Allah"
  },
  "defaults": {
    "voice": "child_boy",
    "speed": "1.0",
    "repeat": "1",
    "filter": "all"
  },
  "wordLimit": 99,
  "content": {
    "items": [
      {
        "key": "noa_01",
        "text": "الرَّحْمَنُ",
        "ar": "الرَّحْمَنُ",
        "small": "AR-RAHMAAN",
        "en": "The Beneficent",
        "transliteration": "AR-RAHMAAN",
        "meaning": "The Beneficent",
        "row": 1,
        "displayCol": 4,
        "audio": "noa_01.mp3",
        "video": "noa_01.mp4"
      },
      {
        "key": "noa_02",
        "text": "الرَّحِيمُ",
        "ar": "الرَّحِيمُ",
        "small": "AR-RAHEEM",
        "en": "The Merciful",
        "transliteration": "AR-RAHEEM",
        "meaning": "The Merciful",
        "row": 1,
        "displayCol": 3,
        "audio": "noa_02.mp3",
        "video": "noa_02.mp4"
      },
      {
        "key": "noa_03",
        "text": "الْمَلِكُ",
        "ar": "الْمَلِكُ",
        "small": "AL-MALIK",
        "en": "The King",
        "transliteration": "AL-MALIK",
        "meaning": "The King",
        "row": 1,
        "displayCol": 2,
        "audio": "noa_03.mp3",
        "video": "noa_03.mp4"
      },
      {
        "key": "noa_04",
        "text": "الْقُدُّوسُ",
        "ar": "الْقُدُّوسُ",
        "small": "AL-QUDDUS",
        "en": "The Most Sacred",
        "transliteration": "AL-QUDDUS",
        "meaning": "The Most Sacred",
        "row": 1,
        "displayCol": 1,
        "audio": "noa_04.mp3",
        "video": "noa_04.mp4"
      },
      {
        "key": "noa_05",
        "text": "السَّلاَمُ",
        "ar": "السَّلاَمُ",
        "small": "AS-SALAM",
        "en": "The Source of Peace, The Flawless",
        "transliteration": "AS-SALAM",
        "meaning": "The Source of Peace, The Flawless",
        "row": 2,
        "displayCol": 4,
        "audio": "noa_05.mp3",
        "video": "noa_05.mp4"
      },
      {
        "key": "noa_06",
        "text": "الْمُؤْمِنُ",
        "ar": "الْمُؤْمِنُ",
        "small": "AL-MU’MIN",
        "en": "The Infuser of Faith",
        "transliteration": "AL-MU’MIN",
        "meaning": "The Infuser of Faith",
        "row": 2,
        "displayCol": 3,
        "audio": "noa_06.mp3",
        "video": "noa_06.mp4"
      },
      {
        "key": "noa_07",
        "text": "الْمُهَيْمِنُ",
        "ar": "الْمُهَيْمِنُ",
        "small": "AL-MUHAYMIN",
        "en": "The Preserver of Safety",
        "transliteration": "AL-MUHAYMIN",
        "meaning": "The Preserver of Safety",
        "row": 2,
        "displayCol": 2,
        "audio": "noa_07.mp3",
        "video": "noa_07.mp4"
      },
      {
        "key": "noa_08",
        "text": "الْعَزِيزُ",
        "ar": "الْعَزِيزُ",
        "small": "AL-AZIZ",
        "en": "All Mighty",
        "transliteration": "AL-AZIZ",
        "meaning": "All Mighty",
        "row": 2,
        "displayCol": 1,
        "audio": "noa_08.mp3",
        "video": "noa_08.mp4"
      },
      {
        "key": "noa_09",
        "text": "الْجَبَّارُ",
        "ar": "الْجَبَّارُ",
        "small": "AL-JABBAR",
        "en": "The Compeller, The Restorer",
        "transliteration": "AL-JABBAR",
        "meaning": "The Compeller, The Restorer",
        "row": 3,
        "displayCol": 4,
        "audio": "noa_09.mp3",
        "video": "noa_09.mp4"
      },
      {
        "key": "noa_10",
        "text": "ُالْمُتَكَبِّر",
        "ar": "ُالْمُتَكَبِّر",
        "small": "AL-MUTAKABBIR",
        "en": "The Supreme, The Majestic",
        "transliteration": "AL-MUTAKABBIR",
        "meaning": "The Supreme, The Majestic",
        "row": 3,
        "displayCol": 3,
        "audio": "noa_10.mp3",
        "video": "noa_10.mp4"
      },
      {
        "key": "noa_11",
        "text": "الْخَالِقُ",
        "ar": "الْخَالِقُ",
        "small": "AL-KHAALIQ",
        "en": "The Creator, The Maker",
        "transliteration": "AL-KHAALIQ",
        "meaning": "The Creator, The Maker",
        "row": 3,
        "displayCol": 2,
        "audio": "noa_11.mp3",
        "video": "noa_11.mp4"
      },
      {
        "key": "noa_12",
        "text": "الْبَارِئُ",
        "ar": "الْبَارِئُ",
        "small": "AL-BAARI",
        "en": "The Evolver",
        "transliteration": "AL-BAARI",
        "meaning": "The Evolver",
        "row": 3,
        "displayCol": 1,
        "audio": "noa_12.mp3",
        "video": "noa_12.mp4"
      },
      {
        "key": "noa_13",
        "text": "الْمُصَوِّرُ",
        "ar": "الْمُصَوِّرُ",
        "small": "AL-MUSAWWIR",
        "en": "The Fashioner",
        "transliteration": "AL-MUSAWWIR",
        "meaning": "The Fashioner",
        "row": 4,
        "displayCol": 4,
        "audio": "noa_13.mp3",
        "video": "noa_13.mp4"
      },
      {
        "key": "noa_14",
        "text": "الْغَفَّارُ",
        "ar": "الْغَفَّارُ",
        "small": "AL-GHAFFAR",
        "en": "The Constant Forgiver",
        "transliteration": "AL-GHAFFAR",
        "meaning": "The Constant Forgiver",
        "row": 4,
        "displayCol": 3,
        "audio": "noa_14.mp3",
        "video": "noa_14.mp4"
      },
      {
        "key": "noa_15",
        "text": "الْقَهَّارُ",
        "ar": "الْقَهَّارُ",
        "small": "AL-QAHHAR",
        "en": "The All-Prevailing One",
        "transliteration": "AL-QAHHAR",
        "meaning": "The All-Prevailing One",
        "row": 4,
        "displayCol": 2,
        "audio": "noa_15.mp3",
        "video": "noa_15.mp4"
      },
      {
        "key": "noa_16",
        "text": "الْوَهَّابُ",
        "ar": "الْوَهَّابُ",
        "small": "AL-WAHHAAB",
        "en": "The Supreme Bestower",
        "transliteration": "AL-WAHHAAB",
        "meaning": "The Supreme Bestower",
        "row": 4,
        "displayCol": 1,
        "audio": "noa_16.mp3",
        "video": "noa_16.mp4"
      },
      {
        "key": "noa_17",
        "text": "الرَّزَّاقُ",
        "ar": "الرَّزَّاقُ",
        "small": "AR-RAZZAAQ",
        "en": "The Provider",
        "transliteration": "AR-RAZZAAQ",
        "meaning": "The Provider",
        "row": 5,
        "displayCol": 4,
        "audio": "noa_17.mp3",
        "video": "noa_17.mp4"
      },
      {
        "key": "noa_18",
        "text": "الْفَتَّاحُ",
        "ar": "الْفَتَّاحُ",
        "small": "AL-FATTAAH",
        "en": "The Supreme Solver",
        "transliteration": "AL-FATTAAH",
        "meaning": "The Supreme Solver",
        "row": 5,
        "displayCol": 3,
        "audio": "noa_18.mp3",
        "video": "noa_18.mp4"
      },
      {
        "key": "noa_19",
        "text": "اَلْعَلِيْمُ",
        "ar": "اَلْعَلِيْمُ",
        "small": "AL-‘ALEEM",
        "en": "The All-Knowing",
        "transliteration": "AL-‘ALEEM",
        "meaning": "The All-Knowing",
        "row": 5,
        "displayCol": 2,
        "audio": "noa_19.mp3",
        "video": "noa_19.mp4"
      },
      {
        "key": "noa_20",
        "text": "الْقَابِضُ",
        "ar": "الْقَابِضُ",
        "small": "AL-QAABID",
        "en": "The Withholder",
        "transliteration": "AL-QAABID",
        "meaning": "The Withholder",
        "row": 5,
        "displayCol": 1,
        "audio": "noa_20.mp3",
        "video": "noa_20.mp4"
      },
      {
        "key": "noa_21",
        "text": "الْبَاسِطُ",
        "ar": "الْبَاسِطُ",
        "small": "AL-BAASIT",
        "en": "The Extender",
        "transliteration": "AL-BAASIT",
        "meaning": "The Extender",
        "row": 6,
        "displayCol": 4,
        "audio": "noa_21.mp3",
        "video": "noa_21.mp4"
      },
      {
        "key": "noa_22",
        "text": "الْخَافِضُ",
        "ar": "الْخَافِضُ",
        "small": "AL-KHAAFIDH",
        "en": "The Reducer",
        "transliteration": "AL-KHAAFIDH",
        "meaning": "The Reducer",
        "row": 6,
        "displayCol": 3,
        "audio": "noa_22.mp3",
        "video": "noa_22.mp4"
      },
      {
        "key": "noa_23",
        "text": "الرَّافِعُ",
        "ar": "الرَّافِعُ",
        "small": "AR-RAAFI’",
        "en": "The Exalter, The Elevator",
        "transliteration": "AR-RAAFI’",
        "meaning": "The Exalter, The Elevator",
        "row": 6,
        "displayCol": 2,
        "audio": "noa_23.mp3",
        "video": "noa_23.mp4"
      },
      {
        "key": "noa_24",
        "text": "الْمُعِزُّ",
        "ar": "الْمُعِزُّ",
        "small": "AL-MU’IZZ",
        "en": "The Honourer, The Bestower",
        "transliteration": "AL-MU’IZZ",
        "meaning": "The Honourer, The Bestower",
        "row": 6,
        "displayCol": 1,
        "audio": "noa_24.mp3",
        "video": "noa_24.mp4"
      },
      {
        "key": "noa_25",
        "text": "ٱلْمُذِلُّ",
        "ar": "ٱلْمُذِلُّ",
        "small": "AL-MUZIL",
        "en": "The Dishonourer",
        "transliteration": "AL-MUZIL",
        "meaning": "The Dishonourer",
        "row": 7,
        "displayCol": 4,
        "audio": "noa_25.mp3",
        "video": "noa_25.mp4"
      },
      {
        "key": "noa_26",
        "text": "السَّمِيعُ",
        "ar": "السَّمِيعُ",
        "small": "AS-SAMEE’",
        "en": "The All-Hearing",
        "transliteration": "AS-SAMEE’",
        "meaning": "The All-Hearing",
        "row": 7,
        "displayCol": 3,
        "audio": "noa_26.mp3",
        "video": "noa_26.mp4"
      },
      {
        "key": "noa_27",
        "text": "الْبَصِيرُ",
        "ar": "الْبَصِيرُ",
        "small": "AL-BASEER",
        "en": "The All-Seeing",
        "transliteration": "AL-BASEER",
        "meaning": "The All-Seeing",
        "row": 7,
        "displayCol": 2,
        "audio": "noa_27.mp3",
        "video": "noa_27.mp4"
      },
      {
        "key": "noa_28",
        "text": "الْحَكَمُ",
        "ar": "الْحَكَمُ",
        "small": "AL-HAKAM",
        "en": "The Impartial Judge",
        "transliteration": "AL-HAKAM",
        "meaning": "The Impartial Judge",
        "row": 7,
        "displayCol": 1,
        "audio": "noa_28.mp3",
        "video": "noa_28.mp4"
      },
      {
        "key": "noa_29",
        "text": "الْعَدْلُ",
        "ar": "الْعَدْلُ",
        "small": "AL-‘ADL",
        "en": "The Utterly Just",
        "transliteration": "AL-‘ADL",
        "meaning": "The Utterly Just",
        "row": 8,
        "displayCol": 4,
        "audio": "noa_29.mp3",
        "video": "noa_29.mp4"
      },
      {
        "key": "noa_30",
        "text": "اللَّطِيفُ",
        "ar": "اللَّطِيفُ",
        "small": "AL-LATEEF",
        "en": "The Subtle One, The Most Gentle",
        "transliteration": "AL-LATEEF",
        "meaning": "The Subtle One, The Most Gentle",
        "row": 8,
        "displayCol": 3,
        "audio": "noa_30.mp3",
        "video": "noa_30.mp4"
      },
      {
        "key": "noa_31",
        "text": "الْخَبِيرُ",
        "ar": "الْخَبِيرُ",
        "small": "AL-KHABEER",
        "en": "The All-Aware",
        "transliteration": "AL-KHABEER",
        "meaning": "The All-Aware",
        "row": 8,
        "displayCol": 2,
        "audio": "noa_31.mp3",
        "video": "noa_31.mp4"
      },
      {
        "key": "noa_32",
        "text": "الْحَلِيمُ",
        "ar": "الْحَلِيمُ",
        "small": "AL-HALEEM",
        "en": "The Most Forbearing",
        "transliteration": "AL-HALEEM",
        "meaning": "The Most Forbearing",
        "row": 8,
        "displayCol": 1,
        "audio": "noa_32.mp3",
        "video": "noa_32.mp4"
      },
      {
        "key": "noa_33",
        "text": "الْعَظِيمُ",
        "ar": "الْعَظِيمُ",
        "small": "AL-‘AZEEM",
        "en": "The Magnificent, The Supreme",
        "transliteration": "AL-‘AZEEM",
        "meaning": "The Magnificent, The Supreme",
        "row": 9,
        "displayCol": 4,
        "audio": "noa_33.mp3",
        "video": "noa_33.mp4"
      },
      {
        "key": "noa_34",
        "text": "الْغَفُور",
        "ar": "الْغَفُور",
        "small": "AL-GHAFOOR",
        "en": "The Great Forgiver",
        "transliteration": "AL-GHAFOOR",
        "meaning": "The Great Forgiver",
        "row": 9,
        "displayCol": 3,
        "audio": "noa_34.mp3",
        "video": "noa_34.mp4"
      },
      {
        "key": "noa_35",
        "text": "الشَّكُورُ",
        "ar": "الشَّكُورُ",
        "small": "ASH-SHAKOOR",
        "en": "The Most Appreciative",
        "transliteration": "ASH-SHAKOOR",
        "meaning": "The Most Appreciative",
        "row": 9,
        "displayCol": 2,
        "audio": "noa_35.mp3",
        "video": "noa_35.mp4"
      },
      {
        "key": "noa_36",
        "text": "الْعَلِيُّ",
        "ar": "الْعَلِيُّ",
        "small": "AL-‘ALEE",
        "en": "The Most High, The Exalted",
        "transliteration": "AL-‘ALEE",
        "meaning": "The Most High, The Exalted",
        "row": 9,
        "displayCol": 1,
        "audio": "noa_36.mp3",
        "video": "noa_36.mp4"
      },
      {
        "key": "noa_37",
        "text": "الْكَبِيرُ",
        "ar": "الْكَبِيرُ",
        "small": "AL-KABEER",
        "en": "The Most Great",
        "transliteration": "AL-KABEER",
        "meaning": "The Most Great",
        "row": 10,
        "displayCol": 4,
        "audio": "noa_37.mp3",
        "video": "noa_37.mp4"
      },
      {
        "key": "noa_38",
        "text": "الْحَفِيظُ",
        "ar": "الْحَفِيظُ",
        "small": "AL-HAFEEDH",
        "en": "The Preserver",
        "transliteration": "AL-HAFEEDH",
        "meaning": "The Preserver",
        "row": 10,
        "displayCol": 3,
        "audio": "noa_38.mp3",
        "video": "noa_38.mp4"
      },
      {
        "key": "noa_39",
        "text": "المُقيِت",
        "ar": "المُقيِت",
        "small": "AL-MUQEET",
        "en": "The Sustainer",
        "transliteration": "AL-MUQEET",
        "meaning": "The Sustainer",
        "row": 10,
        "displayCol": 2,
        "audio": "noa_39.mp3",
        "video": "noa_39.mp4"
      },
      {
        "key": "noa_40",
        "text": "اﻟْﺣَسِيبُ",
        "ar": "اﻟْﺣَسِيبُ",
        "small": "AL-HASEEB",
        "en": "The Reckoner",
        "transliteration": "AL-HASEEB",
        "meaning": "The Reckoner",
        "row": 10,
        "displayCol": 1,
        "audio": "noa_40.mp3",
        "video": "noa_40.mp4"
      },
      {
        "key": "noa_41",
        "text": "الْجَلِيلُ",
        "ar": "الْجَلِيلُ",
        "small": "AL-JALEEL",
        "en": "The Majestic",
        "transliteration": "AL-JALEEL",
        "meaning": "The Majestic",
        "row": 11,
        "displayCol": 4,
        "audio": "noa_41.mp3",
        "video": "noa_41.mp4"
      },
      {
        "key": "noa_42",
        "text": "الْكَرِيمُ",
        "ar": "الْكَرِيمُ",
        "small": "AL-KAREEM",
        "en": "The Most Generous, The Most Esteemed",
        "transliteration": "AL-KAREEM",
        "meaning": "The Most Generous, The Most Esteemed",
        "row": 11,
        "displayCol": 3,
        "audio": "noa_42.mp3",
        "video": "noa_42.mp4"
      },
      {
        "key": "noa_43",
        "text": "الرَّقِيبُ",
        "ar": "الرَّقِيبُ",
        "small": "AR-RAQEEB",
        "en": "The Watchful",
        "transliteration": "AR-RAQEEB",
        "meaning": "The Watchful",
        "row": 11,
        "displayCol": 2,
        "audio": "noa_43.mp3",
        "video": "noa_43.mp4"
      },
      {
        "key": "noa_44",
        "text": "ٱلْمُجِيبُ",
        "ar": "ٱلْمُجِيبُ",
        "small": "AL-MUJEEB",
        "en": "The Responsive One",
        "transliteration": "AL-MUJEEB",
        "meaning": "The Responsive One",
        "row": 11,
        "displayCol": 1,
        "audio": "noa_44.mp3",
        "video": "noa_44.mp4"
      },
      {
        "key": "noa_45",
        "text": "الْوَاسِعُ",
        "ar": "الْوَاسِعُ",
        "small": "AL-WAASI’",
        "en": "The All-Encompassing, the Boundless",
        "transliteration": "AL-WAASI’",
        "meaning": "The All-Encompassing, the Boundless",
        "row": 12,
        "displayCol": 4,
        "audio": "noa_45.mp3",
        "video": "noa_45.mp4"
      },
      {
        "key": "noa_46",
        "text": "الْحَكِيمُ",
        "ar": "الْحَكِيمُ",
        "small": "AL-HAKEEM",
        "en": "The All-Wise",
        "transliteration": "AL-HAKEEM",
        "meaning": "The All-Wise",
        "row": 12,
        "displayCol": 3,
        "audio": "noa_46.mp3",
        "video": "noa_46.mp4"
      },
      {
        "key": "noa_47",
        "text": "الْوَدُودُ",
        "ar": "الْوَدُودُ",
        "small": "AL-WADUD",
        "en": "The Most Loving",
        "transliteration": "AL-WADUD",
        "meaning": "The Most Loving",
        "row": 12,
        "displayCol": 2,
        "audio": "noa_47.mp3",
        "video": "noa_47.mp4"
      },
      {
        "key": "noa_48",
        "text": "الْمَجِيدُ",
        "ar": "الْمَجِيدُ",
        "small": "AL-MAJEED",
        "en": "The Glorious, The Most Honorable",
        "transliteration": "AL-MAJEED",
        "meaning": "The Glorious, The Most Honorable",
        "row": 12,
        "displayCol": 1,
        "audio": "noa_48.mp3",
        "video": "noa_48.mp4"
      },
      {
        "key": "noa_49",
        "text": "الْبَاعِثُ",
        "ar": "الْبَاعِثُ",
        "small": "AL-BA’ITH",
        "en": "The Infuser of New Life",
        "transliteration": "AL-BA’ITH",
        "meaning": "The Infuser of New Life",
        "row": 13,
        "displayCol": 4,
        "audio": "noa_49.mp3",
        "video": "noa_49.mp4"
      },
      {
        "key": "noa_50",
        "text": "الشَّهِيدُ",
        "ar": "الشَّهِيدُ",
        "small": "ASH-SHAHEED",
        "en": "The All Observing Witnessing",
        "transliteration": "ASH-SHAHEED",
        "meaning": "The All Observing Witnessing",
        "row": 13,
        "displayCol": 3,
        "audio": "noa_50.mp3",
        "video": "noa_50.mp4"
      },
      {
        "key": "noa_51",
        "text": "الْحَقُ",
        "ar": "الْحَقُ",
        "small": "AL-HAQQ",
        "en": "The Absolute Truth",
        "transliteration": "AL-HAQQ",
        "meaning": "The Absolute Truth",
        "row": 13,
        "displayCol": 2,
        "audio": "noa_51.mp3",
        "video": "noa_51.mp4"
      },
      {
        "key": "noa_52",
        "text": "الْوَكِيلُ",
        "ar": "الْوَكِيلُ",
        "small": "AL-WAKEEL",
        "en": "The Trustee, The Disposer of Affairs",
        "transliteration": "AL-WAKEEL",
        "meaning": "The Trustee, The Disposer of Affairs",
        "row": 13,
        "displayCol": 1,
        "audio": "noa_52.mp3",
        "video": "noa_52.mp4"
      },
      {
        "key": "noa_53",
        "text": "الْقَوِيُ",
        "ar": "الْقَوِيُ",
        "small": "AL-QAWIYY",
        "en": "The All-Strong",
        "transliteration": "AL-QAWIYY",
        "meaning": "The All-Strong",
        "row": 14,
        "displayCol": 4,
        "audio": "noa_53.mp3",
        "video": "noa_53.mp4"
      },
      {
        "key": "noa_54",
        "text": "الْمَتِينُ",
        "ar": "الْمَتِينُ",
        "small": "AL-MATEEN",
        "en": "The Firm, The Steadfast",
        "transliteration": "AL-MATEEN",
        "meaning": "The Firm, The Steadfast",
        "row": 14,
        "displayCol": 3,
        "audio": "noa_54.mp3",
        "video": "noa_54.mp4"
      },
      {
        "key": "noa_55",
        "text": "الْوَلِيُّ",
        "ar": "الْوَلِيُّ",
        "small": "AL-WALIYY",
        "en": "The Protecting Associate",
        "transliteration": "AL-WALIYY",
        "meaning": "The Protecting Associate",
        "row": 14,
        "displayCol": 2,
        "audio": "noa_55.mp3",
        "video": "noa_55.mp4"
      },
      {
        "key": "noa_56",
        "text": "الْحَمِيدُ",
        "ar": "الْحَمِيدُ",
        "small": "AL-HAMEED",
        "en": "The Praiseworthy",
        "transliteration": "AL-HAMEED",
        "meaning": "The Praiseworthy",
        "row": 14,
        "displayCol": 1,
        "audio": "noa_56.mp3",
        "video": "noa_56.mp4"
      },
      {
        "key": "noa_57",
        "text": "الْمُحْصِي",
        "ar": "الْمُحْصِي",
        "small": "AL-MUHSEE",
        "en": "The All-Enumerating, The Counter",
        "transliteration": "AL-MUHSEE",
        "meaning": "The All-Enumerating, The Counter",
        "row": 15,
        "displayCol": 4,
        "audio": "noa_57.mp3",
        "video": "noa_57.mp4"
      },
      {
        "key": "noa_58",
        "text": "الْمُبْدِئُ",
        "ar": "الْمُبْدِئُ",
        "small": "AL-MUBDI",
        "en": "The Originator, The Initiator",
        "transliteration": "AL-MUBDI",
        "meaning": "The Originator, The Initiator",
        "row": 15,
        "displayCol": 3,
        "audio": "noa_58.mp3",
        "video": "noa_58.mp4"
      },
      {
        "key": "noa_59",
        "text": "ٱلْمُعِيدُ",
        "ar": "ٱلْمُعِيدُ",
        "small": "AL-MUEED",
        "en": "The Restorer, The Reinstater",
        "transliteration": "AL-MUEED",
        "meaning": "The Restorer, The Reinstater",
        "row": 15,
        "displayCol": 2,
        "audio": "noa_59.mp3",
        "video": "noa_59.mp4"
      },
      {
        "key": "noa_60",
        "text": "الْمُحْيِي",
        "ar": "الْمُحْيِي",
        "small": "AL-MUHYI",
        "en": "The Giver of Life",
        "transliteration": "AL-MUHYI",
        "meaning": "The Giver of Life",
        "row": 15,
        "displayCol": 1,
        "audio": "noa_60.mp3",
        "video": "noa_60.mp4"
      },
      {
        "key": "noa_61",
        "text": "اَلْمُمِيتُ",
        "ar": "اَلْمُمِيتُ",
        "small": "AL-MUMEET",
        "en": "The Creator of Death",
        "transliteration": "AL-MUMEET",
        "meaning": "The Creator of Death",
        "row": 16,
        "displayCol": 4,
        "audio": "noa_61.mp3",
        "video": "noa_61.mp4"
      },
      {
        "key": "noa_62",
        "text": "الْحَيُّ",
        "ar": "الْحَيُّ",
        "small": "AL-HAYY",
        "en": "The Ever-Living",
        "transliteration": "AL-HAYY",
        "meaning": "The Ever-Living",
        "row": 16,
        "displayCol": 3,
        "audio": "noa_62.mp3",
        "video": "noa_62.mp4"
      },
      {
        "key": "noa_63",
        "text": "الْقَيُّومُ",
        "ar": "الْقَيُّومُ",
        "small": "AL-QAYYOOM",
        "en": "The Sustainer, The Self-Subsisting",
        "transliteration": "AL-QAYYOOM",
        "meaning": "The Sustainer, The Self-Subsisting",
        "row": 16,
        "displayCol": 2,
        "audio": "noa_63.mp3",
        "video": "noa_63.mp4"
      },
      {
        "key": "noa_64",
        "text": "الْوَاجِدُ",
        "ar": "الْوَاجِدُ",
        "small": "AL-WAAJID",
        "en": "The Perceiver",
        "transliteration": "AL-WAAJID",
        "meaning": "The Perceiver",
        "row": 16,
        "displayCol": 1,
        "audio": "noa_64.mp3",
        "video": "noa_64.mp4"
      },
      {
        "key": "noa_65",
        "text": "الْمَاجِدُ",
        "ar": "الْمَاجِدُ",
        "small": "AL-MAAJID",
        "en": "The Illustrious, the Magnificent",
        "transliteration": "AL-MAAJID",
        "meaning": "The Illustrious, the Magnificent",
        "row": 17,
        "displayCol": 4,
        "audio": "noa_65.mp3",
        "video": "noa_65.mp4"
      },
      {
        "key": "noa_66",
        "text": "الْواحِدُ",
        "ar": "الْواحِدُ",
        "small": "AL-WAAHID",
        "en": "The One",
        "transliteration": "AL-WAAHID",
        "meaning": "The One",
        "row": 17,
        "displayCol": 3,
        "audio": "noa_66.mp3",
        "video": "noa_66.mp4"
      },
      {
        "key": "noa_67",
        "text": "اَلاَحَدُ",
        "ar": "اَلاَحَدُ",
        "small": "AL-AHAD",
        "en": "The Unique, The Only One",
        "transliteration": "AL-AHAD",
        "meaning": "The Unique, The Only One",
        "row": 17,
        "displayCol": 2,
        "audio": "noa_67.mp3",
        "video": "noa_67.mp4"
      },
      {
        "key": "noa_68",
        "text": "الصَّمَدُ",
        "ar": "الصَّمَدُ",
        "small": "AS-SAMAD",
        "en": "The Eternal, Satisfier of Needs",
        "transliteration": "AS-SAMAD",
        "meaning": "The Eternal, Satisfier of Needs",
        "row": 17,
        "displayCol": 1,
        "audio": "noa_68.mp3",
        "video": "noa_68.mp4"
      },
      {
        "key": "noa_69",
        "text": "الْقَادِرُ",
        "ar": "الْقَادِرُ",
        "small": "AL-QADEER",
        "en": "The Omnipotent One",
        "transliteration": "AL-QADEER",
        "meaning": "The Omnipotent One",
        "row": 18,
        "displayCol": 4,
        "audio": "noa_69.mp3",
        "video": "noa_69.mp4"
      },
      {
        "key": "noa_70",
        "text": "الْمُقْتَدِرُ",
        "ar": "الْمُقْتَدِرُ",
        "small": "AL-MUQTADIR",
        "en": "The Powerful",
        "transliteration": "AL-MUQTADIR",
        "meaning": "The Powerful",
        "row": 18,
        "displayCol": 3,
        "audio": "noa_70.mp3",
        "video": "noa_70.mp4"
      },
      {
        "key": "noa_71",
        "text": "الْمُقَدِّمُ",
        "ar": "الْمُقَدِّمُ",
        "small": "AL-MUQADDIM",
        "en": "The Expediter, The Promoter",
        "transliteration": "AL-MUQADDIM",
        "meaning": "The Expediter, The Promoter",
        "row": 18,
        "displayCol": 2,
        "audio": "noa_71.mp3",
        "video": "noa_71.mp4"
      },
      {
        "key": "noa_72",
        "text": "الْمُؤَخِّرُ",
        "ar": "الْمُؤَخِّرُ",
        "small": "AL-MU’AKHKHIR",
        "en": "The Delayer",
        "transliteration": "AL-MU’AKHKHIR",
        "meaning": "The Delayer",
        "row": 18,
        "displayCol": 1,
        "audio": "noa_72.mp3",
        "video": "noa_72.mp4"
      },
      {
        "key": "noa_73",
        "text": "الأوَّلُ",
        "ar": "الأوَّلُ",
        "small": "AL-AWWAL",
        "en": "The First",
        "transliteration": "AL-AWWAL",
        "meaning": "The First",
        "row": 19,
        "displayCol": 4,
        "audio": "noa_73.mp3",
        "video": "noa_73.mp4"
      },
      {
        "key": "noa_74",
        "text": "الآخِرُ",
        "ar": "الآخِرُ",
        "small": "AL-AAKHIR",
        "en": "The Last",
        "transliteration": "AL-AAKHIR",
        "meaning": "The Last",
        "row": 19,
        "displayCol": 3,
        "audio": "noa_74.mp3",
        "video": "noa_74.mp4"
      },
      {
        "key": "noa_75",
        "text": "الظَّاهِرُ",
        "ar": "الظَّاهِرُ",
        "small": "AZ-ZAAHIR",
        "en": "The Manifest",
        "transliteration": "AZ-ZAAHIR",
        "meaning": "The Manifest",
        "row": 19,
        "displayCol": 2,
        "audio": "noa_75.mp3",
        "video": "noa_75.mp4"
      },
      {
        "key": "noa_76",
        "text": "الْبَاطِنُ",
        "ar": "الْبَاطِنُ",
        "small": "AL-BAATIN",
        "en": "The Hidden One, Knower of the Hidden",
        "transliteration": "AL-BAATIN",
        "meaning": "The Hidden One, Knower of the Hidden",
        "row": 19,
        "displayCol": 1,
        "audio": "noa_76.mp3",
        "video": "noa_76.mp4"
      },
      {
        "key": "noa_77",
        "text": "الْوَالِي",
        "ar": "الْوَالِي",
        "small": "AL-WAALI",
        "en": "The Sole Governor",
        "transliteration": "AL-WAALI",
        "meaning": "The Sole Governor",
        "row": 20,
        "displayCol": 4,
        "audio": "noa_77.mp3",
        "video": "noa_77.mp4"
      },
      {
        "key": "noa_78",
        "text": "الْمُتَعَالِي",
        "ar": "الْمُتَعَالِي",
        "small": "AL-MUTA’ALI",
        "en": "The Self Exalted",
        "transliteration": "AL-MUTA’ALI",
        "meaning": "The Self Exalted",
        "row": 20,
        "displayCol": 3,
        "audio": "noa_78.mp3",
        "video": "noa_78.mp4"
      },
      {
        "key": "noa_79",
        "text": "الْبَرُّ",
        "ar": "الْبَرُّ",
        "small": "AL-BARR",
        "en": "The Source of All Goodness",
        "transliteration": "AL-BARR",
        "meaning": "The Source of All Goodness",
        "row": 20,
        "displayCol": 2,
        "audio": "noa_79.mp3",
        "video": "noa_79.mp4"
      },
      {
        "key": "noa_80",
        "text": "التَّوَابُ",
        "ar": "التَّوَابُ",
        "small": "AT-TAWWAB",
        "en": "The Ever-Pardoning",
        "transliteration": "AT-TAWWAB",
        "meaning": "The Ever-Pardoning",
        "row": 20,
        "displayCol": 1,
        "audio": "noa_80.mp3",
        "video": "noa_80.mp4"
      },
      {
        "key": "noa_81",
        "text": "الْمُنْتَقِمُ",
        "ar": "الْمُنْتَقِمُ",
        "small": "AL-MUNTAQIM",
        "en": "The Avenger",
        "transliteration": "AL-MUNTAQIM",
        "meaning": "The Avenger",
        "row": 21,
        "displayCol": 4,
        "audio": "noa_81.mp3",
        "video": "noa_81.mp4"
      },
      {
        "key": "noa_82",
        "text": "العَفُوُ",
        "ar": "العَفُوُ",
        "small": "AL-‘AFUWW",
        "en": "The Pardoner",
        "transliteration": "AL-‘AFUWW",
        "meaning": "The Pardoner",
        "row": 21,
        "displayCol": 3,
        "audio": "noa_82.mp3",
        "video": "noa_82.mp4"
      },
      {
        "key": "noa_83",
        "text": "الرَّؤُوفُ",
        "ar": "الرَّؤُوفُ",
        "small": "AR-RA’OOF",
        "en": "The Most Kind",
        "transliteration": "AR-RA’OOF",
        "meaning": "The Most Kind",
        "row": 21,
        "displayCol": 2,
        "audio": "noa_83.mp3",
        "video": "noa_83.mp4"
      },
      {
        "key": "noa_84",
        "text": "مَالِكُ ٱلْمُلْكُ",
        "ar": "مَالِكُ ٱلْمُلْكُ",
        "small": "MAALIK-UL-MULK",
        "en": "Master of the Kingdom, Owner of the Dominion",
        "transliteration": "MAALIK-UL-MULK",
        "meaning": "Master of the Kingdom, Owner of the Dominion",
        "row": 21,
        "displayCol": 1,
        "audio": "noa_84.mp3",
        "video": "noa_84.mp4"
      },
      {
        "key": "noa_85",
        "text": "ذُوالْجَلاَلِ وَالإكْرَامِ",
        "ar": "ذُوالْجَلاَلِ وَالإكْرَامِ",
        "small": "DHUL-JALAALI WAL-IKRAAM",
        "en": "Lord of Glory and Honour, Lord of Majesty and Generosity",
        "transliteration": "DHUL-JALAALI WAL-IKRAAM",
        "meaning": "Lord of Glory and Honour, Lord of Majesty and Generosity",
        "row": 22,
        "displayCol": 4,
        "audio": "noa_85.mp3",
        "video": "noa_85.mp4"
      },
      {
        "key": "noa_86",
        "text": "الْمُقْسِطُ",
        "ar": "الْمُقْسِطُ",
        "small": "AL-MUQSIT",
        "en": "The Just One",
        "transliteration": "AL-MUQSIT",
        "meaning": "The Just One",
        "row": 22,
        "displayCol": 3,
        "audio": "noa_86.mp3",
        "video": "noa_86.mp4"
      },
      {
        "key": "noa_87",
        "text": "الْجَامِعُ",
        "ar": "الْجَامِعُ",
        "small": "AL-JAAMI’",
        "en": "The Gatherer, the Uniter",
        "transliteration": "AL-JAAMI’",
        "meaning": "The Gatherer, the Uniter",
        "row": 22,
        "displayCol": 2,
        "audio": "noa_87.mp3",
        "video": "noa_87.mp4"
      },
      {
        "key": "noa_88",
        "text": "ٱلْغَنيُّ",
        "ar": "ٱلْغَنيُّ",
        "small": "AL-GHANIYY",
        "en": "The Self-Sufficient, The Wealthy",
        "transliteration": "AL-GHANIYY",
        "meaning": "The Self-Sufficient, The Wealthy",
        "row": 22,
        "displayCol": 1,
        "audio": "noa_88.mp3",
        "video": "noa_88.mp4"
      },
      {
        "key": "noa_89",
        "text": "ٱلْمُغْنِيُّ",
        "ar": "ٱلْمُغْنِيُّ",
        "small": "AL-MUGHNI",
        "en": "The Enricher",
        "transliteration": "AL-MUGHNI",
        "meaning": "The Enricher",
        "row": 23,
        "displayCol": 4,
        "audio": "noa_89.mp3",
        "video": "noa_89.mp4"
      },
      {
        "key": "noa_90",
        "text": "اَلْمَانِعُ",
        "ar": "اَلْمَانِعُ",
        "small": "AL-MANI’",
        "en": "The Withholder",
        "transliteration": "AL-MANI’",
        "meaning": "The Withholder",
        "row": 23,
        "displayCol": 3,
        "audio": "noa_90.mp3",
        "video": "noa_90.mp4"
      },
      {
        "key": "noa_91",
        "text": "الضَّارَ",
        "ar": "الضَّارَ",
        "small": "AD-DHARR",
        "en": "The Distresser",
        "transliteration": "AD-DHARR",
        "meaning": "The Distresser",
        "row": 23,
        "displayCol": 2,
        "audio": "noa_91.mp3",
        "video": "noa_91.mp4"
      },
      {
        "key": "noa_92",
        "text": "النَّافِعُ",
        "ar": "النَّافِعُ",
        "small": "AN-NAFI’",
        "en": "The Propitious, The Benefactor",
        "transliteration": "AN-NAFI’",
        "meaning": "The Propitious, The Benefactor",
        "row": 23,
        "displayCol": 1,
        "audio": "noa_92.mp3",
        "video": "noa_92.mp4"
      },
      {
        "key": "noa_93",
        "text": "النُّورُ",
        "ar": "النُّورُ",
        "small": "AN-NUR",
        "en": "The Light, The Illuminator",
        "transliteration": "AN-NUR",
        "meaning": "The Light, The Illuminator",
        "row": 24,
        "displayCol": 4,
        "audio": "noa_93.mp3",
        "video": "noa_93.mp4"
      },
      {
        "key": "noa_94",
        "text": "الْهَادِي",
        "ar": "الْهَادِي",
        "small": "AL-HAADI",
        "en": "The Guide",
        "transliteration": "AL-HAADI",
        "meaning": "The Guide",
        "row": 24,
        "displayCol": 3,
        "audio": "noa_94.mp3",
        "video": "noa_94.mp4"
      },
      {
        "key": "noa_95",
        "text": "الْبَدِيعُ",
        "ar": "الْبَدِيعُ",
        "small": "AL-BADEE’",
        "en": "The Incomparable Originator",
        "transliteration": "AL-BADEE’",
        "meaning": "The Incomparable Originator",
        "row": 24,
        "displayCol": 2,
        "audio": "noa_95.mp3",
        "video": "noa_95.mp4"
      },
      {
        "key": "noa_96",
        "text": "اَلْبَاقِي",
        "ar": "اَلْبَاقِي",
        "small": "AL-BAAQI",
        "en": "The Everlasting",
        "transliteration": "AL-BAAQI",
        "meaning": "The Everlasting",
        "row": 24,
        "displayCol": 1,
        "audio": "noa_96.mp3",
        "video": "noa_96.mp4"
      },
      {
        "key": "noa_97",
        "text": "الْوَارِثُ",
        "ar": "الْوَارِثُ",
        "small": "AL-WAARITH",
        "en": "The Inheritor, The Heir",
        "transliteration": "AL-WAARITH",
        "meaning": "The Inheritor, The Heir",
        "row": 25,
        "displayCol": 4,
        "audio": "noa_97.mp3",
        "video": "noa_97.mp4"
      },
      {
        "key": "noa_98",
        "text": "الرَّشِيدُ",
        "ar": "الرَّشِيدُ",
        "small": "AR-RASHEED",
        "en": "The Guide, Infallible Teacher",
        "transliteration": "AR-RASHEED",
        "meaning": "The Guide, Infallible Teacher",
        "row": 25,
        "displayCol": 3,
        "audio": "noa_98.mp3",
        "video": "noa_98.mp4"
      },
      {
        "key": "noa_99",
        "text": "الصَّبُورُ",
        "ar": "الصَّبُورُ",
        "small": "AS-SABOOR",
        "en": "The Forbearing, The Patient",
        "transliteration": "AS-SABOOR",
        "meaning": "The Forbearing, The Patient",
        "row": 25,
        "displayCol": 2,
        "audio": "noa_99.mp3",
        "video": "noa_99.mp4"
      }
    ]
  },
  "debug": {
    "showTileAudioNames": false
  },
  "trace": {
    "minPassesRequired": 99
  },
  "audioMap": {
    "noa_01": "noa_01.mp3",
    "noa_02": "noa_02.mp3",
    "noa_03": "noa_03.mp3",
    "noa_04": "noa_04.mp3",
    "noa_05": "noa_05.mp3",
    "noa_06": "noa_06.mp3",
    "noa_07": "noa_07.mp3",
    "noa_08": "noa_08.mp3",
    "noa_09": "noa_09.mp3",
    "noa_10": "noa_10.mp3",
    "noa_11": "noa_11.mp3",
    "noa_12": "noa_12.mp3",
    "noa_13": "noa_13.mp3",
    "noa_14": "noa_14.mp3",
    "noa_15": "noa_15.mp3",
    "noa_16": "noa_16.mp3",
    "noa_17": "noa_17.mp3",
    "noa_18": "noa_18.mp3",
    "noa_19": "noa_19.mp3",
    "noa_20": "noa_20.mp3",
    "noa_21": "noa_21.mp3",
    "noa_22": "noa_22.mp3",
    "noa_23": "noa_23.mp3",
    "noa_24": "noa_24.mp3",
    "noa_25": "noa_25.mp3",
    "noa_26": "noa_26.mp3",
    "noa_27": "noa_27.mp3",
    "noa_28": "noa_28.mp3",
    "noa_29": "noa_29.mp3",
    "noa_30": "noa_30.mp3",
    "noa_31": "noa_31.mp3",
    "noa_32": "noa_32.mp3",
    "noa_33": "noa_33.mp3",
    "noa_34": "noa_34.mp3",
    "noa_35": "noa_35.mp3",
    "noa_36": "noa_36.mp3",
    "noa_37": "noa_37.mp3",
    "noa_38": "noa_38.mp3",
    "noa_39": "noa_39.mp3",
    "noa_40": "noa_40.mp3",
    "noa_41": "noa_41.mp3",
    "noa_42": "noa_42.mp3",
    "noa_43": "noa_43.mp3",
    "noa_44": "noa_44.mp3",
    "noa_45": "noa_45.mp3",
    "noa_46": "noa_46.mp3",
    "noa_47": "noa_47.mp3",
    "noa_48": "noa_48.mp3",
    "noa_49": "noa_49.mp3",
    "noa_50": "noa_50.mp3",
    "noa_51": "noa_51.mp3",
    "noa_52": "noa_52.mp3",
    "noa_53": "noa_53.mp3",
    "noa_54": "noa_54.mp3",
    "noa_55": "noa_55.mp3",
    "noa_56": "noa_56.mp3",
    "noa_57": "noa_57.mp3",
    "noa_58": "noa_58.mp3",
    "noa_59": "noa_59.mp3",
    "noa_60": "noa_60.mp3",
    "noa_61": "noa_61.mp3",
    "noa_62": "noa_62.mp3",
    "noa_63": "noa_63.mp3",
    "noa_64": "noa_64.mp3",
    "noa_65": "noa_65.mp3",
    "noa_66": "noa_66.mp3",
    "noa_67": "noa_67.mp3",
    "noa_68": "noa_68.mp3",
    "noa_69": "noa_69.mp3",
    "noa_70": "noa_70.mp3",
    "noa_71": "noa_71.mp3",
    "noa_72": "noa_72.mp3",
    "noa_73": "noa_73.mp3",
    "noa_74": "noa_74.mp3",
    "noa_75": "noa_75.mp3",
    "noa_76": "noa_76.mp3",
    "noa_77": "noa_77.mp3",
    "noa_78": "noa_78.mp3",
    "noa_79": "noa_79.mp3",
    "noa_80": "noa_80.mp3",
    "noa_81": "noa_81.mp3",
    "noa_82": "noa_82.mp3",
    "noa_83": "noa_83.mp3",
    "noa_84": "noa_84.mp3",
    "noa_85": "noa_85.mp3",
    "noa_86": "noa_86.mp3",
    "noa_87": "noa_87.mp3",
    "noa_88": "noa_88.mp3",
    "noa_89": "noa_89.mp3",
    "noa_90": "noa_90.mp3",
    "noa_91": "noa_91.mp3",
    "noa_92": "noa_92.mp3",
    "noa_93": "noa_93.mp3",
    "noa_94": "noa_94.mp3",
    "noa_95": "noa_95.mp3",
    "noa_96": "noa_96.mp3",
    "noa_97": "noa_97.mp3",
    "noa_98": "noa_98.mp3",
    "noa_99": "noa_99.mp3"
  },
  "watchVideoByKey": {
    "noa_01": "noa_01.mp4",
    "noa_02": "noa_02.mp4",
    "noa_03": "noa_03.mp4",
    "noa_04": "noa_04.mp4",
    "noa_05": "noa_05.mp4",
    "noa_06": "noa_06.mp4",
    "noa_07": "noa_07.mp4",
    "noa_08": "noa_08.mp4",
    "noa_09": "noa_09.mp4",
    "noa_10": "noa_10.mp4",
    "noa_11": "noa_11.mp4",
    "noa_12": "noa_12.mp4",
    "noa_13": "noa_13.mp4",
    "noa_14": "noa_14.mp4",
    "noa_15": "noa_15.mp4",
    "noa_16": "noa_16.mp4",
    "noa_17": "noa_17.mp4",
    "noa_18": "noa_18.mp4",
    "noa_19": "noa_19.mp4",
    "noa_20": "noa_20.mp4",
    "noa_21": "noa_21.mp4",
    "noa_22": "noa_22.mp4",
    "noa_23": "noa_23.mp4",
    "noa_24": "noa_24.mp4",
    "noa_25": "noa_25.mp4",
    "noa_26": "noa_26.mp4",
    "noa_27": "noa_27.mp4",
    "noa_28": "noa_28.mp4",
    "noa_29": "noa_29.mp4",
    "noa_30": "noa_30.mp4",
    "noa_31": "noa_31.mp4",
    "noa_32": "noa_32.mp4",
    "noa_33": "noa_33.mp4",
    "noa_34": "noa_34.mp4",
    "noa_35": "noa_35.mp4",
    "noa_36": "noa_36.mp4",
    "noa_37": "noa_37.mp4",
    "noa_38": "noa_38.mp4",
    "noa_39": "noa_39.mp4",
    "noa_40": "noa_40.mp4",
    "noa_41": "noa_41.mp4",
    "noa_42": "noa_42.mp4",
    "noa_43": "noa_43.mp4",
    "noa_44": "noa_44.mp4",
    "noa_45": "noa_45.mp4",
    "noa_46": "noa_46.mp4",
    "noa_47": "noa_47.mp4",
    "noa_48": "noa_48.mp4",
    "noa_49": "noa_49.mp4",
    "noa_50": "noa_50.mp4",
    "noa_51": "noa_51.mp4",
    "noa_52": "noa_52.mp4",
    "noa_53": "noa_53.mp4",
    "noa_54": "noa_54.mp4",
    "noa_55": "noa_55.mp4",
    "noa_56": "noa_56.mp4",
    "noa_57": "noa_57.mp4",
    "noa_58": "noa_58.mp4",
    "noa_59": "noa_59.mp4",
    "noa_60": "noa_60.mp4",
    "noa_61": "noa_61.mp4",
    "noa_62": "noa_62.mp4",
    "noa_63": "noa_63.mp4",
    "noa_64": "noa_64.mp4",
    "noa_65": "noa_65.mp4",
    "noa_66": "noa_66.mp4",
    "noa_67": "noa_67.mp4",
    "noa_68": "noa_68.mp4",
    "noa_69": "noa_69.mp4",
    "noa_70": "noa_70.mp4",
    "noa_71": "noa_71.mp4",
    "noa_72": "noa_72.mp4",
    "noa_73": "noa_73.mp4",
    "noa_74": "noa_74.mp4",
    "noa_75": "noa_75.mp4",
    "noa_76": "noa_76.mp4",
    "noa_77": "noa_77.mp4",
    "noa_78": "noa_78.mp4",
    "noa_79": "noa_79.mp4",
    "noa_80": "noa_80.mp4",
    "noa_81": "noa_81.mp4",
    "noa_82": "noa_82.mp4",
    "noa_83": "noa_83.mp4",
    "noa_84": "noa_84.mp4",
    "noa_85": "noa_85.mp4",
    "noa_86": "noa_86.mp4",
    "noa_87": "noa_87.mp4",
    "noa_88": "noa_88.mp4",
    "noa_89": "noa_89.mp4",
    "noa_90": "noa_90.mp4",
    "noa_91": "noa_91.mp4",
    "noa_92": "noa_92.mp4",
    "noa_93": "noa_93.mp4",
    "noa_94": "noa_94.mp4",
    "noa_95": "noa_95.mp4",
    "noa_96": "noa_96.mp4",
    "noa_97": "noa_97.mp4",
    "noa_98": "noa_98.mp4",
    "noa_99": "noa_99.mp4"
  },
  "animateVideoByKey": {
    "noa_01": "noa_01.mp4",
    "noa_02": "noa_02.mp4",
    "noa_03": "noa_03.mp4",
    "noa_04": "noa_04.mp4",
    "noa_05": "noa_05.mp4",
    "noa_06": "noa_06.mp4",
    "noa_07": "noa_07.mp4",
    "noa_08": "noa_08.mp4",
    "noa_09": "noa_09.mp4",
    "noa_10": "noa_10.mp4",
    "noa_11": "noa_11.mp4",
    "noa_12": "noa_12.mp4",
    "noa_13": "noa_13.mp4",
    "noa_14": "noa_14.mp4",
    "noa_15": "noa_15.mp4",
    "noa_16": "noa_16.mp4",
    "noa_17": "noa_17.mp4",
    "noa_18": "noa_18.mp4",
    "noa_19": "noa_19.mp4",
    "noa_20": "noa_20.mp4",
    "noa_21": "noa_21.mp4",
    "noa_22": "noa_22.mp4",
    "noa_23": "noa_23.mp4",
    "noa_24": "noa_24.mp4",
    "noa_25": "noa_25.mp4",
    "noa_26": "noa_26.mp4",
    "noa_27": "noa_27.mp4",
    "noa_28": "noa_28.mp4",
    "noa_29": "noa_29.mp4",
    "noa_30": "noa_30.mp4",
    "noa_31": "noa_31.mp4",
    "noa_32": "noa_32.mp4",
    "noa_33": "noa_33.mp4",
    "noa_34": "noa_34.mp4",
    "noa_35": "noa_35.mp4",
    "noa_36": "noa_36.mp4",
    "noa_37": "noa_37.mp4",
    "noa_38": "noa_38.mp4",
    "noa_39": "noa_39.mp4",
    "noa_40": "noa_40.mp4",
    "noa_41": "noa_41.mp4",
    "noa_42": "noa_42.mp4",
    "noa_43": "noa_43.mp4",
    "noa_44": "noa_44.mp4",
    "noa_45": "noa_45.mp4",
    "noa_46": "noa_46.mp4",
    "noa_47": "noa_47.mp4",
    "noa_48": "noa_48.mp4",
    "noa_49": "noa_49.mp4",
    "noa_50": "noa_50.mp4",
    "noa_51": "noa_51.mp4",
    "noa_52": "noa_52.mp4",
    "noa_53": "noa_53.mp4",
    "noa_54": "noa_54.mp4",
    "noa_55": "noa_55.mp4",
    "noa_56": "noa_56.mp4",
    "noa_57": "noa_57.mp4",
    "noa_58": "noa_58.mp4",
    "noa_59": "noa_59.mp4",
    "noa_60": "noa_60.mp4",
    "noa_61": "noa_61.mp4",
    "noa_62": "noa_62.mp4",
    "noa_63": "noa_63.mp4",
    "noa_64": "noa_64.mp4",
    "noa_65": "noa_65.mp4",
    "noa_66": "noa_66.mp4",
    "noa_67": "noa_67.mp4",
    "noa_68": "noa_68.mp4",
    "noa_69": "noa_69.mp4",
    "noa_70": "noa_70.mp4",
    "noa_71": "noa_71.mp4",
    "noa_72": "noa_72.mp4",
    "noa_73": "noa_73.mp4",
    "noa_74": "noa_74.mp4",
    "noa_75": "noa_75.mp4",
    "noa_76": "noa_76.mp4",
    "noa_77": "noa_77.mp4",
    "noa_78": "noa_78.mp4",
    "noa_79": "noa_79.mp4",
    "noa_80": "noa_80.mp4",
    "noa_81": "noa_81.mp4",
    "noa_82": "noa_82.mp4",
    "noa_83": "noa_83.mp4",
    "noa_84": "noa_84.mp4",
    "noa_85": "noa_85.mp4",
    "noa_86": "noa_86.mp4",
    "noa_87": "noa_87.mp4",
    "noa_88": "noa_88.mp4",
    "noa_89": "noa_89.mp4",
    "noa_90": "noa_90.mp4",
    "noa_91": "noa_91.mp4",
    "noa_92": "noa_92.mp4",
    "noa_93": "noa_93.mp4",
    "noa_94": "noa_94.mp4",
    "noa_95": "noa_95.mp4",
    "noa_96": "noa_96.mp4",
    "noa_97": "noa_97.mp4",
    "noa_98": "noa_98.mp4",
    "noa_99": "noa_99.mp4"
  }
});

if (typeof window !== 'undefined') {
  window.UNIT_CFG = UNIT_CFG;
}
